import type { PersonPublication } from "./publications-felicity-gavins";

export const rahaPazokiPublications: PersonPublication[] = [
  {
    slug: "hezkiah-2025-physical-activity-and-favourable-adiposity-genetic-liability",
    type: "journal",
    typeLabel: "Journal article",
    title: "Physical activity and favourable adiposity genetic liability reduce the risk of hypertension among high body mass individuals",
    authors: ["Hezkiah, C", "Pazoki, R"],
    year: 2025,
    journal: "Journal of the American Heart Association",
    volume: "0",
    issue: "accepted, in press",
    pages: "e040701",
    issn: "0263-6352",
    doi: "10.1161/JAHA.124.040701",
    doiUrl: "http://dx.doi.org/10.1161/JAHA.124.040701",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/31654",
  },
  {
    slug: "hezkiah-2025-physical-activity-and-favourable-adiposity-genetic-liability-2",
    type: "conference",
    typeLabel: "Conference paper",
    title: "Physical activity and favourable adiposity genetic liability reduce the risk of hypertension among high body mass individuals",
    authors: ["Hezkiah, C", "Pazoki, R"],
    year: 2025,
    journal: "34th European Meeting on Hypertension and Cardiovascular Protection (ESH 2025).",
    pages: "e184 - e184",
    issn: "0263-6352",
    doi: "10.1097/01.hjh.0001117068.12501.6d",
    doiUrl: "http://dx.doi.org/10.1097/01.hjh.0001117068.12501.6d",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/31655",
  },
  {
    slug: "karkia-2025-the-association-between-metabolic-syndrome-and-the-risk-of-e",
    type: "journal",
    typeLabel: "Journal article",
    title: "The Association Between Metabolic Syndrome and the Risk of Endometrial Cancer in Pre- and Post-Menopausal Women: A UK Biobank Study",
    authors: ["Karkia, R", "Maccarthy, G", "Payne, A", "Karteris, E", "Pazoki, R", "Chatterjee, J"],
    year: 2025,
    journal: "Journal of Clinical Medicine",
    volume: "14",
    issue: "3",
    pages: "1 - 15",
    issn: "2077-0383",
    doi: "10.3390/jcm14030751",
    doiUrl: "http://dx.doi.org/10.3390/jcm14030751",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/30760",
  },
  {
    slug: "maccarthy-2025-evaluation-of-machine-learning-and-traditional-statistical-m",
    type: "journal",
    typeLabel: "Journal article",
    title: "Evaluation of Machine Learning and Traditional Statistical Models to Assess the Value of Stroke Genetic Liability for Prediction of Risk of Stroke Within the UK Biobank",
    authors: ["MacCarthy, G", "Pazoki, R"],
    year: 2025,
    journal: "Healthcare",
    volume: "13",
    issue: "9",
    pages: "1 - 19",
    issn: "2227-9032",
    doi: "10.3390/healthcare13091003",
    doiUrl: "http://dx.doi.org/10.3390/healthcare13091003",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/31098",
  },
  {
    slug: "hezekiah-2024-physical-activity-alters-the-effect-of-genetic-determinants",
    type: "journal",
    typeLabel: "Journal article",
    title: "Physical activity alters the effect of genetic determinants of adiposity on hypertension among individuals of European ancestry in the UKB",
    authors: ["Hezekiah, C", "Blakemore, AI", "Bailey, DP", "Pazoki, R"],
    year: 2024,
    journal: "Scandinavian Journal of Medicine and Science in Sports",
    volume: "34",
    issue: "5",
    pages: "1 - 13",
    issn: "0905-7188",
    doi: "10.1111/sms.14636",
    doiUrl: "http://dx.doi.org/10.1111/sms.14636",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/28821",
  },
  {
    slug: "maccarthy-2024-using-machine-learning-to-evaluate-the-value-of-genetic-liab",
    type: "journal",
    typeLabel: "Journal article",
    title: "Using Machine Learning to Evaluate the Value of Genetic Liabilities in the Classification of Hypertension within the UK Biobank",
    authors: ["MacCarthy, G", "Pazoki, R"],
    year: 2024,
    journal: "Journal of Clinical Medicine",
    volume: "13",
    issue: "10",
    pages: "1 - 20",
    issn: "2077-0383",
    doi: "10.3390/jcm13102955",
    doiUrl: "http://dx.doi.org/10.3390/jcm13102955",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/29411",
  },
  {
    slug: "ofarrell-2023-evidence-for-involvement-of-the-alcohol-consumption-wdpcp-ge",
    type: "journal",
    typeLabel: "Journal article",
    title: "Evidence for involvement of the alcohol consumption WDPCP gene in lipid metabolism, and liver cirrhosis",
    authors: ["O’Farrell, F", "Aleyakpo, B", "Mustafa, R", "Jiang, X", "Pinto, RC", "Elliott, P", "Tzoulaki, I", "Dehghan, A", "Loh, SHY", "Barclay, JW", "Martins, LM", "Pazoki, R"],
    year: 2023,
    journal: "Scientific Reports",
    volume: "13",
    issue: "1",
    pages: "1 - 13",
    issn: "2045-2322",
    doi: "10.1038/s41598-023-47371-7",
    doiUrl: "http://dx.doi.org/10.1038/s41598-023-47371-7",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/27798",
  },
  {
    slug: "jiang-2022-urinary-sodium-excretion-enhances-the-effect-of-alcohol-on-b",
    type: "journal",
    typeLabel: "Journal article",
    title: "Urinary Sodium Excretion Enhances the Effect of Alcohol on Blood Pressure",
    authors: ["Jiang, X", "Anasanti, MD", "Drenos, F", "Blakemore, AI", "Pazoki, R"],
    year: 2022,
    journal: "Healthcare",
    volume: "10",
    issue: "7",
    pages: "1 - 13",
    issn: "2227-9032",
    doi: "10.3390/healthcare10071296",
    doiUrl: "http://dx.doi.org/10.3390/healthcare10071296",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/25046",
  },
  {
    slug: "o-farrell-2022-molecular-alterations-caused-by-alcohol-consumption-in-the-u",
    type: "journal",
    typeLabel: "Journal article",
    title: "Molecular Alterations Caused by Alcohol Consumption in the UK Biobank: A Mendelian Randomisation Study",
    authors: ["O'Farrell, F", "Jiang, X", "Aljifri, S", "Pazoki, R"],
    year: 2022,
    journal: "Nutrients",
    volume: "14",
    issue: "14",
    pages: "1 - 14",
    issn: "2072-6643",
    doi: "10.3390/nu14142943",
    doiUrl: "http://dx.doi.org/10.3390/nu14142943",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/25069",
  },
  {
    slug: "roa-diaz-2022-gene-diet-interactions-and-cardiovascular-diseases-a-system",
    type: "journal",
    typeLabel: "Journal article",
    title: "Gene-diet interactions and cardiovascular diseases: a systematic review of observational and clinical trials",
    authors: ["Roa-Díaz, ZM", "Teuscher, J", "Gamba, M", "Bundo, M", "Grisotto, G", "Wehrli, F", "Gamboa, E", "Rojas, LZ", "Gómez-Ochoa, SA", "Verhoog, S", "Vargas, MF", "Minder, B", "Franco, OH", "Dehghan, A", "Pazoki, R", "Marques-Vidal, P", "Muka, T"],
    year: 2022,
    journal: "BMC Cardiovascular Disorders",
    volume: "22",
    issue: "1",
    pages: "1 - 22",
    issn: "1471-2261",
    doi: "10.1186/s12872-022-02808-1",
    doiUrl: "http://dx.doi.org/10.1186/s12872-022-02808-1",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/25113",
  },
  {
    slug: "said-2022-genetic-analysis-of-over-half-a-million-people-characterises",
    type: "journal",
    typeLabel: "Journal article",
    title: "Genetic analysis of over half a million people characterises C-reactive protein loci",
    authors: ["Said, S", "Pazoki, R", "Karhunen, V", "Võsa, U", "Ligthart, S", "Bodinier, B", "Koskeridis, F", "Welsh, P", "Alizadeh, BZ", "Chasman, DI", "Sattar, N", "Chadeau-Hyam, M", "Evangelou, E", "Jarvelin, M-R", "Elliott, P", "Tzoulaki, I", "Dehghan, A"],
    year: 2022,
    journal: "Nature Communications",
    volume: "13",
    issue: "1",
    pages: "1 - 10",
    issn: "2041-1723",
    doi: "10.1038/s41467-022-29650-5",
    doiUrl: "http://dx.doi.org/10.1038/s41467-022-29650-5",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/24511",
  },
  {
    slug: "evangelou-2021-alcohol-consumption-in-the-general-population-is-associated",
    type: "journal",
    typeLabel: "Journal article",
    title: "Alcohol consumption in the general population is associated with structural changes in multiple organ systems",
    authors: ["Evangelou, E", "Suzuki, H", "Bai, W", "Pazoki, R", "Gao, H", "Matthews, PM", "Elliott, P"],
    year: 2021,
    journal: "eLife",
    volume: "10",
    pages: "e65325",
    issn: "2050-084X",
    doi: "10.7554/eLife.65325",
    doiUrl: "http://dx.doi.org/10.7554/eLife.65325",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/23038",
  },
  {
    slug: "pazoki-2021-genetic-analysis-in-european-ancestry-individuals-identifies",
    type: "journal",
    typeLabel: "Journal article",
    title: "Genetic analysis in European ancestry individuals identifies 517 loci associated with liver enzymes",
    authors: ["Pazoki, R", "Vujkovic, M", "Elliott, J", "Evangelou, E", "Gill, D", "Mohsen, G", "Peter, VDM", "Rui, CP", "Matthias, W", "Matthias, F", "Verena, Z", "Robert, DK", "Harold, S", "André, U", "Lifelines, S", "Julie, L", "Xiyun, J", "Saredo, S", "David, K", "Kyung, ML", "Marina, S", "Rotonya, C", "Phil, T", "Stephen, A", "Abbas, D", "Tzoulaki, I", "Ikram, MA", "Herzig, K-H", "Jarvelin, M-R", "Alizadeh, BZ", "O'Donnell, C", "Saleheen, D", "Voight, B", "Chang, K-M", "Thursz, M", "elliott, P"],
    year: 2021,
    journal: "Nature Communications",
    volume: "12",
    issue: "1",
    pages: "1 - 12",
    issn: "2041-1723",
    doi: "10.1038/s41467-021-22338-2",
    doiUrl: "http://dx.doi.org/10.1038/s41467-021-22338-2",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/22225",
  },
  {
    slug: "roa-diaz-2021-age-at-natural-menopause-and-blood-pressure-traits-mendelia",
    type: "journal",
    typeLabel: "Journal article",
    title: "Age at natural menopause and blood pressure traits: Mendelian randomization study",
    authors: ["Roa-Díaz, ZM", "Asllanaj, E", "Amin, HA", "Rojas, LZ", "Nano, J", "Ikram, MA", "Drenos, F", "Franco, OH", "Pazoki, R", "Marques-Vidal, P", "Voortman, T", "Muka, T"],
    year: 2021,
    journal: "Journal of Clinical Medicine",
    volume: "10",
    issue: "19",
    pages: "1 - 13",
    issn: "2077-0383",
    doi: "10.3390/jcm10194299",
    doiUrl: "http://dx.doi.org/10.3390/jcm10194299",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/24142",
  },
  {
    slug: "elliott-2020-estimated-24-hour-urinary-sodium-excretion-and-incident-card",
    type: "journal",
    typeLabel: "Journal article",
    title: "Estimated 24-Hour Urinary Sodium Excretion and Incident Cardiovascular Disease and Mortality among 398628 Individuals in UK Biobank",
    authors: ["Elliott, P", "Muller, DC", "Schneider-Luftman, D", "Pazoki, R", "Evangelou, E", "Dehghan, A", "Neal, B", "Tzoulaki, I"],
    year: 2020,
    journal: "Hypertension",
    volume: "76",
    issue: "3",
    pages: "683 - 691",
    issn: "0194-911X",
    doi: "10.1161/HYPERTENSIONAHA.119.14302",
    doiUrl: "http://dx.doi.org/10.1161/HYPERTENSIONAHA.119.14302",
  },
  {
    slug: "pazoki-2020-phenome-wide-and-genome-wide-analyses-of-quality-of-life-in",
    type: "journal",
    typeLabel: "Journal article",
    title: "Phenome-wide and genome-wide analyses of quality of life in schizophrenia",
    authors: ["Pazoki, R", "Lin, BD", "van Eijk, KR", "Schijven, D", "de Zwarte, S", "Guloksuz, S", "Luykx, JJ"],
    year: 2020,
    journal: "BJPsych Open",
    volume: "7",
    issue: "1",
    pages: "1 - 7",
    issn: "2056-4724",
    doi: "10.1192/bjo.2020.140",
    doiUrl: "http://dx.doi.org/10.1192/bjo.2020.140",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/22044",
  },
  {
    slug: "robinson-2020-determinants-of-accelerated-metabolomic-and-epigenetic-aging",
    type: "journal",
    typeLabel: "Journal article",
    title: "Determinants of accelerated metabolomic and epigenetic aging in a UK cohort",
    authors: ["Robinson, O", "Chadeau Hyam, M", "Karaman, I", "Climaco Pinto, R", "Ala-Korpela, M", "Handakas, E", "Fiorito, G", "Gao, H", "Heard, A", "Jarvelin, MR", "Lewis, M", "Pazoki, R", "Polidoro, S", "Tzoulaki, I", "Wielscher, M", "Elliott, P", "Vineis, P"],
    year: 2020,
    journal: "Aging Cell",
    volume: "19",
    issue: "6",
    pages: "1 - 13",
    issn: "1474-9718",
    doi: "10.1111/acel.13149",
    doiUrl: "http://dx.doi.org/10.1111/acel.13149",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/20848",
  },
  {
    slug: "de-vries-2019-multiancestry-genome-wide-association-study-of-lipid-levels",
    type: "journal",
    typeLabel: "Journal article",
    title: "Multiancestry Genome-Wide Association Study of Lipid Levels Incorporating Gene-Alcohol Interactions",
    authors: ["De Vries, PS", "Brown, MR", "Bentley, AR", "Sung, YJ", "Winkler, TW", "Ntalla, I", "Schwander, K", "Kraja, AT", "Guo, X", "Franceschini, N", "Cheng, CY", "Sim, X", "Vojinovic, D", "Huffman, JE", "Musani, SK", "Li, C", "Feitosa, MF", "Richard, MA", "Noordam, R", "Aschard, H", "Bartz, TM", "Bielak, LF", "Deng, X", "Dorajoo, R", "Lohman, KK", "Manning, AK", "Rankinen, T", "Smith, AV", "Tajuddin, SM", "Evangelou, E", "Graff, M", "Alver, M", "Boissel, M", "Chai, JF", "Chen, X", "Divers, J", "Gandin, I", "Gao, C", "Goel, A", "Hagemeijer, Y", "Harris, SE", "Hartwig, FP", "He, M", "Horimoto, ARVR", "Hsu, FC", "Jackson, AU", "Kasturiratne, A", "Komulainen, P", "Kühnel, B", "Laguzzi, F", "Lee, JH", "Luan, J", "Lyytikäinen, LP", "Matoba, N", "Nolte, IM", "Pietzner, M", "Riaz, M", "Said, MA", "Scott, RA", "Sofer, T", "Stančáková, A", "Takeuchi, F", "Tayo, BO", "Van Der Most, PJ", "Varga, TV", "Wang, Y", "Ware, EB", "Wen, W", "Yanek, LR", "Zhang, W", "Zhao, JH", "Afaq, S", "Amin, N", "Amini, M", "Arking, DE", "Aung, T", "Ballantyne, C", "Boerwinkle, E", "Broeckel, U", "Campbell, A", "Canouil, M", "Charumathi, S", "Chen, YDI", "Connell, JM", "De Faire, U", "De Las Fuentes, L", "De Mutsert, R", "De Silva, HJ", "Ding, J", "Dominiczak, AF", "Duan, Q", "Eaton, CB", "Eppinga, RN", "Faul, JD", "Fisher, V", "Forrester, T", "Franco, OH", "Friedlander, Y", "Ghanbari, M", "Giulianini, F"],
    year: 2019,
    journal: "American Journal of Epidemiology",
    volume: "188",
    issue: "6",
    pages: "1033 - 1054",
    issn: "0002-9262",
    doi: "10.1093/aje/kwz005",
    doiUrl: "http://dx.doi.org/10.1093/aje/kwz005",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/20681",
  },
  {
    slug: "evangelou-2019-new-alcohol-related-genes-suggest-shared-genetic-mechanisms",
    type: "journal",
    typeLabel: "Journal article",
    title: "New alcohol-related genes suggest shared genetic mechanisms with neuropsychiatric disorders",
    authors: ["Evangelou, E", "Gao, H", "Chu, C", "Ntritsos, G", "Blakeley, P", "Butts, AR", "Pazoki, R", "Suzuki, H", "Koskeridis, F", "Yiorkas, AM", "Karaman, I", "Elliott, J", "Luo, Q", "Aeschbacher, S", "Bartz, TM", "Baumeister, SE", "Braund, PS", "Brown, MR", "Brody, JA", "Clarke, TK", "Dimou, N", "Faul, JD", "Homuth, G", "Jackson, AU", "Kentistou, KA", "Joshi, PK", "Lemaitre, RN", "Lind, PA", "Lyytikäinen, LP", "Mangino, M", "Milaneschi, Y", "Nelson, CP", "Nolte, IM", "Perälä, MM", "Polasek, O", "Porteous, D", "Ratliff, SM", "Smith, JA", "Stančáková, A", "Teumer, A", "Tuominen, S", "Thériault, S", "Vangipurapu, J", "Whitfield, JB", "Wood, A", "Yao, J", "Yu, B", "Zhao, W", "Arking, DE", "Auvinen, J", "Liu, C", "Männikkö, M", "Risch, L", "Rotter, JI", "Snieder, H", "Veijola, J", "Blakemore, AI", "Boehnke, M", "Campbell, H", "Conen, D", "Eriksson, JG", "Grabe, HJ", "Guo, X", "van der Harst, P", "Hartman, CA", "Hayward, C", "Heath, AC", "Jarvelin, MR", "Kähönen, M", "Kardia, SLR", "Kühne, M", "Kuusisto, J", "Laakso, M", "Lahti, J", "Lehtimäki, T", "McIntosh, AM", "Mohlke, KL", "Morrison, AC", "Martin, NG", "Oldehinkel, AJ", "Penninx, BWJH", "Psaty, BM", "Raitakari, OT", "Rudan, I", "Samani, NJ", "Scott, LJ", "Spector, TD", "Verweij, N", "Weir, DR", "Wilson, JF", "Levy, D", "Tzoulaki, I", "Bell, JD", "Matthews, PM", "Rothenfluh, A", "Desrivières, S", "Schumann, G", "Elliott, P"],
    year: 2019,
    journal: "Nature Human Behaviour",
    volume: "3",
    issue: "9",
    pages: "950 - 961",
    issn: "2397-3374",
    doi: "10.1038/s41562-019-0653-z",
    doiUrl: "http://dx.doi.org/10.1038/s41562-019-0653-z",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/20544",
  },
  {
    slug: "kilpelainen-2019-multi-ancestry-study-of-blood-lipid-levels-identifies-four-l",
    type: "journal",
    typeLabel: "Journal article",
    title: "Multi-ancestry study of blood lipid levels identifies four loci interacting with physical activity",
    authors: ["Kilpeläinen, TO", "Bentley, AR", "Noordam, R", "Sung, YJ", "Schwander, K", "Winkler, TW", "Jakupović, H", "Chasman, DI", "Manning, A", "Ntalla, I", "Aschard, H", "Brown, MR", "de las Fuentes, L", "Franceschini, N", "Guo, X", "Vojinovic, D", "Aslibekyan, S", "Feitosa, MF", "Kho, M", "Musani, SK", "Richard, M", "Wang, H", "Wang, Z", "Bartz, TM", "Bielak, LF", "Campbell, A", "Dorajoo, R", "Fisher, V", "Hartwig, FP", "Horimoto, ARVR", "Li, C", "Lohman, KK", "Marten, J", "Sim, X", "Smith, AV", "Tajuddin, SM", "Alver, M", "Amini, M", "Boissel, M", "Chai, JF", "Chen, X", "Divers, J", "Evangelou, E", "Gao, C", "Graff, M", "Harris, SE", "He, M", "Hsu, F-C", "Jackson, AU", "Zhao, JH", "Kraja, AT", "Kühnel, B", "Laguzzi, F", "Lyytikäinen, L-P", "Nolte, IM", "Rauramaa, R", "Riaz, M", "Robino, A", "Rueedi, R", "Stringham, HM", "Takeuchi, F", "van der Most, PJ", "Varga, TV", "Verweij, N", "Ware, EB", "Wen, W", "Li, X", "Yanek, LR", "Amin, N", "Arnett, DK", "Boerwinkle, E", "Brumat, M", "Cade, B", "Canouil, M", "Chen, Y-DI", "Concas, MP", "Connell, J", "de Mutsert, R", "de Silva, HJ", "de Vries, PS", "Demirkan, A", "Ding, J", "Eaton, CB", "Faul, JD", "Friedlander, Y", "Gabriel, KP", "Ghanbari, M", "Giulianini, F", "Gu, CC", "Gu, D", "Harris, TB", "He, J", "Heikkinen, S", "Heng, C-K", "Hunt, SC", "Ikram, MA", "Jonas, JB", "Koh, W-P", "Komulainen, P", "Krieger, JE", "Kritchevsky, SB", "Kutalik, Z", "Kuusisto, J", "Langefeld, CD", "Langenberg, C", "Launer, LJ", "Leander, K", "Lemaitre, RN", "Lewis, CE", "Liang, J", "Alizadeh, BZ", "Boezen, HM", "Franke, L", "Navis, G", "Rots, M", "Swertz, M", "Wolffenbuttel, BHR", "Wijmenga, C", "Liu, J", "Mägi, R", "Manichaikul, A", "Meitinger, T", "Metspalu, A", "Milaneschi, Y", "Mohlke, KL", "Mosley, TH", "Murray, AD", "Nalls, MA", "Nang, E-EK", "Nelson, CP", "Nona, S", "Norris, JM", "Nwuba, CV", "O’Connell, J", "Palmer, ND", "Papanicolau, GJ", "Pazoki, R", "Pedersen, NL", "Peters, A", "Peyser, PA", "Polasek, O", "Porteous, DJ", "Poveda, A", "Raitakari, OT", "Rich, SS", "Risch, N", "Robinson, JG", "Rose, LM", "Rudan, I", "Schreiner, PJ", "Scott, RA", "Sidney, SS", "Sims, M", "Smith, JA", "Snieder, H", "Sofer, T", "Starr, JM", "Sternfeld, B", "Strauch, K", "Tang, H", "Taylor, KD", "Tsai, MY", "Tuomilehto, J", "Uitterlinden, AG", "van der Ende, MY", "van Heemst, D", "Voortman, T", "Waldenberger, M", "Wennberg, P", "Wilson, G", "Xiang, Y-B", "Yao, J", "Yu, C", "Yuan, J-M", "Zhao, W", "Zonderman, AB", "Becker, DM", "Boehnke, M", "Bowden, DW", "de Faire, U", "Deary, IJ", "Elliott, P", "Esko, T", "Freedman, BI", "Froguel, P", "Gasparini, P", "Gieger, C", "Kato, N", "Laakso, M", "Lakka, TA", "Lehtimäki, T", "Magnusson, PKE", "Oldehinkel, AJ", "Penninx, BWJH", "Samani, NJ", "Shu, X-O", "van der Harst, P", "Van Vliet-Ostaptchouk, JV", "Vollenweider, P", "Wagenknecht, LE", "Wang, YX", "Wareham, NJ", "Weir, DR", "Wu, T", "Zheng, W", "Zhu, X", "Evans, MK", "Franks, PW", "Gudnason, V", "Hayward, C", "Horta, BL", "Kelly, TN", "Liu, Y", "North, KE", "Pereira, AC", "Ridker, PM", "Tai, ES", "van Dam, RM", "Fox, ER", "Kardia, SLR", "Liu, C-T", "Mook-Kanamori, DO", "Province, MA", "Redline, S", "van Duijn, CM", "Rotter, JI", "Kooperberg, CB", "Gauderman, WJ", "Psaty, BM", "Rice, K", "Munroe, PB", "Fornage, M", "Cupples, LA", "Rotimi, CN", "Morrison, AC", "Rao, DC", "Loos, RJF"],
    year: 2019,
    journal: "Nature Communications",
    volume: "10",
    issue: "1",
    pages: "376",
    issn: "2041-1723",
    doi: "10.1038/s41467-018-08008-w",
    doiUrl: "http://dx.doi.org/10.1038/s41467-018-08008-w",
  },
  {
    slug: "pazoki-2019-gwas-for-urinary-sodium-and-potassium-excretion-highlights-p",
    type: "journal",
    typeLabel: "Journal article",
    title: "GWAS for urinary sodium and potassium excretion highlights pathways shared with cardiovascular traits",
    authors: ["Pazoki, R", "Evangelou, E", "Mosen-Ansorena, D", "Pinto, RC", "Karaman, I", "Blakeley, P", "Gill, D", "Zuber, V", "Elliott, P", "Tzoulaki, I", "Dehghan, A"],
    year: 2019,
    journal: "Nature Communications",
    volume: "10",
    issue: "1",
    pages: "1 - 11",
    issn: "2041-1723",
    doi: "10.1038/s41467-019-11451-y",
    doiUrl: "http://dx.doi.org/10.1038/s41467-019-11451-y",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/20126",
  },
  {
    slug: "pazoki-2019-cardiovascular-disease-abo-locus-and-markers-of-platelet-f",
    type: "journal",
    typeLabel: "Journal article",
    title: "Cardiovascular disease, ABO locus, and markers of platelet functionality",
    authors: ["Pazoki, R"],
    year: 2019,
    journal: "International Journal of Cardiology",
    volume: "286",
    issue: "1 July 2019",
    pages: "162 - 163",
    issn: "0167-5273",
    doi: "10.1016/j.ijcard.2019.03.061",
    doiUrl: "http://dx.doi.org/10.1016/j.ijcard.2019.03.061",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/20410",
  },
  {
    slug: "schmidt-2019-phenome-wide-association-analysis-of-ldl-cholesterol-lowerin",
    type: "journal",
    typeLabel: "Journal article",
    title: "Phenome-wide association analysis of LDL-cholesterol lowering genetic variants in PCSK9",
    authors: ["Schmidt, AF", "Holmes, MV", "Preiss, D", "Swerdlow, DI", "Denaxas, S", "Fatemifar, G", "Faraway, R", "Finan, C", "Valentine, D", "Fairhurst-Hunter, Z", "Hartwig, FP", "Horta, BL", "Hypponen, E", "Power, C", "Moldovan, M", "Van Iperen, E", "Hovingh, K", "Demuth, I", "Norman, K", "Steinhagen-Thiessen, E", "Demuth, J", "Bertram, L", "Lill, CM", "Coassin, S", "Willeit, J", "Kiechl, S", "Willeit, K", "Mason, D", "Wright, J", "Morris, R", "Wanamethee, G", "Whincup, P", "Ben-Shlomo, Y", "McLachlan, S", "Price, JF", "Kivimaki, M", "Welch, C", "Sanchez-Galvez, A", "Marques-Vidal, P", "Nicolaides, A", "Panayiotou, AG", "Onland-Moret, NC", "Van Der Schouw, YT", "Matullo, G", "Fiorito, G", "Guarrera, S", "Sacerdote, C", "Wareham, NJ", "Langenberg, C", "Scott, RA", "Luan, J", "Bobak, M", "Malyutina, S", "Pajak, A", "Kubinova, R", "Tamosiunas, A", "Pikhart, H", "Grarup, N", "Pedersen, O", "Hansen, T", "Linneberg, A", "Jess, T", "Cooper, J", "Humphries, SE", "Brilliant, M", "Kitchner, T", "Hakonarson, H", "Carrell, DS", "McCarty, CA", "Lester, KH", "Larson, EB", "Crosslin, DR", "De Andrade, M", "Roden, DM", "Denny, JC", "Carty, C", "Hancock, S", "Attia, J", "Holliday, E", "Scott, R", "Schofield, P", "O'Donnell, M", "Yusuf, S", "Chong, M", "Pare, G", "Van Der Harst, P", "Said, MA", "Eppinga, RN", "Verweij, N", "Snieder, H", "Christen, T", "Mook-Kanamori, DO", "Gustafsson, S", "Lind, L", "Ingelsson, E", "Pazoki, R", "Franco, O", "Hofman, A", "Uitterlinden, A", "Dehghan, A"],
    year: 2019,
    journal: "BMC Cardiovascular Disorders",
    volume: "19",
    issue: "1",
    pages: "240",
    issn: "1471-2261",
    doi: "10.1186/s12872-019-1187-z",
    doiUrl: "http://dx.doi.org/10.1186/s12872-019-1187-z",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/20219",
  },
  {
    slug: "ashar-2018-a-comprehensive-evaluation-of-the-genetic-architecture-of-su",
    type: "journal",
    typeLabel: "Journal article",
    title: "A comprehensive evaluation of the genetic architecture of sudden cardiac arrest",
    authors: ["Ashar, FN", "Mitchell, RN", "Albert, CM", "Newton-Cheh, C", "Brody, JA", "Müller-Nurasyid, M", "Moes, A", "Meitinger, T", "Mak, A", "Huikuri, H", "Junttila, MJ", "Goyette, P", "Pulit, SL", "Pazoki, R", "Tanck, MW", "Blom, MT", "Zhao, X", "Havulinna, AS", "Jabbari, R", "Glinge, C", "Tragante, V", "Escher, SA", "Chakravarti, A", "Ehret, G", "Coresh, J", "Li, M", "Prineas, RJ", "Franco, OH", "Kwok, P-Y", "Lumley, T", "Dumas, F", "McKnight, B", "Rotter, JI", "Lemaitre, RN", "Heckbert, SR", "O’Donnell, CJ", "Hwang, S-J", "Tardif, J-C", "VanDenburgh, M", "Uitterlinden, AG", "Hofman, A", "Stricker, BHC", "de Bakker, PIW", "Franks, PW", "Jansson, J-H", "Asselbergs, FW", "Halushka, MK", "Maleszewski, JJ", "Tfelt-Hansen, J", "Engstrøm, T", "Salomaa, V", "Virmani, R", "Kolodgie, F", "Wilde, AAM", "Tan, HL", "Bezzina, CR", "Eijgelsheim, M", "Rioux, JD", "Jouven, X", "Kääb, S", "Psaty, BM", "Siscovick, DS", "Arking, DE", "Sotoodehnia, N"],
    year: 2018,
    journal: "European Heart Journal",
    volume: "39",
    issue: "44",
    pages: "3961 - 3969",
    issn: "0195-668X",
    doi: "10.1093/eurheartj/ehy474",
    doiUrl: "http://dx.doi.org/10.1093/eurheartj/ehy474",
  },
  {
    slug: "davies-2018-study-of-300-486-individuals-identifies-148-independent-gene",
    type: "journal",
    typeLabel: "Journal article",
    title: "Study of 300,486 individuals identifies 148 independent genetic loci influencing general cognitive function",
    authors: ["Davies, G", "Lam, M", "Harris, SE", "Trampush, JW", "Luciano, M", "Hill, WD", "Hagenaars, SP", "Ritchie, SJ", "Marioni, RE", "Fawns-Ritchie, C", "Liewald, DCM", "Okely, JA", "Ahola-Olli, AV", "Barnes, CLK", "Bertram, L", "Bis, JC", "Burdick, KE", "Christoforou, A", "Derosse, P", "Djurovic, S", "Espeseth, T", "Giakoumaki, S", "Giddaluru, S", "Gustavson, DE", "Hayward, C", "Hofer, E", "Ikram, MA", "Karlsson, R", "Knowles, E", "Lahti, J", "Leber, M", "Li, S", "Mather, KA", "Melle, I", "Morris, D", "Oldmeadow, C", "Palviainen, T", "Payton, A", "Pazoki, R", "Petrovic, K", "Reynolds, CA", "Sargurupremraj, M", "Scholz, M", "Smith, JA", "Smith, AV", "Terzikhan, N", "Thalamuthu, A", "Trompet, S", "Van Der Lee, SJ", "Ware, EB", "Windham, BG", "Wright, MJ", "Yang, J", "Yu, J", "Ames, D", "Amin, N", "Amouyel, P", "Andreassen, OA", "Armstrong, NJ", "Assareh, AA", "Attia, JR", "Attix, D", "Avramopoulos, D", "Bennett, DA", "Böhmer, AC", "Boyle, PA", "Brodaty, H", "Campbell, H", "Cannon, TD", "Cirulli, ET", "Congdon, E", "Conley, ED", "Corley, J", "Cox, SR", "Dale, AM", "Dehghan, A", "Dick, D", "Dickinson, D", "Eriksson, JG", "Evangelou, E", "Faul, JD", "Ford, I", "Freimer, NA", "Gao, H", "Giegling, I", "Gillespie, NA", "Gordon, SD", "Gottesman, RF", "Griswold, ME", "Gudnason, V", "Harris, TB", "Hartmann, AM", "Hatzimanolis, A", "Heiss, G", "Holliday, EG", "Joshi, PK", "Kähönen, M", "Kardia, SLR", "Karlsson, I", "Kleineidam, L"],
    year: 2018,
    journal: "Nature Communications",
    volume: "9",
    issue: "1",
    pages: "2098",
    issn: "2041-1723",
    doi: "10.1038/s41467-018-04362-x",
    doiUrl: "http://dx.doi.org/10.1038/s41467-018-04362-x",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/20231",
  },
  {
    slug: "evangelou-2018-genome-wide-association-and-functional-studies-identify-46-n",
    type: "journal",
    typeLabel: "Journal article",
    title: "Genome-wide association and functional studies identify 46 novel loci for alcohol consumption and suggest common genetic mechanisms with neuropsychiatric disorders",
    authors: ["Evangelou, E", "Gao, H", "Chu, C", "Ntritsos, G", "Blakeley, P", "Butts, AR", "Pazoki, R", "Suzuki, H", "Koskeridis, F", "Yiorkas, AM", "Karaman, I", "Elliott, J", "Aeschbacher, S", "Bartz, TM", "Baumeister, SE", "Braund, PS", "Brown, MR", "Brody, JA", "Clarke, T-K", "Dimou, N", "Faul, JD", "Homuth, G", "Jackson, AU", "Kentistou, KA", "Joshi, PK", "Lemaitre, RN", "Lind, PA", "Lyytikäinen, L-P", "Mangino, M", "Milaneschi, Y", "Nelson, CP", "Nolte, IM", "Perälä, M-M", "Polasek, O", "Porteous, D", "Ratliff, SM", "Smith, JA", "Stančáková, A", "Teumer, A", "Tuominen, S", "Thériault, S", "Vangipurapu, J", "Whitfield, JB", "Wood, A", "Yao, J", "Yu, B", "Zhao, W", "Arking, DE", "Auvinen, J", "Liu, C", "Männikkö, M", "Risch, L", "Rotter, JI", "Snieder, H", "Veijola, J", "Blakemore, AI", "Boehnke, M", "Campbell, H", "Conen, D", "Eriksson, JG", "Grabe, HJ", "Guo, X", "Harst, PVD", "Hartman, CA", "Hayward, C", "Heath, AC", "Jarvelin, M-R", "Kähönen, M", "Kardia, SLR", "Kühne, M", "Kuusisto, J", "Laakso, M", "Lahti, J", "Lehtimäki, T", "McIntosh, AM", "Mohlke, KL", "Morrison, AC", "Martin, NG", "Oldehinkel, AJ", "Penninx, BWJH", "Psaty, BM", "Raitakari, OT", "Rudan, I", "Samani, NJ", "Scott, LJ", "Spector, TD", "Verweij, N", "Weir, DR", "Wilson, JF", "Levy, D", "Tzoulaki, I", "Bell, JD", "Matthews, P", "Rothenfluh, A", "Desrivières, S", "Schumann, G", "Elliott, P"],
    year: 2018,
    journal: "bioRxiv",
    doi: "10.1101/453332",
    doiUrl: "http://dx.doi.org/10.1101/453332",
  },
  {
    slug: "evangelou-2018-genetic-analysis-of-over-1-million-people-identifies-535-new",
    type: "journal",
    typeLabel: "Journal article",
    title: "Genetic analysis of over 1 million people identifies 535 new loci associated with blood pressure traits",
    authors: ["Evangelou, E", "Warren, HR", "Mosen-Ansorena, D", "Mifsud, B", "Pazoki, R", "Gao, H", "Ntritsos, G", "Dimou, N", "Cabrera, CP", "Karaman, I", "Ng, FL", "Evangelou, M", "Witkowska, K", "Tzanis, E", "Hellwege, JN", "Giri, A", "Velez Edwards, DR", "Sun, YV", "Cho, K", "Gaziano, JM", "Wilson, PWF", "Tsao, PS", "Kovesdy, CP", "Esko, T", "Mägi, R", "Milani, L", "Almgren, P", "Boutin, T", "Debette, S", "Ding, J", "Giulianini, F", "Holliday, EG", "Jackson, AU", "Li-Gao, R", "Lin, WY", "Luan, J", "Mangino, M", "Oldmeadow, C", "Prins, BP", "Qian, Y", "Sargurupremraj, M", "Shah, N", "Surendran, P", "Thériault, S", "Verweij, N", "Willems, SM", "Zhao, JH", "Amouyel, P", "Connell, J", "de Mutsert, R", "Doney, ASF", "Farrall, M", "Menni, C", "Morris, AD", "Noordam, R", "Paré, G", "Poulter, NR", "Shields, DC", "Stanton, A", "Thom, S", "Abecasis, G", "Amin, N", "Arking, DE", "Ayers, KL", "Barbieri, CM", "Batini, C", "Bis, JC", "Blake, T", "Bochud, M", "Boehnke, M", "Boerwinkle, E", "Boomsma, DI", "Bottinger, EP", "Braund, PS", "Brumat, M", "Campbell, A", "Campbell, H", "Chakravarti, A", "Chambers, JC", "Chauhan, G", "Ciullo, M", "Cocca, M", "Collins, F", "Cordell, HJ", "Davies, G", "Borst, MHD", "Geus, EJD", "Deary, IJ", "Deelen, J", "Del Greco M, F", "Demirkale, CY", "Dörr, M", "Ehret, GB", "Elosua, R", "Enroth, S", "Erzurumluoglu, AM", "Ferreira, T", "Frånberg, M", "Franco, OH", "Gandin, I"],
    year: 2018,
    journal: "Nature Genetics",
    volume: "50",
    issue: "10",
    pages: "1412 - 1425",
    issn: "1061-4036",
    doi: "10.1038/s41588-018-0205-x",
    doiUrl: "http://dx.doi.org/10.1038/s41588-018-0205-x",
  },
  {
    slug: "pazoki-2018-methods-for-polygenic-traits",
    type: "journal",
    typeLabel: "Journal article",
    title: "Methods for Polygenic Traits",
    authors: ["Pazoki, R"],
    year: 2018,
    journal: "Methods in molecular biology (Clifton, N.J.)",
    volume: "1793",
    pages: "145 - 156",
    issn: "1064-3745",
    doi: "10.1007/978-1-4939-7868-7_10",
    doiUrl: "http://dx.doi.org/10.1007/978-1-4939-7868-7_10",
  },
  {
    slug: "robinson-2018-determinants-of-accelerated-metabolomic-and-epigenetic-agein",
    type: "journal",
    typeLabel: "Journal article",
    title: "Determinants of accelerated metabolomic and epigenetic ageing in a UK cohort",
    authors: ["Robinson, O", "Hyam, MC", "Karaman, I", "Pinto, RC", "Fiorito, G", "Gao, H", "Heard, A", "Jarvelin, M-R", "Lewis, M", "Pazoki, R", "Polidoro, S", "Tzoulaki, I", "Wielscher, M", "Elliott, P", "Vineis, P"],
    year: 2018,
    journal: "bioRxiv",
    doi: "10.1101/411603",
    doiUrl: "http://dx.doi.org/10.1101/411603",
  },
  {
    slug: "schmidt-2018-phenome-wide-association-analysis-of-ldl-cholesterol-lowerin",
    type: "journal",
    typeLabel: "Journal article",
    title: "Phenome-wide association analysis of LDL-cholesterol lowering genetic variants inPCSK9",
    authors: ["Schmidt, AF", "Holmes, MV", "Preiss, D", "Swerdlow, D", "Denaxas, S", "Fatemifar, G", "Faraway, R", "Finan, C", "Lumbers, T", "Henry, A", "Valentine, D", "Fairhurst-Hunter, Z", "Hartwig, FP", "Horta, BL", "Hypponen, E", "Power, C", "Moldovan, M", "van Iperen, E", "Hovingh, K", "Demuth, I", "Norman, K", "Steinhagen-Thiessen, E", "Demuth, J", "Bertram, L", "Lill, CM", "Coassin, S", "Willeit, J", "Kiechl, S", "Willeit, K", "Mason, D", "Wright, J", "Morris, R", "Wanamethee, G", "Whincup, P", "Ben-Shlomo, Y", "McLachlan, S", "Price, JF", "Kivimaki, M", "Welch, C", "Sanchez-Galvez, A", "Marques-Vidal, P", "Nicolaides, A", "Panayiotou, AG", "Onland-Moret, NC", "van der Schouw, YT", "Matullo, G", "Fiorito, G", "Guarrera, S", "Sacerdote, C", "Wareham, NJ", "Langenberg, C", "Scott, RA", "Luan, J", "Bobak, M", "Malyutina, S", "Pajak, A", "Kubinova, R", "Tamosiunas, A", "Pikhart, H", "Grarup, N", "Pedersen, O", "Hansen, T", "Linneberg, A", "Jess, T", "Cooper, J", "Humphries, SE", "Brilliant, M", "Kitchner, T", "Hakonarson, H", "Carrell, DS", "McCarty, CA", "Lester, KH", "Larson, EB", "Crosslin, DR", "Andrade, MD", "Roden, DM", "Denny, JC", "Carty, C", "Hancock, S", "Attia, J", "Holliday, E", "Scott, R", "Schofield, P", "O’Donnell, M", "Yusuf, S", "Chong, M", "Pare, G", "van der Harst, P", "Said, MA", "Eppinga, RN", "Verweij, N", "Snieder, H", "Christen, T", "Mook-Kanamori, DO", "Gustafsson, S", "Lind, L", "Ingelsson, E", "Pazoki, R", "Franco, O", "Hofman, A", "Uitterlinden, A", "Dehghan, A", "Teumer, A", "Baumeister, S", "Dörr, M", "Lerch, MM", "Völker, U", "Völzke, H", "Ward, J", "Pell, JP", "Meade, T", "Christophersen, IE", "Maitland-van der Zee, AH", "Baranova, EV", "Young, R", "Ford, I", "Campbell, A", "Padmanabhan, S", "Bots, ML", "Grobbee, DE", "Froguel, P", "Thuillier, D", "Roussel, R", "Bonnefond, A", "Cariou, B", "Smart, M", "Bao, Y", "Kumari, M", "Mahajan, A", "Hopewell, JC", "Seshadri, S", "Dale, C", "Costa, RPE", "Ridker, PM", "Chasman, DI", "Reiner, AP", "Ritchie, MD", "Lange, LA", "Cornish, AJ", "Dobbins, SE", "Hemminki, K", "Kinnersley, B", "Sanson, M", "Labreche, K", "Simon, M", "Bondy, M", "Law, P", "Speedy, H", "Allan, J", "Li, N", "Went, M", "Weinhold, N", "Morgan, G", "Sonneveld, P", "Nilsson, B", "Goldschmidt, H", "Hemminki, K", "Sud, A", "Engert, A", "Hansson, M", "Hemingway, H", "Asselbergs, FW", "Patel, RS", "Keating, BJ", "Sattar, N", "Houlston, R", "Casas, JP", "Hingorani, AD"],
    year: 2018,
    journal: "bioRxiv",
    doi: "10.1101/329052",
    doiUrl: "http://dx.doi.org/10.1101/329052",
  },
  {
    slug: "ashar-2017-a-comprehensive-evaluation-of-the-genetic-architecture-of-su",
    type: "journal",
    typeLabel: "Journal article",
    title: "A Comprehensive Evaluation of the Genetic Architecture of Sudden Cardiac Arrest",
    authors: ["Ashar, FN", "Mitchell, RN", "Albert, CM", "Newton-Cheh, C", "Brody, JA", "Muller-Nurasyid, M", "Moes, A", "Meitinger, T", "Mak, A", "Huikuri, H", "Junttila, MJ", "Goyette, P", "Pulit, SL", "Pazoki, R", "Tanck, MW", "Blom, MT", "Zhao, X", "Hauvlinna, AS", "Jabbari, R", "Glinge, C", "Tragante, V", "Escher, SA", "Chakravarti, A", "Ehret, G", "Coresh, J", "Li, M", "Prineas, RJ", "Franco, OH", "Kwok, P-Y", "Lumley, T", "Dumas, F", "McKnight, B", "Rotter, JI", "Lemaitre, RN", "Heckbert, SR", "O’Donnell, CJ", "Hwang, S-J", "Tardif, J-C", "Kortelainen, M-L", "VanDenburgh, M", "Uitterlinden, AG", "Hofman, A", "Stricker, BHC", "de Bakker, PIW", "Franks, PW", "Jansson, J-H", "Asselbergs, FW", "Halushka, MK", "Maleszewski, JJ", "Tfelt-Hansen, J", "Engstrom, T", "Salomaa, V", "Virmani, R", "Kolodgie, F", "Wilde, AAM", "Tan, HL", "Bezzina, CR", "Eijgelsheim, M", "Rioux, JD", "Jouven, X", "Kaab, S", "Psaty, BM", "Siscovick, DS", "Arking, D", "Sotoodehnia, N"],
    year: 2017,
    journal: "bioRxiv",
    doi: "10.1101/235234",
    doiUrl: "http://dx.doi.org/10.1101/235234",
  },
  {
    slug: "davies-2017-ninety-nine-independent-genetic-loci-influencing-general-cog",
    type: "journal",
    typeLabel: "Journal article",
    title: "Ninety-nine independent genetic loci influencing general cognitive function include genes associated with brain health and structure (N = 280,360)",
    authors: ["Davies, G", "Lam, M", "Harris, SE", "Trampush, JW", "Luciano, M", "Hill, WD", "Hagenaars, SP", "Ritchie, SJ", "Marioni, RE", "Fawns-Ritchie, C", "Liewald, DCM", "Okely, JA", "Ahola-Olli, AV", "Barnes, CLK", "Bertram, L", "Bis, JC", "Burdick, KE", "Christoforou, A", "DeRosse, P", "Djurovic, S", "Espeseth, T", "Giakoumaki, S", "Giddaluru, S", "Gustavson, DE", "Hayward, C", "Hofer, E", "Ikram, MA", "Karlsson, R", "Knowles, E", "Lahti, J", "Leber, M", "Li, S", "Mather, KA", "Melle, I", "Morris, D", "Oldmeadow, C", "Palviainen, T", "Payton, A", "Pazoki, R", "Petrovic, K", "Reynolds, CA", "Sargurupremraj, M", "Scholz, M", "Smith, JA", "Smith, AV", "Terzikhan, N", "Thalamuthu, A", "Trompet, S", "Lee, SJVD", "Ware, EB", "Windham, BG", "Wright, MJ", "Yang, J", "Yu, J", "Ames, D", "Amin, N", "Amouyel, P", "Andreassen, OA", "Armstrong, NJ", "Assareh, AA", "Attia, JR", "Attix, D", "Avramopoulos, D", "Bennett, DA", "Böhmer, AC", "Boyle, PA", "Brodaty, H", "Campbell, H", "Cannon, TD", "Cirulli, ET", "Congdon, E", "Conley, ED", "Corley, J", "Cox, SR", "Dale, AM", "Dehghan, A", "Dick, D", "Dickinson, D", "Eriksson, JG", "Evangelou, E", "Faul, JD", "Ford, I", "Freimer, NA", "Gao, H", "Giegling, I", "Gillespie, NA", "Gordon, SD", "Gottesman, RF", "Griswold, ME", "Gudnason, V", "Harris, TB", "Hartmann, AM", "Hatzimanolis, A", "Heiss, G", "Holliday, EG", "Joshi, PK", "Kähönen, M", "Kardia, SLR", "Karlsson, I", "Kleineidam, L", "Knopman, DS", "Kochan, NA", "Konte, B", "Kwok, JB", "Hellard, SL", "Lee, T", "Lehtimäki, T", "Li, S-C", "Liu, T", "Koini, M", "London, E", "Longstreth, WT", "Lopez, OL", "Loukola, A", "Luck, T", "Lundervold, AJ", "Lundquist, A", "Lyytikäinen, L-P", "Martin, NG", "Montgomery, GW", "Murray, AD", "Need, AC", "Noordam, R", "Nyberg, L", "Ollier, W", "Papenberg, G", "Pattie, A", "Polasek, O", "Poldrack, RA", "Psaty, BM", "Reppermund, S", "Riedel-Heller, SG", "Rose, RJ", "Rotter, JI", "Roussos, P", "Rovio, SP", "Saba, Y", "Sabb, FW", "Sachdev, PS", "Satizabal, C", "Schmid, M", "Scott, RJ", "Scult, MA", "Simino, J", "Slagboom, PE", "Smyrnis, N", "Soumaré, A", "Stefanis, NC", "Stott, DJ", "Straub, RE", "Sundet, K", "Taylor, AM", "Taylor, KD", "Tzoulaki, I", "Tzourio, C", "Uitterlinden, A", "Vitart, V", "Voineskos, AN", "Kaprio, J", "Wagner, M", "Wagner, H", "Weinhold, L", "Wen, KH", "Widen, E", "Yang, Q", "Zhao, W", "Adams, HHH", "Arking, DE", "Bilder, RM", "Bitsios, P", "Boerwinkle, E", "Chiba-Falek, O", "Corvin, A", "Jager, PLD", "Debette, S", "Donohoe, G", "Elliott, P", "Fitzpatrick, AL", "Gill, M", "Glahn, DC", "Hägg, S", "Hansell, NK", "Hariri, AR", "Ikram, MK", "Jukema, JW", "Vuoksimaa, E", "Keller, MC", "Kremen, WS", "Launer, L", "Lindenberger, U", "Palotie, A", "Pedersen, NL", "Pendleton, N", "Porteous, DJ", "Räikkönen, K", "Raitakari, OT", "Ramirez, A", "Reinvang, I", "Rudan, I", "Rujescu, D", "Schmidt, R", "Schmidt, H", "Schofield, PW", "Schofield, PR", "Starr, JM", "Steen, VM", "Trollor, JN", "Turner, ST", "Duijn, CMV", "Villringer, A", "Weinberger, DR", "Weir, DR", "Wilson, JF", "Malhotra, A", "McIntosh, AM", "Gale, CR", "Seshadri, S", "Mosley, TH", "Bressler, J", "Lencz, T", "Deary, IJ"],
    year: 2017,
    journal: "bioRxiv",
    doi: "10.1101/176511",
    doiUrl: "http://dx.doi.org/10.1101/176511",
  },
  {
    slug: "evangelou-2017-genetic-analysis-of-over-one-million-people-identifies-535-n",
    type: "journal",
    typeLabel: "Journal article",
    title: "Genetic analysis of over one million people identifies 535 novel loci for blood pressure",
    authors: ["Evangelou, E", "Warren, HR", "Mosen-Ansorena, D", "Mifsud, B", "Pazoki, R", "Gao, H", "Ntritsos, G", "Dimou, N", "Cabrera, CP", "Karaman, I", "Ng, FL", "Evangelou, M", "Witkowska, K", "Tzanis, E", "Hellwege, JN", "Giri, A", "Velez Edwards, DR", "Sun, YV", "Cho, K", "Gaziano, JM", "Wilson, PWF", "Tsao, PS", "Kovesdy, CP", "Esko, T", "Mägi, R", "Milani, L", "Almgren, P", "Boutin, T", "Debette, S", "Ding, J", "Giulianini, F", "Holliday, EG", "Jackson, AU", "Li-Gao, R", "Lin, W-Y", "Luan, J", "Mangino, M", "Oldmeadow, C", "Prins, B", "Qian, Y", "Sargurupremraj, M", "Shah, N", "Surendran, P", "Thériault, S", "Verweij, N", "Willems, SM", "Zhao, J-H", "Amouyel, P", "Connell, J", "de Mutsert, R", "Doney, ASF", "Farrall, M", "Menni, C", "Morris, AD", "Noordam, R", "Paré, G", "Poulter, NR", "Shields, DC", "Stanton, A", "Thom, S", "Abecasis, G", "Amin, N", "Arking, DE", "Ayers, KL", "Barbieri, CM", "Batini, C", "Bis, JC", "Blake, T", "Bochud, M", "Boehnke, M", "Boerwinkle, E", "Boomsma, DI", "Bottinger, EP", "Braund, PS", "Brumat, M", "Campbell, A", "Campbell, H", "Chakravarti, A", "Chambers, JC", "Chauhan, G", "Ciullo, M", "Cocca, M", "Collins, F", "Cordell, HJ", "Davies, G", "de Borst, MH", "de Geus, EJ", "Deary, IJ", "Deelen, J", "Del Greco, FM", "Demirkale, CY", "Dörr, M", "Ehret, GB", "Elosua, R", "Enroth, S", "Erzurumluoglu, AM", "Ferreira, T", "Frånberg, M", "Franco, OH", "Gandin, I", "Gasparini, P", "Giedraitis, V", "Gieger, C", "Girotto, G", "Goel, A", "Gow, AJ", "Gudnason, V", "Guo, X", "Gyllensten, U", "Hamsten, A", "Harris, TB", "Harris, SE", "Hartman, CA", "Havulinna, AS", "Hicks, AA", "Hofer, E", "Hofman, A", "Hottenga, J-J", "Huffman, JE", "Hwang, S-J", "Ingelsson, E", "James, A", "Jansen, R", "Jarvelin, M-R", "Joehanes, R", "Johansson", "Å.", "Johnson, AD", "Joshi, PK", "Jousilahti, P", "Jukema, JW", "Jula, A", "Kähönen, M", "Kathiresan, S", "Keavney, BD", "Khaw, K-T", "Knekt, P", "Knight, J", "Kolcic, I", "Kooner, JS", "Koskinen, S", "Kristiansson, K", "Kutalik, Z", "Laan, M", "Larson, M", "Launer, LJ", "Lehne, BC", "Lehtimäki, T", "Levy, D", "Liewald, DCM", "Lin, L", "Lind, L", "Lindgren, CM", "Liu, Y", "Loos, RJF", "Lopez, LM", "Lu, L", "Lyytikäinen, L-P", "Mahajan, A", "Mamasoula, C", "Marrugat, J", "Marten, J", "Milaneschi, Y", "Morgan, A", "Morris, AP", "Morrison, AC", "Munson, PJ", "Nalls, MA", "Nandakumar, P", "Nelson, CP", "Newton-Cheh, C", "Niiranen, T", "Nolte, IM", "Nutile, T", "Oldehinkel, AJ", "Oostra, BA", "O'Reilly, PF", "Org, E", "Padmanabhan, S", "Palmas, W", "Palotie, A", "Pattie, A", "Penninx, BWJH", "Perola, M", "Peters, A", "Polasek, O", "Pramstaller, PP", "Quang Tri, N", "Raitakari, OT", "Ren, M", "Rettig, R", "Rice, K", "Ridker, PM", "Reid, JS", "Riese, H", "Ripatti, S", "Robino, A", "Rose, LM", "Rotter, JI", "Rudan, I", "Ruggiero, D", "Saba, Y", "Sala, CF", "Salomaa, V", "Samani, NJ", "Sarin, A-P", "Schmidt, R", "Schmidt, H", "Shrine, N", "Siscovick, D", "Smith, AV", "Schneider, H", "Sõber, S", "Sorice, R", "Starr, JM", "Stott, DJ", "Strachan, DP", "Strawbridge, RJ", "Sundström, J", "Swertz, MA", "Taylor, KD", "Teumer, A", "Tobin, MD", "Toniolo, D", "Traglia, M", "Trompet, S", "Tuomilehto, J", "Tzourio, C", "Uitterlinden, AG", "Vaez, A", "van der Most, PJ", "van Duijn, CM", "Vergnaud, A-C", "Verwoert, GC", "Vitart, V", "Völker, U", "Vollenweider, P", "Vuckovic, D", "Watkins, H", "Wild, SH", "Willemsen, G", "Wilson, JF", "Wright, AF", "Yao, J", "Zemunik, T", "Zhang, W", "Attia, JR", "Butterworth, AS", "Chasman, D", "Conen, D", "Cucca, F", "Danesh, J", "Hayward, C", "Howson, JMM", "Laakso, M", "Lakatta, EG", "Langenberg, C", "Melander, O", "Mook-Kanamori, DO", "Munroe, PB", "Palmer, CNA", "Risch, L", "Scott, RA", "Scott, RJ", "Sever, P", "Spector, TD", "van der Harst, P", "Wareham, NJ", "Zeggini, E", "Brown, MJ", "Metspalu, A", "Hung, AM", "O'Donnell, CJ", "Edwards, TL", "Psaty, BM", "Tzoulaki, I", "Barnes, MR", "Wain, LV", "Elliott, P", "Caulfield, MJ"],
    year: 2017,
    journal: "bioRxiv",
    doi: "10.1101/198234",
    doiUrl: "http://dx.doi.org/10.1101/198234",
  },
  {
    slug: "pazoki-2017-genetic-predisposition-to-high-blood-pressure-and-lifestyle",
    type: "journal",
    typeLabel: "Journal article",
    title: "Genetic Predisposition to High Blood Pressure and Lifestyle Factors Associations With Midlife Blood Pressure Levels and Cardiovascular Events",
    authors: ["Pazoki, R", "Dehghan, A", "Evangelou, E", "Warren, H", "Gao, H", "Caulfield, M", "Elliott, P", "Tzoulaki, I"],
    year: 2017,
    journal: "CIRCULATION",
    volume: "137",
    issue: "7",
    pages: "653 - 661",
    issn: "0009-7322",
    doi: "10.1161/CIRCULATIONAHA.117.030898",
    doiUrl: "http://dx.doi.org/10.1161/CIRCULATIONAHA.117.030898",
  },
  {
    slug: "visser-2017-no-association-between-gluten-sensitivity-and-amyotrophic-la",
    type: "journal",
    typeLabel: "Journal article",
    title: "No association between gluten sensitivity and amyotrophic lateral sclerosis",
    authors: ["Visser, AE", "Pazoki, R", "Pulit, SL", "van Rheenen, W", "Raaphorst, J", "van der Kooi, AJ", "Ricaño-Ponce, I", "Wijmenga, C", "Otten, HG", "Veldink, JH", "van den Berg, LH"],
    year: 2017,
    journal: "Journal of Neurology",
    volume: "264",
    issue: "4",
    pages: "694 - 700",
    issn: "0340-5354",
    doi: "10.1007/s00415-017-8400-8",
    doiUrl: "http://dx.doi.org/10.1007/s00415-017-8400-8",
  },
  {
    slug: "chami-2016-exome-genotyping-identifies-pleiotropic-variants-associated",
    type: "journal",
    typeLabel: "Journal article",
    title: "Exome Genotyping Identifies Pleiotropic Variants Associated with Red Blood Cell Traits",
    authors: ["Chami, N", "Chen, M-H", "Slater, AJ", "Eicher, JD", "Evangelou, E", "Tajuddin, SM", "Love-Gregory, L", "Kacprowski, T", "Schick, UM", "Nomura, A", "Giri, A", "Lessard, S", "Brody, JA", "Schurmann, C", "Pankratz, N", "Yanek, LR", "Manichaikul, A", "Pazoki, R", "Mihailov, E", "Hill, WD", "Raffield, LM", "Burt, A", "Bartz, TM", "Becker, DM", "Becker, LC", "Boerwinkle, E", "Bork-Jensen, J", "Bottinger, EP", "O’Donoghue, ML", "Crosslin, DR", "de Denus, S", "Dubé, M-P", "Elliott, P", "Engström, G", "Evans, MK", "Floyd, JS", "Fornage, M", "Gao, H", "Greinacher, A", "Gudnason, V", "Hansen, T", "Harris, TB", "Hayward, C", "Hernesniemi, J", "Highland, HM", "Hirschhorn, JN", "Hofman, A", "Irvin, MR", "Kähönen, M", "Lange, E", "Launer, LJ", "Lehtimäki, T", "Li, J", "Liewald, DCM", "Linneberg, A", "Liu, Y", "Lu, Y", "Lyytikäinen, L-P", "Mägi, R", "Mathias, RA", "Melander, O", "Metspalu, A", "Mononen, N", "Nalls, MA", "Nickerson, DA", "Nikus, K", "O’Donnell, CJ", "Orho-Melander, M", "Pedersen, O", "Petersmann, A", "Polfus, L", "Psaty, BM", "Raitakari, OT", "Raitoharju, E", "Richard, M", "Rice, KM", "Rivadeneira, F", "Rotter, JI", "Schmidt, F", "Smith, AV", "Starr, JM", "Taylor, KD", "Teumer, A", "Thuesen, BH", "Torstenson, ES", "Tracy, RP", "Tzoulaki, I", "Zakai, NA", "Vacchi-Suzzi, C", "van Duijn, CM", "van Rooij, FJA", "Cushman, M", "Deary, IJ", "Velez Edwards, DR", "Vergnaud, A-C", "Wallentin, L", "Waterworth, DM", "White, HD", "Wilson, JG", "Zonderman, AB", "Kathiresan, S", "Grarup, N", "Esko, T", "Loos, RJF", "Lange, LA", "Faraday, N", "Abumrad, NA", "Edwards, TL", "Ganesh, SK", "Auer, PL", "Johnson, AD", "Reiner, AP", "Lettre, G"],
    year: 2016,
    journal: "The American Journal of Human Genetics",
    volume: "99",
    issue: "1",
    pages: "8 - 21",
    issn: "0002-9297",
    doi: "10.1016/j.ajhg.2016.05.007",
    doiUrl: "http://dx.doi.org/10.1016/j.ajhg.2016.05.007",
  },
  {
    slug: "eicher-2016-platelet-related-variants-identified-by-exomechip-meta-analy",
    type: "journal",
    typeLabel: "Journal article",
    title: "Platelet-Related Variants Identified by Exomechip Meta-analysis in 157,293 Individuals",
    authors: ["Eicher, JD", "Chami, N", "Kacprowski, T", "Nomura, A", "Chen, M-H", "Yanek, LR", "Tajuddin, SM", "Schick, UM", "Slater, AJ", "Pankratz, N", "Polfus, L", "Schurmann, C", "Giri, A", "Brody, JA", "Lange, LA", "Manichaikul, A", "Hill, WD", "Pazoki, R", "Elliot, P", "Evangelou, E", "Tzoulaki, I", "Gao, H", "Vergnaud, A-C", "Mathias, RA", "Becker, DM", "Becker, LC", "Burt, A", "Crosslin, DR", "Lyytikäinen, L-P", "Nikus, K", "Hernesniemi, J", "Kähönen, M", "Raitoharju, E", "Mononen, N", "Raitakari, OT", "Lehtimäki, T", "Cushman, M", "Zakai, NA", "Nickerson, DA", "Raffield, LM", "Quarells, R", "Willer, CJ", "Peloso, GM", "Abecasis, GR", "Liu, DJ", "Deloukas, P", "Samani, NJ", "Schunkert, H", "Erdmann, J", "Fornage, M", "Richard, M", "Tardif, J-C", "Rioux, JD", "Dube, M-P", "de Denus, S", "Lu, Y", "Bottinger, EP", "Loos, RJF", "Smith, AV", "Harris, TB", "Launer, LJ", "Gudnason, V", "Velez Edwards, DR", "Torstenson, ES", "Liu, Y", "Tracy, RP", "Rotter, JI", "Rich, SS", "Highland, HM", "Boerwinkle, E", "Li, J", "Lange, E", "Wilson, JG", "Mihailov, E", "Mägi, R", "Hirschhorn, J", "Metspalu, A", "Esko, T", "Vacchi-Suzzi, C", "Nalls, MA", "Zonderman, AB", "Evans, MK", "Engström, G", "Orho-Melander, M", "Melander, O", "O’Donoghue, ML", "Waterworth, DM", "Wallentin, L", "White, HD", "Floyd, JS", "Bartz, TM", "Rice, KM", "Psaty, BM", "Starr, JM", "Liewald, DCM", "Hayward, C", "Deary, IJ", "Greinacher, A", "Völker, U", "Thiele, T", "Völzke, H", "van Rooij, FJA", "Uitterlinden, AG", "Franco, OH", "Dehghan, A", "Edwards, TL", "Ganesh, SK", "Kathiresan, S", "Faraday, N", "Auer, PL", "Reiner, AP", "Lettre, G", "Johnson, AD"],
    year: 2016,
    journal: "The American Journal of Human Genetics",
    volume: "99",
    issue: "1",
    pages: "40 - 55",
    issn: "0002-9297",
    doi: "10.1016/j.ajhg.2016.05.005",
    doiUrl: "http://dx.doi.org/10.1016/j.ajhg.2016.05.005",
  },
  {
    slug: "iotchkova-2016-discovery-and-refinement-of-genetic-loci-associated-with-car",
    type: "journal",
    typeLabel: "Journal article",
    title: "Discovery and refinement of genetic loci associated with cardiometabolic risk using dense imputation maps",
    authors: ["Iotchkova, V", "Huang, J", "Morris, JA", "Jain, D", "Barbieri, C", "Walter, K", "Min, JL", "Chen, L", "Astle, W", "Cocca, M", "Deelen, P", "Elding, H", "Farmaki, AE", "Franklin, CS", "Franberg, M", "Gaunt, TR", "Hofman, A", "Jiang, T", "Kleber, ME", "Lachance, G", "Luan, J", "Malerba, G", "Matchan, A", "Mead, D", "Memari, Y", "Ntalla, I", "Panoutsopoulou, K", "Pazoki, R", "Perry, JRB", "Rivadeneira, F", "Sabater-Lleal, M", "Sennblad, B", "Shin, SY", "Southam, L", "Traglia, M", "Van Dijk, F", "Van Leeuwen, EM", "Zaza, G", "Zhang, W", "Amin, N", "Butterworth, A", "Chambers, JC", "Dedoussis, G", "Dehghan, A", "Franco, OH", "Franke, L", "Frontini, M", "Gambaro, G", "Gasparini, P", "Hamsten, A", "Issacs, A", "Kooner, JS", "Kooperberg, C", "Langenberg, C", "Marz, W", "Scott, RA", "Swertz, MA", "Toniolo, D", "Uitterlinden, AG", "Van Duijn, CM", "Watkins, H", "Zeggini, E", "Maurano, MT", "Timpson, NJ", "Reiner, AP", "Auer, PL", "Soranzo, N"],
    year: 2016,
    journal: "Nature Genetics",
    volume: "48",
    issue: "11",
    pages: "1303 - 1312",
    issn: "1061-4036",
    doi: "10.1038/ng.3668",
    doiUrl: "http://dx.doi.org/10.1038/ng.3668",
  },
  {
    slug: "pankratz-2016-meta-analysis-of-rare-and-common-exome-chip-variants-identif",
    type: "journal",
    typeLabel: "Journal article",
    title: "Meta-analysis of rare and common exome chip variants identifies S1PR4 and other loci influencing blood cell traits",
    authors: ["Pankratz, N", "Schick, UM", "Zhou, Y", "Zhou, W", "Ahluwalia, TS", "Allende, ML", "Auer, PL", "Bork-Jensen, J", "Brody, JA", "Chen, MH", "Clavo, V", "Eicher, JD", "Grarup, N", "Hagedorn, EJ", "Hu, B", "Hunker, K", "Johnson, AD", "Leusink, M", "Lu, Y", "Lyytikainen, LP", "Manichaikul, A", "Marioni, RE", "Nalls, MA", "Pazoki, R", "Smith, AV", "Van Rooij, FJA", "Yang, ML", "Zhang, X", "Zhang, Y", "Asselbergs, FW", "Boerwinkle, E", "Borecki, IB", "Bottinger, EP", "Cushman, M", "De Bakker, PIW", "Deary, IJ", "Dong, L", "Feitosa, MF", "Floyd, JS", "Franceschini, N", "Franco, OH", "Garcia, ME", "Grove, ML", "Gudnason, V", "Hansen, T", "Harris, TB", "Hofman, A", "Jackson, RD", "Jia, J", "Kahonen, M", "Launer, LJ", "Lehtimaki, T", "Liewald, DC", "Linneberg, A", "Liu, Y", "Loos, RJF", "Nguyen, VM", "Numans, ME", "Pedersen, O", "Psaty, BM", "Raitakari, OT", "Rich, SS", "Rivadeneira, F", "Di Sant, AMR", "Rotter, JI", "Starr, JM", "Taylor, KD", "Thuesen, BH", "Tracy, RP", "Uitterlinden, AG", "Wang, J", "Wang, J", "Dehghan, A", "Huo, Y", "Adrienne Cupples, L", "Wilson, JG", "Proia, RL", "Zon, LI", "O'Donnell, CJ", "Reiner, AP", "Ganesh, SK"],
    year: 2016,
    journal: "Nature Genetics",
    volume: "48",
    issue: "8",
    pages: "867 - 876",
    issn: "1061-4036",
    doi: "10.1038/ng.3607",
    doiUrl: "http://dx.doi.org/10.1038/ng.3607",
  },
  {
    slug: "polfus-2016-whole-exome-sequencing-identifies-loci-associated-with-blood",
    type: "journal",
    typeLabel: "Journal article",
    title: "Whole-Exome Sequencing Identifies Loci Associated with Blood Cell Traits and Reveals a Role for Alternative GFI1B Splice Variants in Human Hematopoiesis",
    authors: ["Polfus, LM", "Khajuria, RK", "Schick, UM", "Pankratz, N", "Pazoki, R", "Brody, JA", "Chen, M-H", "Auer, PL", "Floyd, JS", "Huang, J", "Lange, L", "van Rooij, FJA", "Gibbs, RA", "Metcalf, G", "Muzny, D", "Veeraraghavan, N", "Walter, K", "Chen, L", "Yanek, L", "Becker, LC", "Peloso, GM", "Wakabayashi, A", "Kals, M", "Metspalu, A", "Esko, T", "Fox, K", "Wallace, R", "Franceschini, N", "Matijevic, N", "Rice, KM", "Bartz, TM", "Lyytikäinen, L-P", "Kähönen, M", "Lehtimäki, T", "Raitakari, OT", "Li-Gao, R", "Mook-Kanamori, DO", "Lettre, G", "van Duijn, CM", "Franco, OH", "Rich, SS", "Rivadeneira, F", "Hofman, A", "Uitterlinden, AG", "Wilson, JG", "Psaty, BM", "Soranzo, N", "Dehghan, A", "Boerwinkle, E", "Zhang, X", "Johnson, AD", "O’Donnell, CJ", "Johnsen, JM", "Reiner, AP", "Ganesh, SK", "Sankaran, VG"],
    year: 2016,
    journal: "The American Journal of Human Genetics",
    volume: "99",
    issue: "2",
    pages: "481 - 488",
    issn: "0002-9297",
    doi: "10.1016/j.ajhg.2016.06.016",
    doiUrl: "http://dx.doi.org/10.1016/j.ajhg.2016.06.016",
  },
  {
    slug: "schmidt-2016-pcsk9-genetic-variants-and-risk-of-type-2-diabetes-a-mendel",
    type: "journal",
    typeLabel: "Journal article",
    title: "PCSK9 genetic variants and risk of type 2 diabetes: a mendelian randomisation study",
    authors: ["Schmidt, AF", "Swerdlow, DI", "Holmes, MV", "Patel, RS", "Fairhurst-Hunter, Z", "Lyall, DM", "Hartwig, FP", "Horta, BL", "Hyppönen, E", "Power, C", "Moldovan, M", "van Iperen, E", "Hovingh, GK", "Demuth, I", "Norman, K", "Steinhagen-Thiessen, E", "Demuth, J", "Bertram, L", "Liu, T", "Coassin, S", "Willeit, J", "Kiechl, S", "Willeit, K", "Mason, D", "Wright, J", "Morris, R", "Wanamethee, G", "Whincup, P", "Ben-Shlomo, Y", "McLachlan, S", "Price, JF", "Kivimaki, M", "Welch, C", "Sanchez-Galvez, A", "Marques-Vidal, P", "Nicolaides, A", "Panayiotou, AG", "Onland-Moret, NC", "van der Schouw, YT", "Matullo, G", "Fiorito, G", "Guarrera, S", "Sacerdote, C", "Wareham, NJ", "Langenberg, C", "Scott, R", "Luan, J", "Bobak, M", "Malyutina, S", "Pająk, A", "Kubinova, R", "Tamosiunas, A", "Pikhart, H", "Husemoen, LLN", "Grarup, N", "Pedersen, O", "Hansen, T", "Linneberg, A", "Simonsen, KS", "Cooper, J", "Humphries, SE", "Brilliant, M", "Kitchner, T", "Hakonarson, H", "Carrell, DS", "McCarty, CA", "Kirchner, HL", "Larson, EB", "Crosslin, DR", "de Andrade, M", "Roden, DM", "Denny, JC", "Carty, C", "Hancock, S", "Attia, J", "Holliday, E", "O'Donnell, M", "Yusuf, S", "Chong, M", "Pare, G", "van der Harst, P", "Said, MA", "Eppinga, RN", "Verweij, N", "Snieder, H", "Christen, T", "Mook-Kanamori, DO", "Gustafsson, S", "Lind, L", "Ingelsson, E", "Pazoki, R", "Franco, O", "Hofman, A", "Uitterlinden, A", "Dehghan, A", "Teumer, A", "Baumeister, S", "Dörr, M", "Lerch, MM", "Völker, U"],
    year: 2016,
    journal: "The Lancet Diabetes and Endocrinology",
    volume: "5",
    issue: "2",
    pages: "97 - 105",
    issn: "2213-8587",
    doi: "10.1016/S2213-8587(16)30396-5",
    doiUrl: "http://dx.doi.org/10.1016/S2213-8587(16)30396-5",
  },
  {
    slug: "tajuddin-2016-large-scale-exome-wide-association-analysis-identifies-loci",
    type: "journal",
    typeLabel: "Journal article",
    title: "Large-Scale Exome-wide Association Analysis Identifies Loci for White Blood Cell Traits and Pleiotropy with Immune-Mediated Diseases",
    authors: ["Tajuddin, SM", "Schick, UM", "Eicher, JD", "Chami, N", "Giri, A", "Brody, JA", "Hill, WD", "Kacprowski, T", "Li, J", "Lyytikäinen, L-P", "Manichaikul, A", "Mihailov, E", "O’Donoghue, ML", "Pankratz, N", "Pazoki, R", "Polfus, LM", "Smith, AV", "Schurmann, C", "Vacchi-Suzzi, C", "Waterworth, DM", "Evangelou, E", "Yanek, LR", "Burt, A", "Chen, M-H", "van Rooij, FJA", "Floyd, JS", "Greinacher, A", "Harris, TB", "Highland, HM", "Lange, LA", "Liu, Y", "Mägi, R", "Nalls, MA", "Mathias, RA", "Nickerson, DA", "Nikus, K", "Starr, JM", "Tardif, J-C", "Tzoulaki, I", "Velez Edwards, DR", "Wallentin, L", "Bartz, TM", "Becker, LC", "Denny, JC", "Raffield, LM", "Rioux, JD", "Friedrich, N", "Fornage, M", "Gao, H", "Hirschhorn, JN", "Liewald, DCM", "Rich, SS", "Uitterlinden, A", "Bastarache, L", "Becker, DM", "Boerwinkle, E", "de Denus, S", "Bottinger, EP", "Hayward, C", "Hofman, A", "Homuth, G", "Lange, E", "Launer, LJ", "Lehtimäki, T", "Lu, Y", "Metspalu, A", "O’Donnell, CJ", "Quarells, RC", "Richard, M", "Torstenson, ES", "Taylor, KD", "Vergnaud, A-C", "Zonderman, AB", "Crosslin, DR", "Deary, IJ", "Dörr, M", "Elliott, P", "Evans, MK", "Gudnason, V", "Kähönen, M", "Psaty, BM", "Rotter, JI", "Slater, AJ", "Dehghan, A", "White, HD", "Ganesh, SK", "Loos, RJF", "Esko, T", "Faraday, N", "Wilson, JG", "Cushman, M", "Johnson, AD", "Edwards, TL", "Zakai, NA", "Lettre, G", "Reiner, AP", "Auer, PL"],
    year: 2016,
    journal: "The American Journal of Human Genetics",
    volume: "99",
    issue: "1",
    pages: "22 - 39",
    issn: "0002-9297",
    doi: "10.1016/j.ajhg.2016.05.003",
    doiUrl: "http://dx.doi.org/10.1016/j.ajhg.2016.05.003",
  },
  {
    slug: "chaker-2015-the-global-impact-of-non-communicable-diseases-on-macro-econ",
    type: "journal",
    typeLabel: "Journal article",
    title: "The global impact of non-communicable diseases on macro-economic productivity: a systematic review",
    authors: ["Chaker, L", "Falla, A", "van der Lee, SJ", "Muka, T", "Imo, D", "Jaspers, L", "Colpani, V", "Mendis, S", "Chowdhury, R", "Bramer, WM", "Pazoki, R", "Franco, OH"],
    year: 2015,
    journal: "European Journal of Epidemiology",
    volume: "30",
    issue: "5",
    pages: "357 - 395",
    issn: "0393-2990",
    doi: "10.1007/s10654-015-0026-5",
    doiUrl: "http://dx.doi.org/10.1007/s10654-015-0026-5",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/20125",
  },
  {
    slug: "jaspers-2015-the-global-impact-of-non-communicable-diseases-on-households",
    type: "journal",
    typeLabel: "Journal article",
    title: "The global impact of non-communicable diseases on households and impoverishment: a systematic review",
    authors: ["Jaspers, L", "Colpani, V", "Chaker, L", "van der Lee, SJ", "Muka, T", "Imo, D", "Mendis, S", "Chowdhury, R", "Bramer, WM", "Falla, A", "Pazoki, R", "Franco, OH"],
    year: 2015,
    journal: "European Journal of Epidemiology",
    volume: "30",
    issue: "3",
    pages: "163 - 188",
    issn: "0393-2990",
    doi: "10.1007/s10654-014-9983-3",
    doiUrl: "http://dx.doi.org/10.1007/s10654-014-9983-3",
  },
  {
    slug: "muka-2015-the-global-impact-of-non-communicable-diseases-on-healthcare",
    type: "journal",
    typeLabel: "Journal article",
    title: "The global impact of non-communicable diseases on healthcare spending and national income: a systematic review",
    authors: ["Muka, T", "Imo, D", "Jaspers, L", "Colpani, V", "Chaker, L", "van der Lee, SJ", "Mendis, S", "Chowdhury, R", "Bramer, WM", "Falla, A", "Pazoki, R", "Franco, OH"],
    year: 2015,
    journal: "European Journal of Epidemiology",
    volume: "30",
    issue: "4",
    pages: "251 - 277",
    issn: "0393-2990",
    doi: "10.1007/s10654-014-9984-2",
    doiUrl: "http://dx.doi.org/10.1007/s10654-014-9984-2",
  },
  {
    slug: "sedaghat-2014-association-of-uric-acid-genetic-risk-score-with-blood-press",
    type: "journal",
    typeLabel: "Journal article",
    title: "Association of Uric Acid Genetic Risk Score With Blood Pressure",
    authors: ["Sedaghat, S", "Pazoki, R", "Uitterlinden, AG", "Hofman, A", "Stricker, BHC", "Ikram, MA", "Franco, OH", "Dehghan, A"],
    year: 2014,
    journal: "Hypertension",
    volume: "64",
    issue: "5",
    pages: "1061 - 1066",
    issn: "0194-911X",
    doi: "10.1161/hypertensionaha.114.03757",
    doiUrl: "http://dx.doi.org/10.1161/hypertensionaha.114.03757",
  },
  {
    slug: "pazoki-2013-complex-inheritance-for-susceptibility-to-sudden-cardiac-dea",
    type: "journal",
    typeLabel: "Journal article",
    title: "Complex Inheritance for Susceptibility to Sudden Cardiac Death",
    authors: ["Pazoki, R", "Tanck, M", "Wilde, A", "Bezzina, C"],
    year: 2013,
    journal: "Current Pharmaceutical Design",
    volume: "19",
    issue: "39",
    pages: "6864 - 6872",
    issn: "1381-6128",
    doi: "10.2174/138161281939131127112906",
    doiUrl: "http://dx.doi.org/10.2174/138161281939131127112906",
  },
  {
    slug: "pazoki-2013-snps-identified-as-modulators-of-ecg-traits-in-the-general-p",
    type: "journal",
    typeLabel: "Journal article",
    title: "SNPs Identified as Modulators of ECG Traits in the General Population Do Not Markedly Affect ECG Traits during Acute Myocardial Infarction nor Ventricular Fibrillation Risk in This Condition",
    authors: ["Pazoki, R", "de Jong, JSSG", "Marsman, RF", "Bruinsma, N", "Dekker, LRC", "Wilde, AAM", "Bezzina, CR", "Tanck, MWT"],
    year: 2013,
    journal: "PLoS ONE",
    volume: "8",
    issue: "2",
    pages: "e57216 - e57216",
    issn: "1932-6203",
    doi: "10.1371/journal.pone.0057216",
    doiUrl: "http://dx.doi.org/10.1371/journal.pone.0057216",
  },
  {
    slug: "eghbali-2012-oncogenic-human-papillomavirus-genital-infection-in-southern",
    type: "journal",
    typeLabel: "Journal article",
    title: "Oncogenic human papillomavirus genital infection in southern Iranian women: population-based study versus clinic-based data",
    authors: ["Eghbali, SS", "Amirinejad, R", "Obeidi, N", "Mosadeghzadeh, S", "Vahdat, K", "Azizi, F", "Pazoki, R", "Sanjdideh, Z", "Amiri, Z", "Nabipour, I", "Zandi, K"],
    year: 2012,
    journal: "Virology Journal",
    volume: "9",
    issue: "1",
    pages: "194",
    issn: "1743-422X",
    doi: "10.1186/1743-422x-9-194",
    doiUrl: "http://dx.doi.org/10.1186/1743-422x-9-194",
  },
  {
    slug: "arking-2011-identification-of-a-sudden-cardiac-death-susceptibility-locu",
    type: "journal",
    typeLabel: "Journal article",
    title: "Identification of a Sudden Cardiac Death Susceptibility Locus at 2q24.2 through Genome-Wide Association in European Ancestry Individuals",
    authors: ["Arking, DE", "Junttila, MJ", "Goyette, P", "Huertas-Vazquez, A", "Eijgelsheim, M", "Blom, MT", "Newton-Cheh, C", "Reinier, K", "Teodorescu, C", "Uy-Evanado, A", "Carter-Monroe, N", "Kaikkonen, KS", "Kortelainen, M-L", "Boucher, G", "Lagacé, C", "Moes, A", "Zhao, X", "Kolodgie, F", "Rivadeneira, F", "Hofman, A", "Witteman, JCM", "Uitterlinden, AG", "Marsman, RF", "Pazoki, R", "Bardai, A", "Koster, RW", "Dehghan, A", "Hwang, S-J", "Bhatnagar, P", "Post, W", "Hilton, G", "Prineas, RJ", "Li, M", "Köttgen, A", "Ehret, G", "Boerwinkle, E", "Coresh, J", "Kao, WHL", "Psaty, BM", "Tomaselli, GF", "Sotoodehnia, N", "Siscovick, DS", "Burke, GL", "Marbán, E", "Spooner, PM", "Cupples, LA", "Jui, J", "Gunson, K", "Kesäniemi, YA", "Wilde, AAM", "Tardif, J-C", "O'Donnell, CJ", "Bezzina, CR", "Virmani, R", "Stricker, BHCH", "Tan, HL", "Albert, CM", "Chakravarti, A", "Rioux, JD", "Huikuri, HV", "Chugh, SS"],
    year: 2011,
    journal: "PLoS Genetics",
    volume: "7",
    issue: "6",
    pages: "e1002158 - e1002158",
    issn: "1553-7390",
    doi: "10.1371/journal.pgen.1002158",
    doiUrl: "http://dx.doi.org/10.1371/journal.pgen.1002158",
  },
  {
    slug: "bezzina-2010-genome-wide-association-study-identifies-a-susceptibility-lo",
    type: "journal",
    typeLabel: "Journal article",
    title: "Genome-wide association study identifies a susceptibility locus at 21q21 for ventricular fibrillation in acute myocardial infarction",
    authors: ["Bezzina, CR", "Pazoki, R", "Bardai, A", "Marsman, RF", "de Jong, JSSG", "Blom, MT", "Scicluna, BP", "Jukema, JW", "Bindraban, NR", "Lichtner, P", "Pfeufer, A", "Bishopric, NH", "Roden, DM", "Meitinger, T", "Chugh, SS", "Myerburg, RJ", "Jouven, X", "Kääb, S", "Dekker, LRC", "Tan, HL", "Tanck, MWT", "Wilde, AAM"],
    year: 2010,
    journal: "Nature Genetics",
    volume: "42",
    issue: "8",
    pages: "688 - 691",
    issn: "1061-4036",
    doi: "10.1038/ng.623",
    doiUrl: "http://dx.doi.org/10.1038/ng.623",
  },
  {
    slug: "pazoki-2010-genetic-basis-of-ventricular-arrhythmias",
    type: "journal",
    typeLabel: "Journal article",
    title: "Genetic Basis of Ventricular Arrhythmias",
    authors: ["Pazoki, R", "Wilde, AAM", "Bezzina, CR"],
    year: 2010,
    journal: "Current Cardiovascular Risk Reports",
    volume: "4",
    issue: "6",
    pages: "454 - 460",
    issn: "1932-9520",
    doi: "10.1007/s12170-010-0128-2",
    doiUrl: "http://dx.doi.org/10.1007/s12170-010-0128-2",
  },
  {
    slug: "nabipour-2008-relationship-among-insulinlike-growth-factor-i-concentration",
    type: "journal",
    typeLabel: "Journal article",
    title: "Relationship among insulinlike growth factor I concentrations, bone mineral density, and biochemical markers of bone turnover in postmenopausal women",
    authors: ["Nabipour, I", "Larijani, B", "Beigi, S", "Jafari, SM", "Amiri, M", "Assadi, M", "Pazoki, R", "Amiri, Z", "Sanjdideh, Z"],
    year: 2008,
    journal: "Menopause",
    volume: "15",
    issue: "5",
    pages: "934 - 939",
    issn: "1072-3714",
    doi: "10.1097/gme.0b013e31816665a7",
    doiUrl: "http://dx.doi.org/10.1097/gme.0b013e31816665a7",
  },
  {
    slug: "nabipour-2007-correlation-of-hyperhomocysteinaemia-and-chlamydia-pneumonia",
    type: "journal",
    typeLabel: "Journal article",
    title: "Correlation of Hyperhomocysteinaemia and Chlamydia Pneumoniae IgG Seropositivity with Coronary Artery Disease in a General Population",
    authors: ["Nabipour, I", "Vahdat, K", "Jafari, SM", "Amiri, M", "Shafeiae, E", "Riazi, A", "Amini, A-L", "Pazoki, R", "Sanjdideh, Z"],
    year: 2007,
    journal: "Heart, Lung and Circulation",
    volume: "16",
    issue: "6",
    pages: "416 - 422",
    issn: "1443-9506",
    doi: "10.1016/j.hlc.2007.02.100",
    doiUrl: "http://dx.doi.org/10.1016/j.hlc.2007.02.100",
  },
  {
    slug: "nabipour-2007-concurrent-increased-high-sensitivity-c-reactive-protein-and",
    type: "journal",
    typeLabel: "Journal article",
    title: "Concurrent increased high sensitivity C-reactive protein and chronic infections are associated with coronary artery disease: A population-based study",
    authors: ["Nabipour, I", "Vahdat, K", "Jafari, S", "Pazoki, R"],
    year: 2007,
    journal: "Indian Journal of Medical Sciences",
    volume: "61",
    issue: "3",
    pages: "135 - 135",
    issn: "0019-5359",
    doi: "10.4103/0019-5359.30748",
    doiUrl: "http://dx.doi.org/10.4103/0019-5359.30748",
  },
  {
    slug: "pazoki-2007-effects-of-a-community-based-healthy-heart-program-on-increa",
    type: "journal",
    typeLabel: "Journal article",
    title: "Effects of a community-based healthy heart program on increasing healthy women's physical activity: a randomized controlled trial guided by Community-based Participatory Research (CBPR)",
    authors: ["Pazoki, R", "Nabipour, I", "Seyednezami, N", "Imami, SR"],
    year: 2007,
    journal: "BMC Public Health",
    volume: "7",
    issue: "1",
    pages: "216",
    issn: "1471-2458",
    doi: "10.1186/1471-2458-7-216",
    doiUrl: "http://dx.doi.org/10.1186/1471-2458-7-216",
  },
  {
    slug: "nabipour-2006-the-association-of-metabolic-syndrome-and-chlamydia-pneumoni",
    type: "journal",
    typeLabel: "Journal article",
    title: "The association of metabolic syndrome and Chlamydia pneumoniae, helicobacter pylori, cytomegalovirus, and herpes simplex virus type 1: The Persian Gulf healthy heart study",
    authors: ["Nabipour, I", "Vahdat, K", "Jafari, S", "Pazoki, R", "Sanjdideh, Z"],
    year: 2006,
    journal: "Cardiovascular Diabetology",
    volume: "5",
    issue: "1",
    pages: "25 - 25",
    issn: "1475-2840",
    doi: "10.1186/1475-2840-5-25",
    doiUrl: "http://dx.doi.org/10.1186/1475-2840-5-25",
  },
  {
    slug: "nabipour-2004-a-school-based-intervention-to-teach-3-4-grades-children-abo",
    type: "journal",
    typeLabel: "Journal article",
    title: "A school-based intervention to teach 3-4 grades children about healthy heart; The Persian Gulf Healthy Heart Project",
    authors: ["Nabipour, I", "Imami, SR", "Mohammadi, MM", "Heidari, G", "Bahramian, F", "Azizi, F", "Khosravizadegan, Z", "Pazoki, R", "Soltanian, AR", "Ramazanzadeh, M", "Emadi, A", "Arab, J", "Larijani, B"],
    year: 2004,
    journal: "Indian Journal of Medical Sciences",
    volume: "58",
    issue: "7",
    pages: "289 - 296",
    issn: "0019-5359",
  },
];
