import type { PersonPublication } from "./publications-felicity-gavins";

export const stevenSmithPublications: PersonPublication[] = [
  {
    slug: "smith-2025-host-directed-therapy-in-diabetes-and-tuberculosis-comorbidi",
    type: "journal",
    typeLabel: "Journal article",
    title: "Host-directed therapy in diabetes and tuberculosis comorbidity toward global tuberculosis elimination",
    authors: ["Smith, SG", "Bowness, R", "Cliff, JM"],
    year: 2025,
    journal: "International Journal of Infectious Diseases",
    volume: "155",
    pages: "1 - 8",
    issn: "1201-9712",
    doi: "10.1016/j.ijid.2025.107877",
    doiUrl: "http://dx.doi.org/10.1016/j.ijid.2025.107877",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/30944",
  },
  {
    slug: "musvosvi-2023-t-cell-receptor-repertoires-associated-with-control-and-dise",
    type: "journal",
    typeLabel: "Journal article",
    title: "T cell receptor repertoires associated with control and disease progression following Mycobacterium tuberculosis infection",
    authors: ["Musvosvi, M", "Huang, H", "Wang, C", "Xia, Q", "Rozot, V", "Krishnan, A", "Acs, P", "Cheruku, A", "Obermoser, G", "Leslie, A", "Behar, SM", "Hanekom, WA", "Bilek, N", "Fisher, M", "Kaufmann, SHE", "Walzl, G", "Hatherill, M", "Davis, MM", "Scriba, TJ", "Kafaar, F", "Workman, L", "Mulenga, H", "Hughes, EJ", "Erasmus, M", "Nombida, O", "Veldsman, A", "Cloete, Y", "Abrahams, D", "Moyo, S", "Gelderbloem, S", "Tameris, M", "Geldenhuys, H", "Hussey, G", "Ehrlich, R", "Verver, S", "Geiter, L", "Black, GF", "van der Spuy, G", "Stanley, K", "Kriel, M", "Du Plessis, N", "Nene, N", "Roberts, T", "Kleynhans, L", "Gutschmidt, A", "Smith, B", "Loxton, AG", "Chegou, NN", "Tromp, G", "Tabb, D", "Ottenhoff, THM", "Klein, MR", "Haks, MC", "Franken, KLMC", "Geluk, A", "van Meijgaarden, KE", "Joosten, SA", "Boom, WH", "Thiel, B", "Mayanja-Kizza, H", "Joloba, M", "Zalwango, S", "Nsereko, M", "Okwera, B", "Kisingo, H", "Parida, SK", "Golinski, R", "Maertzdorf, J", "Weiner, J", "Jacobson, M", "Dockrell, HM", "Lalor, M", "Smith, S", "Gorak-Stolinska, P", "Hur, YG", "Lee, J-S", "Crampin, AC", "French, N", "Ngwira, B", "Ben-Smith, A", "Watkins, K", "Ambrose, L", "Simukonda, F", "Mvula, H", "Chilongo, F", "Saul, J", "Branson, K", "Suliman, S", "Mahomed, H", "Adolescent Cohort Study team.", "GC6-74 Consortium"],
    year: 2023,
    journal: "Nature Medicine",
    volume: "29",
    issue: "1",
    pages: "258 - 269",
    issn: "1078-8956",
    doi: "10.1038/s41591-022-02110-9",
    doiUrl: "http://dx.doi.org/10.1038/s41591-022-02110-9",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/29277",
  },
  {
    slug: "bitencourt-2022-induction-of-functional-specific-antibodies-igg-secreting-p",
    type: "journal",
    typeLabel: "Journal article",
    title: "Induction of Functional Specific Antibodies, IgG-Secreting Plasmablasts and Memory B Cells Following BCG Vaccination",
    authors: ["Bitencourt, J", "Peralta-Álvarez, MP", "Wilkie, M", "Jacobs, A", "Wright, D", "Salman Almujri, S", "Li, S", "Harris, SA", "Smith, SG", "Elias, SC", "White, AD", "Satti, I", "Sharpe, SS", "O’Shea, MK", "McShane, H", "Tanner, R"],
    year: 2022,
    journal: "Frontiers in Immunology",
    volume: "12",
    pages: "1 - 1",
    issn: "1664-3224",
    doi: "10.3389/fimmu.2021.798207",
    doiUrl: "http://dx.doi.org/10.3389/fimmu.2021.798207",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/24050",
  },
  {
    slug: "meier-2022-neutrophil-degranulation-netosis-and-platelet-degranulation",
    type: "journal",
    typeLabel: "Journal article",
    title: "Neutrophil degranulation, NETosis and platelet degranulation pathway genes are co-induced in whole blood up to six months before tuberculosis diagnosis",
    authors: ["Meier, S", "Seddon, JA", "Maasdorp, E", "Kleynhans, L", "du Plessis, N", "Loxton, AG", "Malherbe, ST", "Zak, DE", "Thompson, E", "Duffy, FJ", "Kaufmann, SHE", "Ottenhoff, THM", "Scriba, TJ", "Suliman, S", "Sutherland, JS", "Winter, J", "Kuivaniemi, H", "Walzl, G", "Tromp, G", "Black, GF", "van der Spuy, G", "Stanley, K", "Kriel, M", "Nene, N", "Roberts, T", "Gutschmidt, A", "Smith, B", "Chegou, NN", "Tabb, D", "Klein, MR", "Haks, MC", "Franken, KLMC", "Geluk, A", "van Meijgaarden, KE", "Joosten, SA", "Henry Boom, W", "Thiel, B", "Mayanja-Kizza, H", "Joloba, M", "Zalwango, S", "Nsereko, M", "Okwera, B", "Kisingo, H", "Parida, SK", "Golinski, R", "Maertzdorf, J", "Weiner, J", "Jacobson, M", "Dockrell, HM", "Lalor, M", "Smith, S", "Gorak-Stolinska, P", "Hur, YG", "Lee, JS", "Crampin, AC", "French, N", "Ngwira, B", "Ben-Smith, A", "Watkins, K", "Ambrose, L", "Simukonda, F", "Mvula, H", "Chilongo, F", "Saul, J", "Branson, K", "Mahomed, H", "Jane Hughes, E", "Bilek, N", "Erasmus, M", "Xasa, O", "Veldsman, A", "Downing, K", "Fisher, M", "Penn-Nicholson, A", "Mulenga, H", "Abel, B", "Bowmaker, M", "Kagina, B", "Chung, WK", "Hanekom, WA", "Sadoff, J", "Sizemore, D", "Ramachandran, S", "Barker, L", "Brennan, M", "Weichold, F", "Muller, S", "Geiter, L", "Kassa, D", "Abebe, A", "Mesele, T", "Tegbaru, B", "van Baarle, D", "Miedema, F", "Howe, R", "Mihret, A", "Aseffa, A", "Bekele, Y", "Iwnetu, R", "Tafesse, M", "GC6-74 Consortium.", "Catalysis TB Biomarkers Consortium"],
    year: 2022,
    journal: "PLoS ONE",
    volume: "17",
    issue: "12",
    pages: "1 - 24",
    issn: "1932-6203",
    doi: "10.1371/journal.pone.0278295",
    doiUrl: "http://dx.doi.org/10.1371/journal.pone.0278295",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/30150",
  },
  {
    slug: "kimuda-2020-mycobacterium-tuberculosis-infection-is-associated-with-incr",
    type: "journal",
    typeLabel: "Journal article",
    title: "Mycobacterium tuberculosis infection is associated with increased B cell responses to unrelated pathogens",
    authors: ["Kimuda, SG", "Andia-Biraro, I", "Sebina, I", "Egesa, M", "Nalwoga, A", "Smith, SG", "Bagaya, BS", "Levin, J", "Elliott, AM", "Raynes, JG", "Cose, S"],
    year: 2020,
    journal: "Scientific Reports",
    volume: "10",
    issue: "1",
    pages: "1 - 11",
    issn: "2045-2322",
    doi: "10.1038/s41598-020-71044-4",
    doiUrl: "http://dx.doi.org/10.1038/s41598-020-71044-4",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/21580",
  },
  {
    slug: "lubyayi-2020-maternal-latent-mycobacterium-tuberculosis-does-not-affect-t",
    type: "journal",
    typeLabel: "Journal article",
    title: "Maternal Latent Mycobacterium tuberculosis Does Not Affect the Infant Immune Response Following BCG at Birth: An Observational Longitudinal Study in Uganda",
    authors: ["Lubyayi, L", "Mawa, PA", "Nabakooza, G", "Nakibuule, M", "Tushabe, JV", "Serubanja, J", "Aibo, D", "Akurut, H", "Tumusiime, J", "Hasso-Agopsowicz, M", "Kaleebu, P", "Levin, J", "Dockrell, HM", "Smith, S", "Webb, EL", "Elliott, AM", "Cose, S"],
    year: 2020,
    journal: "Frontiers in Immunology",
    volume: "11",
    pages: "929",
    issn: "1664-3224",
    doi: "10.3389/fimmu.2020.00929",
    doiUrl: "http://dx.doi.org/10.3389/fimmu.2020.00929",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/20845",
  },
  {
    slug: "perez-hernandez-2020-mitochondrial-signature-in-human-monocytes-and-resistance-t",
    type: "journal",
    typeLabel: "Journal article",
    title: "Mitochondrial Signature in Human Monocytes and Resistance to Infection in C. elegans During Fumarate-Induced Innate Immune Training",
    authors: ["Pérez-Hernández, CA", "Kern, CC", "Butkeviciute, E", "McCarthy, E", "Dockrell, HM", "Moreno-Altamirano, MMB", "Aguilar-López, BA", "Bhosale, G", "Wang, H", "Gems, D", "Duchen, MR", "Smith, SG", "Sánchez-García, FJ"],
    year: 2020,
    journal: "Frontiers in Immunology",
    volume: "11",
    pages: "1715",
    issn: "1664-3224",
    doi: "10.3389/fimmu.2020.01715",
    doiUrl: "http://dx.doi.org/10.3389/fimmu.2020.01715",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/21347",
  },
  {
    slug: "duffy-2019-immunometabolic-signatures-predict-risk-of-progression-to-ac",
    type: "journal",
    typeLabel: "Journal article",
    title: "Immunometabolic signatures predict risk of progression to active tuberculosis and disease outcome",
    authors: ["Duffy, FJ", "Weiner, J", "Hansen, S", "Tabb, DL", "Suliman, S", "Thompson, E", "Maertzdorf, J", "Shankar, S", "Tromp, G", "Parida, S", "Dover, D", "Axthelm, MK", "Sutherland, JS", "Dockrell, HM", "Ottenhoff, THM", "Scriba, TJ", "Picker, LJ", "Walzl, G", "Kaufmann, SHE", "Zak, DE", "GC6-74 Consortium"],
    year: 2019,
    journal: "Frontiers in Immunology",
    volume: "10",
    issue: "MAR",
    pages: "1 - 16",
    issn: "1664-3224",
    doi: "10.3389/fimmu.2019.00527",
    doiUrl: "http://dx.doi.org/10.3389/fimmu.2019.00527",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/31628",
  },
  {
    slug: "lee-2019-in-vitro-mycobacterial-growth-inhibition-in-south-korean-adu",
    type: "journal",
    typeLabel: "Journal article",
    title: "In vitro Mycobacterial Growth Inhibition in South Korean Adults With Latent TB Infection",
    authors: ["Lee, H", "Kim, J", "Kang, YA", "Kim, DR", "Sim, B", "Zelmer, A", "Fletcher, HA", "Dockrell, HM", "Smith, SG", "Cho, S-N"],
    year: 2019,
    journal: "Frontiers in Immunology",
    volume: "10",
    issue: "APR",
    pages: "896",
    issn: "1664-3224",
    doi: "10.3389/fimmu.2019.00896",
    doiUrl: "http://dx.doi.org/10.3389/fimmu.2019.00896",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/20161",
  },
  {
    slug: "prabowo-2019-impact-of-individual-level-factors-on-ex-vivo-mycobacterial",
    type: "journal",
    typeLabel: "Journal article",
    title: "Impact of individual-level factors on Ex vivo mycobacterial growth inhibition: Associations of immune cell phenotype, cytomegalovirus-specific response and sex with immunity following BCG vaccination in humans",
    authors: ["Prabowo, SA", "Smith, SG", "Seifert, K", "Fletcher, HA"],
    year: 2019,
    journal: "Tuberculosis",
    volume: "119",
    pages: "101876 - 101876",
    issn: "1472-9792",
    doi: "10.1016/j.tube.2019.101876",
    doiUrl: "http://dx.doi.org/10.1016/j.tube.2019.101876",
  },
  {
    slug: "prabowo-2019-ruti-vaccination-enhances-inhibition-of-mycobacterial-growth",
    type: "journal",
    typeLabel: "Journal article",
    title: "RUTI vaccination enhances inhibition of mycobacterial growth ex vivo and induces a shift of monocyte phenotype in mice",
    authors: ["Prabowo, SA", "Painter, H", "Zelmer, A", "Smith, SG", "Seifert, K", "Amat, M", "Cardona, PJ", "Fletcher, HA"],
    year: 2019,
    journal: "Frontiers in Immunology",
    volume: "10",
    issue: "APR",
    pages: "894",
    issn: "1664-3224",
    doi: "10.3389/fimmu.2019.00894",
    doiUrl: "http://dx.doi.org/10.3389/fimmu.2019.00894",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/20138",
  },
  {
    slug: "tanner-2019-optimisation-harmonisation-and-standardisation-of-the-direc",
    type: "journal",
    typeLabel: "Journal article",
    title: "Optimisation, harmonisation and standardisation of the direct mycobacterial growth inhibition assay using cryopreserved human peripheral blood mononuclear cells",
    authors: ["Tanner, R", "Smith, SG", "van Meijgaarden, KE", "Giannoni, F", "Wilkie, M", "Gabriele, L", "Palma, C", "Dockrell, HM", "Ottenhoff, THM", "McShane, H"],
    year: 2019,
    journal: "Journal of Immunological Methods",
    volume: "469",
    pages: "1 - 10",
    issn: "0022-1759",
    doi: "10.1016/j.jim.2019.01.006",
    doiUrl: "http://dx.doi.org/10.1016/j.jim.2019.01.006",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/20569",
  },
  {
    slug: "butkeviciute-2018-heterologous-effects-of-infant-bcg-vaccination-potential-me",
    type: "journal",
    typeLabel: "Journal article",
    title: "Heterologous effects of infant BCG vaccination: potential mechanisms of immunity",
    authors: ["Butkeviciute, E", "Jones, CE", "Smith, SG"],
    year: 2018,
    journal: "Future Microbiology",
    volume: "13",
    issue: "10",
    pages: "1193 - 1208",
    issn: "1746-0913",
    doi: "10.2217/fmb-2018-0026",
    doiUrl: "http://dx.doi.org/10.2217/fmb-2018-0026",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/20156",
  },
  {
    slug: "hasso-agopsowicz-2018-differential-dna-methylation-of-potassium-channel-kca3-1-a",
    type: "journal",
    typeLabel: "Journal article",
    title: "Differential DNA methylation of potassium channel KCa3.1 and immune signalling pathways is associated with infant immune responses following BCG vaccination",
    authors: ["Hasso-Agopsowicz, M", "Scriba, TJ", "Hanekom, WA", "Dockrell, HM", "Smith, SG"],
    year: 2018,
    journal: "Scientific Reports",
    volume: "8",
    issue: "1",
    pages: "13086",
    issn: "2045-2322",
    doi: "10.1038/s41598-018-31537-9",
    doiUrl: "http://dx.doi.org/10.1038/s41598-018-31537-9",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/20139",
  },
  {
    slug: "oshea-2018-immunological-correlates-of-mycobacterial-growth-inhibition",
    type: "journal",
    typeLabel: "Journal article",
    title: "Immunological correlates of mycobacterial growth inhibition describe a spectrum of tuberculosis infection",
    authors: ["O’Shea, MK", "Tanner, R", "Müller, J", "Harris, SA", "Wright, D", "Stockdale, L", "Stylianou, E", "Satti, I", "Smith, SG", "Dunbar, J", "Fletcher, TE", "Dedicoat, M", "Cunningham, AF", "McShane, H"],
    year: 2018,
    journal: "Scientific Reports",
    volume: "8",
    issue: "1",
    pages: "14480",
    issn: "2045-2322",
    doi: "10.1038/s41598-018-32755-x",
    doiUrl: "http://dx.doi.org/10.1038/s41598-018-32755-x",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/20141",
  },
  {
    slug: "weiner-2018-metabolite-changes-in-blood-predict-the-onset-of-tuberculosi",
    type: "journal",
    typeLabel: "Journal article",
    title: "Metabolite changes in blood predict the onset of tuberculosis",
    authors: ["Weiner, J", "Maertzdorf, J", "Sutherland, JS", "Duffy, FJ", "Thompson, E", "Suliman, S", "McEwen, G", "Thiel, B", "Parida, SK", "Zyla, J", "Hanekom, WA", "Mohney, RP", "Boom, WH", "Mayanja-Kizza, H", "Howe, R", "Dockrell, HM", "Ottenhoff, THM", "Scriba, TJ", "Zak, DE", "Walzl, G", "Kaufmann, SHE", "Abebe, A", "Abel, B", "Adegbola, R", "Adetifa, I", "Ambrose, L", "Andersen, P", "Antonio, M", "Aseffa, A", "van Baarle, D", "Barker, L", "Bekele, Y", "Bilek, N", "Black, GF", "Bowmaker, M", "Branson, K", "Brennan, M", "Chegou, NN", "Chilongo, F", "Chung, WK", "Corrah, T", "Crampin, AC", "Doherty, M", "Dolganov, G", "Donkor, S", "Downing, K", "Fisher, M", "Franken, KLMC", "French, N", "Geiter, L", "Geluk, A", "Golinski, R", "Gorak-Stolinska, P", "Haks, MC", "Hill, P", "Hughes, J", "Hur, YG", "Iwnetu, R", "Jacobson, M", "Joloba, M", "Joosten, SA", "Kagina, B", "Kassa, D", "Kisingo, H", "Klein, MR", "Kriel, M", "Lalor, M", "Lee, JS", "Loxton, AG", "Mahomed, H", "van Meijgaarden, KE", "Mesele, T", "Miedema, F", "Mihret, A", "Mulenga, H", "Muller, S", "Mvula, H", "Nene, N", "Ngwira, B", "Nsereko, M", "Okwera, B", "Ota, M", "Penn-Nicholson, A", "Du Plessis, N", "Ramachandran, S", "Rosenkrands, I", "Sadoff, J", "Saul, J", "Schoolnik, G", "Simukonda, F", "Sizemore, D", "Smith, S", "Ben Smith, A", "van der Spuy, G", "Stanley, K", "Tabb, D", "Tafesse, M", "Tegbaru, B", "Togun, T", "Tromp, G", "The GC6-74 consortium"],
    year: 2018,
    journal: "Nature Communications",
    volume: "9",
    issue: "1",
    pages: "1 - 12",
    issn: "2041-1723",
    doi: "10.1038/s41467-018-07635-7",
    doiUrl: "http://dx.doi.org/10.1038/s41467-018-07635-7",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/30952",
  },
  {
    slug: "dockrell-2017-what-have-we-learnt-about-bcg-vaccination-in-the-last-20-yea",
    type: "journal",
    typeLabel: "Journal article",
    title: "What have we learnt about BCG vaccination in the last 20 years?",
    authors: ["Dockrell, HM", "Smith, SG"],
    year: 2017,
    journal: "Frontiers in Immunology",
    volume: "8",
    issue: "SEP",
    pages: "1134",
    issn: "1664-3224",
    doi: "10.3389/fimmu.2017.01134",
    doiUrl: "http://dx.doi.org/10.3389/fimmu.2017.01134",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/20135",
  },
  {
    slug: "smith-2017-whole-blood-profiling-of-bacillus-calmetteguerin-induced-tr",
    type: "journal",
    typeLabel: "Journal article",
    title: "Whole Blood Profiling of Bacillus Calmette–Guérin-Induced Trained Innate Immunity in Infants Identifies Epidermal Growth Factor, IL-6, Platelet-Derived Growth Factor-AB/BB, and Natural Killer Cell Activation",
    authors: ["Smith, SG", "Kleinnijenhuis, J", "Netea, MG", "Dockrell, HM"],
    year: 2017,
    journal: "Frontiers in Immunology",
    volume: "8",
    pages: "644",
    issn: "1932-6203",
    doi: "10.3389/fimmu.2017.00644",
    doiUrl: "http://dx.doi.org/10.3389/fimmu.2017.00644",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/20137",
  },
  {
    slug: "smith-2016-polyfunctional-cd4-t-cells-correlate-with-in-vitro-mycobacte",
    type: "journal",
    typeLabel: "Journal article",
    title: "Polyfunctional CD4 T-cells correlate with in vitro mycobacterial growth inhibition following Mycobacterium bovis BCG-vaccination of infants",
    authors: ["Smith, SG", "Zelmer, A", "Blitz, R", "Fletcher, HA", "Dockrell, HM"],
    year: 2016,
    journal: "Vaccine",
    volume: "34",
    issue: "44",
    pages: "5298 - 5305",
    issn: "0264-410X",
    doi: "10.1016/j.vaccine.2016.09.002",
    doiUrl: "http://dx.doi.org/10.1016/j.vaccine.2016.09.002",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/20155",
  },
  {
    slug: "biraro-2015-effect-of-isoniazid-preventive-therapy-on-immune-responses-t",
    type: "journal",
    typeLabel: "Journal article",
    title: "Effect of isoniazid preventive therapy on immune responses to mycobacterium tuberculosis: an open label randomised, controlled, exploratory study",
    authors: ["Biraro, IA", "Egesa, M", "Kimuda, S", "Smith, SG", "Toulza, F", "Levin, J", "Joloba, M", "Katamba, A", "Cose, S", "Dockrell, HM", "Elliott, AM"],
    year: 2015,
    journal: "BMC Infectious Diseases",
    volume: "15",
    issue: "1",
    pages: "438",
    issn: "1471-2334",
    doi: "10.1186/s12879-015-1201-8",
    doiUrl: "http://dx.doi.org/10.1186/s12879-015-1201-8",
  },
  {
    slug: "smith-2015-intracellular-cytokine-staining-and-flow-cytometry-consider",
    type: "journal",
    typeLabel: "Journal article",
    title: "Intracellular Cytokine Staining and Flow Cytometry: Considerations for Application in Clinical Trials of Novel Tuberculosis Vaccines",
    authors: ["Smith, SG", "Smits, K", "Joosten, SA", "van Meijgaarden, KE", "Satti, I", "Fletcher, HA", "Caccamo, N", "Dieli, F", "Mascart, F", "McShane, H", "Dockrell, HM", "Ottenhoff, THM"],
    year: 2015,
    journal: "PLOS ONE",
    volume: "10",
    issue: "9",
    pages: "e0138042 - e0138042",
    issn: "1932-6203",
    doi: "10.1371/journal.pone.0138042",
    doiUrl: "http://dx.doi.org/10.1371/journal.pone.0138042",
  },
  {
    slug: "biraro-2014-impact-of-co-infections-and-bcg-immunisation-on-immune-respo",
    type: "journal",
    typeLabel: "Journal article",
    title: "Impact of Co-Infections and BCG Immunisation on Immune Responses among Household Contacts of Tuberculosis Patients in a Ugandan Cohort",
    authors: ["Biraro, IA", "Egesa, M", "Toulza, F", "Levin, J", "Cose, S", "Joloba, M", "Smith, S", "Dockrell, HM", "Katamba, A", "Elliott, AM"],
    year: 2014,
    journal: "PLoS ONE",
    volume: "9",
    issue: "11",
    pages: "e111517 - e111517",
    issn: "1932-6203",
    doi: "10.1371/journal.pone.0111517",
    doiUrl: "http://dx.doi.org/10.1371/journal.pone.0111517",
  },
  {
    slug: "sebina-2012-long-lived-memory-b-cell-responses-following-bcg-vaccination",
    type: "journal",
    typeLabel: "Journal article",
    title: "Long-Lived Memory B-Cell Responses following BCG Vaccination",
    authors: ["Sebina, I", "Cliff, JM", "Smith, SG", "Nogaro, S", "Webb, EL", "Riley, EM", "Dockrell, HM", "Elliott, AM", "Hafalla, JCR", "Cose, S"],
    year: 2012,
    journal: "PLoS ONE",
    volume: "7",
    issue: "12",
    pages: "e51381 - e51381",
    issn: "1932-6203",
    doi: "10.1371/journal.pone.0051381",
    doiUrl: "http://dx.doi.org/10.1371/journal.pone.0051381",
  },
  {
    slug: "lalor-2011-bcg-vaccination-induces-different-cytokine-profiles-followin",
    type: "journal",
    typeLabel: "Journal article",
    title: "BCG Vaccination Induces Different Cytokine Profiles Following Infant BCG Vaccination in the UK and Malawi",
    authors: ["Lalor, MK", "Floyd, S", "Gorak-Stolinska, P", "Ben-Smith, A", "Weir, RE", "Smith, SG", "Newport, MJ", "Blitz, R", "Mvula, H", "Branson, K", "McGrath, N", "Crampin, AC", "Fine, PE", "Dockrell, HM"],
    year: 2011,
    journal: "The Journal of Infectious Diseases",
    volume: "204",
    issue: "7",
    pages: "1075 - 1085",
    issn: "0022-1899",
    doi: "10.1093/infdis/jir515",
    doiUrl: "http://dx.doi.org/10.1093/infdis/jir515",
  },
  {
    slug: "lalor-2010-complex-cytokine-profiles-induced-by-bcg-vaccination-in-uk-i",
    type: "journal",
    typeLabel: "Journal article",
    title: "Complex cytokine profiles induced by BCG vaccination in UK infants",
    authors: ["Lalor, MK", "Smith, SG", "Floyd, S", "Gorak-Stolinska, P", "Weir, RE", "Blitz, R", "Branson, K", "Fine, PE", "Dockrell, HM"],
    year: 2010,
    journal: "Vaccine",
    volume: "28",
    issue: "6",
    pages: "1635 - 1641",
    issn: "0264-410X",
    doi: "10.1016/j.vaccine.2009.11.004",
    doiUrl: "http://dx.doi.org/10.1016/j.vaccine.2009.11.004",
  },
  {
    slug: "smith-2010-mycobacterium-tuberculosis-ppd-induced-immune-biomarkers-mea",
    type: "journal",
    typeLabel: "Journal article",
    title: "Mycobacterium tuberculosis PPD-induced immune biomarkers measurable in vitro following BCG vaccination of UK adolescents by multiplex bead array and intracellular cytokine staining",
    authors: ["Smith, SG", "Lalor, MK", "Gorak-Stolinska, P", "Blitz, R", "Beveridge, NER", "Worth, A", "McShane, H", "Dockrell, HM"],
    year: 2010,
    journal: "BMC Immunology",
    volume: "11",
    issue: "1",
    pages: "35 - 35",
    issn: "1471-2172",
    doi: "10.1186/1471-2172-11-35",
    doiUrl: "http://dx.doi.org/10.1186/1471-2172-11-35",
  },
  {
    slug: "smith-2009-identification-of-major-factors-influencing-elispot-based-mo",
    type: "journal",
    typeLabel: "Journal article",
    title: "Identification of major factors influencing ELISpot-based monitoring of cellular responses to antigens from Mycobacterium tuberculosis.",
    authors: ["Smith, SG", "Joosten, SA", "Verscheure, V", "Pathan, AA", "McShane, H", "Ottenhoff, TH", "Dockrell, HM", "Mascart, F"],
    year: 2009,
    journal: "PLoS One",
    volume: "4",
    issue: "11",
    pages: "e7972 - e7972",
    issn: "1932-6203",
    doi: "10.1371/journal.pone.0007972",
    doiUrl: "http://dx.doi.org/10.1371/journal.pone.0007972",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/4683",
  },
  {
    slug: "lin-2007-lack-of-immune-responses-tomycobacterium-tuberculosisdosr-re",
    type: "journal",
    typeLabel: "Journal article",
    title: "Lack of Immune Responses toMycobacterium tuberculosisDosR Regulon Proteins followingMycobacterium bovisBCG Vaccination",
    authors: ["Lin, MY", "Geluk, A", "Smith, SG", "Stewart, AL", "Friggen, AH", "Franken, KLMC", "Verduyn, MJC", "van Meijgaarden, KE", "Voskuil, MI", "Dockrell, HM", "Huygen, K", "Ottenhoff, THM", "Klein, MR"],
    year: 2007,
    journal: "Infection and Immunity",
    volume: "75",
    issue: "7",
    pages: "3523 - 3530",
    issn: "0019-9567",
    doi: "10.1128/iai.01999-06",
    doiUrl: "http://dx.doi.org/10.1128/iai.01999-06",
  },
];
