import type { PersonPublication } from "./publications-felicity-gavins";

export const camillaCeruttiPublications: PersonPublication[] = [
  {
    slug: "chaudhry-2025-phosphatidylinositol4-5bisphosphate-3kinase-pi3k-inhibit",
    type: "journal",
    typeLabel: "Journal article",
    title: "Phosphatidylinositol‐4,5‐bisphosphate 3‐kinase(PI3K) inhibitors reduce vascular inflammationin vitroandin vivo",
    authors: ["Chaudhry, H", "Zarban, AA", "Trevelin, SC", "Kodji, X", "Cerutti, C", "Xiong, X", "Argunhan, F", "Shah, AM", "Ridley, AJ", "Brain, SD"],
    year: 2025,
    journal: "British Journal of Pharmacology",
    volume: "182",
    issue: "24",
    pages: "6028 - 6042",
    issn: "0007-1188",
    doi: "10.1111/bph.70152",
    doiUrl: "http://dx.doi.org/10.1111/bph.70152",
  },
  {
    slug: "cerutti-2024-iqgap1-and-nwasp-promote-human-cancer-cell-dissemination-and",
    type: "journal",
    typeLabel: "Journal article",
    title: "IQGAP1 and NWASP promote human cancer cell dissemination and metastasis by regulating β1-integrin via FAK and MRTF/SRF",
    authors: ["Cerutti, C", "Lucotti, S", "Menendez, ST", "Reymond, N", "Garg, R", "Romero, IA", "Muschel, R", "Ridley, AJ"],
    year: 2024,
    journal: "Cell Reports",
    volume: "43",
    issue: "4",
    pages: "1 - 48",
    issn: "2639-1856",
    doi: "10.1016/j.celrep.2024.113989",
    doiUrl: "http://dx.doi.org/10.1016/j.celrep.2024.113989",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/28701",
  },
  {
    slug: "kakogiannos-2024-gpr126-is-a-specifier-of-blood-brain-barrier-formation-in-th",
    type: "journal",
    typeLabel: "Journal article",
    title: "GPR126 is a specifier of blood-brain barrier formation in the mouse central nervous system",
    authors: ["Kakogiannos, N", "Scalise, AA", "Martini, E", "Maderna, C", "Benvenuto, AF", "D’Antonio, M", "Carmignani, L", "Magni, S", "Gullotta, GS", "Lampugnani, MG", "Iannelli, F", "Beznoussenko, GV", "Mironov, AA", "Cerutti, C", "Bentley, K", "Philippides, A", "Zanardi, F", "Bacigaluppi, M", "Sigismund, S", "Bassani, C", "Farina, C", "Martino, G", "De Giovanni, M", "Dejana, E", "Iannacone, M", "Inverso, D", "Giannotta, M"],
    year: 2024,
    journal: "Journal of Clinical Investigation",
    volume: "134",
    issue: "15",
    pages: "1 - 17",
    issn: "0021-9738",
    doi: "10.1172/jci165368",
    doiUrl: "http://dx.doi.org/10.1172/jci165368",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/29507",
  },
  {
    slug: "owens-2024-alzheimer-s-disease-associated-p460l-variant-of-epha1-dysreg",
    type: "journal",
    typeLabel: "Journal article",
    title: "Alzheimer's disease-associated P460L variant of EphA1 dysregulates receptor activity and blood-brain barrier function",
    authors: ["Owens, HA", "Thorburn, LE", "Walsby, E", "Moon, OR", "Rizkallah, P", "Sherwani, S", "Tinsley, CL", "Rogers, L", "Cerutti, C", "Ridley, AJ", "Williams, J", "Knäuper, V", "Ager, A"],
    year: 2024,
    journal: "Alzheimer's and Dementia",
    volume: "0",
    issue: "ahead of print",
    pages: "1 - 18",
    issn: "1552-5260",
    doi: "10.1002/alz.13603",
    doiUrl: "http://dx.doi.org/10.1002/alz.13603",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/28177",
  },
  {
    slug: "campanile-2023-bone-marrow-vasculature-advanced-in-vitro-models-for-cancer",
    type: "journal",
    typeLabel: "Journal article",
    title: "Bone marrow vasculature advanced in vitro models for cancer and cardiovascular research",
    authors: ["Campanile, M", "Bettinelli, L", "Cerutti, C", "Spinetti, G"],
    year: 2023,
    journal: "Frontiers in Cardiovascular Medicine",
    volume: "10",
    pages: "1261849 - 1261849",
    issn: "2297-055X",
    doi: "10.3389/fcvm.2023.1261849",
    doiUrl: "http://dx.doi.org/10.3389/fcvm.2023.1261849",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/27500",
  },
  {
    slug: "cerutti-2023-single-cell-imaging-and-transcriptomic-analyses-of-firm-adhe",
    type: "journal",
    typeLabel: "Journal article",
    title: "Single-cell imaging and transcriptomic analyses of firm adhesion between patient-derived cancer and endothelial cells under shear stress",
    authors: ["Cerutti, C", "Luzi, L", "De Michele, G", "Gambino, V", "Migliaccio, E", "Pelicci, PG"],
    year: 2023,
    journal: "Open Research Europe",
    volume: "3",
    pages: "1 - 14",
    doi: "10.12688/openreseurope.15989.1",
    doiUrl: "http://dx.doi.org/10.12688/openreseurope.15989.1",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/27499",
  },
  {
    slug: "ferrari-2023-a-method-to-generate-perfusable-physiologic-like-vascular-ch",
    type: "journal",
    typeLabel: "Journal article",
    title: "A method to generate perfusable physiologic-like vascular channels within a liver-on-chip model",
    authors: ["Ferrari, E", "Monti, E", "Cerutti, C", "Visone, R", "Occhetta, P", "Griffith, LG", "Rasponi, M"],
    year: 2023,
    journal: "Biomicrofluidics",
    volume: "17",
    issue: "6",
    pages: "1 - 12",
    issn: "1932-1058",
    doi: "10.1063/5.0170606",
    doiUrl: "http://dx.doi.org/10.1063/5.0170606",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/27861",
  },
  {
    slug: "cerutti-2022-an-in-vitro-blood-brain-barrier-model-to-study-firm-shear-st",
    type: "book-chapter",
    typeLabel: "Book chapter",
    title: "An In Vitro Blood-Brain Barrier Model to Study Firm Shear Stress-Resistant Leukocyte Adhesion to Human Brain Endothelial Cells",
    authors: ["Cerutti, C", "Romero, IA"],
    year: 2022,
    journal: "Methods in Molecular Biology.",
    pages: "315 - 331",
  },
  {
    slug: "unknown-2021-metastasis",
    type: "book",
    typeLabel: "Book",
    title: "Metastasis",
    authors: [],
    year: 2021,
    journal: "'Metastasis'",
  },
  {
    slug: "cerutti-2021-analyzing-the-roles-of-rho-gtpases-in-cancer-cell-adhesion-t",
    type: "book-chapter",
    typeLabel: "Book chapter",
    title: "Analyzing the Roles of Rho GTPases in Cancer Cell Adhesion to Endothelial Cells Under Flow Conditions",
    authors: ["Cerutti, C", "Ridley, AJ"],
    year: 2021,
    journal: "Methods in Molecular Biology.",
    pages: "93 - 109",
  },
  {
    slug: "gerigk-2021-on-chip-perivascular-niche-supporting-stemness-of-patient-de",
    type: "journal",
    typeLabel: "Journal article",
    title: "On-chip perivascular niche supporting stemness of patient-derived glioma cells in a serum-free, flowable culture",
    authors: ["Gerigk, M", "Bulstrode, H", "Shi, HH", "Tönisen, F", "Cerutti, C", "Morrison, G", "Rowitch, D", "Huang, YYS"],
    year: 2021,
    journal: "Lab on a Chip",
    volume: "21",
    issue: "12",
    pages: "2343 - 2358",
    issn: "1473-0197",
    doi: "10.1039/d1lc00271f",
    doiUrl: "http://dx.doi.org/10.1039/d1lc00271f",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/27370",
  },
  {
    slug: "lucotti-2019-aspirin-blocks-formation-of-metastatic-intravascular-niches",
    type: "journal",
    typeLabel: "Journal article",
    title: "Aspirin blocks formation of metastatic intravascular niches by inhibiting platelet-derived COX-1/ thromboxane A2",
    authors: ["Lucotti, S", "Cerutti, C", "Soyer, M", "Gil-Bernabé, AM", "Gomes, AL", "Allen, PD", "Smart, S", "Markelc, B", "Watson, K", "Armstrong, PC", "Mitchell, JA", "Warner, TD", "Ridley, AJ", "Muschel, RJ"],
    year: 2019,
    journal: "Journal of Clinical Investigation",
    volume: "129",
    issue: "5",
    pages: "1845 - 1862",
    issn: "0021-9738",
    doi: "10.1172/JCI121985",
    doiUrl: "http://dx.doi.org/10.1172/JCI121985",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/29516",
  },
  {
    slug: "cerutti-2017-endothelial-cell-cell-adhesion-and-signaling",
    type: "journal",
    typeLabel: "Journal article",
    title: "Endothelial cell-cell adhesion and signaling",
    authors: ["Cerutti, C", "Ridley, AJ"],
    year: 2017,
    journal: "Experimental Cell Research",
    volume: "358",
    issue: "1",
    pages: "31 - 38",
    issn: "0014-4827",
    doi: "10.1016/j.yexcr.2017.06.003",
    doiUrl: "http://dx.doi.org/10.1016/j.yexcr.2017.06.003",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/29528",
  },
  {
    slug: "cerutti-2017-mir-126-and-mir-126-regulate-shear-resistant-firm-leukocyte",
    type: "journal",
    typeLabel: "Journal article",
    title: "MiR-126 and miR-126∗ regulate shear-resistant firm leukocyte adhesion to human brain endothelium",
    authors: ["Cerutti, C", "Edwards, LJ", "De Vries, HE", "Sharrack, B", "Male, DK", "Romero, IA"],
    year: 2017,
    journal: "Scientific Reports",
    volume: "7",
    issue: "1",
    pages: "1 - 14",
    issn: "2045-2322",
    doi: "10.1038/srep45284",
    doiUrl: "http://dx.doi.org/10.1038/srep45284",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/29529",
  },
  {
    slug: "roig-carles-2017-micrornas-in-brain-endothelium-and-inflammation",
    type: "book-chapter",
    typeLabel: "Book chapter",
    title: "microRNAs in Brain Endothelium and Inflammation",
    authors: ["Roig-Carles, D", "Cerutti, C", "Lopez-Ramirez, MA", "Wu, D", "Male, DK", "de Vries, HE", "Romero, IA"],
    year: 2017,
    journal: "The Blood Brain Barrier and Inflammation.",
    pages: "153 - 173",
  },
  {
    slug: "cerutti-2016-microrna-155-contributes-to-shear-resistant-leukocyte-adhesi",
    type: "journal",
    typeLabel: "Journal article",
    title: "MicroRNA-155 contributes to shear-resistant leukocyte adhesion to human brain endothelium in vitro",
    authors: ["Cerutti, C", "Soblechero-Martin, P", "Wu, D", "Lopez-Ramirez, MA", "de Vries, H", "Sharrack, B", "Male, DK", "Romero, IA"],
    year: 2016,
    journal: "Fluids and Barriers of the CNS",
    volume: "13",
    issue: "1",
    pages: "1 - 7",
    issn: "2045-8118",
    doi: "10.1186/s12987-016-0032-3",
    doiUrl: "http://dx.doi.org/10.1186/s12987-016-0032-3",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/29530",
  },
  {
    slug: "pascual-baixauli-2016-pro-inflammatory-cytokines-promote-adhesion-of-breast-tumo",
    type: "conference",
    typeLabel: "Conference paper",
    title: "Pro-inflammatory cytokines promote adhesion of breast tumour cells to brain endothelium",
    authors: ["Pascual-Baixauli, E", "Cerutti, C", "Garattini, E", "Romero, IA", "Crea, F"],
    year: 2016,
  },
  {
    slug: "chiacchia-2015-zinc-imidazolate-polymers-zips-as-a-potential-carrier-to-b",
    type: "journal",
    typeLabel: "Journal article",
    title: "Zinc-imidazolate polymers (ZIPs) as a potential carrier to brain capillary endothelial cells",
    authors: ["Chiacchia, M", "Cerutti, C", "Gromnicova, R", "Rietdorf, K", "Romero, IA", "Bradshaw, D"],
    year: 2015,
    journal: "Journal of Materials Chemistry B",
    volume: "3",
    issue: "46",
    pages: "9053 - 9059",
    issn: "2050-750X",
    doi: "10.1039/c5tb01814e",
    doiUrl: "http://dx.doi.org/10.1039/c5tb01814e",
  },
  {
    slug: "wu-2015-brain-endothelial-mir-146a-negatively-modulates-t-cell-adhes",
    type: "journal",
    typeLabel: "Journal article",
    title: "Brain Endothelial miR-146a Negatively Modulates T-Cell Adhesion through Repressing Multiple Targets to Inhibit NF-κB Activation",
    authors: ["Wu, D", "Cerutti, C", "Lopez-Ramirez, MA", "Pryce, G", "King-Robson, J", "Simpson, JE", "van der Pol, SMA", "Hirst, MC", "de Vries, HE", "Sharrack, B", "Baker, D", "Male, DK", "Michael, GJ", "Romero, IA"],
    year: 2015,
    journal: "Journal of Cerebral Blood Flow & Metabolism",
    volume: "35",
    issue: "3",
    pages: "412 - 423",
    issn: "0271-678X",
    doi: "10.1038/jcbfm.2014.207",
    doiUrl: "http://dx.doi.org/10.1038/jcbfm.2014.207",
  },
  {
    slug: "cerutti-2012-mir-126-and-mir-126-play-a-role-in-flow-based-leukocyte-adhe",
    type: "conference",
    typeLabel: "Conference paper",
    title: "MiR-126 and miR-126*play a role in flow-based leukocyte adhesion on cytokine-activated human brain microvascular endothelium in vitro",
    authors: ["Cerutti, C", "Lopez, A", "Hirst, M", "Sharrack, B", "Male, D", "Romero, I"],
    year: 2012,
  },
  {
    slug: "caffarel-2010-cannabinoids-reduce-erbb2-driven-breast-cancer-progression-t",
    type: "journal",
    typeLabel: "Journal article",
    title: "Cannabinoids reduce ErbB2-driven breast cancer progression through Akt inhibition",
    authors: ["Caffarel, MM", "Andradas, C", "Mira, E", "Pérez-Gómez, E", "Cerutti, C", "Moreno-Bueno, G", "Flores, JM", "García-Real, I", "Palacios, J", "Mañes, S", "Guzmán, M", "Sánchez, C"],
    year: 2010,
    journal: "Molecular Cancer",
    volume: "9",
    issue: "1",
    pages: "196",
    issn: "1476-4598",
    doi: "10.1186/1476-4598-9-196",
    doiUrl: "http://dx.doi.org/10.1186/1476-4598-9-196",
  },
  {
    slug: "caffarel-2008-jund-is-involved-in-the-antiproliferative-effect-of-9-tetra",
    type: "journal",
    typeLabel: "Journal article",
    title: "JunD is involved in the antiproliferative effect of Δ9-tetrahydrocannabinol on human breast cancer cells",
    authors: ["Caffarel, MM", "Moreno-Bueno, G", "Cerutti, C", "Palacios, J", "Guzman, M", "Mechta-Grigoriou, F", "Sanchez, C"],
    year: 2008,
    journal: "Oncogene",
    volume: "27",
    issue: "37",
    pages: "5033 - 5044",
    issn: "0950-9232",
    doi: "10.1038/onc.2008.145",
    doiUrl: "http://dx.doi.org/10.1038/onc.2008.145",
  },
];
