export type PersonPublication = {
  slug: string;
  type: "journal" | "conference" | "book-chapter" | "book" | "thesis" | "other";
  typeLabel?: string;
  title: string;
  authors: string[];
  year: number;
  journal?: string;
  volume?: string;
  issue?: string;
  pages?: string;
  issn?: string;
  doi?: string;
  doiUrl?: string;
  openAccessUrl?: string;
};

export const felicityGavinsPublications: PersonPublication[] = [
  {
    slug: "becker-2025-a-critical-role-for-monocytes-macrophages-during-intestinal",
    type: "journal",
    typeLabel: "Journal article",
    title: "A Critical Role for Monocytes/Macrophages During Intestinal Inflammation-associated Lymphangiogenesis",
    authors: ["Becker, F", "Kurmaeva, E", "Gavins, FNE", "Stevenson, EV", "Navratil, AR", "Jin, L", "Tsunoda, I", "Orr, AW", "Alexander, JS", "Ostanin, DV"],
    year: 2025,
    journal: "Inflammatory Bowel Diseases",
    volume: "22",
    issue: "6",
    pages: "1326 - 1345",
    issn: "1078-0998",
    doi: "10.1097/mib.0000000000000731",
    doiUrl: "http://dx.doi.org/10.1097/mib.0000000000000731",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/31639",
  },
  {
    slug: "ahmad-2024-exploring-the-role-of-platelets-in-virus-induced-inflammator",
    type: "journal",
    typeLabel: "Journal article",
    title: "Exploring the Role of Platelets in Virus-Induced Inflammatory Demyelinating Disease and Myocarditis",
    authors: ["Ahmad, I", "Omura, S", "Sato, F", "Park, A-M", "Khadka, S", "Gavins, FNE", "Tanaka, H", "Kimura, MY", "Tsunoda, I"],
    year: 2024,
    journal: "International Journal of Molecular Sciences",
    volume: "25",
    issue: "6",
    pages: "1 - 25",
    issn: "1661-6596",
    doi: "10.3390/ijms25063460",
    doiUrl: "http://dx.doi.org/10.3390/ijms25063460",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/28737",
  },
  {
    slug: "gerke-2024-annexins-a-family-of-proteins-with-distinctive-tastes-for-ce",
    type: "journal",
    typeLabel: "Journal article",
    title: "Annexins-a family of proteins with distinctive tastes for cell signaling and membrane dynamics",
    authors: ["Gerke, V", "Gavins, FNE", "Geisow, M", "Grewal, T", "Jaiswal, JK", "Nylandsted, J", "Rescher, U"],
    year: 2024,
    journal: "Nature communications",
    volume: "15",
    issue: "1",
    pages: "1 - 15",
    issn: "2041-1723",
    doi: "10.1038/s41467-024-45954-0",
    doiUrl: "http://dx.doi.org/10.1038/s41467-024-45954-0",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/28495",
  },
  {
    slug: "ansari-2023-regulating-neutrophil-pad4-nox-dependent-cerebrovasular-thro",
    type: "journal",
    typeLabel: "Journal article",
    title: "Regulating Neutrophil PAD4/NOX-Dependent Cerebrovasular Thromboinflammation",
    authors: ["Ansari, J", "Vital, SA", "Yadav, S", "Gavins, FNE"],
    year: 2023,
    journal: "International Journal of Biological Sciences",
    volume: "19",
    issue: "3",
    pages: "852 - 864",
    issn: "1449-2288",
    doi: "10.7150/ijbs.77434",
    doiUrl: "http://dx.doi.org/10.7150/ijbs.77434",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/26592",
  },
  {
    slug: "gibson-2023-skeletal-muscle-angiogenic-regulatory-and-heat-shock-protei",
    type: "journal",
    typeLabel: "Journal article",
    title: "Skeletal muscle angiogenic, regulatory and heat shock protein responses to prolonged passive hyperthermia of the human lower limb",
    authors: ["Gibson, OR", "Astin, R", "Puthucheary, Z", "Preston, S", "Yadav, S", "Gavins, FNE", "González-Alonso, J"],
    year: 2023,
    journal: "American Journal of Physiology: Regulatory, Integrative and Comparative Physiology",
    volume: "324",
    issue: "1",
    pages: "R1 - R14",
    issn: "0363-6119",
    doi: "10.1152/ajpregu.00320.2021",
    doiUrl: "http://dx.doi.org/10.1152/ajpregu.00320.2021",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/25617",
  },
  {
    slug: "sparkenbaugh-2023-factor-xii-contributes-to-thrombotic-complications-and-vaso",
    type: "journal",
    typeLabel: "Journal article",
    title: "Factor XII contributes to thrombotic complications and vaso-occlusion in sickle cell disease",
    authors: ["Sparkenbaugh, EM", "Henderson, MW", "Miller-Awe, M", "Abrams, C", "Ilich, A", "Trebak, F", "Ramadas, N", "Vital, S", "Bohinc, D", "Bane, KL", "Chen, C", "Patel, M", "Wallisch, M", "Renné, T", "Gruber, A", "Cooley, B", "Gailani, D", "Kasztan, M", "Vercellotti, GM", "Belcher, JD", "Gavins, FE", "Stavrou, EX", "Key, NS", "Pawlinski, R"],
    year: 2023,
    journal: "Blood",
    volume: "141",
    issue: "15",
    pages: "1871 - 1883",
    issn: "0006-4971",
    doi: "10.1182/blood.2022017074",
    doiUrl: "http://dx.doi.org/10.1182/blood.2022017074",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/26438",
  },
  {
    slug: "becker-2022-bryostatin-1-attenuates-ischemia-elicited-neutrophil-transmi",
    type: "journal",
    typeLabel: "Journal article",
    title: "Bryostatin-1 Attenuates Ischemia-Elicited Neutrophil Transmigration and Ameliorates Graft Injury after Kidney Transplantation",
    authors: ["Becker, F", "Kebschull, L", "Rieger, C", "Mohr, A", "Heitplatz, B", "Van Marck, V", "Hansen, U", "Ansari, J", "Reuter, S", "Strücker, B", "Pascher, A", "Brockmann, JG", "Castor, T", "Alexander, JS", "Gavins, FNE"],
    year: 2022,
    journal: "Cells",
    volume: "11",
    issue: "6",
    pages: "1 - 19",
    issn: "2073-4409",
    doi: "10.3390/cells11060948",
    doiUrl: "http://dx.doi.org/10.3390/cells11060948",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/24289",
  },
  {
    slug: "clerbaux-2022-covid-19-through-adverse-outcome-pathways-building-networks",
    type: "journal",
    typeLabel: "Journal article",
    title: "COVID-19 through Adverse Outcome Pathways: Building networks to better understand the disease - 3rd CIAO AOP Design Workshop",
    authors: ["Clerbaux, L-A", "Amigó, N", "Amorim, MJ", "Bal-Price, A", "Batista Leite, S", "Beronius, A", "Bezemer, GFG", "Bostroem, A-C", "Carusi, A", "Coecke, S", "Concha, R", "Daskalopoulos, EP", "Debernardi, F", "Edrosa, E", "Edwards, SW", "Filipovska, J", "Garcia-Reyero, N", "Gavins, FNE", "Halappanavar, S", "Hargreaves, AJ", "Hogberg, HT", "Huynh, MT", "Jacobson, D", "Josephs-Spaulding, J", "Kim, YJ", "Kong, HJ", "Krebs, CE", "Lam, A", "Landesmann, B", "Layton, AR", "Lee, YO", "Macmillan, DS", "Mantovani, A", "Margiotta-Casaluci, L", "Martens, M", "Masereeuw, R", "Mayasich, SA", "Mei, LM", "Mortensen, H", "Munoz Pineiro, A", "Nymark, P", "Ohayon, E", "Ojasi, JM", "Paini, A", "Parissis, N", "Parvatam, S", "Pistollato, F", "Sachana, M", "Sørli, JB", "Sullivan, KM", "Sund, J", "Tanabe, S", "Tsaioun, K", "Vinken, M", "Viviani, L", "Waspe, J", "Willett, C", "Wittwehr, C"],
    year: 2022,
    journal: "ALTEX : Alternatives to Animal Experimentation",
    volume: "39",
    issue: "2",
    pages: "322 - 335",
    issn: "0946-7785",
    doi: "10.14573/altex.2112161",
    doiUrl: "http://dx.doi.org/10.14573/altex.2112161",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/25755",
  },
  {
    slug: "gavins-2022-promoting-the-resolution-of-thromboinflammation",
    type: "conference",
    typeLabel: "Conference paper",
    title: "Promoting the Resolution of Thromboinflammation",
    authors: ["Gavins, FN", "Yadav, S", "Ansari, J", "Iffah, R"],
    year: 2022,
    journal: "Experimental Biology 2022.",
    pages: "1 - 1",
    issn: "0892-6638",
    doi: "10.1096/fasebj.2022.36.S1.R5833",
    doiUrl: "http://dx.doi.org/10.1096/fasebj.2022.36.S1.R5833",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/32387",
  },
  {
    slug: "triay-2022-the-spectrum-of-acute-cerebrovascular-disease-in-patients-wi",
    type: "journal",
    typeLabel: "Journal article",
    title: "The Spectrum of Acute Cerebrovascular Disease in Patients with COVID-19",
    authors: ["Triay, R", "Buchhanolla, P", "Gaudet, A", "Winter, V", "Gaudet, A", "Riel-Romero, RMS", "Javalkar, V", "Kelley, RE", "Ansari, J", "Faraji, M", "Gonzalez-Toledo, E", "Cuellar-Saenz, HH", "Bailey, S", "Siddaiah, H", "Gavins, FNE"],
    year: 2022,
    journal: "Biomedicines",
    volume: "10",
    issue: "2",
    pages: "1 - 13",
    issn: "2227-9059",
    doi: "10.3390/biomedicines10020435",
    doiUrl: "http://dx.doi.org/10.3390/biomedicines10020435",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/24149",
  },
  {
    slug: "triay-2022-the-spectrum-of-acute-cerebrovascular-disease-in-patients-ho",
    type: "journal",
    typeLabel: "Journal article",
    title: "The Spectrum of Acute Cerebrovascular Disease in Patients Hospitalized with COVID-19 Diagnosis at OLSU-S",
    authors: ["Triay, R", "Ansari, J", "Winter, V", "Riel-Romero, RMS", "Gonzalez-Toledo, E", "Gavins, FNE", "Kelley, RE"],
    year: 2022,
    journal: "Annals of Neurology",
    volume: "90",
    issue: "Supplement 27: 146th Annual Meeting American Neurological Association",
    pages: "S58 - S58",
    issn: "0364-5134",
    doi: "10.1002/ana.26180",
    doiUrl: "http://dx.doi.org/10.1002/ana.26180",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/24148",
  },
  {
    slug: "ansari-2021-neutrophils-and-platelets-immune-soldiers-fighting-together",
    type: "journal",
    typeLabel: "Journal article",
    title: "Neutrophils and Platelets: Immune Soldiers Fighting Together in Stroke Pathophysiology",
    authors: ["Ansari, J", "Gavins, FNE"],
    year: 2021,
    journal: "Biomedicines",
    volume: "9",
    issue: "12",
    pages: "1 - 13",
    issn: "2227-9059",
    doi: "10.3390/biomedicines9121945",
    doiUrl: "http://dx.doi.org/10.3390/biomedicines9121945",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/23848",
  },
  {
    slug: "ansari-2021-neurological-manifestations-of-patients-hospitalized-with-co",
    type: "journal",
    typeLabel: "Journal article",
    title: "Neurological Manifestations of Patients Hospitalized with COVID-19 Diagnosis at OLSU-S",
    authors: ["Ansari, J", "Gaudet, A", "Hicks, J", "Stevens, A", "Gonzalez-Toledo, E", "Riel-Romero, RM", "Gavins, FNE", "Kelley, R"],
    year: 2021,
    journal: "Neurology",
    volume: "96",
    issue: "15 supplement",
    pages: "3 - 3",
    issn: "0028-3878",
    doi: "10.1212/WNL.96.15_supplement.1892",
    doiUrl: "http://dx.doi.org/10.1212/WNL.96.15_supplement.1892",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/31409",
  },
  {
    slug: "ansari-2021-the-impact-of-thromboinflammation-on-the-cerebral-microcirc",
    type: "journal",
    typeLabel: "Journal article",
    title: "The Impact of Thrombo‐inflammation on the Cerebral Microcirculation",
    authors: ["Ansari, J", "Gavins, FNE"],
    year: 2021,
    journal: "Microcirculation",
    volume: "28",
    issue: "3",
    pages: "1 - 11",
    issn: "1073-9688",
    doi: "10.1111/micc.12689",
    doiUrl: "http://dx.doi.org/10.1111/micc.12689",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/22536",
  },
  {
    slug: "ansari-2021-targeting-anxa1-fpr2-alx-regulates-neutrophil-function-promo",
    type: "journal",
    typeLabel: "Journal article",
    title: "Targeting AnxA1/Fpr2/ALX Regulates Neutrophil Function Promoting Thrombo-Inflammation Resolution in Sickle Cell Disease",
    authors: ["Ansari, J", "Senchenkova, EY", "Vital, SA", "Al-Yafeai, Z", "Kaur, G", "Sparkenbaugh, E", "Orr, A", "Pawlinski, R", "Hebbel, R", "Granger, DN", "Kubes, P", "Gavins, FNE"],
    year: 2021,
    journal: "Blood",
    volume: "137",
    issue: "11",
    pages: "1538 - 1549",
    issn: "0006-4971",
    doi: "10.1182/blood.2020009166",
    doiUrl: "http://dx.doi.org/10.1182/blood.2020009166",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/22185",
  },
  {
    slug: "bazban-shotorbani-2021-a-biomicrofluidic-screening-platform-for-dysfunctional-en",
    type: "journal",
    typeLabel: "Journal article",
    title: "A Biomicrofluidic Screening Platform for Dysfunctional Endothelium‐Targeted Nanoparticles and Therapeutics",
    authors: ["Bazban-Shotorbani, S", "Gavins, F", "Kant, K", "Dufva, M", "Kamaly, N"],
    year: 2021,
    journal: "Advanced NanoBiomed Research",
    volume: "2",
    issue: "1",
    pages: "1 - 13",
    issn: "2699-9307",
    doi: "10.1002/anbr.202100092",
    doiUrl: "http://dx.doi.org/10.1002/anbr.202100092",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/23905",
  },
  {
    slug: "boltersdorf-2021-long-lived-lanthanide-emission-via-a-ph-sensitive-and-switch",
    type: "journal",
    typeLabel: "Journal article",
    title: "Long-lived lanthanide emission via a pH-sensitive and switchable LRET complex",
    authors: ["Boltersdorf, T", "Gavins, FNE", "Long, NJ"],
    year: 2021,
    journal: "Chemical Science",
    volume: "12",
    issue: "25",
    pages: "1 - 5",
    issn: "2041-6520",
    doi: "10.1039/d1sc01503f",
    doiUrl: "http://dx.doi.org/10.1039/d1sc01503f",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/22910",
  },
  {
    slug: "iffah-2021-thromboinflammation-in-coronavirus-disease-2019-the-clot-th",
    type: "journal",
    typeLabel: "Journal article",
    title: "Thromboinflammation in coronavirus disease 2019: The clot thickens",
    authors: ["Iffah, R", "Gavins, FNE"],
    year: 2021,
    journal: "British Journal of Pharmacology",
    volume: "179",
    issue: "10",
    pages: "2100 - 2107",
    issn: "0007-1188",
    doi: "10.1111/bph.15594",
    doiUrl: "http://dx.doi.org/10.1111/bph.15594",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/23849",
  },
  {
    slug: "ansari-2020-targeting-peptidyl-arginine-deiminase-4-and-nadph-oxidase-pa",
    type: "conference",
    typeLabel: "Conference paper",
    title: "Targeting Peptidyl Arginine Deiminase 4 and NADPH Oxidase Pathways Regulates Neutrophil Dependent Thrombo-inflammation",
    authors: ["Ansari, J", "Vital, S", "Esen, E", "Gavins, F"],
    year: 2020,
    journal: "Pharmacology 2020..",
    pages: "409 - 410",
    issn: "0007-1188",
    doi: "10.1111/bph.15316",
    doiUrl: "http://dx.doi.org/10.1111/bph.15316",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/31538",
  },
  {
    slug: "boltersdorf-2020-targeting-of-formyl-peptide-receptor-2-for-in-vivo-imaging-o",
    type: "journal",
    typeLabel: "Journal article",
    title: "Targeting of Formyl Peptide Receptor 2 for in vivo imaging of acute vascular inflammation",
    authors: ["Boltersdorf, T", "Ansari, J", "Senchenkova, EY", "Groeper, J", "Pajonczyk, D", "Vital, SA", "Kaur, G", "Alexander, JS", "Vogl, T", "Rescher, U", "Long, NJ", "Gavins, FNE"],
    year: 2020,
    journal: "Theranostics",
    volume: "10",
    issue: "15",
    pages: "6599 - 6614",
    issn: "1838-7640",
    doi: "10.7150/thno.44226",
    doiUrl: "http://dx.doi.org/10.7150/thno.44226",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/20851",
  },
  {
    slug: "gavins-2020-introduction-overview",
    type: "book-chapter",
    typeLabel: "Book chapter",
    title: "Introduction/overview",
    authors: ["Gavins, FNE", "Alexander, JS"],
    year: 2020,
    journal: "Lymphatic Structure and Function in Health and Disease.",
    pages: "1 - 4",
  },
  {
    slug: "morse-2020-in-vivo-delivery-of-a-fluorescent-fpr2-alx-targeted-probe-us",
    type: "journal",
    typeLabel: "Journal article",
    title: "In vivo delivery of a fluorescent FPR2/ALX-targeted probe using focused ultrasound and microbubbles to image activated microglia",
    authors: ["Morse, SV", "Boltersdorf, T", "Chan, TG", "Gavins, FNE", "Choi, JJ", "Long, NJ"],
    year: 2020,
    journal: "RSC Chemical Biology",
    volume: "1",
    issue: "5",
    pages: "385 - 389",
    issn: "2633-0679",
    doi: "10.1039/d0cb00140f",
    doiUrl: "http://dx.doi.org/10.1039/d0cb00140f",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/24150",
  },
  {
    slug: "omura-2020-bioinformatics-analysis-of-gut-microbiota-and-cns-transcript",
    type: "journal",
    typeLabel: "Journal article",
    title: "Bioinformatics Analysis of Gut Microbiota and CNS Transcriptome in Virus-Induced Acute Myelitis and Chronic Inflammatory Demyelination; Potential Association of Distinct Bacteria with CNS IgA upregulation",
    authors: ["Omura, S", "Sato, F", "Park, A-M", "Fujita, M", "Khadka, S", "Nakamura, Y", "Katsuki, A", "Nishio, K", "Gavins, F", "Tsunoda, I"],
    year: 2020,
    journal: "Frontiers in Immunology Mucosal Immunity",
    volume: "11",
    pages: "1 - 18",
    issn: "1664-3224",
    doi: "10.3389/fimmu.2020.01138",
    doiUrl: "http://dx.doi.org/10.3389/fimmu.2020.01138",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/21308",
  },
  {
    slug: "vital-2020-targeting-anxa1-formyl-peptide-receptor-2-pathway-affords-pr",
    type: "journal",
    typeLabel: "Journal article",
    title: "Targeting AnxA1/Formyl Peptide Receptor 2 Pathway Affords Protection against Pathological Thrombo-Inflammation",
    authors: ["Vital, SA", "Senchenkova, EY", "Ansari, J", "Gavins, FNE"],
    year: 2020,
    journal: "Cells",
    volume: "9",
    issue: "11",
    pages: "1 - 18",
    issn: "2073-4409",
    doi: "10.3390/cells9112473",
    doiUrl: "http://dx.doi.org/10.3390/cells9112473",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/22186",
  },
  {
    slug: "ansari-2019-ischemia-reperfusion-injury-in-sickle-cell-disease-from-bas",
    type: "journal",
    typeLabel: "Journal article",
    title: "Ischemia-Reperfusion Injury in Sickle Cell Disease: From Basics to Therapeutics",
    authors: ["Ansari, J", "Gavins, FNE"],
    year: 2019,
    journal: "The American Journal of Pathology",
    volume: "189",
    issue: "4",
    pages: "706 - 718",
    issn: "0002-9440",
    doi: "10.1016/j.ajpath.2018.12.012",
    doiUrl: "http://dx.doi.org/10.1016/j.ajpath.2018.12.012",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/19464",
  },
  {
    slug: "barzegar-2019-potential-therapeutic-roles-of-stem-cells-in-ischemia-reperf",
    type: "journal",
    typeLabel: "Journal article",
    title: "Potential therapeutic roles of stem cells in ischemia-reperfusion injury",
    authors: ["Barzegar, M", "Kaur, G", "Gavins, FNE", "Wang, Y", "Boyer, CJ", "Alexander, JS"],
    year: 2019,
    journal: "Stem Cell Research",
    volume: "37",
    pages: "1 - 15",
    issn: "1873-5061",
    doi: "10.1016/j.scr.2019.101421",
    doiUrl: "http://dx.doi.org/10.1016/j.scr.2019.101421",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/19173",
  },
  {
    slug: "becker-2019-endogenous-specialized-proresolving-mediator-profiles-in-a-n",
    type: "journal",
    typeLabel: "Journal article",
    title: "Endogenous Specialized Proresolving Mediator Profiles in a Novel Experimental Model of Lymphatic Obstruction and Intestinal Inflammation in African Green Monkeys",
    authors: ["Becker, F", "Romero, E", "Goetzmann, J", "Hasselschwert, DL", "Dray, B", "Vanchiere, J", "Fontenot, J", "Yun, JW", "Norris, PC", "White, L", "Musso, M", "Serhan, CN", "Alexander, JS", "Gavins, FNE"],
    year: 2019,
    journal: "American Journal of Pathology",
    volume: "189",
    issue: "10",
    pages: "1953 - 1972",
    issn: "0002-9440",
    doi: "10.1016/j.ajpath.2019.05.013",
    doiUrl: "http://dx.doi.org/10.1016/j.ajpath.2019.05.013",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/31638",
  },
  {
    slug: "becker-2019-dynamic-gut-microbiome-changes-following-regional-intestinal",
    type: "journal",
    typeLabel: "Journal article",
    title: "Dynamic gut microbiome changes following regional intestinal lymphatic obstruction in primates",
    authors: ["Becker, F", "Gavins, FNE", "Fontenot, J", "Jordan, P", "Yun, JY", "Scott, R", "Polk, PR", "Friday, RE", "Boktor, M", "Musso, M", "Romero, E", "Boudreaux, S", "Simmons, J", "Hasselschwert, DL", "Goetzmann, JE", "Vanchiere, J", "Cvek, U", "Trutschl, M", "Kilgore, P", "Alexander, JS"],
    year: 2019,
    journal: "Pathophysiology",
    volume: "26",
    issue: "3-4",
    pages: "253 - 261",
    issn: "0928-4680",
    doi: "10.1016/j.pathophys.2019.06.004",
    doiUrl: "http://dx.doi.org/10.1016/j.pathophys.2019.06.004",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/19165",
  },
  {
    slug: "boltersdorf-2019-development-characterisation-and-in-vitro-evaluation-of-lan",
    type: "journal",
    typeLabel: "Journal article",
    title: "Development, characterisation and in vitro evaluation of lanthanide-based FPR2/ALX-targeted imaging probes",
    authors: ["Boltersdorf, T", "Ansari, J", "Senchenkova, E", "Jiang, L", "White, AJP", "Coogan, M", "Gavins, F", "Long, NJ"],
    year: 2019,
    journal: "Dalton Transactions",
    volume: "48",
    issue: "44",
    pages: "16764 - 16775",
    issn: "1477-9226",
    doi: "10.1039/c9dt03520f",
    doiUrl: "http://dx.doi.org/10.1039/c9dt03520f",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/19463",
  },
  {
    slug: "gavins-2019-lymphatic-structure-and-function-in-health-and-disease",
    type: "book",
    typeLabel: "Book",
    title: "Lymphatic structure and function in health and disease",
    authors: ["Gavins, FNE", "Alexander, JS"],
    year: 2019,
    journal: "'Lymphatic structure and function in health and disease'",
  },
  {
    slug: "senchenkova-2019-novel-role-for-the-anxa1-fpr2-alx-signaling-axis-as-a-key-re",
    type: "journal",
    typeLabel: "Journal article",
    title: "Novel Role for the AnxA1-Fpr2/ALX Signaling Axis as a Key Regulator of Platelet Function to Promote Resolution of Inflammation",
    authors: ["Senchenkova, EY", "Ansari, J", "Becker, F", "Vital, SA", "Al-Yafeai, Z", "Sparkenbaugh, EM", "Pawlinski, R", "Stokes, KY", "Carroll, JL", "Dragoi, AM", "Qin, CX", "Ritchie, RH", "Sun, H", "Cuellar-Saenz, HH", "Rubinstein, MR", "Han, YW", "Orr, AW", "Perretti, M", "Granger, DN", "Gavins, FNE"],
    year: 2019,
    journal: "Circulation",
    volume: "140",
    issue: "4",
    pages: "319 - 335",
    issn: "0009-7322",
    doi: "10.1161/CIRCULATIONAHA.118.039345",
    doiUrl: "http://dx.doi.org/10.1161/CIRCULATIONAHA.118.039345",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/19067",
  },
  {
    slug: "senchenkova-2019-novel-role-of-t-cells-and-il-6-interleukin-6-in-angiotensi",
    type: "journal",
    typeLabel: "Journal article",
    title: "Novel Role of T Cells and IL-6 (Interleukin-6) in Angiotensin II–Induced Microvascular Dysfunction",
    authors: ["Senchenkova, EY", "Russell, J", "Yildirim, A", "Granger, DN", "Gavins, FNE"],
    year: 2019,
    journal: "Hypertension",
    volume: "73",
    issue: "4",
    pages: "829 - 838",
    issn: "0194-911X",
    doi: "10.1161/hypertensionaha.118.12286",
    doiUrl: "http://dx.doi.org/10.1161/hypertensionaha.118.12286",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/21122",
  },
  {
    slug: "yun-2019-cns-lymphatics-in-health-and-disease",
    type: "book-chapter",
    typeLabel: "Book chapter",
    title: "CNS lymphatics in health and disease",
    authors: ["Yun, JW", "Alexander, JS", "Gavins, FNE"],
    year: 2019,
    journal: "Lymphatic Structure and Function in Health and Disease.",
    pages: "93 - 107",
  },
  {
    slug: "al-kofahi-2018-il-1-reduces-cardiac-lymphatic-muscle-contraction-via-cox-2",
    type: "journal",
    typeLabel: "Journal article",
    title: "IL-1β reduces cardiac lymphatic muscle contraction via COX-2 and PGE2 induction: Potential role in myocarditis",
    authors: ["Al-Kofahi, M", "Omura, S", "Tsunoda, I", "Sato, F", "Becker, F", "Gavins, FNE", "Woolard, MD", "Pattillo, C", "Zawieja, D", "Muthuchamy, M", "Gashev, A", "Shihab, I", "Ghoweba, M", "Von der Weid, P-Y", "Wang, Y", "Alexander, JS"],
    year: 2018,
    journal: "Biomedicine & Pharmacotherapy",
    volume: "107",
    issue: "November 2018",
    pages: "1591 - 1600",
    issn: "0753-3322",
    doi: "10.1016/j.biopha.2018.08.004",
    doiUrl: "http://dx.doi.org/10.1016/j.biopha.2018.08.004",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/31455",
  },
  {
    slug: "ansari-2018-therapeutic-potential-of-annexin-a1-in-ischemia-reperfusion",
    type: "journal",
    typeLabel: "Journal article",
    title: "Therapeutic Potential of Annexin A1 in Ischemia Reperfusion Injury",
    authors: ["Ansari, J", "Kaur, G", "Gavins, F"],
    year: 2018,
    journal: "International Journal of Molecular Sciences",
    volume: "19",
    issue: "4",
    pages: "1 - 19",
    issn: "1661-6596",
    doi: "10.3390/ijms19041211",
    doiUrl: "http://dx.doi.org/10.3390/ijms19041211",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/19180",
  },
  {
    slug: "ansari-2018-sickle-cell-disease-a-malady-beyond-a-hemoglobin-defect-in",
    type: "journal",
    typeLabel: "Journal article",
    title: "Sickle cell disease: a malady beyond a hemoglobin defect in cerebrovascular disease",
    authors: ["Ansari, J", "Moufarrej, YE", "Pawlinski, R", "Gavins, FNE"],
    year: 2018,
    journal: "Expert Review of Hematology",
    volume: "11",
    issue: "1",
    pages: "45 - 55",
    issn: "1747-4086",
    doi: "10.1080/17474086.2018.1407240",
    doiUrl: "http://dx.doi.org/10.1080/17474086.2018.1407240",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/31416",
  },
  {
    slug: "gillespie-2018-the-isothiocyanate-sulforaphane-modulates-platelet-function",
    type: "journal",
    typeLabel: "Journal article",
    title: "The isothiocyanate sulforaphane modulates platelet function and protects against cerebral thrombotic dysfunction",
    authors: ["Gillespie, S", "Holloway, PM", "Becker, F", "Rauzi, F", "Vital, SA", "Taylor, KA", "Stokes, KY", "Emerson, M", "Gavins, FNE"],
    year: 2018,
    journal: "British Journal of Pharmacology",
    volume: "175",
    issue: "16",
    pages: "3333 - 3346",
    issn: "0007-1188",
    doi: "10.1111/bph.14368",
    doiUrl: "http://dx.doi.org/10.1111/bph.14368",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/31535",
  },
  {
    slug: "senchenkova-2018-a-critical-role-for-both-cd40-and-vla5-in-angiotensin-iimed",
    type: "journal",
    typeLabel: "Journal article",
    title: "A critical role for both CD40 and VLA5 in angiotensin II–mediated thrombosis and inflammation",
    authors: ["Senchenkova, EY", "Russell, J", "Vital, SA", "Yildirim, A", "Orr, AW", "Granger, DN", "Gavins, FNE"],
    year: 2018,
    journal: "The FASEB Journal",
    volume: "32",
    issue: "6",
    pages: "3448 - 3456",
    issn: "0892-6638",
    doi: "10.1096/fj.201701068r",
    doiUrl: "http://dx.doi.org/10.1096/fj.201701068r",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/19504",
  },
  {
    slug: "smith-2018-metallothionein-i-as-a-direct-link-between-therapeutic-hemat",
    type: "journal",
    typeLabel: "Journal article",
    title: "Metallothionein I as a direct link between therapeutic hematopoietic stem/progenitor cells and cerebral protection in stroke",
    authors: ["Smith, HK", "Omura, S", "Vital, SA", "Becker, F", "Senchenkova, EY", "Kaur, G", "Tsunoda, I", "Peirce, SM", "Gavins, FNE"],
    year: 2018,
    journal: "The FASEB Journal",
    volume: "32",
    issue: "5",
    pages: "2381 - 2394",
    issn: "0892-6638",
    doi: "10.1096/fj.201700746r",
    doiUrl: "http://dx.doi.org/10.1096/fj.201700746r",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/19466",
  },
  {
    slug: "hughes-2017-mast-cells-mediate-early-neutrophil-recruitment-and-exhibit",
    type: "journal",
    typeLabel: "Journal article",
    title: "Mast cells mediate early neutrophil recruitment and exhibit anti-inflammatory properties via the formyl peptide receptor 2/lipoxin A4receptor",
    authors: ["Hughes, EL", "Becker, F", "Flower, RJ", "Buckingham, JC", "Gavins, FNE"],
    year: 2017,
    journal: "British Journal of Pharmacology",
    volume: "174",
    issue: "14",
    pages: "2393 - 2408",
    issn: "0007-1188",
    doi: "10.1111/bph.13847",
    doiUrl: "http://dx.doi.org/10.1111/bph.13847",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/19513",
  },
  {
    slug: "igbinedion-2017-non-celiac-gluten-sensitivity-all-wheat-attack-is-not-celia",
    type: "journal",
    typeLabel: "Journal article",
    title: "Non-celiac gluten sensitivity: All wheat attack is not celiac",
    authors: ["Igbinedion, SO", "Ansari, J", "Vasikaran, A", "Gavins, F", "Jordan, P", "Boktor, M", "Alexander, JS"],
    year: 2017,
    journal: "World Journal of Gastroenterology",
    volume: "23",
    issue: "40",
    pages: "7201 - 7210",
    issn: "1007-9327",
    doi: "10.3748/wjg.v23.i40.7201",
    doiUrl: "http://dx.doi.org/10.3748/wjg.v23.i40.7201",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/20852",
  },
  {
    slug: "becker-2016-downregulation-of-cx3cr1-ameliorates-experimental-colitis-e",
    type: "journal",
    typeLabel: "Journal article",
    title: "Downregulation of CX3CR1 ameliorates experimental colitis: evidence for CX3CL1-CX3CR1-mediated immune cell recruitment",
    authors: ["Becker, F", "Holthoff, C", "Anthoni, C", "Rijcken, E", "Alexander, JS", "Gavins, FNE", "Spiegel, HU", "Senninger, N", "Vowinkel, T"],
    year: 2016,
    journal: "International Journal of Colorectal Disease",
    volume: "32",
    issue: "3",
    pages: "315 - 324",
    issn: "0179-1958",
    doi: "10.1007/s00384-016-2735-y",
    doiUrl: "http://dx.doi.org/10.1007/s00384-016-2735-y",
  },
  {
    slug: "gavins-2016-overview",
    type: "book",
    typeLabel: "Book",
    title: "Overview",
    authors: ["Gavins, FNE", "Stokes, KY"],
    year: 2016,
    journal: "'Overview'",
  },
  {
    slug: "gavins-2016-sepsis",
    type: "book-chapter",
    typeLabel: "Book chapter",
    title: "Sepsis",
    authors: ["Gavins, FNE"],
    year: 2016,
    journal: "Vascular Responses to Pathogens.",
    pages: "1 - 9",
  },
  {
    slug: "holloway-2016-sulforaphane-induces-neurovascular-protection-against-a-syst",
    type: "journal",
    typeLabel: "Journal article",
    title: "Sulforaphane induces neurovascular protection against a systemic inflammatory challenge via both Nrf2-dependent and independent pathways",
    authors: ["Holloway, PM", "Gillespie, S", "Becker, F", "Vital, SA", "Nguyen, V", "Alexander, JS", "Evans, PC", "Gavins, FNE"],
    year: 2016,
    journal: "Vascular Pharmacology",
    volume: "85",
    pages: "29 - 38",
    issn: "1537-1891",
    doi: "10.1016/j.vph.2016.07.004",
    doiUrl: "http://dx.doi.org/10.1016/j.vph.2016.07.004",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/19178",
  },
  {
    slug: "holloway-2016-modeling-ischemic-stroke-in-vitro-status-quo-and-future-per",
    type: "journal",
    typeLabel: "Journal article",
    title: "Modeling Ischemic Stroke In Vitro: Status Quo and Future Perspectives",
    authors: ["Holloway, PM", "Gavins, FNE"],
    year: 2016,
    journal: "Stroke",
    volume: "47",
    issue: "2",
    pages: "561 - 569",
    issn: "0039-2499",
    doi: "10.1161/strokeaha.115.011932",
    doiUrl: "http://dx.doi.org/10.1161/strokeaha.115.011932",
  },
  {
    slug: "vital-2016-surgical-approach-for-middle-cerebral-artery-occlusion-and-r",
    type: "journal",
    typeLabel: "Journal article",
    title: "Surgical Approach for Middle Cerebral Artery Occlusion and Reperfusion Induced Stroke in Mice",
    authors: ["Vital, SA", "Gavins, FNE"],
    year: 2016,
    journal: "Journal of Visualized Experiments",
    volume: "2016",
    issue: "116",
    pages: "1 - 9",
    issn: "1940-087X",
    doi: "10.3791/54302",
    doiUrl: "http://dx.doi.org/10.3791/54302",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/31446",
  },
  {
    slug: "vital-2016-formyl-peptide-receptor-2-3-lipoxin-a4-receptor-regulates-ne",
    type: "journal",
    typeLabel: "Journal article",
    title: "Formyl-Peptide Receptor 2/3/Lipoxin A4 Receptor Regulates Neutrophil-Platelet Aggregation and Attenuates Cerebral Inflammation Impact for Therapy in Cardiovascular Disease",
    authors: ["Vital, SA", "Becker, F", "Holloway, PM", "Russell, J", "Perretti, M", "Granger, DN", "Gavins, FNE"],
    year: 2016,
    journal: "Circulation",
    volume: "133",
    issue: "22",
    pages: "2169 - 2179",
    issn: "0009-7322",
    doi: "10.1161/circulationaha.115.020633",
    doiUrl: "http://dx.doi.org/10.1161/circulationaha.115.020633",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/19158",
  },
  {
    slug: "alkofahi-2015-il1-reduces-tonic-contraction-of-mesenteric-lymphatic-musc",
    type: "journal",
    typeLabel: "Journal article",
    title: "IL‐1β reduces tonic contraction of mesenteric lymphatic muscle cells, with the involvement of cycloxygenase‐2 and prostaglandinE2",
    authors: ["Al‐Kofahi, M", "Becker, F", "Gavins, FNE", "Woolard, MD", "Tsunoda, I", "Wang, Y", "Ostanin, D", "Zawieja, DC", "Muthuchamy, M", "von der Weid, PY", "Alexander, JS"],
    year: 2015,
    journal: "British Journal of Pharmacology",
    volume: "172",
    issue: "16",
    pages: "4038 - 4051",
    issn: "0007-1188",
    doi: "10.1111/bph.13194",
    doiUrl: "http://dx.doi.org/10.1111/bph.13194",
  },
  {
    slug: "becker-2015-mo1696-cx3cl1-cx3cr1-in-acute-colitis-evidence-for-chemokin",
    type: "journal",
    typeLabel: "Journal article",
    title: "Mo1696 CX3CL1-CX3CR1 in Acute Colitis: Evidence for Chemokine-Mediated Leukocyte Recruitment",
    authors: ["Becker, F", "Holthoff, C", "Anthoni, C", "Alexander, JS", "Gavins, FN", "Senninger, N", "Vowinkel, T"],
    year: 2015,
    journal: "Gastroenterology",
    volume: "148",
    issue: "4",
    pages: "S - 688",
    issn: "0016-5085",
    doi: "10.1016/s0016-5085(15)32326-x",
    doiUrl: "http://dx.doi.org/10.1016/s0016-5085(15)32326-x",
  },
  {
    slug: "buss-2015-targeting-the-annexin-1formyl-peptide-receptor-2-alx-pathwa",
    type: "journal",
    typeLabel: "Journal article",
    title: "Targeting the annexin 1‐formyl peptide receptor 2/ALX pathway affords protection against bacterial LPS‐induced pathologic changes in the murine adrenal cortex",
    authors: ["Buss, NAPS", "Gavins, FNE", "Cover, PO", "Terron, A", "Buckingham, JC"],
    year: 2015,
    journal: "The FASEB Journal",
    volume: "29",
    issue: "7",
    pages: "2930 - 2942",
    issn: "0892-6638",
    doi: "10.1096/fj.14-268375",
    doiUrl: "http://dx.doi.org/10.1096/fj.14-268375",
  },
  {
    slug: "gavins-2015-cell-tracking-technologies-for-acute-ischemic-brain-injury",
    type: "journal",
    typeLabel: "Journal article",
    title: "Cell Tracking Technologies for Acute Ischemic Brain Injury",
    authors: ["Gavins, FNE", "Smith, HK"],
    year: 2015,
    journal: "Journal of Cerebral Blood Flow & Metabolism",
    volume: "35",
    issue: "7",
    pages: "1090 - 1099",
    issn: "0271-678X",
    doi: "10.1038/jcbfm.2015.93",
    doiUrl: "http://dx.doi.org/10.1038/jcbfm.2015.93",
  },
  {
    slug: "gavins-2015-vascular-responses-to-pathogens",
    type: "book",
    typeLabel: "Book",
    title: "Vascular Responses to Pathogens",
    authors: ["Gavins, FNE", "Stokes, KY"],
    year: 2015,
    journal: "'Vascular Responses to Pathogens'",
  },
  {
    slug: "holloway-2015-both-mc-1-and-mc-3-receptors-provide-protection-from-cerebra",
    type: "journal",
    typeLabel: "Journal article",
    title: "Both MC 1 and MC 3 Receptors Provide Protection From Cerebral Ischemia-Reperfusion–Induced Neutrophil Recruitment",
    authors: ["Holloway, PM", "Durrenberger, PF", "Trutschl, M", "Cvek, U", "Cooper, D", "Orr, AW", "Perretti, M", "Getting, SJ", "Gavins, FNE"],
    year: 2015,
    journal: "Arteriosclerosis, Thrombosis, and Vascular Biology",
    volume: "35",
    issue: "9",
    pages: "1936 - 1944",
    issn: "1079-5642",
    doi: "10.1161/atvbaha.115.305348",
    doiUrl: "http://dx.doi.org/10.1161/atvbaha.115.305348",
  },
  {
    slug: "smith-2015-critical-differences-between-two-classical-surgical-approach",
    type: "journal",
    typeLabel: "Journal article",
    title: "Critical differences between two classical surgical approaches for middle cerebral artery occlusion-induced stroke in mice",
    authors: ["Smith, HK", "Russell, JM", "Granger, DN", "Gavins, FNE"],
    year: 2015,
    journal: "Journal of Neuroscience Methods",
    volume: "249",
    pages: "99 - 105",
    issn: "0165-0270",
    doi: "10.1016/j.jneumeth.2015.04.008",
    doiUrl: "http://dx.doi.org/10.1016/j.jneumeth.2015.04.008",
  },
  {
    slug: "smith-2015-targeting-formyl-peptide-receptor-2-reduces-leukocyteendoth",
    type: "journal",
    typeLabel: "Journal article",
    title: "Targeting formyl peptide receptor 2 reduces leukocyte‐endothelial interactions in a murine model of stroke",
    authors: ["Smith, HK", "Gil, CD", "Oliani, SM", "Gavins, FNE"],
    year: 2015,
    journal: "The FASEB Journal",
    volume: "29",
    issue: "5",
    pages: "2161 - 2171",
    issn: "0892-6638",
    doi: "10.1096/fj.14-263160",
    doiUrl: "http://dx.doi.org/10.1096/fj.14-263160",
  },
  {
    slug: "stasiuk-2015-99mtc-spect-imaging-agent-based-on-cflflfk-for-the-detection",
    type: "journal",
    typeLabel: "Journal article",
    title: "99mTc SPECT imaging agent based on cFLFLFK for the detection of FPR1 in inflammation",
    authors: ["Stasiuk, GJ", "Holloway, PM", "Rivas, C", "Trigg, W", "Luthra, SK", "Morisson Iveson, V", "Gavins, FNE", "Long, NJ"],
    year: 2015,
    journal: "Dalton Transactions",
    volume: "44",
    issue: "11",
    pages: "4986 - 4993",
    issn: "1477-9226",
    doi: "10.1039/c4dt02980a",
    doiUrl: "http://dx.doi.org/10.1039/c4dt02980a",
  },
  {
    slug: "amsellem-2014-icam-2-regulates-vascular-permeability-and-n-cadherin-locali",
    type: "journal",
    typeLabel: "Journal article",
    title: "ICAM-2 regulates vascular permeability and N-cadherin localization through ezrin-radixin-moesin (ERM) proteins and Rac-1 signalling",
    authors: ["Amsellem, V", "Dryden, NH", "Martinelli, R", "Gavins, F", "Almagro, LO", "Birdsey, GM", "Haskard, DO", "Mason, JC", "Turowski, P", "Randi, AM"],
    year: 2014,
    journal: "Cell Communication and Signaling",
    volume: "12",
    issue: "1",
    pages: "12",
    issn: "1478-811X",
    doi: "10.1186/1478-811X-12-12",
    doiUrl: "http://dx.doi.org/10.1186/1478-811X-12-12",
  },
  {
    slug: "iqbal-2014-parp-14-combines-with-tristetraprolin-in-the-selective-postt",
    type: "journal",
    typeLabel: "Journal article",
    title: "PARP-14 combines with tristetraprolin in the selective posttranscriptional control of macrophage tissue factor expression",
    authors: ["Iqbal, MB", "Johns, M", "Cao, J", "Liu, Y", "Yu, S-C", "Hyde, GD", "Laffan, MA", "Marchese, FP", "Cho, SH", "Clark, AR", "Gavins, FN", "Woollard, KJ", "Blackshear, PJ", "Mackman, N", "Dean, JL", "Boothby, M", "Haskard, DO"],
    year: 2014,
    journal: "Blood",
    volume: "124",
    issue: "24",
    pages: "3646 - 3655",
    issn: "0006-4971",
    doi: "10.1182/blood-2014-07-588046",
    doiUrl: "http://dx.doi.org/10.1182/blood-2014-07-588046",
  },
  {
    slug: "gillespie-2013-phytochemicals-countering-risk-factors-and-pathological-res",
    type: "journal",
    typeLabel: "Journal article",
    title: "Phytochemicals: Countering risk factors and pathological responses associated with ischaemia reperfusion injury",
    authors: ["Gillespie, S", "Gavins, FNE"],
    year: 2013,
    journal: "Pharmacology & Therapeutics",
    volume: "138",
    issue: "1",
    pages: "38 - 45",
    issn: "0163-7258",
    doi: "10.1016/j.pharmthera.2012.12.005",
    doiUrl: "http://dx.doi.org/10.1016/j.pharmthera.2012.12.005",
  },
  {
    slug: "hughes-2013-role-and-interactions-of-annexina1-and-oestrogens-in-the-man",
    type: "journal",
    typeLabel: "Journal article",
    title: "Role and interactions of annexinA1 and oestrogens in the manifestation of sexual dimorphisms in cerebral and systemic inflammation",
    authors: ["Hughes, EL", "Cover, PO", "Buckingham, JC", "Gavins, FNE"],
    year: 2013,
    journal: "British Journal of Pharmacology",
    volume: "169",
    issue: "3",
    pages: "539 - 553",
    issn: "0007-1188",
    doi: "10.1111/j.1476-5381.2012.02146.x",
    doiUrl: "http://dx.doi.org/10.1111/j.1476-5381.2012.02146.x",
  },
  {
    slug: "stasiuk-2013-gd3-cflflfk-conjugate-for-mri-a-targeted-contrast-agent-for",
    type: "journal",
    typeLabel: "Journal article",
    title: "Gd3+cFLFLFK conjugate for MRI: a targeted contrast agent for FPR1 in inflammation",
    authors: ["Stasiuk, GJ", "Smith, H", "Wylezinska-Arridge, M", "Tremoleda, JL", "Trigg, W", "Luthra, SK", "Iveson, VM", "Gavins, FNE", "Long, NJ"],
    year: 2013,
    journal: "Chem. Commun.",
    volume: "49",
    issue: "6",
    pages: "564 - 566",
    issn: "1359-7345",
    doi: "10.1039/c2cc37460a",
    doiUrl: "http://dx.doi.org/10.1039/c2cc37460a",
  },
  {
    slug: "gavins-2012-leukocyte-recruitment-in-the-brain-in-sepsis-involvement-of",
    type: "journal",
    typeLabel: "Journal article",
    title: "Leukocyte recruitment in the brain in sepsis: involvement of the annexin 1‐FPR2/ALX anti‐inflammatory system",
    authors: ["Gavins, FNE", "Hughes, EL", "Buss, NAPS", "Holloway, PM", "Getting, SJ", "Buckingham, JC"],
    year: 2012,
    journal: "The FASEB Journal",
    volume: "26",
    issue: "12",
    pages: "4977 - 4989",
    issn: "0892-6638",
    doi: "10.1096/fj.12-205971",
    doiUrl: "http://dx.doi.org/10.1096/fj.12-205971",
  },
  {
    slug: "gavins-2012-annexin-a1-and-the-regulation-of-innate-and-adaptive-immunit",
    type: "journal",
    typeLabel: "Journal article",
    title: "Annexin A1 and the regulation of innate and adaptive immunity",
    authors: ["Gavins, FNE", "Hickey, MJ"],
    year: 2012,
    journal: "Frontiers in Immunology",
    volume: "3",
    issue: "NOV",
    pages: "354",
    issn: "1664-3224",
    doi: "10.3389/fimmu.2012.00354",
    doiUrl: "http://dx.doi.org/10.3389/fimmu.2012.00354",
  },
  {
    slug: "gavins-2012-intravital-microscopy-new-insights-into-cellular-interactio",
    type: "journal",
    typeLabel: "Journal article",
    title: "Intravital microscopy: new insights into cellular interactions",
    authors: ["Gavins, FNE"],
    year: 2012,
    journal: "Current Opinion in Pharmacology",
    volume: "12",
    issue: "5",
    pages: "601 - 607",
    issn: "1471-4892",
    doi: "10.1016/j.coph.2012.08.006",
    doiUrl: "http://dx.doi.org/10.1016/j.coph.2012.08.006",
  },
  {
    slug: "gavins-2012-new-technologies-only-a-snapshot-but-look-how-far-we-have",
    type: "journal",
    typeLabel: "Journal article",
    title: "New technologies: only a snapshot, but look how far we have come!",
    authors: ["Gavins, FNE"],
    year: 2012,
    journal: "Current Opinion in Pharmacology",
    volume: "12",
    issue: "5",
    pages: "567 - 568",
    issn: "1471-4892",
    doi: "10.1016/j.coph.2012.07.013",
    doiUrl: "http://dx.doi.org/10.1016/j.coph.2012.07.013",
  },
  {
    slug: "leinster-2012-the-peritoneal-tumour-microenvironment-of-high-grade-serous",
    type: "journal",
    typeLabel: "Journal article",
    title: "The peritoneal tumour microenvironment of high-grade serous ovarian cancer",
    authors: ["Leinster, DA", "Kulbe, H", "Everitt, G", "Thompson, R", "Perretti, M", "Gavins, FNE", "Cooper, D", "Gould, D", "Ennis, DP", "Lockley, M", "McNeish, IA", "Nourshargh, S", "Balkwill, FR"],
    year: 2012,
    journal: "Journal of Pathology",
    volume: "227",
    issue: "2",
    pages: "136 - 145",
    issn: "0022-3417",
    doi: "10.1002/path.4002",
    doiUrl: "http://dx.doi.org/10.1002/path.4002",
  },
  {
    slug: "smith-2012-the-potential-of-stem-cell-therapy-for-stroke-is-pisces-the",
    type: "journal",
    typeLabel: "Journal article",
    title: "The potential of stem cell therapy for stroke: is PISCES the sign?",
    authors: ["Smith, HK", "Gavins, FNE"],
    year: 2012,
    journal: "The FASEB Journal",
    volume: "26",
    issue: "6",
    pages: "2239 - 2252",
    issn: "0892-6638",
    doi: "10.1096/fj.11-195719",
    doiUrl: "http://dx.doi.org/10.1096/fj.11-195719",
  },
  {
    slug: "gavins-2011-modeling-inflammation-and-microvascular-dysfunction",
    type: "journal",
    typeLabel: "Journal article",
    title: "Modeling inflammation and microvascular dysfunction",
    authors: ["Gavins, FNE"],
    year: 2011,
    journal: "Annals of the New York Academy of Sciences",
    volume: "1245",
    issue: "1",
    pages: "34 - 35",
    issn: "0077-8923",
    doi: "10.1111/j.1749-6632.2011.06344.x",
    doiUrl: "http://dx.doi.org/10.1111/j.1749-6632.2011.06344.x",
  },
  {
    slug: "gavins-2011-mechanisms-of-enhanced-thrombus-formation-in-cerebral-microv",
    type: "journal",
    typeLabel: "Journal article",
    title: "Mechanisms of enhanced thrombus formation in cerebral microvessels of mice expressing hemoglobin-S",
    authors: ["Gavins, FNE", "Russell, J", "Senchenkova, EL", "De Almeida Paula, L", "Damazo, AS", "Esmon, CT", "Kirchhofer, D", "Hebbel, RP", "Granger, DN"],
    year: 2011,
    journal: "Blood",
    volume: "117",
    issue: "15",
    pages: "4125 - 4133",
    issn: "0006-4971",
    doi: "10.1182/blood-2010-08-301366",
    doiUrl: "http://dx.doi.org/10.1182/blood-2010-08-301366",
  },
  {
    slug: "gavins-2011-microvascular-thrombosis-and-cd40-cd40l-signaling",
    type: "journal",
    typeLabel: "Journal article",
    title: "Microvascular thrombosis and CD40/CD40L signaling",
    authors: ["GAVINS, FNE", "LI, G", "RUSSELL, J", "PERRETTI, M", "GRANGER, DN"],
    year: 2011,
    journal: "Journal of Thrombosis and Haemostasis",
    volume: "9",
    issue: "3",
    pages: "574 - 581",
    issn: "1538-7836",
    doi: "10.1111/j.1538-7836.2010.04176.x",
    doiUrl: "http://dx.doi.org/10.1111/j.1538-7836.2010.04176.x",
  },
  {
    slug: "holloway-2011-targeting-the-melanocortin-receptor-system-for-anti-stroke-t",
    type: "journal",
    typeLabel: "Journal article",
    title: "Targeting the melanocortin receptor system for anti-stroke therapy",
    authors: ["Holloway, PM", "Smith, HK", "Renshaw, D", "Flower, RJ", "Getting, SJ", "Gavins, FNE"],
    year: 2011,
    journal: "Trends in Pharmacological Sciences",
    volume: "32",
    issue: "2",
    pages: "90 - 98",
    issn: "0165-6147",
    doi: "10.1016/j.tips.2010.11.010",
    doiUrl: "http://dx.doi.org/10.1016/j.tips.2010.11.010",
  },
  {
    slug: "flower-2010-amcinonide",
    type: "book-chapter",
    typeLabel: "Book chapter",
    title: "Amcinonide",
    authors: ["Flower, RJ", "Gavins, F"],
    year: 2010,
    journal: "xPharm: The Comprehensive Pharmacology Reference.",
    pages: "1 - 8",
  },
  {
    slug: "gavins-2010-are-formyl-peptide-receptors-novel-targets-for-therapeutic-i",
    type: "journal",
    typeLabel: "Journal article",
    title: "Are formyl peptide receptors novel targets for therapeutic intervention in ischaemia-reperfusion injury?",
    authors: ["Gavins, FNE"],
    year: 2010,
    journal: "Trends in Pharmacological Sciences",
    volume: "31",
    issue: "6",
    pages: "266 - 276",
    issn: "0165-6147",
    doi: "10.1016/j.tips.2010.04.001",
    doiUrl: "http://dx.doi.org/10.1016/j.tips.2010.04.001",
  },
  {
    slug: "hughes-2010-troubleshooting-methods-using-intravital-microscopy-in-drug",
    type: "journal",
    typeLabel: "Journal article",
    title: "Troubleshooting methods: Using intravital microscopy in drug research",
    authors: ["Hughes, EL", "Gavins, FNE"],
    year: 2010,
    journal: "Journal of Pharmacological and Toxicological Methods",
    volume: "61",
    issue: "2",
    pages: "102 - 112",
    issn: "1056-8719",
    doi: "10.1016/j.vascn.2010.01.004",
    doiUrl: "http://dx.doi.org/10.1016/j.vascn.2010.01.004",
  },
  {
    slug: "flower-2009-corticosterone",
    type: "book-chapter",
    typeLabel: "Book chapter",
    title: "Corticosterone",
    authors: ["Flower, RJ", "Gavins, F"],
    year: 2009,
    journal: "xPharm: The Comprehensive Pharmacology Reference.",
    pages: "1 - 3",
  },
  {
    slug: "gavins-2009-current-treatments-and-development-of-modern-therapies-for-s",
    type: "journal",
    typeLabel: "Journal article",
    title: "Current treatments and development of modern therapies for stroke",
    authors: ["Gavins, FNE"],
    year: 2009,
    journal: "Pharmaceutical Journal",
    volume: "282",
    issue: "7546",
    pages: "381 - 382",
    issn: "0031-6873",
  },
  {
    slug: "flower-2008-deflazacort",
    type: "book-chapter",
    typeLabel: "Book chapter",
    title: "Deflazacort",
    authors: ["Flower, RJ", "Gavins, F"],
    year: 2008,
    journal: "xPharm: The Comprehensive Pharmacology Reference.",
    pages: "1 - 5",
  },
  {
    slug: "flower-2008-fluprednisolone",
    type: "book-chapter",
    typeLabel: "Book chapter",
    title: "Fluprednisolone",
    authors: ["Flower, RJ", "Gavins, F"],
    year: 2008,
    journal: "xPharm: The Comprehensive Pharmacology Reference.",
    pages: "1 - 5",
  },
  {
    slug: "flower-2008-halobetasol",
    type: "book-chapter",
    typeLabel: "Book chapter",
    title: "Halobetasol",
    authors: ["Flower, RJ", "Gavins, F"],
    year: 2008,
    journal: "xPharm: The Comprehensive Pharmacology Reference.",
    pages: "1 - 4",
  },
  {
    slug: "flower-2008-difluprednate",
    type: "book-chapter",
    typeLabel: "Book chapter",
    title: "Difluprednate",
    authors: ["Flower, RJ", "Gavins, F"],
    year: 2008,
    journal: "xPharm: The Comprehensive Pharmacology Reference.",
    pages: "1 - 4",
  },
  {
    slug: "flower-2008-halcinonide",
    type: "book-chapter",
    typeLabel: "Book chapter",
    title: "Halcinonide",
    authors: ["Flower, RJ", "Gavins, F"],
    year: 2008,
    journal: "xPharm: The Comprehensive Pharmacology Reference.",
    pages: "1 - 4",
  },
  {
    slug: "flower-2008-clobetasol",
    type: "book-chapter",
    typeLabel: "Book chapter",
    title: "Clobetasol",
    authors: ["Flower, RJ", "Gavins, F"],
    year: 2008,
    journal: "xPharm: The Comprehensive Pharmacology Reference.",
    pages: "1 - 4",
  },
  {
    slug: "flower-2008-cortisone",
    type: "book-chapter",
    typeLabel: "Book chapter",
    title: "Cortisone",
    authors: ["Flower, RJ", "Gavins, F"],
    year: 2008,
    journal: "xPharm: The Comprehensive Pharmacology Reference.",
    pages: "1 - 7",
  },
  {
    slug: "flower-2008-dexamethasone",
    type: "book-chapter",
    typeLabel: "Book chapter",
    title: "Dexamethasone",
    authors: ["Flower, RJ", "Gavins, F"],
    year: 2008,
    journal: "xPharm: The Comprehensive Pharmacology Reference.",
    pages: "1 - 6",
  },
  {
    slug: "flower-2008-clobetasone",
    type: "book-chapter",
    typeLabel: "Book chapter",
    title: "Clobetasone",
    authors: ["Flower, RJ", "Gavins, F"],
    year: 2008,
    journal: "xPharm: The Comprehensive Pharmacology Reference.",
    pages: "1 - 4",
  },
  {
    slug: "flower-2008-fluocortolone",
    type: "book-chapter",
    typeLabel: "Book chapter",
    title: "Fluocortolone",
    authors: ["Flower, RJ", "Gavins, F"],
    year: 2008,
    journal: "xPharm: The Comprehensive Pharmacology Reference.",
    pages: "1 - 4",
  },
  {
    slug: "gavins-2008-budesonide",
    type: "book-chapter",
    typeLabel: "Book chapter",
    title: "Budesonide",
    authors: ["Gavins, F", "Flower, RJ"],
    year: 2008,
    journal: "xPharm: The Comprehensive Pharmacology Reference.",
    pages: "1 - 5",
  },
  {
    slug: "john-2008-annexin-a1-and-the-formyl-peptide-receptor-family-neuroendo",
    type: "journal",
    typeLabel: "Journal article",
    title: "Annexin A1 and the formyl peptide receptor family: neuroendocrine and metabolic aspects",
    authors: ["JOHN, C", "GAVINS, F", "BUSS, N", "COVER, P", "BUCKINGHAM, J"],
    year: 2008,
    journal: "Current Opinion in Pharmacology",
    volume: "8",
    issue: "6",
    pages: "765 - 776",
    issn: "1471-4892",
    doi: "10.1016/j.coph.2008.09.005",
    doiUrl: "http://dx.doi.org/10.1016/j.coph.2008.09.005",
  },
  {
    slug: "leoni-2008-inflamed-phenotype-of-the-mesenteric-microcirculation-of-mel",
    type: "journal",
    typeLabel: "Journal article",
    title: "Inflamed phenotype of the mesenteric microcirculation of melanocortin type 3 receptor‐null mice after ischemia‐reperfusion",
    authors: ["Leoni, G", "Patel, HB", "Sampaio, ALF", "Gavins, FNE", "Murray, JF", "Grieco, P", "Getting, SJ", "Perretti, M"],
    year: 2008,
    journal: "The FASEB Journal",
    volume: "22",
    issue: "12",
    pages: "4228 - 4238",
    issn: "0892-6638",
    doi: "10.1096/fj.08-113886",
    doiUrl: "http://dx.doi.org/10.1096/fj.08-113886",
  },
  {
    slug: "solito-2008-annexin-a1-in-the-brain-undiscovered-roles",
    type: "journal",
    typeLabel: "Journal article",
    title: "Annexin A1 in the brain – undiscovered roles?",
    authors: ["Solito, E", "McArthur, S", "Christian, H", "Gavins, F", "Buckingham, JC", "Gillies, GE"],
    year: 2008,
    journal: "Trends in Pharmacological Sciences",
    volume: "29",
    issue: "3",
    pages: "135 - 142",
    issn: "0165-6147",
    doi: "10.1016/j.tips.2007.12.003",
    doiUrl: "http://dx.doi.org/10.1016/j.tips.2007.12.003",
  },
  {
    slug: "gavins-2007-the-evolving-paradigm-for-blood-cellendothelial-cell-intera",
    type: "journal",
    typeLabel: "Journal article",
    title: "The Evolving Paradigm for Blood Cell‐Endothelial Cell Interactions in the Cerebral Microcirculation",
    authors: ["GAVINS, F", "YILMAZ, G", "GRANGER, DN"],
    year: 2007,
    journal: "Microcirculation",
    volume: "14",
    issue: "7",
    pages: "667 - 681",
    issn: "1073-9688",
    doi: "10.1080/10739680701404903",
    doiUrl: "http://dx.doi.org/10.1080/10739680701404903",
  },
  {
    slug: "gavins-2007-11-deoxycortisol",
    type: "book-chapter",
    typeLabel: "Book chapter",
    title: "11 Deoxycortisol",
    authors: ["Gavins, F"],
    year: 2007,
    journal: "xPharm: The Comprehensive Pharmacology Reference.",
    pages: "1 - 3",
  },
  {
    slug: "gavins-2007-fluticasone",
    type: "book-chapter",
    typeLabel: "Book chapter",
    title: "Fluticasone",
    authors: ["Gavins, F"],
    year: 2007,
    journal: "xPharm: The Comprehensive Pharmacology Reference.",
    pages: "1 - 4",
  },
  {
    slug: "gavins-2007-activation-of-the-annexin-1-counterregulatory-circuit-affor",
    type: "journal",
    typeLabel: "Journal article",
    title: "Activation of the annexin 1 counter‐regulatory circuit affords protection in the mouse brain microcirculation",
    authors: ["Gavins, FNE", "Dalli, J", "Flower, RJ", "Granger, DN", "Perretti, M"],
    year: 2007,
    journal: "The FASEB Journal",
    volume: "21",
    issue: "8",
    pages: "1751 - 1758",
    issn: "0892-6638",
    doi: "10.1096/fj.06-7842com",
    doiUrl: "http://dx.doi.org/10.1096/fj.06-7842com",
  },
  {
    slug: "wan-2007-stem-progenitor-cell-like-properties-of-desmoglein-3dim-cell",
    type: "journal",
    typeLabel: "Journal article",
    title: "Stem/Progenitor Cell-Like Properties of Desmoglein 3dim Cells in Primary and Immortalized Keratinocyte Lines",
    authors: ["Wan, H", "Yuan, M", "Simpson, C", "Allen, K", "Gavins, FNE", "Ikram, MS", "Basu, S", "Baksh, N", "O'Toole, EA", "Hart, IR"],
    year: 2007,
    journal: "Stem Cells",
    volume: "25",
    issue: "5",
    pages: "1286 - 1297",
    issn: "1066-5099",
    doi: "10.1634/stemcells.2006-0304",
    doiUrl: "http://dx.doi.org/10.1634/stemcells.2006-0304",
  },
  {
    slug: "gavins-2006-annexin-1-and-melanocortin-peptide-therapy-for-protection-ag",
    type: "journal",
    typeLabel: "Journal article",
    title: "Annexin 1 and melanocortin peptide therapy for protection against ischaemic-reperfusion damage in the heart",
    authors: ["Gavins, FNE", "Leoni, G", "Getting, SJ"],
    year: 2006,
    journal: "TheScientificWorldJournal",
    volume: "6",
    pages: "1008 - 1023",
    issn: "1537-744X",
    doi: "10.1100/tsw.2006.196",
    doiUrl: "http://dx.doi.org/10.1100/tsw.2006.196",
  },
  {
    slug: "getting-2006-d-trp8-melanocyte-stimulating-hormone-exhibits-anti-infl",
    type: "journal",
    typeLabel: "Journal article",
    title: "[d-Trp8]-γ-Melanocyte-Stimulating Hormone Exhibits Anti-Inflammatory Efficacy in Mice Bearing a Nonfunctional MC1R (Recessive Yellow e/e Mouse)",
    authors: ["Getting, SJ", "Lam, CW", "Leoni, G", "Gavins, FNE", "Grieco, P", "Perretti, M"],
    year: 2006,
    journal: "Molecular Pharmacology",
    volume: "70",
    issue: "6",
    pages: "1850 - 1855",
    issn: "0026-895X",
    doi: "10.1124/mol.106.028878",
    doiUrl: "http://dx.doi.org/10.1124/mol.106.028878",
  },
  {
    slug: "gavins-2005-a-twist-in-anti-inflammation-annexin-1-acts-via-the-lipoxin",
    type: "journal",
    typeLabel: "Journal article",
    title: "A twist in anti-inflammation: Annexin 1 acts via the lipoxin A4 receptor",
    authors: ["Gavins, FNE", "Sawmynaden, P", "Chatterjee, BE", "Perretti, M"],
    year: 2005,
    journal: "Prostaglandins, Leukotrienes and Essential Fatty Acids",
    volume: "73",
    issue: "3-4",
    pages: "211 - 219",
    issn: "0952-3278",
    doi: "10.1016/j.plefa.2005.05.008",
    doiUrl: "http://dx.doi.org/10.1016/j.plefa.2005.05.008",
  },
  {
    slug: "gavins-2005-formylpeptide-receptor-is-not-involved-in-the-protection-af",
    type: "journal",
    typeLabel: "Journal article",
    title: "Formyl‐peptide receptor is not involved in the protection afforded by annexin 1 in murine acute myocardial infarct",
    authors: ["Gavins, FNE", "Kamal, AM", "D'Amico, M", "Oliani, SM", "Perretti, M"],
    year: 2005,
    journal: "The FASEB Journal",
    volume: "19",
    issue: "1",
    pages: "100 - 102",
    issn: "0892-6638",
    doi: "10.1096/fj.04-2178fje",
    doiUrl: "http://dx.doi.org/10.1096/fj.04-2178fje",
  },
  {
    slug: "gavins-2004-intravital-microscopy-for-the-study-of-mouse-microcirculatio",
    type: "journal",
    typeLabel: "Journal article",
    title: "Intravital microscopy for the study of mouse microcirculation in anti-inflammatory drug research: Focus on the mesentery and cremaster preparations",
    authors: ["Gavins, FNE", "Chatterjee, BE"],
    year: 2004,
    journal: "Journal of Pharmacological and Toxicological Methods",
    volume: "49",
    issue: "1",
    pages: "1 - 14",
    issn: "1056-8719",
    doi: "10.1016/s1056-8719(03)00057-1",
    doiUrl: "http://dx.doi.org/10.1016/s1056-8719(03)00057-1",
  },
  {
    slug: "gavins-2003-leukocyte-antiadhesive-actions-of-annexin-1-alxr-and-fpr-r",
    type: "journal",
    typeLabel: "Journal article",
    title: "Leukocyte antiadhesive actions of annexin 1: ALXR- and FPR-related anti-inflammatory mechanisms",
    authors: ["Gavins, FNE", "Yona, S", "Kamal, AM", "Flower, RJ", "Perretti, M"],
    year: 2003,
    journal: "Blood",
    volume: "101",
    issue: "10",
    pages: "4140 - 4147",
    issn: "0006-4971",
    doi: "10.1182/blood-2002-11-3411",
    doiUrl: "http://dx.doi.org/10.1182/blood-2002-11-3411",
  },
  {
    slug: "getting-2003-redundancy-of-a-functional-melanocortin-1-receptor-in-the-an",
    type: "journal",
    typeLabel: "Journal article",
    title: "Redundancy of a Functional Melanocortin 1 Receptor in the Anti-inflammatory Actions of Melanocortin Peptides: Studies in the Recessive Yellow (e/e) Mouse Suggest an Important Role for Melanocortin 3 Receptor",
    authors: ["Getting, SJ", "Christian, HC", "Lam, CW", "Gavins, FNE", "Flower, RJ", "Schiöth, HB", "Perretti, M"],
    year: 2003,
    journal: "The Journal of Immunology",
    volume: "170",
    issue: "6",
    pages: "3323 - 3330",
    issn: "0022-1767",
    doi: "10.4049/jimmunol.170.6.3323",
    doiUrl: "http://dx.doi.org/10.4049/jimmunol.170.6.3323",
  },
  {
    slug: "hannon-2003-aberrant-inflammation-and-resistance-to-glucocorticoids-in-a",
    type: "journal",
    typeLabel: "Journal article",
    title: "Aberrant inflammation and resistance to glucocorticoids in Annexin 1−/−Mouse",
    authors: ["Hannon, R", "Croxtall, JD", "Getting, SJ", "Roviezzo, F", "Yona, S", "Paul‐Clark, MJ", "Gavins, FNE", "Perretti, M", "Morris, JF", "Buckingham, JC", "Flower, RJ"],
    year: 2003,
    journal: "The FASEB Journal",
    volume: "17",
    issue: "2",
    pages: "253 - 255",
    issn: "0892-6638",
    doi: "10.1096/fj.02-0239fje",
    doiUrl: "http://dx.doi.org/10.1096/fj.02-0239fje",
  },
  {
    slug: "perretti-2003-annexin-1-an-endogenous-anti-inflammatory-protein",
    type: "journal",
    typeLabel: "Journal article",
    title: "Annexin 1: An Endogenous Anti-Inflammatory Protein",
    authors: ["Perretti, M", "Gavins, FNE"],
    year: 2003,
    journal: "Physiology",
    volume: "18",
    issue: "2",
    pages: "60 - 64",
    issn: "1548-9213",
    doi: "10.1152/nips.01424.2002",
    doiUrl: "http://dx.doi.org/10.1152/nips.01424.2002",
  },
  {
    slug: "roviezzo-2002-the-annexin-1-knockout-mouse-what-it-tells-us-about-the-inf",
    type: "journal",
    typeLabel: "Journal article",
    title: "The annexin-1 knockout mouse: What it tells us about the inflammatory response",
    authors: ["Roviezzo, F", "Getting, SJ", "Paul-Clark, MJ", "Yona, S", "Gavins, FNE", "Perretti, M", "Hannon, R", "Croxtall, JD", "Buckingham, JC", "Flower, RJ"],
    year: 2002,
    journal: "Journal of Physiology and Pharmacology",
    volume: "53",
    issue: "4 I",
    pages: "541 - 553",
    issn: "0867-5910",
  },
  {
    slug: "henderson-2001-the-use-of-lymphocyte-function-associated-antigen-lfa-1-de",
    type: "journal",
    typeLabel: "Journal article",
    title: "The use of lymphocyte function-associated antigen (LFA)-1-deficient mice to determine the role of LFA-1, Mac-1, and α4 integrin in the inflammatory response of neutrophils",
    authors: ["Henderson, RB", "Lim, LHK", "Tessier, PA", "Gavins, FNE", "Mathies, M", "Perretti, M", "Hogg, N"],
    year: 2001,
    journal: "Journal of Experimental Medicine",
    volume: "194",
    issue: "2",
    pages: "219 - 226",
    issn: "0022-1007",
    doi: "10.1084/jem.194.2.219",
    doiUrl: "http://dx.doi.org/10.1084/jem.194.2.219",
  },
  {
    slug: "la-2001-annexin-1-peptides-protect-against-experimental-myocardial-i",
    type: "journal",
    typeLabel: "Journal article",
    title: "Annexin 1 peptides protect against experimental myocardial ischemia‐reperfusion: analysis of their mechanism of action",
    authors: ["La, M", "D'Amico, M", "Bandiera, S", "Filippo, CD", "Oliani, SM", "Gavins, FNE", "Flower, RJ", "Perretti, M"],
    year: 2001,
    journal: "The FASEB Journal",
    volume: "15",
    issue: "12",
    pages: "2247 - 2256",
    issn: "0892-6638",
    doi: "10.1096/fj.01-0196com",
    doiUrl: "http://dx.doi.org/10.1096/fj.01-0196com",
  },];
