import type { PersonPublication } from "./publications-felicity-gavins";

export const keithRedpathPublications: PersonPublication[] = [
  {
    slug: "bozbas-2024-dietary-n-3-polyunsaturated-fatty-acids-alter-the-number-fa",
    type: "journal",
    typeLabel: "Journal article",
    title: "Dietary n-3 polyunsaturated fatty acids alter the number, fatty acid profile and coagulatory activity of circulating and platelet-derived extracellular vesicles: a randomized, controlled crossover trial",
    authors: ["Bozbas, E", "Zhou, R", "Soyama, S", "Allen-Redpath, K", "Mitchell, JL", "Fisk, HL", "Calder, PC", "Jones, C", "Gibbins, JM", "Fischer, R", "Hester, S", "Yaqoob, P"],
    year: 2024,
    journal: "American Journal of Clinical Nutrition",
    volume: "119",
    issue: "5",
    pages: "1175 - 1186",
    issn: "0002-9165",
    doi: "10.1016/j.ajcnut.2024.03.008",
    doiUrl: "http://dx.doi.org/10.1016/j.ajcnut.2024.03.008",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/29133",
  },
  {
    slug: "hajeyah-2024-phosphatidylthreonine-is-a-procoagulant-lipid-detected-in-hu",
    type: "journal",
    typeLabel: "Journal article",
    title: "Phosphatidylthreonine is a procoagulant lipid detected in human blood and elevated in coronary artery disease",
    authors: ["Hajeyah, AA", "Protty, MB", "Paul, D", "Costa, D", "Omidvar, N", "Morgan, B", "Iwasaki, Y", "McGill, B", "Jenkins, PV", "Yousef, Z", "Allen-Redpath, K", "Soyama, S", "Choudhury, A", "Mitra, R", "Yaqoob, P", "Morrissey, JH", "Collins, PW", "O'Donnell, VB"],
    year: 2024,
    journal: "Journal of Lipid Research",
    volume: "65",
    issue: "1",
    pages: "1 - 15",
    issn: "0022-2275",
    doi: "10.1016/j.jlr.2023.100484",
    doiUrl: "http://dx.doi.org/10.1016/j.jlr.2023.100484",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/29132",
  },
  {
    slug: "protty-2024-thrombin-generation-is-associated-with-extracellular-vesicle",
    type: "journal",
    typeLabel: "Journal article",
    title: "Thrombin Generation Is Associated With Extracellular Vesicle and Leukocyte Lipid Membranes in Atherosclerotic Cardiovascular Disease",
    authors: ["Protty, MB", "Tyrrell, VJ", "Allen-Redpath, K", "Soyama, S", "Hajeyah, AA", "Costa, D", "Choudhury, A", "Mitra, R", "Sharman, A", "Yaqoob, P", "Jenkins, PV", "Yousef, Z", "Collins, PW", "O'Donnell, VB"],
    year: 2024,
    journal: "Arteriosclerosis Thrombosis and Vascular Biology",
    volume: "44",
    issue: "9",
    pages: "2038 - 2052",
    issn: "1079-5642",
    doi: "10.1161/ATVBAHA.124.320902",
    doiUrl: "http://dx.doi.org/10.1161/ATVBAHA.124.320902",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/32228",
  },
  {
    slug: "zhou-2022-circulating-extracellular-vesicles-are-strongly-associated-w",
    type: "journal",
    typeLabel: "Journal article",
    title: "Circulating Extracellular Vesicles Are Strongly Associated With Cardiovascular Risk Markers",
    authors: ["Zhou, R", "Bozbas, E", "Allen-Redpath, K", "Yaqoob, P"],
    year: 2022,
    journal: "Frontiers in Cardiovascular Medicine",
    volume: "9",
    pages: "1 - 14",
    issn: "2297-055X",
    doi: "10.3389/fcvm.2022.907457",
    doiUrl: "http://dx.doi.org/10.3389/fcvm.2022.907457",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/25888",
  },
  {
    slug: "allen-redpath-2019-phospholipid-membranes-drive-abdominal-aortic-aneurysm-devel",
    type: "journal",
    typeLabel: "Journal article",
    title: "Phospholipid membranes drive abdominal aortic aneurysm development through stimulating coagulation factor activity",
    authors: ["Allen-Redpath, K", "Aldrovandi, M", "Lauder, SN", "Gketsopoulou, A", "Tyrrell, VJ", "Slatter, DA", "Andrews, R", "Watkins, WJ", "Atkinson, G", "McNeill, E", "Gilfedder, A", "Protty, M", "Burston, J", "Johnson, SRC", "Rodrigues, PRS", "Jones, DO", "Lee, R", "Handa, A", "Channon, K", "Obaji, S", "Alvarez-Jarreta, J", "Krönke, G", "Ackermann, J", "Jenkins, PV", "Collins, PW", "O’Donnell, VB"],
    year: 2019,
    journal: "Proceedings of the National Academy of Sciences of the United States of America",
    volume: "116",
    issue: "16",
    pages: "8038 - 8047",
    issn: "0027-8424",
    doi: "10.1073/pnas.1814409116",
    doiUrl: "http://dx.doi.org/10.1073/pnas.1814409116",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/26257",
  },
  {
    slug: "slatter-2018-enzymatically-oxidized-phospholipids-restore-thrombin-genera",
    type: "journal",
    typeLabel: "Journal article",
    title: "Enzymatically oxidized phospholipids restore thrombin generation in coagulation factor deficiencies",
    authors: ["Slatter, DA", "Percy, CL", "Allen-Redpath, K", "Gajsiewicz, JM", "Brooks, NJ", "Clayton, A", "Tyrrell, VJ", "Rosas, M", "Lauder, SN", "Watson, A", "Dul, M", "Garcia-Diaz, Y", "Aldrovandi, M", "Heurich, M", "Hall, J", "Morrissey, JH", "Lacroix-Desmazes, S", "Delignat, S", "Jenkins, PV", "Collins, PW", "O'Donnell, VB"],
    year: 2018,
    journal: "JCI insight",
    volume: "3",
    issue: "6",
    pages: "1 - 18",
    issn: "2379-3708",
    doi: "10.1172/jci.insight.98459",
    doiUrl: "http://dx.doi.org/10.1172/jci.insight.98459",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/29145",
  },
  {
    slug: "lauder-2017-networks-of-enzymatically-oxidized-membrane-lipids-support-c",
    type: "journal",
    typeLabel: "Journal article",
    title: "Networks of enzymatically oxidized membrane lipids support calcium-dependent coagulation factor binding to maintain hemostasis",
    authors: ["Lauder, SN", "Allen-Redpath, K", "Slatter, DA", "Aldrovandi, M", "O’Connor, A", "Farewell, D", "Percy, CL", "Molhoek, JE", "Rannikko, S", "Tyrrell, VJ", "Ferla, S", "Milne, GL", "Poole, AW", "Thomas, CP", "Obaji, S", "Taylor, PR", "Jones, SA", "de Groot, PG", "Urbanus, RT", "Hörkkö, S", "Uderhardt, S", "Ackermann, J", "Vince Jenkins, P", "Brancale, A", "Krönke, G", "Collins, PW", "O’Donnell, VB"],
    year: 2017,
    journal: "Science Signaling",
    volume: "10",
    issue: "507",
    pages: "eaan2787",
    issn: "1945-0877",
    doi: "10.1126/scisignal.aan2787",
    doiUrl: "http://dx.doi.org/10.1126/scisignal.aan2787",
  },
  {
    slug: "lauder-2017-myeloid-12-15-lox-regulates-b-cell-numbers-and-innate-immune",
    type: "journal",
    typeLabel: "Journal article",
    title: "Myeloid 12/15-LOX regulates B cell numbers and innate immune antibody levels in vivo",
    authors: ["Lauder, SN", "Tyrrell, VJ", "Allen-Redpath, K", "Aldrovandi, M", "Gray, D", "Collins, P", "Jones, SA", "Taylor, PR", "O'Donnell, V"],
    year: 2017,
    journal: "Wellcome Open Research",
    volume: "2",
    pages: "1 - 1",
    issn: "2398-502X",
    doi: "10.12688/wellcomeopenres.10308.1",
    doiUrl: "http://dx.doi.org/10.12688/wellcomeopenres.10308.1",
  },
  {
    slug: "hinz-2016-human-platelets-utilize-cycloxygenase-1-to-generate-dioxolan",
    type: "journal",
    typeLabel: "Journal article",
    title: "Human Platelets Utilize Cycloxygenase-1 to Generate Dioxolane A3, a Neutrophil-activating Eicosanoid",
    authors: ["Hinz, C", "Aldrovandi, M", "Uhlson, C", "Marnett, LJ", "Longhurst, HJ", "Warner, TD", "Alam, S", "Slatter, DA", "Lauder, SN", "Allen-Redpath, K", "Collins, PW", "Murphy, RC", "Thomas, CP", "O’Donnell, VB"],
    year: 2016,
    journal: "Journal of Biological Chemistry",
    volume: "291",
    issue: "26",
    pages: "13448 - 13464",
    issn: "0021-9258",
    doi: "10.1074/jbc.m115.700609",
    doiUrl: "http://dx.doi.org/10.1074/jbc.m115.700609",
  },
  {
    slug: "allen-redpath-2013-marginal-dietary-zinc-deficiency-in-vivo-induces-vascular-sm",
    type: "journal",
    typeLabel: "Journal article",
    title: "Marginal dietary zinc deficiency in vivo induces vascular smooth muscle cell apoptosis in large arteries",
    authors: ["Allen-Redpath, K", "Ou, O", "Beattie, JH", "Kwun, I-S", "Feldmann, J", "Nixon, GF"],
    year: 2013,
    journal: "Cardiovascular Research",
    volume: "99",
    issue: "3",
    pages: "525 - 534",
    issn: "0008-6363",
    doi: "10.1093/cvr/cvt114",
    doiUrl: "http://dx.doi.org/10.1093/cvr/cvt114",
  },
  {
    slug: "ou-2013-plasma-zinc-s-alter-ego-is-a-lowmolecularweight-humoral-fa",
    type: "journal",
    typeLabel: "Journal article",
    title: "Plasma zinc's alter ego is a low‐molecular‐weight humoral factor",
    authors: ["Ou, O", "Allen‐Redpath, K", "Urgast, D", "Gordon, M", "Campbell, G", "Feldmann, J", "Nixon, GF", "Mayer, C", "Kwun, I", "Beattie, JH"],
    year: 2013,
    journal: "The FASEB Journal",
    volume: "27",
    issue: "9",
    pages: "3672 - 3682",
    issn: "0892-6638",
    doi: "10.1096/fj.13-228791",
    doiUrl: "http://dx.doi.org/10.1096/fj.13-228791",
  },
  {
    slug: "khairy-2010-actions-of-ethanolamine-on-cultured-sensory-neurones-from-ne",
    type: "journal",
    typeLabel: "Journal article",
    title: "Actions of ethanolamine on cultured sensory neurones from neonatal rats",
    authors: ["Khairy, H", "Adjei, G", "Allen-Redpath, K", "Scott, RH"],
    year: 2010,
    journal: "Neuroscience Letters",
    volume: "468",
    issue: "3",
    pages: "326 - 329",
    issn: "0304-3940",
    doi: "10.1016/j.neulet.2009.11.025",
    doiUrl: "http://dx.doi.org/10.1016/j.neulet.2009.11.025",
  },
];
