import type { PersonPublication } from "./publications-felicity-gavins";

export const ashleyHouldenPublications: PersonPublication[] = [
  {
    slug: "houlden-2021-can-microfluidics-be-used-to-create-a-more-realistic-in-vitr",
    type: "journal",
    typeLabel: "Journal article",
    title: "Can microfluidics be used to create a more realistic in vitro model of the vaginal ectocervix to better understand bacterial vaginosis?",
    authors: ["Houlden, A", "Mackay, R"],
    year: 2021,
    journal: "Sexually Transmitted Infections",
    volume: "98",
    issue: "1",
    pages: "74 - 74",
    issn: "1368-4973",
    doi: "10.1136/sextrans-2021-055225",
    doiUrl: "http://dx.doi.org/10.1136/sextrans-2021-055225",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/23185",
  },
  {
    slug: "white-2018-manipulation-of-host-and-parasite-microbiotas-survival-stra",
    type: "journal",
    typeLabel: "Journal article",
    title: "Manipulation of host and parasite microbiotas: Survival strategies during chronic nematode infection",
    authors: ["White, EC", "Houlden, A", "Bancroft, AJ", "Hayes, KS", "Goldrick, M", "Grencis, RK", "Roberts, IS"],
    year: 2018,
    journal: "Science Advances",
    volume: "4",
    issue: "3",
    pages: "eaap7399",
    issn: "2375-2548",
    doi: "10.1126/sciadv.aap7399",
    doiUrl: "http://dx.doi.org/10.1126/sciadv.aap7399",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/16213",
  },
  {
    slug: "ramirez-2017-detecting-macroecological-patterns-in-bacterial-communities",
    type: "journal",
    typeLabel: "Journal article",
    title: "Detecting macroecological patterns in bacterial communities across independent studies of global soils",
    authors: ["Ramirez, KS", "Knight, CG", "De Hollander, M", "Brearley, FQ", "Constantinides, B", "Cotton, A", "Creer, S", "Crowther, TW", "Davison, J", "Delgado-Baquerizo, M", "Dorrepaal, E", "Elliott, DR", "Fox, G", "Griffiths, RI", "Hale, C", "Hartman, K", "Houlden, A", "Jones, DL", "Krab, EJ", "Maestre, FT", "McGuire, KL", "Monteux, S", "Orr, CH", "Van Der Putten, WH", "Roberts, IS", "Robinson, DA", "Rocca, JD", "Rowntree, J", "Schlaeppi, K", "Shepherd, M", "Singh, BK", "Straathof, AL", "Bhatnagar, JM", "Thion, C", "Van Der Heijden, MGA", "De Vries, FT"],
    year: 2017,
    journal: "Nature Microbiology",
    volume: "3",
    issue: "2",
    pages: "189 - 196",
    issn: "2058-5276",
    doi: "10.1038/s41564-017-0062-x",
    doiUrl: "http://dx.doi.org/10.1038/s41564-017-0062-x",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/19056",
  },
  {
    slug: "houlden-2016-brain-injury-induces-specific-changes-in-the-caecal-microbio",
    type: "journal",
    typeLabel: "Journal article",
    title: "Brain injury induces specific changes in the caecal microbiota of mice via altered autonomic activity and mucoprotein production",
    authors: ["Houlden, A", "Goldrick, M", "Brough, D", "Vizi, ES", "Lénárt, N", "Martinecz, B", "Roberts, IS", "Denes, A"],
    year: 2016,
    journal: "Brain, Behavior, and Immunity",
    volume: "57",
    pages: "10 - 20",
    issn: "0889-1591",
    doi: "10.1016/j.bbi.2016.04.003",
    doiUrl: "http://dx.doi.org/10.1016/j.bbi.2016.04.003",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/16962",
  },
  {
    slug: "houlden-2015-chronic-trichuris-muris-infection-in-c57bl-6-mice-causes-sig",
    type: "journal",
    typeLabel: "Journal article",
    title: "Chronic Trichuris muris Infection in C57BL/6 Mice Causes Significant Changes in Host Microbiota and Metabolome: Effects Reversed by Pathogen Clearance",
    authors: ["Houlden, A", "Hayes, KS", "Bancroft, AJ", "Worthington, JJ", "Wang, P", "Grencis, RK", "Roberts, IS"],
    year: 2015,
    journal: "PLOS ONE",
    volume: "10",
    issue: "5",
    pages: "e0125945 - e0125945",
    issn: "1932-6203",
    doi: "10.1371/journal.pone.0125945",
    doiUrl: "http://dx.doi.org/10.1371/journal.pone.0125945",
  },
  {
    slug: "karamanlioglu-2014-isolation-and-characterisation-of-fungal-communities-associa",
    type: "journal",
    typeLabel: "Journal article",
    title: "Isolation and characterisation of fungal communities associated with degradation and growth on the surface of poly(lactic) acid (PLA) in soil and compost",
    authors: ["Karamanlioglu, M", "Houlden, A", "Robson, GD"],
    year: 2014,
    journal: "International Biodeterioration & Biodegradation",
    volume: "95",
    issue: "PB",
    pages: "301 - 310",
    issn: "0964-8305",
    doi: "10.1016/j.ibiod.2014.09.006",
    doiUrl: "http://dx.doi.org/10.1016/j.ibiod.2014.09.006",
  },
  {
    slug: "langarica-fuentes-2014-an-investigation-of-the-biodiversity-of-thermophilic-and-",
    type: "journal",
    typeLabel: "Journal article",
    title: "An investigation of the biodiversity of thermophilic and thermotolerant fungal species in composts using culture-based and molecular techniques",
    authors: ["Langarica-Fuentes, A", "Handley, PS", "Houlden, A", "Fox, G", "Robson, GD"],
    year: 2014,
    journal: "Fungal Ecology",
    volume: "11",
    issue: "October 2014",
    pages: "132 - 144",
    issn: "1754-5048",
    doi: "10.1016/j.funeco.2014.05.007",
    doiUrl: "http://dx.doi.org/10.1016/j.funeco.2014.05.007",
  },
  {
    slug: "zafar-2014-biodegradation-of-polyester-polyurethane-during-commercial-c",
    type: "journal",
    typeLabel: "Journal article",
    title: "Biodegradation of polyester polyurethane during commercial composting and analysis of associated fungal communities",
    authors: ["Zafar, U", "Nzeram, P", "Langarica-Fuentes, A", "Houlden, A", "Heyworth, A", "Saiani, A", "Robson, GD"],
    year: 2014,
    journal: "Bioresource Technology",
    volume: "158",
    issue: "April 2014",
    pages: "374 - 377",
    issn: "0960-8524",
    doi: "10.1016/j.biortech.2014.02.077",
    doiUrl: "http://dx.doi.org/10.1016/j.biortech.2014.02.077",
  },
  {
    slug: "zafar-2013-fungal-communities-associated-with-the-biodegradation-of-pol",
    type: "journal",
    typeLabel: "Journal article",
    title: "Fungal Communities Associated with the Biodegradation of Polyester Polyurethane Buried under Compost at Different Temperatures",
    authors: ["Zafar, U", "Houlden, A", "Robson, GD"],
    year: 2013,
    journal: "Applied and Environmental Microbiology",
    volume: "79",
    issue: "23",
    pages: "7313 - 7324",
    issn: "0099-2240",
    doi: "10.1128/aem.02536-13",
    doiUrl: "http://dx.doi.org/10.1128/aem.02536-13",
  },
  {
    slug: "houlden-2008-influence-of-plant-developmental-stage-on-microbial-communit",
    type: "journal",
    typeLabel: "Journal article",
    title: "Influence of plant developmental stage on microbial community structure and activity in the rhizosphere of three field crops",
    authors: ["Houlden, A", "Timms-Wilson, TM", "Day, MJ", "Bailey, MJ"],
    year: 2008,
    journal: "FEMS Microbiology Ecology",
    volume: "65",
    issue: "2",
    pages: "193 - 201",
    issn: "0168-6496",
    doi: "10.1111/j.1574-6941.2008.00535.x",
    doiUrl: "http://dx.doi.org/10.1111/j.1574-6941.2008.00535.x",
  },
  {
    slug: "timms-wilson-2006-microbial-diversity-in-the-phyllosphere-and-rhizosphere-of-f",
    type: "book-chapter",
    typeLabel: "Book chapter",
    title: "Microbial diversity in the phyllosphere and rhizosphere of field grown crop plants: Microbial specialisation at the plant surface",
    authors: ["Timms-Wilson, TM", "Smalla, K", "Goodall, TI", "Houlden, A", "Gallego, V", "Bailey, MJ"],
    year: 2006,
    journal: "Microbial Ecology of Aerial Plant Surfaces.",
    pages: "21 - 36",
  },
];
