import type { PersonPublication } from "./publications-felicity-gavins";

export const ronanMccarthyPublications: PersonPublication[] = [
  {
    slug: "de-dios-2025-saccharin-disrupts-bacterial-cell-envelope-stability-and-int",
    type: "journal",
    typeLabel: "Journal article",
    title: "Saccharin disrupts bacterial cell envelope stability and interferes with DNA replication dynamics",
    authors: ["de Dios, R", "Gadar, K", "Proctor, CR", "Maslova, E", "Soliman, MAN", "Han, J", "Krawiel, D", "Dunbar, EL", "Singh, B", "Peros, S", "Killelea, T", "Warnke, A-L", "Haugland, MM", "Bolt, EL", "Lentz, CS", "Rudolph, CJ", "McCarthy, RR"],
    year: 2025,
    journal: "EMBO Molecular Medicine",
    volume: "17",
    issue: "5",
    pages: "993 - 1017",
    issn: "1757-4676",
    doi: "10.1038/s44321-025-00219-1",
    doiUrl: "http://dx.doi.org/10.1038/s44321-025-00219-1",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/31004",
  },
  {
    slug: "edzeamey-2025-galleria-mellonella-as-a-drug-discovery-model-to-study-oxida",
    type: "journal",
    typeLabel: "Journal article",
    title: "Galleria mellonella as a drug discovery model to study oxidative stress",
    authors: ["Edzeamey, FJ", "Ramchunder, Z", "McCarthy, RR", "Anjomani-Virmouni, S"],
    year: 2025,
    journal: "Scientific Reports",
    volume: "15",
    issue: "1",
    pages: "1 - 10",
    issn: "2045-2322",
    doi: "10.1038/s41598-025-99337-6",
    doiUrl: "http://dx.doi.org/10.1038/s41598-025-99337-6",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/28236",
  },
  {
    slug: "howard-2025-pseudomonas-aeruginosa-clinical-isolates-can-encode-plastic",
    type: "journal",
    typeLabel: "Journal article",
    title: "Pseudomonas aeruginosa clinical isolates can encode plastic-degrading enzymes that allow survival on plastic and augment biofilm formation",
    authors: ["Howard, SA", "de Dios, R", "Maslova, E", "Myridakis, A", "Miller, TH", "McCarthy, RR"],
    year: 2025,
    journal: "Cell Reports",
    volume: "44",
    issue: "5",
    pages: "1 - 21",
    issn: "2639-1856",
    doi: "10.1016/j.celrep.2025.115650",
    doiUrl: "http://dx.doi.org/10.1016/j.celrep.2025.115650",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/31296",
  },
  {
    slug: "lea-smith-2025-engineering-biology-applications-for-environmental-solutions",
    type: "journal",
    typeLabel: "Journal article",
    title: "Engineering biology applications for environmental solutions: potential and challenges",
    authors: ["Lea-Smith, DJ", "Hassard, F", "Coulon, F", "Partridge, N", "Horsfall, L", "Parker, KDJ", "Smith, RDJ", "McCarthy, RR", "McKew, B", "Gutierrez, T", "Kumar, V", "Dotro, G", "Yang, Z", "Zhang, Y", "Yakunin, A", "Smith, C", "Lyu, T", "Liu, Y", "Le Corre Pidou, K", "Jones, DL", "Jeffrey, P", "Jefferson, B", "Heaven, S", "Golyshin, P", "Curtis, TP", "Krasnogor, N"],
    year: 2025,
    journal: "Nature Communications",
    volume: "16",
    issue: "1",
    pages: "1 - 12",
    issn: "2041-1723",
    doi: "10.1038/s41467-025-58492-0",
    doiUrl: "http://dx.doi.org/10.1038/s41467-025-58492-0",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/31217",
  },
  {
    slug: "payoe-2025-nanoparticle-induced-systemic-toxicity-and-immune-response-i",
    type: "journal",
    typeLabel: "Journal article",
    title: "Nanoparticle-induced systemic toxicity and immune response in Galleria mellonella larvae",
    authors: ["Payoe, KS", "Gadar, K", "Flahaut, E", "McCarthy, RR", "Stenbeck, G"],
    year: 2025,
    journal: "Frontiers in Pharmacology",
    volume: "16",
    pages: "1 - 14",
    issn: "1663-9812",
    doi: "10.3389/fphar.2025.1625472",
    doiUrl: "http://dx.doi.org/10.3389/fphar.2025.1625472",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/32085",
  },
  {
    slug: "soliman-2025-comparative-study-of-common-over-the-counter-wound-care-prod",
    type: "journal",
    typeLabel: "Journal article",
    title: "Comparative study of common over-the-counter wound care products against early and mature biofilms of antibiotic-resistant wound pathogens",
    authors: ["Soliman, MAN", "Garg, S", "Harkova, LG", "McCarthy, RR"],
    year: 2025,
    journal: "JAC-Antimicrobial Resistance",
    volume: "7",
    issue: "6",
    pages: "1 - 10",
    issn: "2632-1823",
    doi: "10.1093/jacamr/dlaf233",
    doiUrl: "http://dx.doi.org/10.1093/jacamr/dlaf233",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/32321",
  },
  {
    slug: "valcek-2025-inter-and-intra-bacterial-strain-diversity-remains-the-ele",
    type: "journal",
    typeLabel: "Journal article",
    title: "Inter- and intra-bacterial strain diversity remains the “elephant in the (living) room”",
    authors: ["Valcek, A", "Kröger, C", "de Dios, R", "McCarthy, RR", "Coenye, T", "Trent, MS", "Karah, N", "Uhlin, BE", "Classen, AY", "Higgins, PG", "Ebersberger, I", "Laaberki, M-H", "Charpentier, X", "Visca, P", "Rather, PN", "Van der Henst, C"],
    year: 2025,
    journal: "npj Antimicrobials and Resistance",
    volume: "3",
    issue: "1",
    pages: "1 - 8",
    issn: "2731-8745",
    doi: "10.1038/s44259-025-00138-8",
    doiUrl: "http://dx.doi.org/10.1038/s44259-025-00138-8",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/32296",
  },
  {
    slug: "carr-2024-engineering-biology-approaches-to-modulate-bacterial-biofilm",
    type: "journal",
    typeLabel: "Journal article",
    title: "Engineering biology approaches to modulate bacterial biofilms",
    authors: ["Carr, CM", "Harkova, LG", "McCarthy, RR"],
    year: 2024,
    journal: "Trends in Biotechnology",
    volume: "43",
    issue: "7",
    pages: "1525 - 1527",
    issn: "0167-7799",
    doi: "10.1016/j.tibtech.2024.11.002",
    doiUrl: "http://dx.doi.org/10.1016/j.tibtech.2024.11.002",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/30546",
  },
  {
    slug: "harkova-2024-cyclic-amp-is-a-global-virulence-regulator-governing-inter-a",
    type: "journal",
    typeLabel: "Journal article",
    title: "Cyclic AMP is a global virulence regulator governing inter and intrabacterial signalling in Acinetobacter baumannii",
    authors: ["Harkova, LG", "de Dios, R", "Rubio Valle, A", "Pérez Pulido, AJ", "McCarthy, RR"],
    year: 2024,
    journal: "PLoS Pathogens",
    volume: "20",
    issue: "9",
    pages: "1 - 30",
    issn: "1553-7366",
    doi: "10.1371/journal.ppat.1012529",
    doiUrl: "http://dx.doi.org/10.1371/journal.ppat.1012529",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/29699",
  },
  {
    slug: "hassard-2024-scaling-up-engineering-biology-for-enhanced-environmental-so",
    type: "journal",
    typeLabel: "Journal article",
    title: "Scaling-up Engineering Biology for Enhanced Environmental Solutions",
    authors: ["Hassard, F", "Curtis, TP", "Dotro, GC", "Golyshin, P", "Gutierrez, T", "Heaven, S", "Horsfall, L", "Jefferson, B", "Jones, DL", "Krasnogor, N", "Kumar, V", "Lea-Smith, DJ", "Le Corre Pidou, K", "Liu, Y", "Lyu, T", "McCarthy, RR", "McKew, B", "Smith, C", "Yakunin, A", "Yang, Z", "Zhang, Y", "Coulon, F"],
    year: 2024,
    journal: "ACS synthetic biology",
    volume: "13",
    issue: "6",
    pages: "1586 - 1588",
    issn: "2161-5063",
    doi: "10.1021/acssynbio.4c00292",
    doiUrl: "http://dx.doi.org/10.1021/acssynbio.4c00292",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/29456",
  },
  {
    slug: "maslova-2024-carbon-source-competition-within-the-wound-microenvironment",
    type: "journal",
    typeLabel: "Journal article",
    title: "Carbon source competition within the wound microenvironment can significantly influence infection progression",
    authors: ["Maslova, E", "EisaianKhongi, L", "Rigole, P", "Coenye, T", "McCarthy, RR"],
    year: 2024,
    journal: "npj Biofilms and Microbiomes",
    volume: "10",
    issue: "1",
    pages: "1 - 10",
    issn: "2055-5008",
    doi: "10.1038/s41522-024-00518-4",
    doiUrl: "http://dx.doi.org/10.1038/s41522-024-00518-4",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/28825",
  },
  {
    slug: "wallach-2024-ai-is-a-viable-alternative-to-high-throughput-screening-a-3",
    type: "journal",
    typeLabel: "Journal article",
    title: "AI is a viable alternative to high throughput screening: a 318-target study",
    authors: ["Wallach, I", "Bernard, D", "Nguyen, K", "Ho, G", "Morrison, A", "Stecula, A", "Rosnik, A", "O’Sullivan, AM", "Davtyan, A", "Samudio, B", "Thomas, B", "Worley, B", "Butler, B", "Laggner, C", "Thayer, D", "Moharreri, E", "Friedland, G", "Truong, H", "van den Bedem, H", "Ng, HL", "Stafford, K", "Sarangapani, K", "Giesler, K", "Ngo, L", "Mysinger, M", "Ahmed, M", "Anthis, NJ", "Henriksen, N", "Gniewek, P", "Eckert, S", "de Oliveira, S", "Suterwala, S", "PrasadPrasad, SVK", "Shek, S", "Contreras, S", "Hare, S", "Palazzo, T", "O’Brien, TE", "Van Grack, T", "Williams, T", "Chern, TR", "Kenyon, V", "Lee, AH", "Cann, AB", "Bergman, B", "Anderson, BM", "Cox, BD", "Warrington, JM", "Sorenson, JM", "Goldenberg, JM", "Young, MA", "DeHaan, N", "Pemberton, RP", "Schroedl, S", "Abramyan, TM", "Gupta, T", "Mysore, V", "Presser, AG", "Ferrando, AA", "Andricopulo, AD", "Ghosh, A", "Ayachi, AG", "Mushtaq, A", "Shaqra, AM", "Toh, AKL", "Smrcka, AV", "Ciccia, A", "de Oliveira, AS", "Sverzhinsky, A", "de Sousa, AM", "Agoulnik, AI", "Kushnir, A", "Freiberg, AN", "Statsyuk, AV", "Gingras, AR", "Degterev, A", "Tomilov, A", "Vrielink, A", "Garaeva, AA", "Bryant-Friedrich, A", "Caflisch, A", "Patel, AK", "Rangarajan, AV", "Matheeussen, A", "Battistoni, A", "Caporali, A", "Chini, A", "Ilari, A", "Mattevi, A", "Foote, AT", "Trabocchi, A", "Stahl, A", "Herr, AB", "Berti, A", "Freywald, A", "Reidenbach, AG", "Lam, A", "Cuddihy, AR", "White, A", "Taglialatela, A", "Gadar, K", "McCarthy, RR", "The Atomwise AIMS Program"],
    year: 2024,
    journal: "Scientific Reports",
    volume: "14",
    issue: "1",
    pages: "1 - 16",
    issn: "2045-2322",
    doi: "10.1038/s41598-024-54655-z",
    doiUrl: "http://dx.doi.org/10.1038/s41598-024-54655-z",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/29093",
  },
  {
    slug: "gadar-2023-using-next-generation-antimicrobials-to-target-the-mechanism",
    type: "journal",
    typeLabel: "Journal article",
    title: "Using next generation antimicrobials to target the mechanisms of infection",
    authors: ["Gadar, K", "McCarthy, RR"],
    year: 2023,
    journal: "npj Antimicrobials and Resistance",
    volume: "1",
    issue: "1",
    pages: "1 - 14",
    issn: "2731-8745",
    doi: "10.1038/s44259-023-00011-6",
    doiUrl: "http://dx.doi.org/10.1038/s44259-023-00011-6",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/27373",
  },
  {
    slug: "gadar-2023-disrupting-iron-homeostasis-can-potentiate-colistin-activity",
    type: "journal",
    typeLabel: "Journal article",
    title: "Disrupting iron homeostasis can potentiate colistin activity and overcome colistin resistance mechanisms in Gram-Negative Bacteria",
    authors: ["Gadar, K", "de Dios, R", "Kadeřábková, N", "Prescott, TAK", "Mavridou, DAI", "McCarthy, RR"],
    year: 2023,
    journal: "Communications Biology",
    volume: "6",
    issue: "1",
    pages: "1 - 16",
    issn: "2399-3642",
    doi: "10.1038/s42003-023-05302-2",
    doiUrl: "http://dx.doi.org/10.1038/s42003-023-05302-2",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/27199",
  },
  {
    slug: "howard-2023-modulating-biofilm-can-potentiate-activity-of-novel-plastic",
    type: "journal",
    typeLabel: "Journal article",
    title: "Modulating biofilm can potentiate activity of novel plastic-degrading enzymes",
    authors: ["Howard, SA", "McCarthy, RR"],
    year: 2023,
    journal: "npj Biofilms and Microbiomes",
    volume: "9",
    issue: "1",
    pages: "1 - 10",
    issn: "2055-5008",
    doi: "10.1038/s41522-023-00440-1",
    doiUrl: "http://dx.doi.org/10.1038/s41522-023-00440-1",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/27233",
  },
  {
    slug: "howard-2023-enrichment-of-native-plastic-associated-biofilm-communities",
    type: "journal",
    typeLabel: "Journal article",
    title: "Enrichment of native plastic associated biofilm communities to enhance polyester degrading activity",
    authors: ["Howard, SA", "Carr, CM", "Sbahtu, HI", "Onwukwe, U", "López, MJ", "Dobson, ADW", "McCarthy, RR"],
    year: 2023,
    journal: "Environmental Microbiology",
    volume: "25",
    issue: "12",
    pages: "2698 - 2718",
    issn: "1462-2912",
    doi: "10.1111/1462-2920.16466",
    doiUrl: "http://dx.doi.org/10.1111/1462-2920.16466",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/26897",
  },
  {
    slug: "maslova-2023-using-the-galleria-mellonella-burn-wound-and-infection-model",
    type: "journal",
    typeLabel: "Journal article",
    title: "Using the Galleria mellonella burn wound and infection model to identify and characterize potential wound probiotics",
    authors: ["Maslova, E", "Osman, S", "McCarthy, RR"],
    year: 2023,
    journal: "Microbiology",
    volume: "169",
    issue: "6",
    pages: "1 - 9",
    issn: "1350-0872",
    doi: "10.1099/mic.0.001350",
    doiUrl: "http://dx.doi.org/10.1099/mic.0.001350",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/26648",
  },
  {
    slug: "proctor-2023-furanone-loaded-aerogels-are-effective-antibiofilm-therapeut",
    type: "journal",
    typeLabel: "Journal article",
    title: "Furanone loaded aerogels are effective antibiofilm therapeutics in a model of chronic Pseudomonas aeruginosa wound infection",
    authors: ["Proctor, CR", "Taggart, MG", "O'Hagan, BMG", "McCarron, PA", "McCarthy, RR", "Ternan, NG"],
    year: 2023,
    journal: "Biofilm",
    volume: "5",
    pages: "1 - 10",
    issn: "2590-2075",
    doi: "10.1016/j.bioflm.2023.100128",
    doiUrl: "http://dx.doi.org/10.1016/j.bioflm.2023.100128",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/26523",
  },
  {
    slug: "arroyo-moreno-2022-identification-and-characterization-of-novel-endolysins-targ",
    type: "journal",
    typeLabel: "Journal article",
    title: "Identification and characterization of novel endolysins targeting Gardnerella vaginalis biofilms to treat bacterial vaginosis",
    authors: ["Arroyo-Moreno, S", "Cummings, M", "Corcoran, DB", "Coffey, A", "McCarthy, RR"],
    year: 2022,
    journal: "npj Biofilms and Microbiomes",
    volume: "8",
    issue: "1",
    pages: "1 - 12",
    issn: "2055-5008",
    doi: "10.1038/s41522-022-00285-0",
    doiUrl: "http://dx.doi.org/10.1038/s41522-022-00285-0",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/24071",
  },
  {
    slug: "de-dios-2022-artificial-sweeteners-inhibit-multidrugresistant-pathogen-g",
    type: "journal",
    typeLabel: "Journal article",
    title: "Artificial sweeteners inhibit multidrug‐resistant pathogen growth and potentiate antibiotic activity",
    authors: ["de Dios, R", "Proctor, CR", "Maslova, E", "Dzalbe, S", "Rudolph, CJ", "McCarthy, RR"],
    year: 2022,
    journal: "EMBO Molecular Medicine",
    volume: "15",
    issue: "1",
    pages: "1 - 21",
    issn: "1757-4676",
    doi: "10.15252/emmm.202216397",
    doiUrl: "http://dx.doi.org/10.15252/emmm.202216397",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/25534",
  },
  {
    slug: "de-dios-2022-a-high-efficiency-scar-free-genome-editing-toolkit-foracinet",
    type: "journal",
    typeLabel: "Journal article",
    title: "A high-efficiency scar-free genome-editing toolkit forAcinetobacter baumannii",
    authors: ["de Dios, R", "Gadar, K", "McCarthy, RR"],
    year: 2022,
    journal: "Journal of Antimicrobial Chemotherapy",
    volume: "77",
    issue: "12",
    pages: "3390 - 3398",
    issn: "0305-7453",
    doi: "10.1093/jac/dkac328",
    doiUrl: "http://dx.doi.org/10.1093/jac/dkac328",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/25224",
  },
  {
    slug: "furniss-2022-breaking-antimicrobial-resistance-by-disrupting-extracytopla",
    type: "journal",
    typeLabel: "Journal article",
    title: "Breaking antimicrobial resistance by disrupting extracytoplasmic protein folding",
    authors: ["Furniss, RCD", "Kaderabkova, N", "Barker, D", "Bernal, P", "Maslova, E", "Antwi, AAA", "McNeil, HE", "Pugh, HL", "Dortet, L", "Blair, JMA", "Larrouy-Maumus, GJ", "McCarthy, RR", "Gonzalez, D", "Mavridou, DAI"],
    year: 2022,
    journal: "eLife",
    volume: "11",
    pages: "1 - 69",
    issn: "2050-084X",
    doi: "10.7554/elife.57974",
    doiUrl: "http://dx.doi.org/10.7554/elife.57974",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/24032",
  },
  {
    slug: "maslova-2021-burns-and-biofilms-priority-pathogens-and-in-vivo-models",
    type: "journal",
    typeLabel: "Journal article",
    title: "Burns and Biofilms: Priority pathogens and in vivo models",
    authors: ["Maslova, E", "Eisaiankhongi, L", "Sjöberg, F", "McCarthy, R"],
    year: 2021,
    journal: "npj Biofilms and Microbiomes",
    volume: "7",
    issue: "1",
    pages: "1 - 9",
    issn: "2055-5008",
    doi: "10.1038/s41522-021-00243-2",
    doiUrl: "http://dx.doi.org/10.1038/s41522-021-00243-2",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/23101",
  },
  {
    slug: "mccleary-2021-inactivation-of-african-swine-fever-virus-by-reagents-common",
    type: "journal",
    typeLabel: "Journal article",
    title: "Inactivation of African Swine Fever Virus by reagents commonly used in containment laboratories",
    authors: ["McCleary, S", "McCarthy, RR", "Strong, R", "Edwards, J", "Crooke, H"],
    year: 2021,
    journal: "Journal of Virological Methods",
    volume: "295",
    pages: "1 - 5",
    issn: "0166-0934",
    doi: "10.1016/j.jviromet.2021.114203",
    doiUrl: "http://dx.doi.org/10.1016/j.jviromet.2021.114203",
  },
  {
    slug: "sanchez-cordon-2021-evaluation-of-lesions-and-viral-antigen-distribution-in-dome",
    type: "journal",
    typeLabel: "Journal article",
    title: "Evaluation of Lesions and Viral Antigen Distribution in Domestic Pigs Inoculated Intranasally with African Swine Fever Virus Ken05/Tk1 (Genotype X)",
    authors: ["Sánchez-Cordón, PJ", "Floyd, T", "Hicks, D", "Crooke, HR", "McCleary, S", "McCarthy, RR", "Strong, R", "Dixon, LK", "Neimanis, A", "Wikström-Lassa, E", "Gavier-Widén, D", "Núñez, A"],
    year: 2021,
    journal: "Pathogens",
    volume: "10",
    issue: "6",
    pages: "768 - 768",
    issn: "2076-0817",
    doi: "10.3390/pathogens10060768",
    doiUrl: "http://dx.doi.org/10.3390/pathogens10060768",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/22885",
  },
  {
    slug: "ullah-2021-editorial-nanocellulose-a-multipurpose-advanced-functional",
    type: "journal",
    typeLabel: "Journal article",
    title: "Editorial: Nanocellulose: A Multipurpose Advanced Functional Material",
    authors: ["Ullah, MW", "Rojas, OJ", "McCarthy, RR", "Yang, G"],
    year: 2021,
    journal: "Frontiers in Bioengineering and Biotechnology",
    volume: "9",
    pages: "1 - 4",
    issn: "2296-4185",
    doi: "10.3389/fbioe.2021.738779",
    doiUrl: "http://dx.doi.org/10.3389/fbioe.2021.738779",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/22975",
  },
  {
    slug: "evgenia-2020-an-invertebrate-burn-wound-model-that-recapitulates-the-hall",
    type: "journal",
    typeLabel: "Journal article",
    title: "An Invertebrate Burn Wound Model That Recapitulates the Hallmarks of Burn Trauma and Infection Seen in Mammalian Models",
    authors: ["Evgenia, M", "Shi, Y", "Sjöberg, F", "Azevedo, HS", "David, W", "McCarthy, RR"],
    year: 2020,
    journal: "Frontiers in Microbiology",
    volume: "11",
    pages: "1 - 8",
    issn: "1664-302X",
    doi: "10.3389/fmicb.2020.00998",
    doiUrl: "http://dx.doi.org/10.3389/fmicb.2020.00998",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/20724",
  },
  {
    slug: "mccleary-2020-substitution-of-warthog-nf-b-motifs-into-rela-of-domestic-p",
    type: "journal",
    typeLabel: "Journal article",
    title: "Substitution of warthog NF-κB motifs into RELA of domestic pigs is not sufficient to confer resilience to African swine fever virus",
    authors: ["McCleary, S", "Strong, R", "McCarthy, RR", "Edwards, JC", "Howes, EL", "Stevens, LM", "Sánchez-Cordón, PJ", "Núñez, A", "Watson, S", "Mileham, AJ", "Lillico, SG", "Tait-Burkard, C", "Proudfoot, C", "Ballantyne, M", "Whitelaw, CBA", "Steinbach, F", "Crooke, HR"],
    year: 2020,
    journal: "Scientific Reports",
    volume: "10",
    issue: "1",
    pages: "1 - 11",
    issn: "2045-2322",
    doi: "10.1038/s41598-020-65808-1",
    doiUrl: "http://dx.doi.org/10.1038/s41598-020-65808-1",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/20960",
  },
  {
    slug: "mccarthy-2019-head-start-immunity-characterising-the-early-protection-of",
    type: "journal",
    typeLabel: "Journal article",
    title: "Head Start Immunity: Characterising the early protection of C strain vaccine against subsequent classical swine fever virus infection",
    authors: ["McCarthy, R", "Everett, H", "Graham, SP", "Steinbach, F", "Crooke, HR"],
    year: 2019,
    journal: "Frontiers in Immunology",
    volume: "10",
    pages: "1 - 34",
    issn: "1664-3224",
    doi: "10.3389/fimmu.2019.01584",
    doiUrl: "http://dx.doi.org/10.3389/fimmu.2019.01584",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/18598",
  },
  {
    slug: "mccarthy-2019-antimicrobial-inks-the-anti-infective-applications-of-biopr",
    type: "journal",
    typeLabel: "Journal article",
    title: "Antimicrobial Inks: The Anti-Infective Applications of Bioprinted Bacterial Polysaccharides",
    authors: ["McCarthy, R", "Ullah, MW", "Pei, E", "Yang, G"],
    year: 2019,
    journal: "Trends in Biotechnology",
    volume: "37",
    issue: "11",
    pages: "1155 - 1159",
    issn: "0167-7799",
    doi: "10.1016/j.tibtech.2019.05.004",
    doiUrl: "http://dx.doi.org/10.1016/j.tibtech.2019.05.004",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/18333",
  },
  {
    slug: "mccarthy-2019-cyclic-digmp-inactivates-t6ss-and-t4ss-activity-in-agrobact",
    type: "journal",
    typeLabel: "Journal article",
    title: "Cyclic di‐GMP inactivates T6SS and T4SS activity in Agrobacterium tumefaciens",
    authors: ["McCarthy, R", "Yu, M", "Eilers, K", "Wang, Y-C", "Lai, E-M", "Filloux, A"],
    year: 2019,
    journal: "Molecular Microbiology",
    volume: "112",
    issue: "2",
    pages: "632 - 648",
    issn: "0950-382X",
    doi: "10.1111/mmi.14279",
    doiUrl: "http://dx.doi.org/10.1111/mmi.14279",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/18310",
  },
  {
    slug: "mccarthy-2019-the-use-of-bacterial-polysaccharides-in-bioprinting",
    type: "journal",
    typeLabel: "Journal article",
    title: "The use of bacterial polysaccharides in bioprinting",
    authors: ["McCarthy, RR", "Ullah, MW", "Booth, P", "Pei, E", "Yang, G"],
    year: 2019,
    journal: "Biotechnology Advances",
    volume: "37",
    issue: "8",
    pages: "1 - 14",
    issn: "0734-9750",
    doi: "10.1016/j.biotechadv.2019.107448",
    doiUrl: "http://dx.doi.org/10.1016/j.biotechadv.2019.107448",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/19228",
  },
  {
    slug: "reen-2019-quorum-sensing-signalling-alters-virulence-potential-and-pop",
    type: "journal",
    typeLabel: "Journal article",
    title: "Quorum sensing signalling alters virulence potential and population dynamics in complex microbiome-host interactomes",
    authors: ["Reen, FJ", "Gutierrez Barranquero, JA", "McCarthy, RR", "Woods, DF", "Scarciglia, S", "Adams, C", "Fog Nielsen, K", "Gram, L", "O'Gara, F"],
    year: 2019,
    journal: "Frontiers in Microbiology",
    volume: "10",
    pages: "1 - 13",
    issn: "1664-302X",
    doi: "10.3389/fmicb.2019.02131",
    doiUrl: "http://dx.doi.org/10.3389/fmicb.2019.02131",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/19112",
  },
  {
    slug: "gutierrez-barranquero-2017-disruption-of-n-acyl-homoserine-lactone-specific-sign",
    type: "journal",
    typeLabel: "Journal article",
    title: "Disruption of N -acyl-homoserine lactone-specific signalling and virulence in clinical pathogens by marine sponge bacteria",
    authors: ["Gutiérrez-Barranquero, JA", "Reen, FJ", "Parages, ML", "McCarthy, R", "Dobson, ADW", "O'Gara, F"],
    year: 2017,
    journal: "Microbial Biotechnology",
    volume: "12",
    issue: "5",
    pages: "1049 - 1063",
    issn: "1751-7915",
    doi: "10.1111/1751-7915.12867",
    doiUrl: "http://dx.doi.org/10.1111/1751-7915.12867",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/16963",
  },
  {
    slug: "mccarthy-2017-contribution-of-cyclic-di-gmp-in-the-control-of-type-iii-and",
    type: "book",
    typeLabel: "Book",
    title: "Contribution of Cyclic di-GMP in the Control of Type III and Type VI Secretion in Pseudomonas aeruginosa",
    authors: ["McCarthy, RR", "Valentini, M", "Filloux, A"],
    year: 2017,
    journal: "'Contribution of Cyclic di-GMP in the Control of Type III and Type VI Secretion in Pseudomonas aeruginosa.'",
  },
  {
    slug: "mccarthy-2017-cyclic-di-gmp-regulates-lipopolysaccharide-modification-and",
    type: "journal",
    typeLabel: "Journal article",
    title: "Cyclic-di-GMP regulates lipopolysaccharide modification and contributes to Pseudomonas aeruginosa immune evasion",
    authors: ["McCarthy, RR", "Mazon-Moya, MJ", "Moscoso, JA", "Hao, Y", "Lam, JS", "Bordi, C", "Mostowy, S", "Filloux, A"],
    year: 2017,
    journal: "Nature Microbiology",
    volume: "2",
    issue: "6",
    pages: "17027",
    issn: "2058-5276",
    doi: "10.1038/nmicrobiol.2017.27",
    doiUrl: "http://dx.doi.org/10.1038/nmicrobiol.2017.27",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/16968",
  },
  {
    slug: "gutierrez-barranquero-2015-deciphering-the-role-of-coumarin-as-a-novel-quorum-se",
    type: "journal",
    typeLabel: "Journal article",
    title: "Deciphering the role of coumarin as a novel quorum sensing inhibitor suppressing virulence phenotypes in bacterial pathogens",
    authors: ["Gutiérrez-Barranquero, JA", "Reen, FJ", "McCarthy, RR", "O’Gara, F"],
    year: 2015,
    journal: "Applied Microbiology and Biotechnology",
    volume: "99",
    issue: "7",
    pages: "3303 - 3316",
    issn: "0175-7598",
    doi: "10.1007/s00253-015-6436-1",
    doiUrl: "http://dx.doi.org/10.1007/s00253-015-6436-1",
  },
  {
    slug: "larrouy-maumus-2015-direct-detection-of-lipid-a-on-intact-gram-negative-bacteria",
    type: "journal",
    typeLabel: "Journal article",
    title: "Direct detection of lipid A on intact Gram-negative bacteria by MALDI-TOF mass spectrometry",
    authors: ["Larrouy-Maumus, G", "Clements, A", "Filloux, A", "McCarthy, RR", "Mostowy, S"],
    year: 2015,
    journal: "Journal of Microbiological Methods",
    volume: "120",
    pages: "68 - 71",
    issn: "0167-7012",
    doi: "10.1016/j.mimet.2015.12.004",
    doiUrl: "http://dx.doi.org/10.1016/j.mimet.2015.12.004",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/16961",
  },
  {
    slug: "mccarthy-2015-the-impact-of-phytochemicals-present-in-the-diet-on-microbia",
    type: "journal",
    typeLabel: "Journal article",
    title: "The impact of phytochemicals present in the diet on microbial signalling in the human gut",
    authors: ["McCarthy, RR", "O'Gara, F"],
    year: 2015,
    journal: "Journal of Functional Foods",
    volume: "14",
    pages: "684 - 691",
    issn: "1756-4646",
    doi: "10.1016/j.jff.2015.02.032",
    doiUrl: "http://dx.doi.org/10.1016/j.jff.2015.02.032",
  },
  {
    slug: "mccarthy-2014-a-new-regulator-of-pathogenicity-bvlr-is-required-for-full",
    type: "journal",
    typeLabel: "Journal article",
    title: "A new regulator of pathogenicity (bvlR) is required for full virulence and tight microcolony formation in Pseudomonas aeruginosa",
    authors: ["McCarthy, RR", "Mooij, MJ", "Reen, FJ", "Lesouhaitier, O", "O'Gara, F"],
    year: 2014,
    journal: "Microbiology",
    volume: "160",
    issue: "Pt_7",
    pages: "1488 - 1500",
    issn: "1350-0872",
    doi: "10.1099/mic.0.075291-0",
    doiUrl: "http://dx.doi.org/10.1099/mic.0.075291-0",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/17012",
  },
  {
    slug: "mac-aogain-2012-the-non-classical-arsr-family-repressor-pyer-pa4354-modula",
    type: "journal",
    typeLabel: "Journal article",
    title: "The non-classical ArsR-family repressor PyeR (PA4354) modulates biofilm formation in Pseudomonas aeruginosa",
    authors: ["Mac Aogáin, M", "Mooij, MJ", "McCarthy, RR", "Plower, E", "Wang, YP", "Tian, ZX", "Dobson, A", "Morrissey, J", "Adams, C", "O’Gara, F"],
    year: 2012,
    journal: "Microbiology",
    volume: "158",
    issue: "10",
    pages: "2598 - 2609",
    issn: "1350-0872",
    doi: "10.1099/mic.0.058636-0",
    doiUrl: "http://dx.doi.org/10.1099/mic.0.058636-0",
  },
];
