import type { PersonPublication } from "./publications-felicity-gavins";

export const arturoSalaPublications: PersonPublication[] = [
  {
    slug: "bibbo-2024-ev20-omomyc-a-novel-dual-myc-her3-targeting-immunoconjugate",
    type: "journal",
    typeLabel: "Journal article",
    title: "EV20/Omomyc: A novel dual MYC/HER3 targeting immunoconjugate",
    authors: ["Bibbò, S", "Capone, E", "Lovato, G", "Lamolinara, A", "Ponziani, S", "Iezzi, M", "Lattanzio, R", "Mazzocco, K", "Morini, M", "Giansanti, F", "De Laurenzi, V", "Whitfield, J", "Iacobelli, S", "Ippoliti, R", "Beaulieu, M-E", "Soucek, L", "Sala, A", "Sala, G"],
    year: 2024,
    journal: "Journal of Controlled Release",
    volume: "374",
    pages: "171 - 180",
    issn: "0168-3659",
    doi: "10.1016/j.jconrel.2024.08.009",
    doiUrl: "http://dx.doi.org/10.1016/j.jconrel.2024.08.009",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/29740",
  },
  {
    slug: "ciciro-2024-expression-of-the-checkpoint-kinase-bub1-is-a-predictor-of-r",
    type: "journal",
    typeLabel: "Journal article",
    title: "Expression of the checkpoint kinase BUB1 is a predictor of response to cancer therapies",
    authors: ["Cicirò, Y", "Ragusa, D", "Sala, A"],
    year: 2024,
    journal: "Scientific Reports",
    volume: "14",
    issue: "1",
    pages: "1 - 15",
    issn: "2045-2322",
    doi: "10.1038/s41598-024-55080-y",
    doiUrl: "http://dx.doi.org/10.1038/s41598-024-55080-y",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/28433",
  },
  {
    slug: "ciciro-2023-the-mitotic-checkpoint-kinase-bub1-is-a-direct-and-actionabl",
    type: "journal",
    typeLabel: "Journal article",
    title: "The mitotic checkpoint kinase BUB1 is a direct and actionable target of MYB in adenoid cystic carcinoma",
    authors: ["Cicirò, Y", "Ragusa, D", "Tejera Nevado, P", "Lattanzio, R", "Sala, G", "DesRochers, T", "Millard, M", "Andersson, MK", "Stenman, G", "Sala, A"],
    year: 2023,
    journal: "FEBS Letters",
    volume: "598",
    issue: "2",
    pages: "252 - 265",
    issn: "0014-5793",
    doi: "10.1002/1873-3468.14786",
    doiUrl: "http://dx.doi.org/10.1002/1873-3468.14786",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/27688",
  },
  {
    slug: "ciciro-2021-myb-oncoproteins-emerging-players-and-potential-therapeutic",
    type: "journal",
    typeLabel: "Journal article",
    title: "MYB oncoproteins: emerging players and potential therapeutic targets in human cancer",
    authors: ["Cicirò, Y", "Sala, A"],
    year: 2021,
    journal: "Oncogenesis",
    volume: "10",
    issue: "2",
    pages: "1 - 15",
    issn: "2157-9024",
    doi: "10.1007/s11356-021-17359-9",
    doiUrl: "http://dx.doi.org/10.1007/s11356-021-17359-9",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/22274",
  },
  {
    slug: "tagalakis-2021-integrin-targeted-short-interfering-rna-nanocomplexes-for-n",
    type: "journal",
    typeLabel: "Journal article",
    title: "Integrin-Targeted, Short Interfering RNA Nanocomplexes for Neuroblastoma Tumor-Specific Delivery Achieve MYCN Silencing with Improved Survival",
    authors: ["Tagalakis, AD", "Jayarajan, V", "Maeshima, R", "Ho, KH", "Syed, F", "Wu, L-P", "Aldossary, AM", "Munye, MM", "Mistry, T", "Ogunbiyi, OK", "Sala, A", "Standing, JF", "Moghimi, SM", "Stoker, AW", "Hart, SL"],
    year: 2021,
    journal: "Advanced Functional Materials",
    volume: "31",
    issue: "37",
    pages: "1 - 12",
    issn: "1616-301X",
    doi: "10.1002/adfm.202104843",
    doiUrl: "http://dx.doi.org/10.1002/adfm.202104843",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/28252",
  },
  {
    slug: "tsakaneli-2021-myc-regulates-metabolism-through-vesicular-transfer-of-glyco",
    type: "journal",
    typeLabel: "Journal article",
    title: "MYC regulates metabolism through vesicular transfer of glycolytic kinases",
    authors: ["Tsakaneli, A", "Carregari, VC", "Morini, M", "Eva, A", "Cangemi, G", "Chayka, O", "Makarov, E", "Bibbò, S", "Capone, E", "Sala, G", "De Laurenzi, V", "Poon, E", "Chesler, L", "Pieroni, L", "Larsen, MR", "Palmisano, G", "Sala, A"],
    year: 2021,
    journal: "Open Biology",
    volume: "11",
    issue: "12",
    pages: "1 - 15",
    issn: "2046-2441",
    doi: "10.1098/rsob.210276",
    doiUrl: "http://dx.doi.org/10.1098/rsob.210276",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/23894",
  },
  {
    slug: "andersson-2020-atr-is-a-myb-regulated-gene-and-potential-therapeutic-target",
    type: "journal",
    typeLabel: "Journal article",
    title: "ATR is a MYB regulated gene and potential therapeutic target in adenoid cystic carcinoma",
    authors: ["Andersson, MK", "Mangiapane, G", "Nevado, PT", "Tsakaneli, A", "Carlsson, T", "Corda, G", "Nieddu, V", "Abrahamian, C", "Chayka, O", "Rai, L", "Wick, M", "Kedaigle, A", "Stenman, G", "Sala, A"],
    year: 2020,
    journal: "Oncogenesis",
    volume: "9",
    issue: "1",
    pages: "5",
    issn: "2157-9024",
    doi: "10.1038/s41389-020-0194-3",
    doiUrl: "http://dx.doi.org/10.1038/s41389-020-0194-3",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/20287",
  },
  {
    slug: "capone-2020-targeting-vesicular-lgals3bp-by-an-antibody-drug-conjugate-a",
    type: "journal",
    typeLabel: "Journal article",
    title: "Targeting Vesicular LGALS3BP by an Antibody-Drug Conjugate as Novel Therapeutic Strategy for Neuroblastoma",
    authors: ["Capone, E", "Lamolinara, A", "Pastorino, F", "Gentile, R", "Ponziani, S", "Di Vittorio, G", "D’Agostino, D", "Bibbò, S", "Rossi, C", "Piccolo, E", "Iacobelli, V", "Lattanzio, R", "Panella, V", "Sallese, M", "De Laurenzi, V", "Giansanti, F", "Sala, A", "Iezzi, M", "Ponzoni, M", "Ippoliti, R", "Iacobelli, S", "Sala, G"],
    year: 2020,
    journal: "Cancers",
    volume: "12",
    issue: "10",
    pages: "1 - 18",
    issn: "2072-6694",
    doi: "10.3390/cancers12102989",
    doiUrl: "http://dx.doi.org/10.3390/cancers12102989",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/21742",
  },
  {
    slug: "karteris-2019-engineered-human-mesenchymal-stem-cells-for-neuroblastoma-th",
    type: "journal",
    typeLabel: "Journal article",
    title: "Engineered human mesenchymal stem cells for neuroblastoma therapeutics",
    authors: ["Karteris, E", "Nieddu, V", "Piredda, R", "Bexel, D", "Barton, J", "Anderson, J", "Sebire, N", "Kolluri, K", "Janes, SM", "Sala, A"],
    year: 2019,
    journal: "Oncology Reports",
    volume: "42",
    issue: "1",
    pages: "1 - 8",
    issn: "1021-335X",
    doi: "10.3892/or.2019.7152",
    doiUrl: "http://dx.doi.org/10.3892/or.2019.7152",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/17659",
  },
  {
    slug: "capone-2017-generation-of-a-novel-antibody-drug-conjugate-targeting-endo",
    type: "journal",
    typeLabel: "Journal article",
    title: "Generation of a novel Antibody-Drug Conjugate targeting endosialin: potent and durable antitumor response in sarcoma.",
    authors: ["Capone, E", "Piccolo, E", "Fichera, I", "Ciufici, P", "Barcaroli, D", "Sala, A", "De Laurenzi, V", "Iacobelli, V", "Iacobelli, S", "Sala, G"],
    year: 2017,
    journal: "Oncotarget",
    volume: "8",
    issue: "36",
    pages: "60368 - 60377",
    issn: "1949-2553",
    doi: "10.18632/oncotarget.19499",
    doiUrl: "http://dx.doi.org/10.18632/oncotarget.19499",
  },
  {
    slug: "sala-2017-non-canonical-wnt-pcp-signalling-in-cancer-fzd6-takes-centr",
    type: "journal",
    typeLabel: "Journal article",
    title: "Non-canonical WNT/PCP signalling in cancer: Fzd6 takes centre stage.",
    authors: ["Sala, A", "corda, G"],
    year: 2017,
    journal: "Oncogenesis",
    volume: "6",
    issue: "7",
    pages: "e364 - e364",
    issn: "2157-9024",
    doi: "10.1038/oncsis.2017.69",
    doiUrl: "http://dx.doi.org/10.1038/oncsis.2017.69",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/14935",
  },
  {
    slug: "corda-2016-functional-and-prognostic-significance-of-the-genomic-amplif",
    type: "journal",
    typeLabel: "Journal article",
    title: "Functional and prognostic significance of the genomic amplification of frizzled receptor 6 ( FZD6 ) in breast cancer",
    authors: ["Corda, G", "Sala, G", "Lattanzio, R", "Iezzi, M", "Sallese, M", "Fragassi, G", "Lamolinara, A", "Mirza, H", "Barcaroli, D", "Ermler, S", "Silva, E", "Yasaei, H", "Newbold, RF", "Vagnarelli, P", "Mottolese, M", "Natali, PG", "Perracchio, L", "Quist, J", "Grigoriadis, A", "Marra, P", "Tutt, AN", "Piantelli, M", "Iacobelli, S", "De Laurenzi, V", "Sala, A"],
    year: 2016,
    journal: "The Journal of Pathology",
    volume: "241",
    issue: "3",
    pages: "350 - 361",
    issn: "0022-3417",
    doi: "10.1002/path.4841",
    doiUrl: "http://dx.doi.org/10.1002/path.4841",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/13942",
  },
  {
    slug: "corda-2016-cutaneous-cylindroma-it-s-all-about-myb",
    type: "journal",
    typeLabel: "Journal article",
    title: "Cutaneous cylindroma: it's all about MYB",
    authors: ["Corda, G", "Sala, A"],
    year: 2016,
    journal: "The Journal of Pathology",
    volume: "29",
    issue: "4",
    pages: "391 - 393",
    issn: "0022-3417",
    doi: "10.1002/path.4746",
    doiUrl: "http://dx.doi.org/10.1002/path.4746",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/13096",
  },
  {
    slug: "dvorkina-2016-a-promyelocytic-leukemia-protein-thrombospondin-2-axis-and-t",
    type: "journal",
    typeLabel: "Journal article",
    title: "A promyelocytic leukemia protein-thrombospondin 2 axis and the risk of relapse in neuroblastoma.",
    authors: ["Dvorkina, M", "Nieddu, V", "Chakelam, S", "Pezzolo, A", "Cantilena, S", "Leite, AP", "Chayka, O", "Regad, T", "Pistorio, A", "Sementa, AR", "Virasami, A", "Barton, J", "Montano, X", "Lechertier, T", "Brindle, N", "Morgenstern, D", "LE Bras, M", "Burns, A", "Saunders, N", "Hodivala-Dilke, K", "Bagella, L", "de The, H", "Anderson, J", "Sebire, N", "Pistoia, V", "Sala, A", "Salomoni, P"],
    year: 2016,
    journal: "Clinical cancer research : an official journal of the American Association for Cancer Research",
    volume: "22",
    issue: "13",
    pages: "3398 - 3409",
    issn: "1078-0432",
    doi: "10.1158/1078-0432.CCR-15-2081",
    doiUrl: "http://dx.doi.org/10.1158/1078-0432.CCR-15-2081",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/13759",
  },
  {
    slug: "sala-2015-editorial-targeting-mycn-in-pediatric-cancers",
    type: "journal",
    typeLabel: "Journal article",
    title: "Editorial: Targeting MYCN in pediatric cancers",
    authors: ["Sala, A"],
    year: 2015,
    journal: "Frontiers in Oncology",
    volume: "5",
    issue: "MAY",
    pages: "1 - 2",
    issn: "2234-943X",
    doi: "10.3389/fonc.2014.00330",
    doiUrl: "http://dx.doi.org/10.3389/fonc.2014.00330",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/28253",
  },
  {
    slug: "chayka-2014-identification-and-pharmacological-inactivation-of-the-mycn",
    type: "journal",
    typeLabel: "Journal article",
    title: "Identification and pharmacological inactivation of the MYCN gene network as a therapeutic strategy for neuroblastic tumor cells",
    authors: ["Chayka, O", "D'Acunto, CW", "Middleton, O", "Arab, M", "Sala, A"],
    year: 2014,
    journal: "Journal of Biological Chemistry",
    volume: "290",
    issue: "4",
    pages: "2198 - 2212",
    issn: "0021-9258",
    doi: "10.1074/jbc.M114.624056",
    doiUrl: "http://dx.doi.org/10.1074/jbc.M114.624056",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/10247",
  },
  {
    slug: "corvetta-2013-physical-interaction-between-mycn-oncogene-and-polycomb-repr",
    type: "journal",
    typeLabel: "Journal article",
    title: "Physical interaction between MYCN oncogene and polycomb repressive complex 2 (PRC2) in neuroblastoma: Functional and therapeutic implications",
    authors: ["Corvetta, D", "Chayka, O", "Gherardi, S", "D'Acunto, CW", "Cantilena, S", "Valli, E", "Piotrowska, I", "Perini, G", "Sala, A"],
    year: 2013,
    journal: "Journal of Biological Chemistry",
    volume: "288",
    issue: "12",
    pages: "8332 - 8341",
    issn: "0021-9258",
    doi: "10.1074/jbc.M113.454280",
    doiUrl: "http://dx.doi.org/10.1074/jbc.M113.454280",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/7977",
  },
  {
    slug: "santilli-2013-catechins-and-antitumor-immunity",
    type: "journal",
    typeLabel: "Journal article",
    title: "Catechins and antitumor immunity",
    authors: ["Santilli, G", "Anderson, J", "Thrasher, AJ", "Sala, A"],
    year: 2013,
    journal: "OncoImmunology",
    volume: "2",
    issue: "6",
    pages: "e24443 - e24443",
    issn: "2162-4011",
    doi: "10.4161/onci.24443",
    doiUrl: "http://dx.doi.org/10.4161/onci.24443",
  },
  {
    slug: "santilli-2013-polyphenon-e-enhances-the-antitumor-immune-response-in-neuro",
    type: "journal",
    typeLabel: "Journal article",
    title: "Polyphenon E enhances the antitumor immune response in neuroblastoma by inactivating myeloid suppressor cells",
    authors: ["Santilli, G", "Thrasher, AJ", "Piotrowska, I", "Cantilena, S", "Chayka, O", "D'Alicarnasso, M", "Morgenstern, DA", "Himoudi, N", "Pearson, K", "Anderson, J", "Sala, A"],
    year: 2013,
    journal: "Clinical Cancer Research",
    volume: "19",
    issue: "5",
    pages: "1116 - 1125",
    issn: "1078-0432",
    doi: "10.1158/1078-0432.CCR-12-2528",
    doiUrl: "http://dx.doi.org/10.1158/1078-0432.CCR-12-2528",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/8725",
  },
  {
    slug: "sala-2012-c-myb-and-tgf-emts-dynamic-duo-in-breast-cancer",
    type: "journal",
    typeLabel: "Journal article",
    title: "c-MYB and TGFβ: EMT’s dynamic duo in breast cancer",
    authors: ["Sala, A"],
    year: 2012,
    journal: "Cell Cycle",
    volume: "11",
    issue: "1",
    pages: "17 - 17",
    issn: "1538-4101",
    doi: "10.4161/cc.11.1.18733",
    doiUrl: "http://dx.doi.org/10.4161/cc.11.1.18733",
  },
  {
    slug: "sottile-2012-a-chemical-screen-identifies-the-chemotherapeutic-drug-topot",
    type: "journal",
    typeLabel: "Journal article",
    title: "A chemical screen identifies the chemotherapeutic drug topotecan as a specific inhibitor of the B-MYB/MYCN axis in neuroblastoma",
    authors: ["Sottile, F", "Gnemmi, I", "Cantilena, S", "D'Acunto, WC", "Sala, A"],
    year: 2012,
    journal: "Oncotarget",
    volume: "3",
    issue: "5",
    pages: "535 - 545",
    issn: "1949-2553",
    doi: "10.18632/oncotarget.498",
    doiUrl: "http://dx.doi.org/10.18632/oncotarget.498",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/6547",
  },
  {
    slug: "cantilena-2011-frizzled-receptor-6-marks-rare-highly-tumourigenic-stem-lik",
    type: "journal",
    typeLabel: "Journal article",
    title: "Frizzled receptor 6 marks rare, highly tumourigenic stem-like cells in mouse and human neuroblastomas",
    authors: ["Cantilena, S", "Pastorino, F", "Pezzolo, A", "Chayka, O", "Pistoia, V", "Ponzoni, M", "Sala, A"],
    year: 2011,
    journal: "Oncotarget",
    volume: "2",
    issue: "12",
    pages: "976 - 983",
    issn: "1949-2553",
    doi: "10.18632/oncotarget.410",
    doiUrl: "http://dx.doi.org/10.18632/oncotarget.410",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/6275",
  },
  {
    slug: "chaiwatanasirikul-2011-the-tumour-suppressive-function-of-clu-is-explained-by-it",
    type: "journal",
    typeLabel: "Journal article",
    title: "The tumour-suppressive function of CLU is explained by its localisation and interaction with HSP60",
    authors: ["Chaiwatanasirikul, K-A", "Sala, A"],
    year: 2011,
    journal: "Cell Death and Disease",
    volume: "2",
    issue: "10",
    issn: "2041-4889",
    doi: "10.1038/cddis.2011.99",
    doiUrl: "http://dx.doi.org/10.1038/cddis.2011.99",
  },
  {
    slug: "gualdrini-2010-addiction-of-mycn-amplified-tumours-to-b-myb-underscores-a-r",
    type: "journal",
    typeLabel: "Journal article",
    title: "Addiction of MYCN amplified tumours to B-MYB underscores a reciprocal regulatory loop",
    authors: ["Gualdrini, F", "Corvetta, D", "Cantilena, S", "Chayka, O", "Tanno, B", "Raschellà, G", "Sala, A"],
    year: 2010,
    journal: "Oncotarget",
    volume: "1",
    issue: "4",
    pages: "278 - 288",
    issn: "1949-2553",
    doi: "10.18632/oncotarget.138",
    doiUrl: "http://dx.doi.org/10.18632/oncotarget.138",
  },
  {
    slug: "bettuzzi-2009-genetic-inactivation-of-apoj-clusterin-effects-on-prostate",
    type: "journal",
    typeLabel: "Journal article",
    title: "Genetic inactivation of ApoJ/clusterin: Effects on prostate tumourigenesis and metastatic spread",
    authors: ["Bettuzzi, S", "Davalli, P", "Davoli, S", "Chayka, O", "Rizzi, F", "Belloni, L", "Pellacani, D", "Fregni, G", "Astancolle, S", "Fassan, M", "Corti, A", "Baffa, R", "Sala, A"],
    year: 2009,
    journal: "Oncogene",
    volume: "28",
    issue: "49",
    pages: "4344 - 4352",
    issn: "0950-9232",
    doi: "10.1038/onc.2009.286",
    doiUrl: "http://dx.doi.org/10.1038/onc.2009.286",
  },
  {
    slug: "chayka-2009-clusterin-a-haploinsufficient-tumor-suppressor-gene-in-neur",
    type: "journal",
    typeLabel: "Journal article",
    title: "Clusterin, a haploinsufficient tumor suppressor gene in neuroblastomas",
    authors: ["Chayka, O", "Corvetta, D", "Dews, M", "Caccamo, AE", "Piotrowska, I", "Santilli, G", "Gibson, S", "Sebire, NJ", "Himoudi, N", "Hogarty, MD", "Anderson, J", "Bettuzzi, S", "Thomas-Tikhonenko, A", "Sala, A"],
    year: 2009,
    journal: "Journal of the National Cancer Institute",
    volume: "101",
    issue: "9",
    pages: "663 - 677",
    issn: "0027-8874",
    doi: "10.1093/jnci/djp063",
    doiUrl: "http://dx.doi.org/10.1093/jnci/djp063",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/8827",
  },
  {
    slug: "sala-2009-regulation-of-clu-gene-expression-by-oncogenes-and-epigeneti",
    type: "journal",
    typeLabel: "Journal article",
    title: "Regulation of CLU gene expression by oncogenes and epigenetic factors implications for tumorigenesis",
    authors: ["Sala, A", "Bettuzzi, S", "Pucci, S", "Chayka, O", "Dews, M", "Thomas-Tikhonenko, A"],
    year: 2009,
    journal: "Advances in Cancer Research",
    volume: "105",
    issue: "1",
    pages: "115 - 132",
    issn: "0065-230X",
    doi: "10.1016/S0065-230X(09)05007-6",
    doiUrl: "http://dx.doi.org/10.1016/S0065-230X(09)05007-6",
  },
  {
    slug: "schwab-2008-isolation-and-functional-assessment-of-common-polymorphic-v",
    type: "journal",
    typeLabel: "Journal article",
    title: "Isolation and functional assessment of common, polymorphic variants of the B-MYB proto-oncogene associated with a reduced cancer risk",
    authors: ["Schwab, R", "Bussolari, R", "Corvetta, D", "Chayka, O", "Santilli, G", "Kwok, JM", "Ferrari-Amorotti, G", "Tonini, GP", "Iacoviello, L", "Bertorelle, R", "Menin, C", "Hubank, M", "Calabretta, B", "Sala, A"],
    year: 2008,
    journal: "Oncogene",
    volume: "27",
    issue: "20",
    pages: "2929 - 2933",
    issn: "0950-9232",
    doi: "10.1038/sj.onc.1210947",
    doiUrl: "http://dx.doi.org/10.1038/sj.onc.1210947",
  },
  {
    slug: "schwab-2007-b-myb-is-hypophosphorylated-and-resistant-to-degradation-in",
    type: "journal",
    typeLabel: "Journal article",
    title: "B-MYB is hypophosphorylated and resistant to degradation in neuroblastoma: Implications for cell survival",
    authors: ["Schwab, R", "Caccamo, A", "Bettuzzi, S", "Anderson, J", "Sala, A"],
    year: 2007,
    journal: "Blood Cells, Molecules, and Diseases",
    volume: "39",
    issue: "3",
    pages: "263 - 271",
    issn: "1079-9796",
    doi: "10.1016/j.bcmd.2007.04.006",
    doiUrl: "http://dx.doi.org/10.1016/j.bcmd.2007.04.006",
  },
  {
    slug: "santilli-2003-essential-requirement-of-apolipoprotein-j-clusterin-signal",
    type: "journal",
    typeLabel: "Journal article",
    title: "Essential requirement of apolipoprotein J (clusterin) signaling for IkappaB expression and regulation of NF-kappaB activity",
    authors: ["Santilli, G", "Aronow, BJ", "Sala, A"],
    year: 2003,
    journal: "Journal of Biological Chemistry",
    volume: "278",
    issue: "40",
    pages: "38214 - 38219",
    issn: "0021-9258",
    doi: "10.1074/jbc.C300252200",
    doiUrl: "http://dx.doi.org/10.1074/jbc.C300252200",
  },
];
