import type { PersonPublication } from "./publications-felicity-gavins";

export const doreenLauPublications: PersonPublication[] = [
  {
    slug: "lau-2025-imaging-antigen-processing-and-presentation-in-cancer",
    type: "journal",
    typeLabel: "Journal article",
    title: "Imaging Antigen Processing and Presentation in Cancer",
    authors: ["Lau, D", "Elliott, T"],
    year: 2025,
    journal: "Immunotherapy Advances",
    volume: "0",
    issue: "ahead of print",
    pages: "1 - 42",
    issn: "2732-4303",
    doi: "10.1093/immadv/ltaf002",
    doiUrl: "http://dx.doi.org/10.1093/immadv/ltaf002",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/30684",
  },
  {
    slug: "chan-2023-123i-cc1-a-parp-targeting-auger-electronemitting-radioph",
    type: "journal",
    typeLabel: "Journal article",
    title: "[123I]CC1: A PARP-Targeting, Auger Electron–Emitting Radiopharmaceutical for Radionuclide Therapy of Cancer",
    authors: ["Chan, CY", "Chen, Z", "Guibbal, F", "Dias, G", "Destro, G", "O’Neill, E", "Veal, M", "Lau, D", "Mosley, M", "Wilson, TC", "Gouverneur, V", "Cornelissen, B"],
    year: 2023,
    journal: "Journal of Nuclear Medicine",
    volume: "64",
    issue: "12",
    pages: "1965 - 1971",
    issn: "0161-5505",
    doi: "10.2967/jnumed.123.265429",
    doiUrl: "http://dx.doi.org/10.2967/jnumed.123.265429",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/29407",
  },
  {
    slug: "lau-2023-imaging-inflammation-a-historical-perspective",
    type: "book-chapter",
    typeLabel: "Book chapter",
    title: "Imaging Inflammation: A Historical Perspective",
    authors: ["Lau, D"],
    year: 2023,
    journal: "Imaging Inflammation.",
    pages: "1 - 21",
  },
  {
    slug: "sugiyarto-2023-reactivation-of-low-avidity-tumor-specific-cd8-t-cells-assoc",
    type: "journal",
    typeLabel: "Journal article",
    title: "Reactivation of low avidity tumor-specific CD8+T cells associates with immunotherapeutic efficacy of anti-PD-1",
    authors: ["Sugiyarto, G", "Lau, D", "Hill, SL", "Arcia-Anaya, D", "Boulanger, DSM", "Parkes, EE", "James, E", "Elliott, T"],
    year: 2023,
    journal: "Journal for ImmunoTherapy of Cancer",
    volume: "11",
    issue: "8",
    pages: "1 - 15",
    issn: "2051-1426",
    doi: "10.1136/jitc-2023-007114",
    doiUrl: "http://dx.doi.org/10.1136/jitc-2023-007114",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/29405",
  },
  {
    slug: "uhl-2023-interferon-couples-cd8-t-cell-avidity-and-differentiation",
    type: "journal",
    typeLabel: "Journal article",
    title: "Interferon-γ couples CD8+T cell avidity and differentiation during infection",
    authors: ["Uhl, LFK", "Cai, H", "Oram, SL", "Mahale, JN", "MacLean, AJ", "Mazet, JM", "Piccirilli, T", "He, AJ", "Lau, D", "Elliott, T", "Gerard, A"],
    year: 2023,
    journal: "Nature Communications",
    volume: "14",
    issue: "1",
    pages: "1 - 17",
    issn: "2041-1723",
    doi: "10.1038/s41467-023-42455-4",
    doiUrl: "http://dx.doi.org/10.1038/s41467-023-42455-4",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/29404",
  },
  {
    slug: "chan-2022-correlation-between-molar-activity-injection-mass-and-uptak",
    type: "journal",
    typeLabel: "Journal article",
    title: "Correlation between molar activity, injection mass and uptake of the PARP targeting radiotracer [18F]olaparib in mouse models of glioma",
    authors: ["Chan, CY", "Hopkins, SL", "Guibbal, F", "Pacelli, A", "Baguña Torres, J", "Mosley, M", "Lau, D", "Isenegger, P", "Chen, Z", "Wilson, TC", "Dias, G", "Hueting, R", "Gouverneur, V", "Cornelissen, B"],
    year: 2022,
    journal: "EJNMMI Research",
    volume: "12",
    issue: "1",
    pages: "1 - 10",
    issn: "2191-219X",
    doi: "10.1186/s13550-022-00940-9",
    doiUrl: "http://dx.doi.org/10.1186/s13550-022-00940-9",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/29408",
  },
  {
    slug: "chan-2022-imaging-parp-with-18f-rucaparib-in-pancreatic-cancer-models",
    type: "journal",
    typeLabel: "Journal article",
    title: "Imaging PARP with [18F]rucaparib in pancreatic cancer models",
    authors: ["Chan, CY", "Chen, Z", "Destro, G", "Veal, M", "Lau, D", "O’Neill, E", "Dias, G", "Mosley, M", "Kersemans, V", "Guibbal, F", "Gouverneur, V", "Cornelissen, B"],
    year: 2022,
    journal: "European Journal of Nuclear Medicine and Molecular Imaging",
    volume: "49",
    issue: "11",
    pages: "3668 - 3678",
    issn: "1619-7070",
    doi: "10.1007/s00259-022-05835-4",
    doiUrl: "http://dx.doi.org/10.1007/s00259-022-05835-4",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/29412",
  },
  {
    slug: "fraser-2022-radiofluorination-of-a-highly-potent-atm-inhibitor-as-a-pote",
    type: "journal",
    typeLabel: "Journal article",
    title: "Radiofluorination of a highly potent ATM inhibitor as a potential PET imaging agent",
    authors: ["Fraser, CR", "Ajenjo, J", "Veal, M", "Dias, GM", "Chan, C", "O’Neill, E", "Destro, G", "Lau, D", "Pacelli, A", "Gouverneur, V", "Hueting, R", "Cornelissen, B"],
    year: 2022,
    journal: "EJNMMI Research",
    volume: "12",
    issue: "1",
    pages: "1 - 12",
    issn: "2191-219X",
    doi: "10.1186/s13550-022-00920-z",
    doiUrl: "http://dx.doi.org/10.1186/s13550-022-00920-z",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/29410",
  },
  {
    slug: "lau-2022-mri-techniques-for-immunotherapy-monitoring",
    type: "journal",
    typeLabel: "Journal article",
    title: "MRI techniques for immunotherapy monitoring",
    authors: ["Lau, D", "Corrie, PG", "Gallagher, FA"],
    year: 2022,
    journal: "Journal for ImmunoTherapy of Cancer",
    volume: "10",
    issue: "9",
    pages: "1 - 17",
    issn: "2051-1426",
    doi: "10.1136/jitc-2022-004708",
    doiUrl: "http://dx.doi.org/10.1136/jitc-2022-004708",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/29409",
  },
  {
    slug: "lau-2021-clinical-translation-of-neutrophil-imaging-and-its-role-in-c",
    type: "journal",
    typeLabel: "Journal article",
    title: "Clinical Translation of Neutrophil Imaging and Its Role in Cancer",
    authors: ["Lau, D", "Lechermann, LM", "Gallagher, FA"],
    year: 2021,
    journal: "Molecular Imaging and Biology",
    volume: "24",
    issue: "2",
    pages: "221 - 234",
    issn: "1536-1632",
    doi: "10.1007/s11307-021-01649-2",
    doiUrl: "http://dx.doi.org/10.1007/s11307-021-01649-2",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/29414",
  },
  {
    slug: "lau-2021-multiparametric-mri-of-early-tumor-response-to-immune-checkp",
    type: "journal",
    typeLabel: "Journal article",
    title: "Multiparametric MRI of early tumor response to immune checkpoint blockade in metastatic melanoma",
    authors: ["Lau, D", "McLean, MA", "Priest, AN", "Gill, AB", "Scott, F", "Patterson, I", "Carmo, B", "Riemer, F", "Kaggie, JD", "Frary, A", "Milne, D", "Booth, C", "Lewis, A", "Sulikowski, M", "Brown, L", "Lapointe, J-M", "Aloj, L", "Graves, MJ", "Brindle, KM", "Corrie, PG", "Gallagher, FA"],
    year: 2021,
    journal: "Journal for ImmunoTherapy of Cancer",
    volume: "9",
    issue: "9",
    pages: "1 - 14",
    issn: "2051-1426",
    doi: "10.1136/jitc-2021-003125",
    doiUrl: "http://dx.doi.org/10.1136/jitc-2021-003125",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/29415",
  },
  {
    slug: "lechermann-2021-in-vivo-cell-tracking-using-pet-opportunities-and-challenge",
    type: "journal",
    typeLabel: "Journal article",
    title: "In vivo cell tracking using pet: Opportunities and challenges for clinical translation in oncology",
    authors: ["Lechermann, LM", "Lau, D", "Attili, B", "Aloj, L", "Gallagher, FA"],
    year: 2021,
    journal: "Cancers",
    volume: "13",
    issue: "16",
    pages: "1 - 19",
    issn: "2072-6694",
    doi: "10.3390/cancers13164042",
    doiUrl: "http://dx.doi.org/10.3390/cancers13164042",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/29416",
  },
  {
    slug: "rabbie-2021-unraveling-the-cartography-of-the-cancer-ecosystem",
    type: "journal",
    typeLabel: "Journal article",
    title: "Unraveling the cartography of the cancer ecosystem",
    authors: ["Rabbie, R", "Lau, D", "White, RM", "Adams, DJ"],
    year: 2021,
    journal: "Genome Biology",
    volume: "22",
    issue: "1",
    pages: "1 - 9",
    issn: "1474-7596",
    doi: "10.1186/s13059-021-02310-5",
    doiUrl: "http://dx.doi.org/10.1186/s13059-021-02310-5",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/29413",
  },
  {
    slug: "lau-2020-intravital-imaging-of-adoptive-t-cell-morphology-mobility-a",
    type: "journal",
    typeLabel: "Journal article",
    title: "Intravital Imaging of Adoptive T-Cell Morphology, Mobility and Trafficking Following Immune Checkpoint Inhibition in a Mouse Melanoma Model",
    authors: ["Lau, D", "Garçon, F", "Chandra, A", "Lechermann, LM", "Aloj, L", "Chilvers, ER", "Corrie, PG", "Okkenhaug, K", "Gallagher, FA"],
    year: 2020,
    journal: "Frontiers in Immunology",
    volume: "11",
    pages: "1514",
    issn: "1664-3224",
    doi: "10.3389/fimmu.2020.01514",
    doiUrl: "http://dx.doi.org/10.3389/fimmu.2020.01514",
  },
  {
    slug: "brickute-2019-development-and-evaluation-of-an18f-radiolabeled-monocyclam",
    type: "journal",
    typeLabel: "Journal article",
    title: "Development and Evaluation of an18F-Radiolabeled Monocyclam Derivative for Imaging CXCR4 Expression",
    authors: ["Brickute, D", "Braga, M", "Kaliszczak, MA", "Barnes, C", "Lau, D", "Carroll, L", "Stevens, E", "Trousil, S", "Alam, IS", "Nguyen, Q-D", "Aboagye, EO"],
    year: 2019,
    journal: "Molecular Pharmaceutics",
    volume: "16",
    issue: "5",
    pages: "2106 - 2117",
    issn: "1543-8384",
    doi: "10.1021/acs.molpharmaceut.9b00069",
    doiUrl: "http://dx.doi.org/10.1021/acs.molpharmaceut.9b00069",
  },
];
