import type { PersonPublication } from "./publications-felicity-gavins";

export const samWillcocksPublications: PersonPublication[] = [
  {
    slug: "alshabani-2026-3-pyridine-3-ylmethylene-chroman-4-one-and-tetralone-deriva",
    type: "journal",
    typeLabel: "Journal article",
    title: "3-(Pyridine-3-ylmethylene)chroman-4-one and tetralone derivatives: synthesis,Mycobacterium tuberculosisCYP121A1 enzyme inhibition and antimycobacterial activityvsdrug-sensitive and drug-resistant strains",
    authors: ["Alshabani, LA", "Abdali, JM", "Brown, AK", "de Sousa, DP", "Willcocks, S", "Kumar, A", "Alhejaili, AYG", "Estrada, DF", "Simons, C"],
    year: 2026,
    journal: "RSC Medicinal Chemistry",
    volume: "17",
    issue: "3",
    pages: "1672 - 1686",
    issn: "2632-8682",
    doi: "10.1039/d5md00738k",
    doiUrl: "http://dx.doi.org/10.1039/d5md00738k",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/33080",
  },
  {
    slug: "lamprecht-2025-targeting-de-novo-purine-biosynthesis-for-tuberculosis-treat",
    type: "journal",
    typeLabel: "Journal article",
    title: "Targeting de novo purine biosynthesis for tuberculosis treatment",
    authors: ["Lamprecht, DA", "Wall, RJ", "Leemans, A", "Truebody, B", "Sprangers, J", "Fiogbe, P", "Davies, C", "Wetzel, J", "Daems, S", "Pearson, W", "Pillay, V", "Saylock, S", "Ricketts, MD", "Davis, E", "Huff, A", "Grell, T", "Lin, S", "Gerber, M", "Vos, A", "Dallow, J", "Willcocks, SJ", "Roubert, C", "Sans, S", "Desorme, A", "Chappat, N", "Ray, A", "Pereira Moraes, M", "Washington, T", "D’Erasmo, H", "Sancheti, P", "Everaerts, M", "Monshouwer, M", "Esquivias, J", "Larrouy-Maumus, G", "Draghia Akli, R", "Fletcher, H", "Pym, AS", "Aldridge, BB", "Sarathy, JP", "Clancy, KW", "Stoops, B", "Dhar, N", "Steyn, AJC", "Jackson, P", "Aguilar-Pérez, C", "Koul, A"],
    year: 2025,
    journal: "Nature",
    volume: "644",
    issue: "8075",
    pages: "214 - 220",
    issn: "0028-0836",
    doi: "10.1038/s41586-025-09177-7",
    doiUrl: "http://dx.doi.org/10.1038/s41586-025-09177-7",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/31611",
  },
  {
    slug: "martin-2025-development-of-carprofen-analogues-with-activity-against-myc",
    type: "journal",
    typeLabel: "Journal article",
    title: "Development of Carprofen analogues with activity against Mycobacterium tuberculosis",
    authors: ["Martin, LT", "Daniel, C", "Guldberg-Allen, M", "Navaratnarajah, A", "Anselmi, S", "Burova, T-MD", "Willcocks, S", "Hailes, HC", "Bhakta, S"],
    year: 2025,
    journal: "Bioorganic and Medicinal Chemistry",
    volume: "127",
    pages: "1 - 15",
    issn: "0968-0896",
    doi: "10.1016/j.bmc.2025.118226",
    doiUrl: "http://dx.doi.org/10.1016/j.bmc.2025.118226",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/31612",
  },
  {
    slug: "daniel-2024-rapid-gene-silencing-followed-by-antimicrobial-susceptibilit",
    type: "book-chapter",
    typeLabel: "Book chapter",
    title: "Rapid Gene Silencing Followed by Antimicrobial Susceptibility Testing for Target Validation in Antibiotic Discovery",
    authors: ["Daniel, C", "Willcocks, S", "Bhakta, S"],
    year: 2024,
    journal: "Methods in Molecular Biology.",
    pages: "23 - 33",
  },
  {
    slug: "gibson-2022-defining-the-genes-required-for-survival-of-mycobacterium-bo",
    type: "journal",
    typeLabel: "Journal article",
    title: "Defining the Genes Required for Survival of Mycobacterium bovis in the Bovine Host Offers Novel Insights into the Genetic Basis of Survival of Pathogenic Mycobacteria",
    authors: ["Gibson, AJ", "Stiens, J", "Passmore, IJ", "Faulkner, V", "Miculob, J", "Willcocks, S", "Coad, M", "Berg, S", "Werling, D", "Wren, BW", "Nobeli, I", "Villarreal-Ramos, B", "Kendall, SL"],
    year: 2022,
    journal: "mBio",
    volume: "13",
    issue: "4",
    pages: "e0067222",
    issn: "2161-2129",
    doi: "10.1128/mbio.00672-22",
    doiUrl: "http://dx.doi.org/10.1128/mbio.00672-22",
  },
  {
    slug: "bartens-2021-single-nucleotide-polymorphisms-in-the-bovine-tlr2-extracell",
    type: "journal",
    typeLabel: "Journal article",
    title: "Single Nucleotide Polymorphisms in the Bovine TLR2 Extracellular Domain Contribute to Breed and Species-Specific Innate Immune Functionality",
    authors: ["Bartens, MC", "Gibson, AJ", "Etherington, GJ", "Di Palma, F", "Holder, A", "Werling, D", "Willcocks, S"],
    year: 2021,
    journal: "Frontiers in Immunology",
    volume: "12",
    pages: "764390",
    issn: "1664-3224",
    doi: "10.3389/fimmu.2021.764390",
    doiUrl: "http://dx.doi.org/10.3389/fimmu.2021.764390",
  },
  {
    slug: "faulkner-2021-re-sensitization-of-mycobacterium-smegmatis-to-rifampicin-us",
    type: "journal",
    typeLabel: "Journal article",
    title: "Re-sensitization of Mycobacterium smegmatis to Rifampicin Using CRISPR Interference Demonstrates Its Utility for the Study of Non-essential Drug Resistance Traits",
    authors: ["Faulkner, V", "Cox, AA", "Goh, S", "van Bohemen, A", "Gibson, AJ", "Liebster, O", "Wren, BW", "Willcocks, S", "Kendall, SL"],
    year: 2021,
    journal: "Frontiers in Microbiology",
    volume: "11",
    pages: "619427",
    issn: "1664-302X",
    doi: "10.3389/fmicb.2020.619427",
    doiUrl: "http://dx.doi.org/10.3389/fmicb.2020.619427",
  },
  {
    slug: "munshi-2020-the-antimicrobial-peptide-bactenecin-5-supports-cell-media",
    type: "journal",
    typeLabel: "Journal article",
    title: "The Antimicrobial Peptide, Bactenecin 5, Supports Cell-Mediated but Not Humoral Immunity in the Context of a Mycobacterial Antigen Vaccine Model",
    authors: ["Munshi, T", "Sparrow, A", "Wren, BW", "Reljic, R", "Willcocks, SJ"],
    year: 2020,
    journal: "Antibiotics",
    volume: "9",
    issue: "12",
    pages: "1 - 10",
    issn: "2079-6382",
    doi: "10.3390/antibiotics9120926",
    doiUrl: "http://dx.doi.org/10.3390/antibiotics9120926",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/33085",
  },
  {
    slug: "willcocks-2020-revisiting-aminocoumarins-for-the-treatment-of-melioidosis",
    type: "journal",
    typeLabel: "Journal article",
    title: "Revisiting aminocoumarins for the treatment of melioidosis",
    authors: ["Willcocks, SJ", "Cia, F", "Francisco, AF", "Wren, BW"],
    year: 2020,
    journal: "International Journal of Antimicrobial Agents",
    volume: "56",
    issue: "1",
    pages: "106002 - 106002",
    issn: "0924-8579",
    doi: "10.1016/j.ijantimicag.2020.106002",
    doiUrl: "http://dx.doi.org/10.1016/j.ijantimicag.2020.106002",
  },
  {
    slug: "willcocks-2020-virulence-of-the-emerging-pathogen-burkholderia-pseudomallei",
    type: "journal",
    typeLabel: "Journal article",
    title: "Virulence of the Emerging Pathogen,Burkholderia Pseudomallei, Depends Upon theO-linked Oligosaccharyltransferase, PglL",
    authors: ["Willcocks, SJ", "Denman, C", "Cia, F", "McCarthy, E", "Cuccui, J", "Wren, BW"],
    year: 2020,
    journal: "Future Microbiology",
    volume: "15",
    issue: "4",
    pages: "241 - 257",
    issn: "1746-0913",
    doi: "10.2217/fmb-2019-0165",
    doiUrl: "http://dx.doi.org/10.2217/fmb-2019-0165",
  },
  {
    slug: "price-2019-in-vitro-and-in-vivo-properties-of-the-bovine-antimicrobial",
    type: "journal",
    typeLabel: "Journal article",
    title: "In vitro and in vivo properties of the bovine antimicrobial peptide, Bactenecin 5",
    authors: ["Price, RL", "Bugeon, L", "Mostowy, S", "Makendi, C", "Wren, BW", "Williams, HD", "Willcocks, SJ"],
    year: 2019,
    journal: "PLOS ONE",
    volume: "14",
    issue: "1",
    pages: "e0210508 - e0210508",
    issn: "1932-6203",
    doi: "10.1371/journal.pone.0210508",
    doiUrl: "http://dx.doi.org/10.1371/journal.pone.0210508",
  },
  {
    slug: "willcocks-2019-genome-wide-assessment-of-antimicrobial-tolerance-in-yersini",
    type: "journal",
    typeLabel: "Journal article",
    title: "Genome-wide assessment of antimicrobial tolerance in Yersinia pseudotuberculosis under ciprofloxacin stress",
    authors: ["Willcocks, S", "Huse, KK", "Stabler, R", "Oyston, PCF", "Scott, A", "Atkins, HS", "Wren, BW"],
    year: 2019,
    journal: "Microbial Genomics",
    volume: "5",
    issue: "11",
    issn: "2057-5858",
    doi: "10.1099/mgen.0.000304",
    doiUrl: "http://dx.doi.org/10.1099/mgen.0.000304",
  },
  {
    slug: "willcocks-2018-high-throughput-analysis-of-yersinia-pseudotuberculosis-gene",
    type: "journal",
    typeLabel: "Journal article",
    title: "High-throughput analysis of Yersinia pseudotuberculosis gene essentiality in optimised in vitro conditions, and implications for the speciation of Yersinia pestis",
    authors: ["Willcocks, SJ", "Stabler, RA", "Atkins, HS", "Oyston, PF", "Wren, BW"],
    year: 2018,
    journal: "BMC Microbiology",
    volume: "18",
    issue: "1",
    pages: "46",
    issn: "1471-2180",
    doi: "10.1186/s12866-018-1189-5",
    doiUrl: "http://dx.doi.org/10.1186/s12866-018-1189-5",
  },
];
