import type { PersonPublication } from "./publications-felicity-gavins";

export const jacquelineCliffPublications: PersonPublication[] = [
  {
    slug: "anwar-2025-impact-of-helminth-co-infection-and-treatment-on-mycobacteri",
    type: "journal",
    typeLabel: "Journal article",
    title: "Impact of helminth co-infection and treatment on mycobacterial growth inhibition in UK migrants with TB infection",
    authors: ["Anwar, S", "Turienzo, CF", "Tsang, L", "Smith, SG", "Fletcher, H", "Toulza, F", "Cliff, JM", "Brown, M", "Dockrell, HM"],
    year: 2025,
    journal: "IJTLD Open",
    volume: "2",
    issue: "4",
    pages: "217 - 223",
    issn: "3005-7590",
    doi: "10.5588/ijtldopen.24.0528",
    doiUrl: "http://dx.doi.org/10.5588/ijtldopen.24.0528",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/32334",
  },
  {
    slug: "goletti-2025-world-tb-day-2025-theme-yes-we-can-end-tb-commit-invest",
    type: "journal",
    typeLabel: "Journal article",
    title: "World TB Day 2025 Theme “Yes! We Can End TB: Commit, Invest, Deliver” can be made a reality through concerted global efforts to advance diagnosis, treatment and research of tuberculosis infection and disease",
    authors: ["Goletti, D", "Matteelli, A", "Cliff, JM", "Meintjes, G", "Graham, S", "Esmail, H", "Shan Lee, S"],
    year: 2025,
    journal: "International Journal of Infectious Diseases",
    volume: "155",
    pages: "1 - 3",
    issn: "1201-9712",
    doi: "10.1016/j.ijid.2025.107892",
    doiUrl: "http://dx.doi.org/10.1016/j.ijid.2025.107892",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/30946",
  },
  {
    slug: "smith-2025-host-directed-therapy-in-diabetes-and-tuberculosis-comorbidi",
    type: "journal",
    typeLabel: "Journal article",
    title: "Host-directed therapy in diabetes and tuberculosis comorbidity toward global tuberculosis elimination",
    authors: ["Smith, SG", "Bowness, R", "Cliff, JM"],
    year: 2025,
    journal: "International Journal of Infectious Diseases",
    volume: "155",
    pages: "1 - 8",
    issn: "1201-9712",
    doi: "10.1016/j.ijid.2025.107877",
    doiUrl: "http://dx.doi.org/10.1016/j.ijid.2025.107877",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/30944",
  },
  {
    slug: "eckold-2023-impaired-resolution-of-blood-transcriptomes-through-tubercul",
    type: "journal",
    typeLabel: "Journal article",
    title: "Impaired resolution of blood transcriptomes through tuberculosis treatment with diabetes comorbidity",
    authors: ["Eckold, C", "van Doorn, CLR", "Ruslami, R", "Ronacher, K", "Riza, A", "van Veen, S", "Lee, J", "Kumar, V", "Kerry‐Barnard, S", "Malherbe, ST", "Kleynhans, L", "Stanley, K", "Joosten, SA", "Critchley, JA", "Hill, PC", "van Crevel, R", "Wijmenga, C", "Haks, MC", "Ioana, M", "Alisjahbana, B", "Walzl, G", "Ottenhoff, THM", "Dockrell, HM", "Vianello, E", "Cliff, JM"],
    year: 2023,
    journal: "Clinical and Translational Medicine",
    volume: "13",
    issue: "9",
    pages: "1 - 19",
    issn: "2001-1326",
    doi: "10.1002/ctm2.1375",
    doiUrl: "http://dx.doi.org/10.1002/ctm2.1375",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/27160",
  },
  {
    slug: "jacobs-2022-concurrent-evaluation-of-cytokines-improves-the-accuracy-of",
    type: "journal",
    typeLabel: "Journal article",
    title: "Concurrent evaluation of cytokines improves the accuracy of antibodies against Mycobacterium tuberculosis antigens in the diagnosis of active tuberculosis",
    authors: ["Jacobs, R", "Awoniyi, DO", "Baumann, R", "Stanley, K", "McAnda, S", "Kaempfer, S", "Malherbe, ST", "Singh, M", "Walzl, G", "Chegou, NN", "Walzl, G", "Chegou, NN", "Kriel, M", "van der Spuy, G", "Loxton, AG", "Stanley, K", "Malherbe, ST", "Kriel, B", "Sutherland, JS", "Owolabi, O", "Sillah, A", "Mendy, J", "Gindeh, A", "Donkor, S", "Togun, T", "Ota, M", "Crampin, AC", "Simukonda, F", "Amberbir, A", "Chilongo, F", "Houben, R", "Kassa, D", "Gebrezgeabher, A", "Mesfin, G", "Belay, Y", "Gebremichael, G", "Alemayehu, Y", "van der Vyver, M", "Amutenya, FN", "Nelongo, JN", "Monye, L", "Sheehama, JA", "Iipinge, S", "Mayanja-Kizza, H", "Namuganga, AR", "Muzanye, G", "Nsereko, M", "Peters, P", "Howe, R", "Mihret, A", "Bekele, Y", "Tessema, B", "Yamuah, L", "Ottenhoff, THM", "Geluk, A", "Franken, K", "van der Ploeg-van Schip, JJ", "Corstjens, PLAM", "Tjon Kon Fat, EM", "de Dood, CJ", "Rosenkrands, I", "Aagaard, C", "Kaufmann, SHE", "Esterhuyse, MM", "Cliff, JM", "Dockrell, HM"],
    year: 2022,
    journal: "Tuberculosis",
    volume: "133",
    pages: "1 - 8",
    issn: "1472-9792",
    doi: "10.1016/j.tube.2022.102169",
    doiUrl: "http://dx.doi.org/10.1016/j.tube.2022.102169",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/25422",
  },
  {
    slug: "van-doorn-2022-transcriptional-profiles-predict-treatment-outcome-in-patien",
    type: "journal",
    typeLabel: "Journal article",
    title: "Transcriptional profiles predict treatment outcome in patients with tuberculosis and diabetes at diagnosis and at two weeks after initiation of anti-tuberculosis treatment",
    authors: ["van Doorn, CLR", "Eckold, C", "Ronacher, K", "Ruslami, R", "van Veen, S", "Lee, J-S", "Kumar, V", "Kerry-Barnard, S", "Malherbe, ST", "Kleynhans, L", "Stanley, K", "Hill, PC", "Joosten, SA", "van Crevel, R", "Wijmenga, C", "Critchley, JA", "Walzl, G", "Alisjahbana, B", "Haks, MC", "Dockrell, HM", "Ottenhoff, THM", "Vianello, E", "Cliff, JM", "the TANDEM Consortium"],
    year: 2022,
    journal: "eBioMedicine",
    volume: "82",
    pages: "1 - 17",
    issn: "2352-3964",
    doi: "10.1016/j.ebiom.2022.104173",
    doiUrl: "http://dx.doi.org/10.1016/j.ebiom.2022.104173",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/25421",
  },
  {
    slug: "domingues-2021-herpesviruses-serology-distinguishes-different-subgroups-of",
    type: "journal",
    typeLabel: "Journal article",
    title: "Herpesviruses Serology Distinguishes Different Subgroups of Patients From the United Kingdom Myalgic Encephalomyelitis/Chronic Fatigue Syndrome Biobank",
    authors: ["Domingues, TD", "Grabowska, AD", "Lee, J-S", "Ameijeiras-Alonso, J", "Westermeier, F", "Scheibenbogen, C", "Cliff, JM", "Nacul, L", "Lacerda, EM", "Mouriño, H", "Sepúlveda, N"],
    year: 2021,
    journal: "Frontiers in Medicine",
    volume: "8",
    pages: "1 - 11",
    issn: "2296-858X",
    doi: "10.3389/fmed.2021.686736",
    doiUrl: "http://dx.doi.org/10.3389/fmed.2021.686736",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/26093",
  },
  {
    slug: "lee-2021-salivary-dna-loads-for-human-herpesviruses-6-and-7-are-corre",
    type: "journal",
    typeLabel: "Journal article",
    title: "Salivary DNA Loads for Human Herpesviruses 6 and 7 Are Correlated With Disease Phenotype in Myalgic Encephalomyelitis/Chronic Fatigue Syndrome",
    authors: ["Lee, J-S", "Lacerda, EM", "Nacul, L", "Kingdon, CC", "Norris, J", "O'Boyle, S", "Roberts, CH", "Palla, L", "Riley, EM", "Cliff, JM"],
    year: 2021,
    journal: "Frontiers in Medicine",
    volume: "8",
    pages: "1 - 17",
    issn: "2296-858X",
    doi: "10.3389/fmed.2021.656692",
    doiUrl: "http://dx.doi.org/10.3389/fmed.2021.656692",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/26094",
  },
  {
    slug: "eckold-2020-impact-of-intermediate-hyperglycemia-and-diabetes-on-immune",
    type: "journal",
    typeLabel: "Journal article",
    title: "Impact of Intermediate Hyperglycemia and Diabetes on Immune Dysfunction in Tuberculosis",
    authors: ["Eckold, C", "Kumar, V", "Weiner, J", "Alisjahbana, B", "Riza, A-L", "Ronacher, K", "Coronel, J", "Kerry-Barnard, S", "Malherbe, ST", "Kleynhans, L", "Stanley, K", "Ruslami, R", "Ioana, M", "Ugarte-Gil, C", "Walzl, G", "van Crevel, R", "Wijmenga, C", "Critchley, JA", "Dockrell, HM", "Cliff, JM", "Dockrell, H", "Cliff, J", "Eckold, C", "Moore, D", "Griffiths, U", "Laurence, Y", "Aarnouste, R", "Netea, M", "van Crevel, R", "Ruesen, C", "Lachmandas, E", "Kaufmann, S", "Beigier, M", "Golinski, R", "Joosten, S", "Ottenhoff, T", "Vrieling, F", "Haks, M", "Walzl, G", "Ronacher, K", "Malherbe, S", "Kleynhans, L", "Smith, B", "Stanley, K", "van der Spuy, G", "Loxton, A", "Chegou, N", "Bosman, M", "Thiart, L", "Wagman, C", "Tshivhula, H", "Selamolela, M", "Prins, N", "du Plessis, W", "van Rensburg, I", "du Toit, L", "Critchley, J", "Kerry-Barnard, S", "Pearson, F", "Grint, D", "McAllister, S", "Hill, P", "Verrall, A", "Ioana, M", "Riza, A", "Cioboata, R", "Dudau, M", "Nitu, F", "Bazavan, I", "Olteanu, M", "Editoiu, C", "Florescu, A", "Mota, M", "Popa, SG", "Firanescu, A", "Popa, A", "Gheonea, I", "Bicuti, S", "Lepadat, A", "Vladu, I", "Clenciu, D", "Bicu, M", "Streba, C", "Demetrian, A", "Ciurea, M", "Cimpoeru, A", "Ciocoiu, A", "Dorobantu, S", "Plesea, R", "Popescu, EL", "Cucu, M", "Streata, I", "Burada, F", "Serban-Sosoi, S", "Panduru, N", "Nicoli, E", "Ciontea, M", "Capitanescu, I", "Olaru, M", "Tataru, T", "Papurica, M", "Valutanu, I", "Dubreu, V", "Stamatoiu, L", "Kumar, V", "Wijmenga, C", "Ugarte-Gil, C", "Coronel, J", "Lopez, S", "Limascca, R", "Villaizan, K", "Castro, B", "Flores, J", "Solano, W", "Alisjahbana, B", "Ruslami, R", "Soetedjo, N", "Santoso, P", "Chaidir, L", "Koesoemadinata, R", "Susilawati, N", "Annisa, J", "Livia, R", "Yunivita, V", "Soeroto, A", "Permana, H", "Imaculata, S", "Gunawan, Y", "Dewi, N", "Apriani, L", "TANDEM (Concurrent Tuberculosis", "Diabetes Mellitus; unraveling the causal link", "improving care) Consortium"],
    year: 2020,
    journal: "Clinical Infectious Diseases",
    volume: "72",
    issue: "1",
    pages: "69 - 78",
    issn: "1058-4838",
    doi: "10.1093/cid/ciaa751",
    doiUrl: "http://dx.doi.org/10.1093/cid/ciaa751",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/26672",
  },
  {
    slug: "nacul-2020-how-myalgic-encephalomyelitis-chronic-fatigue-syndrome-me-c",
    type: "journal",
    typeLabel: "Journal article",
    title: "How Myalgic Encephalomyelitis/Chronic Fatigue Syndrome (ME/CFS) Progresses: The Natural History of ME/CFS",
    authors: ["Nacul, L", "O'Boyle, S", "Palla, L", "Nacul, FE", "Mudie, K", "Kingdon, CC", "Cliff, JM", "Clark, TG", "Dockrell, HM", "Lacerda, EM"],
    year: 2020,
    journal: "Frontiers in Neurology",
    volume: "11",
    pages: "1 - 13",
    issn: "1664-2295",
    doi: "10.3389/fneur.2020.00826",
    doiUrl: "http://dx.doi.org/10.3389/fneur.2020.00826",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/27162",
  },
  {
    slug: "yimthin-2020-blood-transcriptomics-to-characterize-key-biological-pathway",
    type: "journal",
    typeLabel: "Journal article",
    title: "Blood transcriptomics to characterize key biological pathways and identify biomarkers for predicting mortality in melioidosis",
    authors: ["Yimthin, T", "Cliff, JM", "Phunpang, R", "Ekchariyawat, P", "Kaewarpai, T", "Lee, J-S", "Eckold, C", "Andrada, M", "Thiansukhon, E", "Tanwisaid, K", "Chuananont, S", "Morakot, C", "Sangsa, N", "Silakun, W", "Chayangsu, S", "Buasi, N", "Day, N", "Lertmemongkolchai, G", "Chantratita, W", "West, TE", "Chantratita, N"],
    year: 2020,
    journal: "Emerging Microbes and Infections",
    volume: "10",
    issue: "1",
    pages: "8 - 18",
    issn: "2222-1751",
    doi: "10.1080/22221751.2020.1858176",
    doiUrl: "http://dx.doi.org/10.1080/22221751.2020.1858176",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/26095",
  },
  {
    slug: "cliff-2019-cellular-immune-function-in-myalgic-encephalomyelitis-chroni",
    type: "journal",
    typeLabel: "Journal article",
    title: "Cellular immune function in myalgic encephalomyelitis/chronic fatigue syndrome (ME/CFS)",
    authors: ["Cliff, JM", "King, EC", "Lee, J-S", "Sepúlveda, N", "Wolf, A-S", "Kingdon, C", "Bowman, E", "Dockrell, HM", "Nacul, L", "Lacerda, E", "Riley, EM"],
    year: 2019,
    journal: "Frontiers in Immunology",
    volume: "10",
    issue: "MAR",
    pages: "1 - 15",
    issn: "1664-3224",
    doi: "10.3389/fimmu.2019.00796",
    doiUrl: "http://dx.doi.org/10.3389/fimmu.2019.00796",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/26097",
  },
  {
    slug: "lachmandas-2019-metformin-alters-human-host-responses-to-mycobacterium-tuber",
    type: "journal",
    typeLabel: "Journal article",
    title: "Metformin Alters Human Host Responses to Mycobacterium tuberculosis in Healthy Subjects",
    authors: ["Lachmandas, E", "Eckold, C", "Böhme, J", "Koeken, VACM", "Marzuki, MB", "Blok, B", "Arts, RJW", "Chen, J", "Teng, KWW", "Ratter, J", "Smolders, EJ", "Van den Heuvel, C", "Stienstra, R", "Dockrell, HM", "Newell, E", "Netea, MG", "Singhal, A", "Cliff, JM", "Van Crevel, R"],
    year: 2019,
    journal: "The Journal of Infectious Diseases",
    volume: "220",
    issue: "1",
    pages: "139 - 150",
    issn: "0022-1899",
    doi: "10.1093/infdis/jiz064",
    doiUrl: "http://dx.doi.org/10.1093/infdis/jiz064",
  },
  {
    slug: "nacul-2019-evidence-of-clinical-pathology-abnormalities-in-people-with",
    type: "journal",
    typeLabel: "Journal article",
    title: "Evidence of clinical pathology abnormalities in people with myalgic encephalomyelitis/chronic fatigue syndrome (ME/CFS) from an analytic cross-sectional study",
    authors: ["Nacul, L", "De Barros, B", "Kingdon, CC", "Cliff, JM", "Clark, TG", "Mudie, K", "Dockrell, HM", "Lacerda, EM"],
    year: 2019,
    journal: "Diagnostics",
    volume: "9",
    issue: "2",
    pages: "1 - x",
    issn: "2075-4418",
    doi: "10.3390/diagnostics9020041",
    doiUrl: "http://dx.doi.org/10.3390/diagnostics9020041",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/32749",
  },
  {
    slug: "ronacher-2019-distinct-serum-biosignatures-are-associated-with-different-t",
    type: "journal",
    typeLabel: "Journal article",
    title: "Distinct serum biosignatures are associated with different tuberculosis treatment outcomes",
    authors: ["Ronacher, K", "Chegou, NN", "Kleynhans, L", "Djoba Siawaya, JF", "du Plessis, N", "Loxton, AG", "Maasdorp, E", "Tromp, G", "Kidd, M", "Stanley, K", "Kriel, M", "Menezes, A", "Gutschmidt, A", "van der Spuy, GD", "Warren, RM", "Dietze, R", "Okwera, A", "Thiel, B", "Belisle, JT", "Cliff, JM", "Boom, WH", "Johnson, JL", "van Helden, PD", "Dockrell, HM", "Walzl, G"],
    year: 2019,
    journal: "Tuberculosis",
    volume: "118",
    pages: "101859 - 101859",
    issn: "1472-9792",
    doi: "10.1016/j.tube.2019.101859",
    doiUrl: "http://dx.doi.org/10.1016/j.tube.2019.101859",
  },
  {
    slug: "chegou-2018-africa-wide-evaluation-of-host-biomarkers-in-quantiferon-sup",
    type: "journal",
    typeLabel: "Journal article",
    title: "Africa-wide evaluation of host biomarkers in QuantiFERON supernatants for the diagnosis of pulmonary tuberculosis",
    authors: ["Chegou, NN", "Sutherland, JS", "Namuganga, A-R", "Corstjens, PLAM", "Geluk, A", "Gebremichael, G", "Mendy, J", "Malherbe, S", "Stanley, K", "van der Spuy, GD", "Kriel, M", "Loxton, AG", "Kriel, B", "Simukonda, F", "Bekele, Y", "Sheehama, JA", "Nelongo, J", "van der Vyver, M", "Gebrexabher, A", "Hailu, H", "Esterhuyse, MM", "Rosenkrands, I", "Aagard, C", "Kidd, M", "Kassa, D", "Mihret, A", "Howe, R", "Cliff, JM", "Crampin, AC", "Mayanja-Kizza, H", "Kaufmann, SHE", "Dockrell, HM", "Ottenhoff, THM", "Walzl, G", "McAnda, SP", "Owolabi, O", "Sillah, A", "Gindeh, A", "Donkor, S", "Togun, T", "Ota, M", "Muzanye, G", "Nsereko, M", "Peters, P", "Tjon Kon Fat, EM", "de Dood, CJ", "Franken, K", "van der Ploeg-van Schip, JJ", "Gebrezgeabher, A", "Mesfin, G", "Belay, Y", "Alemayehu, Y", "Amberbir, A", "Chilongo, F", "Houben, R", "Tessema, B", "Yamuah, L", "Amutenya, FN", "Monye, L", "Iipinge, S"],
    year: 2018,
    journal: "Scientific Reports",
    volume: "8",
    issue: "1",
    pages: "2675",
    issn: "2045-2322",
    doi: "10.1038/s41598-018-20855-7",
    doiUrl: "http://dx.doi.org/10.1038/s41598-018-20855-7",
  },
  {
    slug: "gebremicael-2018-host-gene-expression-kinetics-during-treatment-of-tuberculos",
    type: "journal",
    typeLabel: "Journal article",
    title: "Host Gene Expression Kinetics During Treatment of Tuberculosis in HIV-Coinfected Individuals Is Independent of Highly Active Antiretroviral Therapy",
    authors: ["Gebremicael, G", "Kassa, D", "Quinten, E", "Alemayehu, Y", "Gebreegziaxier, A", "Belay, Y", "van Baarle, D", "Ottenhoff, THM", "Cliff, JM", "Haks, MC"],
    year: 2018,
    journal: "The Journal of Infectious Diseases",
    volume: "218",
    issue: "11",
    pages: "1833 - 1846",
    issn: "0022-1899",
    doi: "10.1093/infdis/jiy404",
    doiUrl: "http://dx.doi.org/10.1093/infdis/jiy404",
  },
  {
    slug: "andreu-2017-primary-macrophages-and-j774-cells-respond-differently-to-in",
    type: "journal",
    typeLabel: "Journal article",
    title: "Primary macrophages and J774 cells respond differently to infection with Mycobacterium tuberculosis",
    authors: ["Andreu, N", "Phelan, J", "de Sessions, PF", "Cliff, JM", "Clark, TG", "Hibberd, ML"],
    year: 2017,
    journal: "Scientific Reports",
    volume: "7",
    issue: "1",
    pages: "42225",
    issn: "2045-2322",
    doi: "10.1038/srep42225",
    doiUrl: "http://dx.doi.org/10.1038/srep42225",
  },
  {
    slug: "cliff-2015-excessive-cytolytic-responses-predict-tuberculosis-relapse-a",
    type: "journal",
    typeLabel: "Journal article",
    title: "Excessive cytolytic responses predict tuberculosis relapse after apparently successful treatment",
    authors: ["Cliff, JM", "Cho, JE", "Lee, JS", "Ronacher, K", "King, EC", "Van Helden, P", "Walzl, G", "Dockrell, HM"],
    year: 2015,
    journal: "Journal of Infectious Diseases",
    volume: "213",
    issue: "3",
    pages: "485 - 495",
    issn: "0022-1899",
    doi: "10.1093/infdis/jiv447",
    doiUrl: "http://dx.doi.org/10.1093/infdis/jiv447",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/27855",
  },
  {
    slug: "cliff-2015-the-human-immune-response-to-tuberculosis-and-its-treatment",
    type: "journal",
    typeLabel: "Journal article",
    title: "The human immune response to tuberculosis and its treatment: a view from the blood",
    authors: ["Cliff, JM", "Kaufmann, SHE", "McShane, H", "van Helden, P", "O'Garra, A"],
    year: 2015,
    journal: "Immunological Reviews",
    volume: "264",
    issue: "1",
    pages: "88 - 102",
    issn: "0105-2896",
    doi: "10.1111/imr.12269",
    doiUrl: "http://dx.doi.org/10.1111/imr.12269",
  },
  {
    slug: "hassan-2015-pd-1-pd-l1-and-pd-l2-gene-expression-on-t-cells-and-natural",
    type: "journal",
    typeLabel: "Journal article",
    title: "PD-1, PD-L1 and PD-L2 Gene Expression on T-Cells and Natural Killer Cells Declines in Conjunction with a Reduction in PD-1 Protein during the Intensive Phase of Tuberculosis Treatment",
    authors: ["Hassan, SS", "Akram, M", "King, EC", "Dockrell, HM", "Cliff, JM"],
    year: 2015,
    journal: "PLOS ONE",
    volume: "10",
    issue: "9",
    pages: "e0137646 - e0137646",
    issn: "1932-6203",
    doi: "10.1371/journal.pone.0137646",
    doiUrl: "http://dx.doi.org/10.1371/journal.pone.0137646",
  },
  {
    slug: "cliff-2013-distinct-phases-of-blood-gene-expression-pattern-through-tub",
    type: "journal",
    typeLabel: "Journal article",
    title: "Distinct Phases of Blood Gene Expression Pattern Through Tuberculosis Treatment Reflect Modulation of the Humoral Immune Response",
    authors: ["Cliff, JM", "Lee, J-S", "Constantinou, N", "Cho, J-E", "Clark, TG", "Ronacher, K", "King, EC", "Lukey, PT", "Duncan, K", "Van Helden, PD", "Walzl, G", "Dockrell, HM"],
    year: 2013,
    journal: "The Journal of Infectious Diseases",
    volume: "207",
    issue: "1",
    pages: "18 - 29",
    issn: "0022-1899",
    doi: "10.1093/infdis/jis499",
    doiUrl: "http://dx.doi.org/10.1093/infdis/jis499",
  },
  {
    slug: "sebina-2012-long-lived-memory-b-cell-responses-following-bcg-vaccination",
    type: "journal",
    typeLabel: "Journal article",
    title: "Long-Lived Memory B-Cell Responses following BCG Vaccination",
    authors: ["Sebina, I", "Cliff, JM", "Smith, SG", "Nogaro, S", "Webb, EL", "Riley, EM", "Dockrell, HM", "Elliott, AM", "Hafalla, JCR", "Cose, S"],
    year: 2012,
    journal: "PLoS ONE",
    volume: "7",
    issue: "12",
    pages: "e51381 - e51381",
    issn: "1932-6203",
    doi: "10.1371/journal.pone.0051381",
    doiUrl: "http://dx.doi.org/10.1371/journal.pone.0051381",
  },
  {
    slug: "hasan-2009-ccl2-responses-to-mycobacterium-tuberculosis-are-associated",
    type: "journal",
    typeLabel: "Journal article",
    title: "CCL2 Responses to Mycobacterium tuberculosis Are Associated with Disease Severity in Tuberculosis",
    authors: ["Hasan, Z", "Cliff, JM", "Dockrell, HM", "Jamil, B", "Irfan, M", "Ashraf, M", "Hussain, R"],
    year: 2009,
    journal: "PLoS ONE",
    volume: "4",
    issue: "12",
    pages: "e8459 - e8459",
    issn: "1932-6203",
    doi: "10.1371/journal.pone.0008459",
    doiUrl: "http://dx.doi.org/10.1371/journal.pone.0008459",
  },
  {
    slug: "kirk-2009-biogenesis-of-secretory-organelles-during-b-cell-differentia",
    type: "journal",
    typeLabel: "Journal article",
    title: "Biogenesis of secretory organelles during B cell differentiation",
    authors: ["Kirk, SJ", "Cliff, JM", "Thomas, JA", "Ward, TH"],
    year: 2009,
    journal: "Journal of Leukocyte Biology",
    volume: "87",
    issue: "2",
    pages: "245 - 255",
    issn: "0741-5400",
    doi: "10.1189/jlb.1208774",
    doiUrl: "http://dx.doi.org/10.1189/jlb.1208774",
  },
  {
    slug: "cehovin-2007-extended-culture-enhances-sensitivity-of-a-gamma-interferon",
    type: "journal",
    typeLabel: "Journal article",
    title: "Extended Culture Enhances Sensitivity of a Gamma Interferon Assay for LatentMycobacterium tuberculosisInfection",
    authors: ["Cehovin, A", "Cliff, JM", "Hill, PC", "Brookes, RH", "Dockrell, HM"],
    year: 2007,
    journal: "Clinical and Vaccine Immunology",
    volume: "14",
    issue: "6",
    pages: "796 - 798",
    issn: "1556-6811",
    doi: "10.1128/cvi.00093-07",
    doiUrl: "http://dx.doi.org/10.1128/cvi.00093-07",
  },
  {
    slug: "mistry-2007-geneexpression-patterns-in-whole-blood-identify-subjects-at",
    type: "journal",
    typeLabel: "Journal article",
    title: "Gene‐Expression Patterns in Whole Blood Identify Subjects at Risk for Recurrent Tuberculosis",
    authors: ["Mistry, R", "Cliff, JM", "Clayton, CL", "Beyers, N", "Mohamed, YS", "Wilson, PA", "Dockrell, HM", "Wallace, DM", "Helden, PDV", "Duncan, K", "Lukey, PT"],
    year: 2007,
    journal: "The Journal of Infectious Diseases",
    volume: "195",
    issue: "3",
    pages: "357 - 365",
    issn: "0022-1899",
    doi: "10.1086/510397",
    doiUrl: "http://dx.doi.org/10.1086/510397",
  },
  {
    slug: "cliff-2004-differential-gene-expression-identifies-novel-markers-of-cd4",
    type: "journal",
    typeLabel: "Journal article",
    title: "Differential Gene Expression Identifies Novel Markers of CD4+ and CD8+ T Cell Activation Following Stimulation byMycobacterium tuberculosis",
    authors: ["Cliff, JM", "Andrade, INJ", "Mistry, R", "Clayton, CL", "Lennon, MG", "Lewis, AP", "Duncan, K", "Lukey, PT", "Dockrell, HM"],
    year: 2004,
    journal: "The Journal of Immunology",
    volume: "173",
    issue: "1",
    pages: "485 - 493",
    issn: "0022-1767",
    doi: "10.4049/jimmunol.173.1.485",
    doiUrl: "http://dx.doi.org/10.4049/jimmunol.173.1.485",
  },
];
