export type Publication = {
  slug: string;
  title: string;
  authors: string[];
  year: number;
  journal?: string;
  volume?: string;
  issue?: string;
  pages?: string;
  issn?: string;
  doi?: string;
  url?: string;
  personSlugs?: string[];
  researchAreaSlugs?: string[];
  projectSlugs?: string[];
};

export const publications: Publication[] = [
  {
    slug: "tsolaki-2004-functional-and-evolutionary-genomics-of-mycobacterium",
    title: "Functional and evolutionary genomics of Mycobacterium tuberculosis: Insights from genomic deletions in 100 strains",
    authors: ["Tsolaki AG", "Hirsh AE", "DeRiemer K", "Enciso JA", "Wong M", "Hannan M", "Goguet Y", "Aman K", "Kato-Maeda M", "Small PM"],
    year: 2004,
    journal: "Proc Natl Acad Sci U S A",
    volume: "101",
    pages: "4865-4870",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC387340/",
    personSlugs: ["anthony-tsolaki"],
    projectSlugs: ["host-pathogen-interactions-in-tuberculosis"],
  },
  {
    slug: "tsolaki-2005-genomic-deletions-classify-the-beijing-w-strains",
    title: "Genomic Deletions classify the Beijing/W strains as a distinct genetic lineage of Mycobacterium tuberculosis: Implications for pathogenesis, epidemiology and evolution",
    authors: ["Tsolaki AG", "Gagneux S", "Pym AS", "Goguet Y", "Kreiswirth B", "Van Soolingen D", "Small PM"],
    year: 2005,
    journal: "Journal of Clinical Microbiology",
    volume: "43",
    issue: "7",
    pages: "3185-3191",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC1169157/",
    personSlugs: ["anthony-tsolaki"],
    projectSlugs: ["host-pathogen-interactions-in-tuberculosis"],
  },
  {
    slug: "hirsh-2004-stable-association-between-strains-of-mycobacterium",
    title: "Stable association between strains of Mycobacterium tuberculosis and their human host populations",
    authors: ["Hirsh AE", "Tsolaki AG", "DeRiemer K", "Feldman M", "Small PM"],
    year: 2004,
    journal: "Proc Natl Acad Sci U S A",
    volume: "101",
    pages: "4871-4876",
    url: "https://pubmed.ncbi.nlm.nih.gov/15041743/",
    personSlugs: ["anthony-tsolaki"],
    projectSlugs: ["host-pathogen-interactions-in-tuberculosis"],
  },
  {
    slug: "kadebkov-2023-antibiotic-potentiation-and-inhibition-of-cross-re",
    title: "Antibiotic potentiation and inhibition of cross-resistance in pathogens associated with cystic fibrosis. bioRxiv [Preprint]. 2023",
    authors: ["Kadeřábková N", "Furniss RCD", "Maslova E", "Eisaiankhongi L", "Bernal P", "Filloux A", "et al."],
    year: 2023,
  },
  {
    slug: "de-2023-artificial-sweeteners-inhibit-multidrug-resistant",
    title: "Artificial sweeteners inhibit multidrug-resistant pathogen growth and potentiate antibiotic activity",
    authors: ["De Dios R", "Proctor CR", "Maslova E", "Dzalbe S", "Rudolph CJ", "McCarthy RR"],
    year: 2023,
    journal: "EMBO Mol Med",
  },
  {
    slug: "sparkenbaugh-2023-factor-xii-contributes-to-thrombotic-complications",
    title: "Factor XII contributes to thrombotic complications and vaso-occlusion in sickle cell disease",
    authors: ["Sparkenbaugh EM", "Henderson MW", "Miller-Awe MD", "Abrams C", "Ilich A", "Trebak F", "et al."],
    year: 2023,
    journal: "Blood",
    issn: "1528-0020",
  },
  {
    slug: "proctor-2023-furanone-loaded-aerogels-are-effective-antibiofilm",
    title: "Furanone loaded aerogels are effective antibiofilm therapeutics in a model of chronic Pseudomonas aeruginosa wound infection",
    authors: ["Proctor CR", "Taggart MG", "O'Hagan BMG", "McCarron PA", "McCarthy RR", "Ternan NG"],
    year: 2023,
    journal: "Biofilm",
  },
  {
    slug: "bah-2023-genomic-characterization-of-skin-and-soft-tissue-s",
    title: "Genomic Characterization of Skin and Soft Tissue Streptococcus pyogenes Isolates from a Low-Income and a High-Income Setting",
    authors: ["Bah", "S. Y", "Keeley", "A. J", "Armitage", "E. P. Khalid", "et al."],
    year: 2023,
    journal: "mSphere",
    volume: "8",
    issue: "1",
    issn: "2379-5042",
  },
  {
    slug: "bland-2023-metabolically-favorable-adiposity-and-bone-mineral",
    title: "Metabolically favorable adiposity and bone mineral density: a Mendelian randomization analysis",
    authors: ["Bland", "V. L", "Bea", "J. W", "Going", "S. B", "et al."],
    year: 2023,
    journal: "Obesity",
    volume: "31",
    issue: "1",
    pages: "267-278",
    issn: "1930-739X",
  },
  {
    slug: "ansari-2023-regulating-neutrophil-pad4-nox-dependent-cerebrova",
    title: "Regulating Neutrophil PAD4/NOX-Dependent Cerebrovasular Thromboinflammation",
    authors: ["Ansari", "J", "Vital", "S. A", "Yadav", "S. and Gavins", "et al."],
    year: 2023,
    journal: "International Journal of Biological Sciences",
    volume: "19",
    issue: "3",
    pages: "852-864",
    issn: "1449-2288",
  },
  {
    slug: "gibson-2023-skeletal-muscle-angiogenic-regulatory-and-heat-sh",
    title: "Skeletal muscle angiogenic, regulatory and heat shock protein responses to prolonged passive hyperthermia of the human lower limb",
    authors: ["Gibson", "O. R", "Astin", "R", "Puthucheary", "Z", "et al."],
    year: 2023,
    journal: "American Journal of Physiology-Regulatory, Integrative and Comparative Physiology",
    volume: "324",
    issue: "1",
    issn: "1522-1490",
  },
  {
    slug: "kim-2023-understanding-the-consumption-of-antimicrobial-res",
    title: "Understanding the Consumption of Antimicrobial Resistance-Related Content on Social Media: Twitter Analysis",
    authors: ["Kim H", "Proctor CR", "Walker D", "McCarthy RR"],
    year: 2023,
    journal: "J Med Internet Res",
  },
  {
    slug: "maslova-2023-using-the-galleria-mellonella-burn-wound-and-infec",
    title: "Using the Galleria mellonella burn wound and infection model to identify and characterize potential wound probiotics",
    authors: ["Maslova E", "Osman S", "McCarthy RR"],
    year: 2023,
    journal: "Microbiology (Reading)",
  },
  {
    slug: "de-2022-a-high-efficiency-scar-free-genome-editing-toolkit",
    title: "A high-efficiency scar-free genome-editing toolkit for Acinetobacter baumannii",
    authors: ["de Dios R", "Gadar K", "McCarthy RR"],
    year: 2022,
    journal: "J Antimicrob Chemother",
  },
  {
    slug: "oboyle-2022-a-natural-history-of-disease-framework-for-improvi",
    title: "A Natural History of Disease Framework for Improving the Prevention, Management, and Research on Post-viral Fatigue Syndrome and Other Forms of Myalgic Encephalomyelitis/Chronic Fatigue Syndrome",
    authors: ["O'Boyle", "S", "Nacul", "L", "Nacul", "F. E", "et al."],
    year: 2022,
    journal: "Frontiers in Medicine 8",
    issn: "2296-858X",
  },
  {
    slug: "seidelin-2022-a-rare-genetic-variant-in-the-manganese-transporte",
    title: "A rare genetic variant in the manganese transporter SLC30A10 and elevated liver enzymes in the general population",
    authors: ["Seidelin", "A. S", "Nordestgaard", "B. G", "Tybjaerg-Hansen", "A", "et al."],
    year: 2022,
    journal: "Atherosclerosis",
    volume: "16",
    issue: "3",
    pages: "702-711",
    issn: "0021-9150",
  },
  {
    slug: "ahmed-2022-advancing-a-causal-role-of-type-2-diabetes-and-its",
    title: "Advancing a causal role of type 2 diabetes and its components in developing macro and microvascular complications via genetic studies",
    authors: ["Ahmed", "A", "Sattar", "N. and Yaghootkar", "H"],
    year: 2022,
    journal: "Diabetic Medicine",
    volume: "39",
    issue: "12",
    issn: "1464-5491",
  },
  {
    slug: "said-2022-author-correction-genetic-analysis-of-over-half-a",
    title: "Author Correction: Genetic analysis of over half a million people characterises C-reactive protein loci",
    authors: ["Said", "S", "Pazoki", "R", "Karhunen", "V", "et al."],
    year: 2022,
    journal: "Nature Communications",
    volume: "13",
    issue: "1",
    issn: "2041-1723",
  },
  {
    slug: "becker-2022-bryostatin-1-attenuates-ischemia-elicited-neutroph",
    title: "Bryostatin-1 Attenuates Ischemia-Elicited Neutrophil Transmigration and Ameliorates Graft Injury after Kidney Transplantation",
    authors: ["Becker", "F", "Kebschull", "L", "Rieger", "C", "et al."],
    year: 2022,
    journal: "Cells",
    volume: "11",
    issue: "6",
    issn: "2073-4409",
  },
  {
    slug: "turner-2022-can-group-a-streptococcus-infections-be-influenced",
    title: "Can group A streptococcus infections be influenced by viruses in the respiratory tract?",
    authors: ["Turner", "C. E"],
    year: 2022,
    journal: "The Lancet Infectious Diseases",
    volume: "23",
    issue: "2",
    pages: "142-144",
    issn: "1473-3099",
  },
  {
    slug: "martin-2022-correction-disease-consequences-of-higher-adiposi",
    title: "Correction: Disease consequences of higher adiposity uncoupled from its adverse metabolic effects using Mendelian randomisation",
    authors: ["Martin", "S", "Tyrrell", "J", "Thomas E. L", "Bown", "et al."],
    year: 2022,
    journal: "eLife 11",
    issn: "2050-084X",
  },
  {
    slug: "clerbaux-2022-covid-19-through-adverse-outcome-pathways-buildin",
    title: "COVID-19 through Adverse Outcome Pathways: Building networks to better understand the disease – 3rd CIAO AOP Design Workshop",
    authors: ["Clerbaux", "L.-A", "et al."],
    year: 2022,
    journal: "ALTEX",
    volume: "39",
    issue: "2",
    pages: "322-335",
    issn: "1868-596X",
  },
  {
    slug: "korn-2022-development-of-methodology-for-assessing-steroid-t",
    title: "Development of methodology for assessing steroid-tapering in clinical trials for biologics in asthma",
    authors: ["Korn", "S", "Howarth", "P", "Smith", "S. G", "et al."],
    year: 2022,
    journal: "Respiratory Research",
    volume: "23",
    issue: "1",
    issn: "1465-993X",
  },
  {
    slug: "symonds-2022-egr2-and-3-maintain-anti-tumour-responses-of-exhau",
    title: "Egr2 and 3 maintain anti-tumour responses of exhausted tumour infiltrating CD8 + T cells",
    authors: ["Symonds", "A. L. J", "Miao", "T", "Busharat", "Z", "et al."],
    year: 2022,
    journal: "Cancer Immunology, Immunotherapy",
    issn: "1432-0851",
  },
  {
    slug: "ragusa-2022-engineered-model-of-t-7-12-q36-p13-aml-recapitul",
    title: "Engineered model of t(7;12)(q36;p13) AML recapitulates patient-specific features and gene expression profiles",
    authors: ["Ragusa", "D", "Cicirò", "Y", "Federico", "C", "et al."],
    year: 2022,
    journal: "Oncogenesis",
    volume: "11",
    issue: "1",
    issn: "2157-9024",
  },
  {
    slug: "martin-2022-estimating-the-effect-of-liver-and-pancreas-volume",
    title: "Estimating the Effect of Liver and Pancreas Volume and Fat Content on Risk of Diabetes: A Mendelian Randomization Study",
    authors: ["Martin", "S", "Sorokin", "E. P", "Thomas", "E. L", "et al."],
    year: 2022,
    journal: "Diabetes Care",
    volume: "45",
    issue: "2",
    pages: "460-468",
    issn: "0149-5992",
  },
  {
    slug: "borish-2022-evaluating-enrolment-and-outcome-criteria-in-trial",
    title: "Evaluating enrolment and outcome criteria in trials of biologics for chronic rhinosinusitis with nasal polyps",
    authors: ["Borish", "L", "Cohen", "N. A", "Chupp", "G", "et al."],
    year: 2022,
    journal: "Annals of Allergy, Asthma & Immunology",
    volume: "129",
    issue: "2",
    pages: "160-168",
    issn: "1081-1206",
  },
  {
    slug: "thompson-2022-fetal-alleles-predisposing-to-metabolically-favora",
    title: "Fetal alleles predisposing to metabolically favorable adiposity are associated with higher birth weight",
    authors: ["Thompson", "W. D", "Beaumont", "R. N", "Kuang", "A", "et al."],
    year: 2022,
    journal: "Human Molecular Genetics",
    volume: "31",
    issue: "11",
    pages: "1762-1775",
    issn: "1460-2083",
  },
  {
    slug: "roadaz-2022-gene-diet-interactions-and-cardiovascular-diseases",
    title: "Gene-diet interactions and cardiovascular diseases: a systematic review of observational and clinical trials",
    authors: ["Roa-Díaz", "Z. M", "Teuscher", "J", "Gamba", "M", "et al."],
    year: 2022,
    journal: "BMC cardiovascular disorders",
    volume: "22",
    issue: "1",
    issn: "1471-2261",
  },
  {
    slug: "liu-2022-health-outcomes-after-stopping-long-term-mepolizum",
    title: "Health outcomes after stopping long-term mepolizumab in severe eosinophilic asthma: COMET",
    authors: ["Liu", "M. C", "Bel", "E. H", "Kornmann", "O", "et al."],
    year: 2022,
    journal: "ERJ Open Research",
    volume: "8",
    issue: "1",
    pages: "419-2021",
    issn: "2312-0541",
  },
  {
    slug: "jagne-2022-impact-of-intra-partum-azithromycin-on-carriage-of",
    title: "Impact of intra-partum azithromycin on carriage of group A streptococcus in the Gambia: a posthoc analysis of a double-blind randomized placebo-controlled trial",
    authors: ["Jagne", "I", "Keeley", "A. J", "Bojang", "A", "et al."],
    year: 2022,
    journal: "BMC Infectious Diseases",
    volume: "22",
    issue: "1",
    issn: "1471-2334",
  },
  {
    slug: "bitencourt-2022-induction-of-functional-specific-antibodies-igg-s",
    title: "Induction of Functional Specific Antibodies, IgG-Secreting Plasmablasts and Memory B Cells Following BCG Vaccination",
    authors: ["Bitencourt", "J", "Peralta-Álvarez", "M. P", "Wilkie", "M", "et al."],
    year: 2022,
    journal: "Frontiers in Immunology 12:798207",
    issn: "1664-3224",
  },
  {
    slug: "razzaghyazar-2022-investigating-genetic-mutations-in-a-large-cohort",
    title: "Investigating Genetic Mutations in a Large Cohort of Iranian Patients with Congenital Hyperinsulinism",
    authors: ["Razzaghy-Azar", "M", "Saeedi", "S", "Dayani", "S. B", "et al."],
    year: 2022,
    journal: "Journal of Clinical Research in Pediatric Endocrinology",
    volume: "14",
    issue: "1",
    pages: "87-95",
    issn: "1308-5735",
  },
  {
    slug: "bachert-2022-mepolizumab-for-chronic-rhinosinusitis-with-nasal",
    title: "Mepolizumab for chronic rhinosinusitis with nasal polyps: Treatment efficacy by comorbidity and blood eosinophil count",
    authors: ["Bachert", "C", "Sousa", "A. R", "Han", "J. K", "et al."],
    year: 2022,
    journal: "Journal of Allergy and Clinical Immunology",
    volume: "149",
    issue: "5",
    pages: "1711-1721",
    issn: "0091-6749",
  },
  {
    slug: "prezhernndez-2022-mitochondrial-ultrastructure-and-activity-are-diff",
    title: "Mitochondrial Ultrastructure and Activity Are Differentially Regulated by Glycolysis-, Krebs Cycle-, and Microbiota-Derived Metabolites in Monocytes",
    authors: ["Pérez-Hernández", "C. A", "Moreno-Altamirano", "M. M. B", "López-Villegas", "E. O", "et al."],
    year: 2022,
    journal: "Biology",
    volume: "11",
    issue: "8",
    issn: "2079-7737",
  },
  {
    slug: "ofarrell-2022-molecular-alterations-caused-by-alcohol-consumptio",
    title: "Molecular Alterations Caused by Alcohol Consumption in the UK Biobank: A Mendelian Randomisation Study",
    authors: ["O'Farrell", "F", "Jiang", "X", "Aljifri", "S., and Pazoki", "et al."],
    year: 2022,
    journal: "Nutrients",
    volume: "14",
    issue: "14",
    issn: "2072-6643",
  },
  {
    slug: "israel-2022-real-life-effectiveness-of-mepolizumab-in-severe-a",
    title: "Real-life effectiveness of mepolizumab in severe asthma: a systematic literature review",
    authors: ["Israel", "E", "Canonica", "G. W", "Brusselle", "G", "et al."],
    year: 2022,
    journal: "Journal of Asthma",
    volume: "59",
    issue: "11",
    pages: "2201-2217",
    issn: "1532-4303",
  },
  {
    slug: "moore-2022-stopping-versus-continuing-long-term-mepolizumab-t",
    title: "Stopping versus continuing long-term mepolizumab treatment in severe eosinophilic asthma (COMET study)",
    authors: ["Moore", "W. C", "Kornmann", "O", "Humbert", "M", "et al."],
    year: 2022,
    journal: "European Respiratory Journal",
    volume: "59",
    issue: "1",
    issn: "1399-3003",
  },
  {
    slug: "gevaert-2022-the-roles-of-eosinophils-and-interleukin5-in-the",
    title: "The roles of eosinophils and interleukin‐5 in the pathophysiology of chronic rhinosinusitis with nasal polyps",
    authors: ["Gevaert", "P", "Han", "J. K", "Smith", "S. G", "et al."],
    year: 2022,
    journal: "International Forum of Allergy & Rhinology",
    volume: "12",
    issue: "11",
    pages: "1413-1423",
    issn: "2042-6984",
  },
  {
    slug: "triay-2022-the-spectrum-of-acute-cerebrovascular-disease-in-p",
    title: "The Spectrum of Acute Cerebrovascular Disease in Patients with COVID-19",
    authors: ["Triay", "R", "Buchhanolla", "P", "Gaudet", "A", "et al."],
    year: 2022,
    journal: "Biomedicines",
    volume: "10",
    issue: "2",
    issn: "2227-9059",
  },
  {
    slug: "iffah-2022-thromboinflammation-in-covid19-the-clot-thickens",
    title: "Thromboinflammation in COVID‐19: The Clot Thickens",
    authors: ["Iffah", "Raayma, and Felicity N. E. Gavins"],
    year: 2022,
    journal: "British Journal of Pharmacology",
    issn: "1476-5381",
  },
  {
    slug: "jiang-2022-urinary-sodium-excretion-enhances-the-effect-of-al",
    title: "Urinary Sodium Excretion Enhances the Effect of Alcohol on Blood Pressure",
    authors: ["Jiang", "X", "Anasanti", "M. D", "Drenos", "F", "et al."],
    year: 2022,
    journal: "Healthcare (Basel, Switzerland)",
    volume: "10",
    issue: "7",
    issn: "2227-9032",
  },
  {
    slug: "boulind-2022-urinary-volatile-organic-compound-testing-in-fast",
    title: "Urinary Volatile Organic Compound Testing in Fast-Track Patients with Suspected Colorectal Cancer",
    authors: ["Boulind", "C. E", "Gould", "O., de Lacy Costello", "B", "Allison", "et al."],
    year: 2022,
    journal: "Cancers",
    volume: "14",
    issue: "9",
    issn: "2072-6694",
  },
  {
    slug: "li-2021-mechanism-of-gynostemma-pentaphyllum-in-treatment",
    title: "[Mechanism of Gynostemma pentaphyllum in treatment of metabolism associated fatty liver disease based on network pharmacology and molecular docking]",
    authors: ["Li", "S", "Li", "S", "Liu", "J", "et al."],
    year: 2021,
    journal: "Zhongguo Zhong Yao Za Zhi",
    volume: "46",
    issue: "19",
    pages: "5080-5087",
  },
  {
    slug: "bazbanshotorbani-2021-a-biomicrofluidic-screening-platform-for-dysfuncti",
    title: "A biomicrofluidic screening platform for dysfunctional endothelium targeted nanoparticles and therapeutics",
    authors: ["Bazban-Shotorbani", "S", "Gavins", "F", "Kant", "K", "et al."],
    year: 2021,
    journal: "BioRXiv",
    doi: "10.1101/2021.05.09.443301.",
  },
  {
    slug: "madan-2021-a-recombinant-fragment-of-human-surfactant-protein",
    title: "A Recombinant Fragment of Human Surfactant Protein D Binds Spike Protein and Inhibits Infectivity and Replication of SARS-CoV-2 in Clinical Samples",
    authors: ["Madan", "T", "Biswas", "B", "Varghese", "M", "et al."],
    year: 2021,
    journal: "American journal of respiratory cell and molecular biology",
    volume: "65",
    issue: "1",
    pages: "41-53",
    issn: "1044-1549",
  },
  {
    slug: "roadaz-2021-age-at-natural-menopause-and-blood-pressure-traits",
    title: "Age at natural menopause and blood pressure traits: Mendelian randomization study",
    authors: ["Roa-Díaz", "ZM", "Asllanaj", "E", "Amin", "HA", "et al."],
    year: 2021,
    journal: "Journal of clinical medicine",
    volume: "10",
    issue: "19",
    issn: "2077-0383",
  },
  {
    slug: "evangelou-2021-alcohol-consumption-in-the-general-population-is-a",
    title: "Alcohol consumption in the general population is associated with structural changes in multiple organ systems",
    authors: ["Evangelou", "E", "Suzuki", "H", "Bai", "W", "et al."],
    year: 2021,
    journal: "eLife",
    issn: "2050-084X",
  },
  {
    slug: "mccarthy-2021-antibiotic-resistance-mechanisms-and-their-transmi",
    title: "Antibiotic Resistance Mechanisms and Their Transmission in Acinetobacter baumannii",
    authors: ["McCarthy", "RR", "Larrouy-Maumus", "GJ", "Meiqi Tan", "MGC", "et al."],
    year: 2021,
    journal: "Advances in experimental medicine and biology",
    pages: "135 -153",
    issn: "0065-2598",
  },
  {
    slug: "liu-2021-benefit-of-switching-to-mepolizumab-from-omalizuma",
    title: "Benefit of switching to mepolizumab from omalizumab in severe eosinophilic asthma based on patient characteristics",
    authors: ["Liu", "M. C", "Chipps", "B", "Munoz", "X", "et al."],
    year: 2021,
    journal: "Respiratory Research",
    volume: "22",
    issue: "1",
  },
  {
    slug: "maslova-2021-burns-and-biofilms-priority-pathogens-and-in-vivo",
    title: "Burns and biofilms: priority pathogens and in vivo models",
    authors: ["Maslova", "E", "Eisaiankhongi", "L", "Sjöberg", "F", "et al."],
    year: 2021,
    journal: "NPJ biofilms and microbiomes",
    volume: "7",
    issue: "1",
    issn: "2055-5008",
  },
  {
    slug: "varghese-2021-c4b-binding-protein-acts-as-an-innate-immune-effec",
    title: "C4b Binding Protein Acts as an Innate Immune Effector Against Influenza A Virus",
    authors: ["Varghese", "PM", "Murugaiah", "V", "Beirag", "N", "et al."],
    year: 2021,
    journal: "Frontiers in immunology",
    issn: "1664-3224",
  },
  {
    slug: "houlden-2021-can-microfluidics-be-used-to-create-a-more-realist",
    title: "Can microfluidics be used to create a more realistic in vitro model of the vaginal ectocervix to better understand bacterial vaginosis?",
    authors: ["Houlden", "A., and MacKay", "R"],
    year: 2021,
    journal: "Sexually Transmitted Infections",
    issn: "1368-4973",
  },
  {
    slug: "katopodis-2021-circulating-tumour-cells-and-circulating-cell-free",
    title: "Circulating tumour cells and circulating cell-free DNA in patients with lung cancer: a comparison between thoracotomy and video-assisted thoracoscopic surgery",
    authors: ["Katopodis", "P", "Anikin", "V", "Kishore", "U", "et al."],
    year: 2021,
    journal: "BMJ open respiratory research",
    volume: "8",
    issue: "1",
    issn: "2052-4439",
  },
  {
    slug: "lugogo-2021-clinical-effects-of-mepolizumab-in-patients-with-s",
    title: "Clinical effects of mepolizumab in patients with severe eosinophilic asthma according to background therapy: A meta-analysis",
    authors: ["Lugogo", "N", "Liu", "M. C", "Pavord", "I", "et al."],
    year: 2021,
    journal: "The Journal of Allergy and Clinical Immunology: In Practice",
    volume: "9",
    issue: "9",
    pages: "3506-3509",
    issn: "2213-2198",
  },
  {
    slug: "remmington-2021-cryptic-prophages-within-a-streptococcus-pyogenes",
    title: "Cryptic prophages within a streptococcus pyogenes genotype EMM4 lineage",
    authors: ["Remmington", "A", "Haywood", "S", "Edgar", "J", "et al."],
    year: 2021,
    journal: "Microbial genomics",
    volume: "7",
    issue: "1",
    pages: "1 - 14",
    issn: "2057-5858",
  },
  {
    slug: "ullah-2021-editorial-nanocellulose-a-multipurpose-advanced",
    title: "Editorial: Nanocellulose: A Multipurpose Advanced Functional Material",
    authors: ["Ullah", "MW", "Rojas", "OJ", "McCarthy", "RR", "et al."],
    year: 2021,
    journal: "Frontiers in bioengineering and biotechnology",
    issn: "2296-4185",
  },
  {
    slug: "snchezcordn-2021-evaluation-of-lesions-and-viral-antigen-distributi",
    title: "Evaluation of Lesions and Viral Antigen Distribution in Domestic Pigs Inoculated Intranasally with African Swine Fever Virus Ken05/Tk1 (Genotype X)",
    authors: ["Sánchez-Cordón", "PJ", "Floyd", "T", "Hicks", "D", "et al."],
    year: 2021,
    journal: "Pathogens (Basel)",
    volume: "10",
    issue: "6",
    issn: "2076-0817",
  },
  {
    slug: "simonovich-2021-examining-effective-communication-in-nursing-pract",
    title: "Examining effective communication in nursing practice during COVID‐19: A large‐scale qualitative study",
    authors: ["Simonovich", "S. D", "Spurlark", "R. S", "Badowski", "D", "et al."],
    year: 2021,
    journal: "International Nursing Review",
    volume: "68",
    issue: "4",
    pages: "512-523",
    issn: "1466-7657",
  },
  {
    slug: "pazoki-2021-genetic-analysis-in-european-ancestry-individuals",
    title: "Genetic analysis in European ancestry individuals identifies 517 loci associated with liver enzymes",
    authors: ["Pazoki", "R", "Vujkovic", "M", "Elliott", "J", "et al."],
    year: 2021,
    journal: "Nature communications",
    volume: "12",
    issue: "1",
    issn: "2041-1723",
  },
  {
    slug: "casanova-2021-higher-adiposity-and-mental-health-causal-inferen",
    title: "Higher adiposity and mental health: causal inference using Mendelian randomization",
    authors: ["Casanova", "F", "O’Loughlin", "J", "Martin", "S", "et al."],
    year: 2021,
    journal: "Human Molecular Genetics",
    volume: "30",
    issue: "24",
    pages: "2371-2382",
    issn: "1460-2083",
  },
  {
    slug: "broderick-2021-host-transcriptional-response-to-tb-preventive-the",
    title: "Host transcriptional response to TB preventive therapy differentiates two sub-groups of IGRA-positive individuals",
    authors: ["Broderick", "C", "Cliff", "J. M", "Lee", "J.-S", "et al."],
    year: 2021,
    journal: "Tuberculosis pp",
    issn: "1472-9792",
  },
  {
    slug: "pate-2021-how-researchers-clinicians-and-patient-advocates",
    title: "How Researchers, Clinicians and Patient Advocates Can Accelerate Lobular Breast Cancer Research",
    authors: ["Pate", "L", "Desmedt", "C", "Metzger", "O", "et al."],
    year: 2021,
    journal: "Cancers",
    volume: "13",
    issue: "13",
    issn: "2072-6694",
  },
  {
    slug: "hsieh-2021-human-surfactant-protein-d-binds-spike-protein-and",
    title: "Human Surfactant Protein D Binds Spike Protein and Acts as an Entry Inhibitor of SARS-CoV-2 Pseudotyped Viral Particles",
    authors: ["Hsieh", "MH", "Beirag", "N", "Murugaiah", "V", "et al."],
    year: 2021,
    journal: "Frontiers in immunology",
    issn: "1664-3224",
  },
  {
    slug: "mawa-2021-immune-responses-following-bcg-immunization-of-inf",
    title: "Immune Responses Following BCG Immunization of Infants in Uganda and United Kingdom Are Similar for Purified Protein Derivative but Differ for Secretory Proteins",
    authors: ["Mawa", "PA", "Hasso-Agopsowicz", "M", "Lubyayi", "L", "et al."],
    year: 2021,
    journal: "Frontiers in Immunology",
    issn: "1664-3224",
  },
  {
    slug: "ferluga-2021-immune-responses-in-malaria-and-vaccine-strategies",
    title: "Immune Responses in Malaria and Vaccine Strategies",
    authors: ["Ferluga", "J", "Singh", "I", "Rout", "S", "et al."],
    year: 2021,
    journal: "Advances in experimental medicine and biology",
    pages: "273-291",
    issn: "0065-2598",
  },
  {
    slug: "rehman-2021-immunity-sex-hormones-and-environmental-factors",
    title: "Immunity, Sex Hormones, and Environmental Factors as Determinants of COVID-19 Disparity in Women",
    authors: ["Rehman", "S", "Ravinayagam", "V", "Nahvi", "I", "et al."],
    year: 2021,
    journal: "Frontiers in immunology",
    issn: "1664-3224",
  },
  {
    slug: "agostinis-2021-immunological-basis-of-the-endometriosis-the-comp",
    title: "Immunological Basis of the Endometriosis: The Complement System as a Potential Therapeutic Target",
    authors: ["Agostinis", "C", "Balduit", "A", "Mangogna", "A", "et al."],
    year: 2021,
    journal: "Frontiers in Immunology",
    issn: "1664-3224",
  },
  {
    slug: "lemiere-2021-impact-of-baseline-clnical-asthma-characteristics",
    title: "Impact of baseline clnical asthma characteristics on the response to mepolizumab: a post hoc meta-analysis of two Phase III trials",
    authors: ["Lemiere", "C", "Taille", "C", "Lee", "J. K", "et al."],
    year: 2021,
    journal: "Journal of Allergy and Clinical Immunology",
    volume: "147",
    issue: "2",
    issn: "0091-6749",
  },
  {
    slug: "mccleary-2021-inactivation-of-african-swine-fever-virus-by-reage",
    title: "Inactivation of African Swine Fever Virus by reagents commonly used in containment laboratories",
    authors: ["McCleary", "S", "McCarthy", "RR", "Strong", "R", "et al."],
    year: 2021,
    journal: "Journal of virological methods",
    issn: "0166-0934",
  },
  {
    slug: "tsolaki-2021-innate-immune-pattern-recognition-receptors-of-myc",
    title: "Innate Immune Pattern Recognition Receptors of Mycobacterium tuberculosis: Nature and Consequences for Pathogenesis of Tuberculosis",
    authors: ["Tsolaki", "AG", "Varghese", "PM", "Kishore", "U"],
    year: 2021,
    journal: "Advances in experimental medicine and biology",
    pages: "179 - 215",
    issn: "0065-2598",
  },
  {
    slug: "murugaiah-2021-innate-immune-response-against-hiv-1",
    title: "Innate Immune Response Against HIV-1",
    authors: ["Murugaiah", "V", "Yasmin", "H", "Pandit", "H", "et al."],
    year: 2021,
    journal: "Advances in experimental medicine and biology",
    pages: "23- 58",
    issn: "0065-2598",
  },
  {
    slug: "tagalakis-2021-integrin-targeted-short-interfering-rna-nanocomp",
    title: "Integrin- Targeted, Short Interfering RNA Nanocomplexes for Neuroblastoma Tumor-Specific Delivery Achieve MYCN Silencing with Improved Survival",
    authors: ["Tagalakis", "AD", "Jayarajan", "V", "Maeshima", "R", "et al."],
    year: 2021,
    journal: "Advanced functional materials",
    volume: "31",
    issue: "37",
    pages: "2104843 - n",
    issn: "1616-301X",
  },
  {
    slug: "ganguly-2021-interplay-between-c-type-lectin-receptors-and-micr",
    title: "Interplay between C-type lectin receptors and microRNAs in cellular homeostasis and immune response",
    authors: ["Ganguly", "K", "Kishore", "U", "Madan", "T"],
    year: 2021,
    journal: "The FEBS journal",
    volume: "288",
    issue: "14",
    pages: "4210 - 4229",
    issn: "1742-464X",
  },
  {
    slug: "boltersdorf-2021-long-lived-lanthanide-emission-via-a-ph-sensitive",
    title: "Long-lived lanthanide emission via a pH-sensitive and switchable LRET complex",
    authors: ["Boltersdorf", "T", "Gavins", "F", "Long", "NJ"],
    year: 2021,
    journal: "Chemical Science",
    volume: "12",
    issue: "25",
    pages: "8740 - 8745",
    issn: "2041-6520",
  },
  {
    slug: "kamble-2021-mareks-disease-virus-modulates-t-cell-proliferati",
    title: "Marek’s Disease Virus Modulates T Cell Proliferation via Activation of Cyclooxygenase 2-Dependent Prostaglandin E2",
    authors: ["Kamble", "N", "Gurung", "A", "Kaufer", "B. B", "et al."],
    year: 2021,
    journal: "Frontiers in Immunology",
    issn: "1664-3224",
  },
  {
    slug: "han-2021-mepolizumab-for-chronic-rhinosinusitis-with-nasal",
    title: "Mepolizumab for chronic rhinosinusitis with nasal polyps (SYNAPSE): a randomised, double-blind, placebo-controlled, phase 3 trial",
    authors: ["Han", "J. K.  Bachart", "C", "Fokkens", "W", "Desrosiers", "et al."],
    year: 2021,
    journal: "The Lancet Respiratory Medicine",
    volume: "9",
    issue: "10",
    pages: "1141-1153",
    issn: "2213-2600",
  },
  {
    slug: "gibson-2021-mepolizumab-improves-clinical-outcomes-in-patients",
    title: "Mepolizumab improves clinical outcomes in patients with severe asthma and comorbid conditions",
    authors: ["Gibson", "P. G", "Prazma", "C. M", "Chupp", "G. L", "et al."],
    year: 2021,
    journal: "Respiratory Research",
    volume: "22",
    issue: "1",
    issn: "1465-993X",
  },
  {
    slug: "cicir-2021-myb-oncoproteins-emerging-players-and-potential-t",
    title: "MYB oncoproteins: emerging players and potential therapeutic targets in human cancer",
    authors: ["Cicirò", "Y", "Sala", "A"],
    year: 2021,
    journal: "Oncogenesis",
    volume: "10",
    issue: "2",
    issn: "2157-9024",
  },
  {
    slug: "tsakaneli-2021-myc-regulates-metabolism-through-vesicular-transfe",
    title: "MYC regulates metabolism through vesicular transfer of glycolytic kinases",
    authors: ["Tsakaneli", "A", "Carregari", "V. C", "Morini", "M", "et al."],
    year: 2021,
    journal: "Open Biology",
    volume: "11",
    issue: "12",
    issn: "2046-2441",
  },
  {
    slug: "cilliers-2021-mycobacterium-tuberculosis-stimulated-whole-blood",
    title: "Mycobacterium tuberculosis-stimulated whole blood culture to detect host biosignatures for tuberculosis treatment response",
    authors: ["Cilliers", "K", "Menezes", "A", "Webber", "T", "et al."],
    year: 2021,
    journal: "Tuberculosis 128",
    issn: "1472-9792",
  },
  {
    slug: "ansari-2021-neutrophils-and-platelets-immune-soldiers-fightin",
    title: "Neutrophils and Platelets: Immune Soldiers Fighting Together in Stroke Pathophysiology",
    authors: ["Ansari", "Junaid, and Felicity N. E. Gavins"],
    year: 2021,
    journal: "Biomedicines",
    volume: "9",
    issue: "12",
    issn: "2227-9059",
  },
  {
    slug: "yasmin-2021-pathogenesis-and-host-immune-response-in-leprosy",
    title: "Pathogenesis and Host Immune Response in Leprosy",
    authors: ["Yasmin", "H", "Varghese", "PM", "Bhakta", "S", "et al."],
    year: 2021,
    journal: "Advances in experimental medicine and biology",
    pages: "155-177",
    issn: "0065-2598",
  },
  {
    slug: "marmon-2021-pharmacology-informed-prediction-of-the-risk-posed",
    title: "Pharmacology-informed prediction of the risk posed to fish by mixtures of non-steroidal anti-inflammatory drugs (NSAIDs) in the environment",
    authors: ["Marmon", "P", "Owen", "SF", "Margiotta-Casaluci", "L"],
    year: 2021,
    journal: "Environment international",
    issn: "0160-4120",
  },
  {
    slug: "kishore-2021-preface",
    title: "Preface",
    authors: ["Kishore", "U"],
    year: 2021,
    journal: "Advances in experimental medicine and biology",
    pages: "ix- x",
    issn: "0065-2598",
  },
  {
    slug: "khan-2021-pro-apoptotic-and-immunotherapeutic-effects-of-car",
    title: "Pro-apoptotic and immunotherapeutic effects of carbon nanotubes functionalized with recombinant human surfactant protein d on leukemic cells",
    authors: ["Khan", "HA", "Kishore", "U", "Alsulami", "HM", "et al."],
    year: 2021,
    journal: "International journal of molecular sciences",
    volume: "22",
    issue: "19",
    issn: "1661-6596",
  },
  {
    slug: "mangogna-2021-prognostic-value-of-complement-properdin-in-cancer",
    title: "Prognostic Value of Complement Properdin in Cancer",
    authors: ["Mangogna", "A", "Varghese", "PM", "Agostinis", "C", "et al."],
    year: 2021,
    journal: "Frontiers in immunology",
    issn: "1664-3224",
  },
  {
    slug: "mills-2021-publisher-correction-identification-of-371-geneti",
    title: "Publisher Correction: Identification of 371 genetic variants for age at first sex and birth linked to externalising behavior",
    authors: ["Mills", "M. C", "Tropf", "F. C", "Brazel", "D. M", "et al."],
    year: 2021,
    journal: "National Human Behavior",
    volume: "5",
    issue: "8",
    issn: "2397-3374",
  },
  {
    slug: "teo-2021-rs641738c-t-near-mboat7-is-associated-with-liver-f",
    title: "rs641738C>T near MBOAT7 is associated with liver fat, ALT and fibrosis in NAFLD: A meta-analysis",
    authors: ["Teo", "K", "Abeysekera", "K. W. M", "Adams", "L", "et al."],
    year: 2021,
    journal: "Journal of Hepatology",
    volume: "74",
    issue: "1",
    pages: "20-30",
    issn: "0168-8278",
  },
  {
    slug: "yasmin-2021-sars-cov-2-pathogenic-mechanisms-and-host-immune",
    title: "SARS-CoV-2: Pathogenic Mechanisms and Host Immune Response",
    authors: ["Yasmin", "H", "Saha", "S", "Butt", "MT", "et al."],
    year: 2021,
    journal: "Advances in experimental medicine and biology",
    pages: "99 - 134",
    issn: "0065-2598",
  },
  {
    slug: "awoyemi-2021-syncytiotrophoblast-extracellular-vesicles-from-la",
    title: "Syncytiotrophoblast Extracellular Vesicles From Late-Onset Preeclampsia Placentae Suppress Pro-Inflammatory Immune Response in THP-1 Macrophages",
    authors: ["Awoyemi", "T", "Motta-Mejia", "C", "Zhang", "W", "et al."],
    year: 2021,
    journal: "Frontiers in immunology",
    issn: "1664-3224",
  },
  {
    slug: "ansari-2021-targeting-the-ana1-fpr2-alx-pathway-regulates-neut",
    title: "Targeting the AnA1/Fpr2/ALX pathway regulates neutrophil function, promoting thromboinflammation resolution in sickle cell disease",
    authors: ["Ansari", "J", "Senchenkova", "EY", "Vital", "SA", "et al."],
    year: 2021,
    journal: "Blood",
    volume: "137",
    issue: "13",
    pages: "1538 - 1549",
    issn: "0006-4971",
  },
  {
    slug: "ansari-2021-the-impact-of-thrombo-inflammation-on-the-cerebral",
    title: "The Impact of Thrombo-inflammation on the Cerebral Microcirculation. Microcirculation",
    authors: ["Ansari", "J", "Gavins", "F"],
    year: 2021,
    journal: "Microcirculation",
    volume: "10",
    issue: "15",
    pages: "6599 - 6614",
    issn: "1838-7640",
  },
  {
    slug: "agostinis-2021-the-inflammatory-feed-forward-loop-triggered-by-th",
    title: "The inflammatory Feed-Forward Loop Triggered by the Complement Component C3 as a Potential Target in Endometriosis",
    authors: ["Agostinis", "C", "Zorzet", "S", "Balduit", "A", "et al."],
    year: 2021,
    journal: "Frontiers in immunology",
    issn: "1664-3224",
  },
  {
    slug: "jagatia-2021-the-role-of-complement-system-and-the-immune-respo",
    title: "The role of complement system and the immune response to tuberculosis infection",
    authors: ["Jagatia", "H", "Tsolaki", "AG"],
    year: 2021,
    journal: "Medicina",
    volume: "57",
    issue: "2",
    pages: "1 - 18",
    issn: "1010-660X",
  },
  {
    slug: "iffah-2021-thromboinflammation-in-coronavirus-disease-2019-t",
    title: "Thromboinflammation in coronavirus disease 2019: The Clot Thickens",
    authors: ["Iffah", "R", "Gavins", "F"],
    year: 2021,
    journal: "Br J British Journal of pharmacology",
    issn: "0007-1188",
  },
  {
    slug: "ferluga-2021-vaccination-strategies-against-mycobacterium-tuber",
    title: "Vaccination Strategies Against Mycobacterium tuberculosis: BCG and Beyond",
    authors: ["Ferluga", "J", "Yasmin", "H", "Bhakta", "S", "et al."],
    year: 2021,
    journal: "Advances in experimental medicine and biology",
    pages: "217 - 240",
    issn: "0065-2598",
  },
  {
    slug: "tan-2021-vaccine-induce-but-not-natural-immunity-against",
    title: "Vaccine-induce, but not natural immunity, against the Streptococcal inhibitor of complement protects against invasive disease",
    authors: ["Tan", "LKK", "Reglinski", "M", "Teo", "D", "et al."],
    year: 2021,
    journal: "Npj vaccines",
    volume: "6",
    issue: "1",
    issn: "2059-0105",
  },
  {
    slug: "tan-2021-vaccine-induced-but-not-natural-immunity-against",
    title: "Vaccine-induced, but not natural immunity, against the Streptococcal inhibitor of complement protects against invasive disease",
    authors: ["Tan", "L. K. K", "Reglinski", "M", "Teo", "D", "et al."],
    year: 2021,
    journal: "NPJ Vaccines",
    volume: "6",
    issue: "1",
    issn: "2059-0105",
  },
  {
    slug: "maslova-2020-an-invertebrate-burn-wound-model-that-recapitulate",
    title: "An Invertebrate Burn Wound Model That Recapitulates the Hallmarks of Burn Trauma and Infection Seen in Mammalian Models",
    authors: ["Maslova", "E", "Shi", "Y", "Sjöberg", "F", "et al."],
    year: 2020,
    journal: "Frontiers in microbiology",
    issn: "1664-302X",
  },
  {
    slug: "huerta-2020-anti-anxiety-drug-and-fish-behavior-establishing",
    title: "Anti-anxiety drug and fish behavior: establishing the link between internal concentrations of oxazepam and behavioral effects",
    authors: ["Huerta Buitrago", "B", "Margiotta-Casaluci", "L", "Rodríguez Mozaz", "S", "et al."],
    year: 2020,
    journal: "Environmental toxicology and chemistry",
    issn: "0730-7268",
  },
  {
    slug: "andersson-2020-atr-is-a-myb-regulated-gene-and-potential-therapeu",
    title: "ATR is a MYB regulated gene and potential therapeutic target in adenoid cystic carcinoma",
    authors: ["Andersson", "MK", "Mangiapane", "G", "Nevado", "PJ", "et al."],
    year: 2020,
    journal: "Oncogenesis",
    volume: "9",
    issue: "1",
    issn: "2157-9024",
  },
  {
    slug: "omura-2020-bioinformatics-analysis-of-gut-microbiota-and-cns",
    title: "Bioinformatics Analysis of Gut Microbiota and CNS Transcriptome in Virus-Induced Acute Myelitis and Chronic Inflammatory Demyelination; Potential Association of Distinct Bacteria with CNS IgA upregulation. Frontiers in Immunology, section Mucosal Immunity",
    authors: ["Omura", "S", "Sato", "F", "Park", "A", "et al."],
    year: 2020,
    journal: "Frontiers in Immunology",
    issn: "1664-3224",
  },
  {
    slug: "kishore-2020-c1q-a-molecular-bridge-to-innate-and-adaptive-imm",
    title: "C1q: A molecular bridge to innate and adaptive immunity",
    authors: ["Kishore", "U", "Ghebrehiwet", "B"],
    year: 2020,
    journal: "ISSN: 1664-3224",
    issn: "1664-3224",
  },
  {
    slug: "murugaiah-2020-collectins-innate-immune-pattern-recognition-mole",
    title: "Collectins: Innate Immune Pattern Recognition Molecules",
    authors: ["Murugaiah", "V", "Tsolaki", "AG", "Kishore", "U"],
    year: 2020,
    journal: "Advances in experimental medicine and biology",
    pages: "75 -  127",
    issn: "0065-2598",
  },
  {
    slug: "murugaiah-2020-complement-independent-modulation-of-influenza-a",
    title: "Complement- Independent Modulation of Influenza A Virus Infection by Factor H",
    authors: ["Murugaiah", "V", "Varghese", "PM", "Saleh", "SM", "et al."],
    year: 2020,
    journal: "Frontiers in immunology",
    issn: "1664-3224",
  },
  {
    slug: "robinson-2020-determinants-of-accelerated-metabolomic-and-epigen",
    title: "Determinants of accelerated metabolomic and epigenetic ageing in a UK cohort",
    authors: ["Robinson", "O", "Chadeau Hyam", "M", "Karaman", "I", "et al."],
    year: 2020,
    journal: "Aging cell",
    volume: "19",
    issue: "6",
    pages: "e13149 - n",
    issn: "1474-9718",
  },
  {
    slug: "riaz-2020-dissecting-the-mechanism-of-intracellularmycobacte",
    title: "Dissecting the Mechanism of IntracellularMycobacterium smegmatisGrowth Inhibition by Platelet Activating Factor C-16",
    authors: ["Riaz", "MS", "Kaur", "A", "Shwayat", "SN", "et al."],
    year: 2020,
    journal: "Frontiers in microbiology",
    issn: "1664-302X",
  },
  {
    slug: "kishore-2020-editorial-odyssey-of-surfactant-proteins-sp-a-and",
    title: "Editorial: Odyssey of Surfactant Proteins SP-A and SP-D: Innate Immune Surveillance Molecules",
    authors: ["Kishore", "U", "Bulla", "R", "Madan", "T"],
    year: 2020,
    journal: "Frontiers in immunology",
    issn: "1664-3224",
  },
  {
    slug: "symonds-2020-egr2-and-3-control-inflammation-but-maintain-home",
    title: "Egr2 and 3 control inflammation, but maintain homeostasis, of PD-1 high memory phenotype CD4 T cells",
    authors: ["Symonds", "ALJ", "Zheng", "W", "Miao", "T", "et al."],
    year: 2020,
    journal: "Life science alliance",
    volume: "3",
    issue: "9",
    issn: "2575-1077",
  },
  {
    slug: "elliott-2020-estimated-24-hour-urinary-sodium-excretion-and-inc",
    title: "Estimated 24-Hour Urinary Sodium Excretion and Incident Cardiovascular Disease and Mortality Among 398 628 Individuals in UK Biobank",
    authors: ["Elliott", "P", "Muller", "DC", "Schneider-Luftman", "D", "et al."],
    year: 2020,
    journal: "Hypertension (Dallas, Tex",
    volume: "76",
    issue: "3",
    pages: "683-691",
    issn: "0194-911X",
  },
  {
    slug: "siggins-2020-extracellular-bacterial-lymphatic-metastasis-drive",
    title: "Extracellular bacterial lymphatic metastasis drives Streptococcus pyogenes systemic infection",
    authors: ["Siggins", "MK", "Lynskey", "NN", "Lamb", "LE", "et al."],
    year: 2020,
    journal: "Nature communications",
    volume: "11",
    issue: "1",
    issn: "2041-1723",
  },
  {
    slug: "thompson-2020-higher-maternal-adiposity-reduces-offspring-birthw",
    title: "Higher maternal adiposity reduces offspring birthweight if associated with a metabolically favourable profile",
    authors: ["Thompson", "WD", "Beaumont", "RN", "Kuang", "A", "et al."],
    year: 2020,
    journal: "Diabetologia",
    volume: "64",
    issue: "12",
    pages: "2790 - 2802",
    issn: "0012-186X",
  },
  {
    slug: "varghese-2020-host-pathogen-interaction-in-covid-19-pathogenesi",
    title: "Host-pathogen interaction in COVID-19: Pathogenesis, potential therapeutics and vaccination strategies",
    authors: ["Varghese", "PM", "Tsolaki", "AG", "Yasmin", "H", "et al."],
    year: 2020,
    journal: "Immunobiology",
    volume: "225",
    issue: "6",
    issn: "0171-2985",
  },
  {
    slug: "murugaiah-2020-hyaluronic-acid-present-in-the-tumor-microenvironm",
    title: "Hyaluronic Acid Present in the Tumor Microenvironment Can Negate the Pro-apototic Effect of a Recombinant Fragment of Human Surfactant Protein D on Breast Cancer Cells",
    authors: ["Murugaiah", "V", "Agostinis", "C", "Varghese", "PM", "et al."],
    year: 2020,
    journal: "Frontiers in Immunology",
    issn: "1664-3224",
  },
  {
    slug: "ellis-2020-immunoassays-are-not-immune-to-errors-examples-fr",
    title: "Immunoassays are not immune to errors: Examples from two studies of steroid output from freshwater trout farms",
    authors: ["Ellis", "T", "Margiotta-Casaluci", "L", "Pottinger", "TG", "et al."],
    year: 2020,
    journal: "General and comparative endocrinology",
    issn: "0016-6480",
  },
  {
    slug: "vsa-2020-large-scale-cis-and-trans-eqtl-analyses-identify",
    title: "Large-scale cis- and trans-eQTL analyses identify thousands of genetic loci and polygenic scores that regulate blood gene expression",
    authors: ["Võsa", "U", "Claringbould", "A", "Westra", "HJ", "et al."],
    year: 2020,
    journal: "Nature genetics",
    volume: "53",
    issue: "9",
    pages: "1300 - 1310",
    issn: "1061-4036",
  },
  {
    slug: "moses-2020-lepiniopsis-ternatensis-sap-stimulates-fibroblast",
    title: "Lepiniopsis ternatensis  sap stimulates fibroblast proliferation and down regulates macrophage TNF-⍺ secretion",
    authors: ["Moses", "RL", "Dally", "J", "Lundy", "FT", "et al."],
    year: 2020,
    journal: "Fitoterapia",
    issn: "0367-326X",
  },
  {
    slug: "lubyayi-2020-maternal-latent-mycobacterium-tuberculosis-does-no",
    title: "Maternal Latent Mycobacterium tuberculosis Does Not Affect the Infant Immune Response Following BCG at Birth: An Observational Longitudinal Study in Uganda",
    authors: ["Lubyayi", "L", "Mawa", "PA", "Nabakooza", "G", "et al."],
    year: 2020,
    journal: "Frontiers in immunology",
    issn: "1664-3224",
  },
  {
    slug: "thakur-2020-membrane-interactome-of-a-recombinant-fragment-of",
    title: "Membrane Interactome of a Recombinant Fragment of Human Surfactant Protein D Reveals GRP78 as a Novel Binding Partner in PC3, a Metastatic Prostate Cancer Cell Line",
    authors: ["Thakur", "G", "Sathe", "G", "Kundu", "I", "et al."],
    year: 2020,
    journal: "Frontiers in immunology",
    issn: "1664-3224",
  },
  {
    slug: "prezhernndez-2020-mitochondrial-signature-in-human-monocytes-and-res",
    title: "Mitochondrial Signature in Human Monocytes and Resistance to Infection in C. elegans During Fumarate-Induced Innate Immune Training",
    authors: ["Pérez-Hernández", "CA", "Kern", "CC", "Butkeviciute", "E", "et al."],
    year: 2020,
    journal: "Frontiers in immunology",
    issn: "1664-3224",
  },
  {
    slug: "decordova-2020-molecular-heterogeneity-and-immunosuppressive-micr",
    title: "Molecular Heterogeneity and Immunosuppressive Microenvironment in Glioblastoma",
    authors: ["DeCordova", "S", "Shastri", "A", "Tsolaki", "AG", "et al."],
    year: 2020,
    journal: "Frontiers in immunology",
    issn: "1664-3224",
  },
  {
    slug: "ferluga-2020-natural-and-trained-innate-immunity-against-mycoba",
    title: "Natural and trained innate immunity against Mycobacterium tuberculosis",
    authors: ["Ferluga", "J", "Yasmin", "H", "Al-Ahdal", "MN", "et al."],
    year: 2020,
    journal: "Immunobiology",
    volume: "225",
    issue: "3",
    issn: "0171-2985",
  },
  {
    slug: "gomez-2020-neutrophil-microvesicles-drive-atherosclerosis-by",
    title: "Neutrophil microvesicles drive atherosclerosis by delivering miR-155 to atheroprone endothelium",
    authors: ["Gomez", "I", "Ward", "B", "Souilhol", "C", "et al."],
    year: 2020,
    journal: "Nature communications",
    volume: "11",
    issue: "1",
    issn: "2041-1723",
  },
  {
    slug: "mahony-2020-new-ideas-for-non-animal-approaches-to-predict-rep",
    title: "New ideas for non-animal approaches to predict repeated-dose systemic toxicity: Report from an EPAA Blue Sky Workshop",
    authors: ["Mahony", "C", "Ashton", "RS", "Birk", "B", "et al."],
    year: 2020,
    journal: "Regulatory toxicology and pharmacology",
    issn: "0273-2300",
  },
  {
    slug: "pazoki-2020-phenome-wide-and-genome-wide-analyses-of-quality-o",
    title: "Phenome-wide and genome-wide analyses of quality of life in schizophrenia",
    authors: ["Pazoki", "R", "Lin", "BD., van Eijk", "KR", "Schijven", "et al."],
    year: 2020,
    journal: "BJPsych open",
    volume: "7",
    issue: "1",
    issn: "2056-4724",
  },
  {
    slug: "bibbo-2020-repurposing-a-psychoactive-drug-for-children-with",
    title: "Repurposing a psychoactive drug for children with cancer: p27Kip1- dependent inhibition of metastatic neuroblastomas by Prozac",
    authors: ["Bibbo’", "S", "Lamolinara", "A", "Capone", "E", "et al."],
    year: 2020,
    journal: "Oncogenesis",
    volume: "9",
    issue: "1",
    issn: "2157-9024",
  },
  {
    slug: "kale-2020-serum-levels-of-collectins-are-sustained-during-pr",
    title: "Serum Levels of Collectins Are Sustained During Pregnancy: Surfactant Protein D Levels Are Dysregulated Prior to Missed Abortion",
    authors: ["Kale", "K", "Vishwekar", "P", "Balsarkar", "G", "et al."],
    year: 2020,
    journal: "Reproductive sciences",
    volume: "27",
    issue: "10",
    pages: "1894 - 1908",
    issn: "1933-7191",
  },
  {
    slug: "mccleary-2020-substitution-of-warthog-nf-kb-motifs-into-rela-of",
    title: "Substitution of warthog NF-kB motifs into RELA of domestic pigs is not sufficient to confer resilience to African swine fever virus",
    authors: ["McCleary", "S", "Strong", "R", "McCarthy", "RR", "et al."],
    year: 2020,
    journal: "Scientific reports",
    volume: "10",
    issue: "1",
    issn: "2045-2322",
  },
  {
    slug: "madan-2020-surfactant-protein-d-recognises-multiple-fungal-li",
    title: "Surfactant Protein D Recognises Multiple Fungal Ligands: A Key Step to Initiate and Intensify the Anti-fungal Host Defense",
    authors: ["Madan", "T", "Kishore", "U"],
    year: 2020,
    journal: "Frontiers in cellular and infection microbiology",
    issn: "2235-2988",
  },
  {
    slug: "vital-2020-targeting-anxa1-formyl-peptide-receptor-2-pathway",
    title: "Targeting AnxA1/Formyl Peptide Receptor 2 Pathway Affords Protection against Pathological Thrombo-Inflammation",
    authors: ["Vital", "SA", "Senchenkova", "EY", "Ansari", "J", "et al."],
    year: 2020,
    journal: "Cells",
    volume: "9",
    issue: "11",
    issn: "2073-4409",
  },
  {
    slug: "boltersdorf-2020-targeting-of-formyl-peptide-receptor-2-for-in-vivo",
    title: "Targeting of Formyl Peptide Receptor 2 for in vivo imaging of acute vascular inflammation",
    authors: ["Boltersdorf", "T", "Ansari", "J", "Senchenkova", "EY", "et al."],
    year: 2020,
    journal: "Theranostics",
    volume: "10",
    issue: "15",
    pages: "6599 - 6614",
    issn: "0006-4971",
  },
  {
    slug: "capone-2020-targeting-vesicular-lgals3bp-by-an-antibody-drug-c",
    title: "Targeting vesicular lgals3bp by an antibody-drug conjugate as novel therapeutic strategy for neuroblastoma",
    authors: ["Capone", "E", "Lamolinara", "A", "Pastorino", "F", "et al."],
    year: 2020,
    journal: "Cancers",
    volume: "12",
    issue: "10",
    pages: "1 - 18",
    issn: "2072-6694",
  },
  {
    slug: "legler-2020-the-goliath-project-towards-an-internationally-ha",
    title: "The GOLIATH Project: Towards an Internationally Harmonised Approach for Testing Metabolism Disrupting Compounds",
    authors: ["Legler", "J", "Zalko", "D", "Jourdan", "F", "et al."],
    year: 2020,
    journal: "International journal of molecular sciences",
    volume: "21",
    issue: "10",
    issn: "1661-6596",
  },
  {
    slug: "brooks-2020-toxicology-advances-for-21st-century-chemical-poll",
    title: "Toxicology Advances for 21st Century Chemical Pollution",
    authors: ["Brooks", "BW", "Sabo-Attwood", "T", "Choi", "K", "et al."],
    year: 2020,
    journal: "One earth (Cambridge, Mass",
    volume: "2",
    issue: "4",
    pages: "312- 316",
    issn: "2590-3330",
  },
  {
    slug: "rivetti-2020-vision-of-a-near-future-bridging-the-human-health",
    title: "Vision of a near future: Bridging the human health-environment divide. Toward an integrated strategy to understand mechanisms across species for chemical safety assessment",
    authors: ["Rivetti", "C", "Allen", "TEH", "Brown", "JB", "et al."],
    year: 2020,
    journal: "Toxicology in vitro",
    pages: "1-9",
    issn: "0887-2333",
  },
  {
    slug: "mccarthy-2019-antimicrobial-inks-the-anti-infective-application",
    title: "Antimicrobial Inks: The Anti-Infective Applications of Bioprinted Bacterial Polysaccharides",
    authors: ["McCarthy", "RR", "Ullah", "MW", "Pei", "E", "et al."],
    year: 2019,
    journal: "Trends in biotechnology (Regular ed",
    volume: "37",
    issue: "11",
    pages: "1155-1159",
    issn: "0167-7799",
  },
  {
    slug: "harris-2019-author-correction-study-of-300-486-individuals-id",
    title: "Author Correction: Study of 300,486 individuals identifies 148 independent genetic loci influencing general cognitive function",
    authors: ["Harris", "SE", "Hagenaars", "SP", "Ritchie", "SJ", "et al."],
    year: 2019,
    journal: "Nature communications",
    volume: "10",
    issue: "1",
    issn: "2041-1723",
  },
  {
    slug: "pazoki-2019-cardiovascular-disease-abo-locus-and-markers-of",
    title: "Cardiovascular disease, ABO locus, and markers of platelet functionality",
    authors: ["Pazoki", "R"],
    year: 2019,
    journal: "International journal of cardiology",
    pages: "162-163",
    issn: "0167-5273",
  },
  {
    slug: "mccarthy-2019-cyclic-di-gmp-inactivates-t6ss-and-t4ss-activity-i",
    title: "Cyclic di-GMP inactivates T6SS and T4SS activity in Agrobacterium tumefaciens",
    authors: ["McCarthy", "RR", "Yu", "M", "Eilers", "K", "et al."],
    year: 2019,
    journal: "Molecular microbiology",
    volume: "112",
    issue: "2",
    pages: "632- 648",
    issn: "0950-382X",
  },
  {
    slug: "booth-2019-developing-high-through-put-screening-strategies-t",
    title: "Developing high through put screening strategies to identify the next generation of antimicrobials",
    authors: ["Booth", "P", "McCarthy", "R"],
    year: 2019,
    journal: "Access microbiology",
    volume: "1",
    issue: "10",
    issn: "2516-8290",
  },
  {
    slug: "margiottacasaluci-2019-development-of-an-adverse-outcome-pathway-aop-fo",
    title: "Development of an adverse outcome pathway (AOP) for cardiotoxicity mediated by the blockade of L-type calcium channels",
    authors: ["Margiotta-Casaluci", "L", "Dusza", "H", "Moreira", "I", "et al."],
    year: 2019,
    journal: "Journal of pharmacological and toxicological methods",
    issn: "1056-8719",
  },
  {
    slug: "boltersdorf-2019-development-characterisation-and-in-vitro-evalua",
    title: "Development, characterisation, and in vitro evaluation of lanthanide-based FPR2/ALX-targeted imaging probes",
    authors: ["Boltersdorf", "T", "Ansari", "J", "Senchenkova", "EY", "et al."],
    year: 2019,
    journal: "Dalton transactions : an international journal of inorganic chemistry",
    volume: "48",
    issue: "44",
    pages: "16764 - 16775",
    issn: "1477-9226",
  },
  {
    slug: "guitrrezbarranquero-2019-disruption-of-n-acyl-homoserine-lactone-specific-s",
    title: "Disruption of N-acyl-homoserine lactone-specific signalling and virulence in clinical pathogens by marine sponge bacteria",
    authors: ["Guitérrez-Barranquero", "JA", "Reen", "FJ", "Parages", "ML", "et al."],
    year: 2019,
    journal: "Microbial biotechnology",
    volume: "12",
    issue: "5",
    pages: "1049 -  1063",
    issn: "1751-7915",
  },
  {
    slug: "becker-2019-dynamic-gut-microbiome-changes-following-regional",
    title: "Dynamic gut microbiome changes following regional intestinal lymphatic obstruction in primates",
    authors: ["Becker", "F.*", "Gavins", "F.*", "Fontenot", "J", "et al."],
    year: 2019,
    journal: "Pathophysiology",
  },
  {
    slug: "lynskey-2019-emergence-of-dominant-toxigenic-m1t1-streptococcus",
    title: "Emergence of dominant toxigenic M1T1 Streptococcus pyogenes clone during increased scarlet fever activity in England: a population-based molecular epidemiological study",
    authors: ["Lynskey", "NN", "Jauneikaite", "E", "Li", "HK", "et al."],
    year: 2019,
    journal: "The Lancet infectious diseases",
    volume: "19",
    issue: "11",
    pages: "1209 - 1218",
    issn: "1473-3099",
  },
  {
    slug: "becker-2019-endogenous-specialized-proresolving-mediator-profi",
    title: "Endogenous Specialized Proresolving Mediator Profiles in a Novel Experimental Model of Lymphatic Obstruction and Intestinal Inflammation in African Green Monkeys",
    authors: ["Becker", "F", "Romero", "E", "Goetzmann", "J", "et al."],
    year: 2019,
    journal: "The American journal of pathology",
    volume: "189",
    issue: "10",
    pages: "1953 - 1972",
    issn: "0002-9440",
  },
  {
    slug: "nieddu-2019-engineered-human-mesenchymal-stem-cells-for-neurob",
    title: "Engineered human mesenchymal stem cells for neuroblastoma therapeutics",
    authors: ["Nieddu", "V", "Piredda", "R", "Bexell", "D", "et al."],
    year: 2019,
    journal: "Oncology reports",
    volume: "42",
    issue: "1",
    pages: "35 - 42",
    issn: "1021-335X",
  },
  {
    slug: "prabowo-2019-fletcher-ha-ruti-vaccination-enhances-inhibition",
    title: "Fletcher HA. RUTI Vaccination Enhances Inhibition of Mycobacterial Growth ex vivo and Induces a Shift of Monocyte Phenotype in Mice",
    authors: ["Prabowo", "SA", "Painter", "H", "Zelmer", "A", "et al."],
    year: 2019,
    journal: "Frontiers in immunology",
    issn: "1664-3224",
  },
  {
    slug: "alqahtani-2019-full-length-human-surfactant-protein-a-inhibits-in",
    title: "Full length human surfactant protein A inhibits influenza A virus infection of A549 lung epithelial cells: A recombinant form containing neck and lectin domains promotes infectivity",
    authors: ["Al-Qahtani", "AA", "Murugaiah", "V", "Bashir", "HA", "et al."],
    year: 2019,
    journal: "Immunobiology (1979)",
    volume: "224",
    issue: "3",
    pages: "408-418",
    issn: "0171-2985",
  },
  {
    slug: "pazoki-2019-genetic-predisposition-to-high-blood-pressure-and",
    title: "Genetic Predisposition to High Blood Pressure and Lifestyle Factors: Associations With Midlife Blood Pressure Levels and Cardiovascular Events",
    authors: ["Pazoki", "R", "Dehghan", "A", "Evangelou", "E", "et al."],
    year: 2019,
    journal: "Circulation",
    volume: "139",
    issue: "2",
    issn: "0009-7322",
  },
  {
    slug: "pazoki-2019-gwas-for-urinary-sodium-and-potassium-excretion-hi",
    title: "GWAS for urinary sodium and potassium excretion highlights pathways shared with cardiovascular traits",
    authors: ["Pazoki", "R", "Evangelou", "E", "Mosen-Ansorena", "D", "et al."],
    year: 2019,
    journal: "Nature communication",
    volume: "10",
    issue: "1",
    pages: "3653 - 11",
    issn: "2041-1723",
  },
  {
    slug: "mccarthy-2019-head-start-immunity-characterizing-the-early-prot",
    title: "Head Start Immunity: Characterizing the Early Protection of C Strain Vaccine Against Subsequent Classical Swine Fever Virus Infection",
    authors: ["McCarthy", "RR", "Everett", "HE", "Graham", "SP", "et al."],
    year: 2019,
    journal: "Frontiers in immunology",
    issn: "1664-3224",
  },
  {
    slug: "armitage-2019-high-burden-and-seasonal-variation-of-paediatric-s",
    title: "High burden and seasonal variation of paediatric scabies and pyoderma prevalence in the Gambia: A cross-sectional study",
    authors: ["Armitage", "EP", "Senghore", "E", "Darboe", "S", "et al."],
    year: 2019,
    journal: "PLoS neglected tropical diseases",
    volume: "13",
    issue: "10",
    issn: "1935-2727",
  },
  {
    slug: "prabowo-2019-historical-bcg-vaccination-combined-with-drug-trea",
    title: "Historical BCG vaccination combined with drug treatment enhances inhibition of mycobacterial growth ex vivo in human peripheral blood cells",
    authors: ["Prabowo", "SA", "Zelmer", "A", "Stockdale", "L", "et al."],
    year: 2019,
    journal: "Scientific reports",
    volume: "9",
    issue: "1",
    issn: "2045-2322",
  },
  {
    slug: "thakur-2019-human-sp-d-acts-as-an-innate-immune-surveillance-m",
    title: "Human SP-D Acts as an Innate Immune Surveillance Molecule Against Androgen-Responsive and Androgen- Resistant Prostate Cancer Cells",
    authors: ["Thakur", "G", "Prakash", "G", "Murthy", "V", "et al."],
    year: 2019,
    journal: "Frontiers in oncology",
    issn: "2234-943X",
  },
  {
    slug: "reglinski-2019-identification-of-two-new-core-chromosome-encoded",
    title: "Identification of two new core chromosome-encoded superantigens in Streptococcus pyogenes; speQ and speR",
    authors: ["Reglinski", "M", "Sriskandan", "S", "Turner", "CE"],
    year: 2019,
    journal: "The Journal of infection",
    volume: "78",
    issue: "5",
    pages: "358 - 363",
    issn: "0163-4453",
  },
  {
    slug: "sharif-2019-immunologic-mechanisms-of-a-short-course-of-lolium",
    title: "Immunologic mechanisms of a short-course of Lolium perenne peptide immunotherapy: A randomized, double-blind, placebo-controlled trial",
    authors: ["Sharif", "H", "Singh", "I", "Kouser", "L", "et al."],
    year: 2019,
    journal: "Journal of allergy and clinical immunology",
    volume: "144",
    issue: "3",
    pages: "738- 749",
    issn: "0091-6749",
  },
  {
    slug: "prabowo-2019-impact-of-individual-level-factors-on-ex-vivo-myco",
    title: "Impact of individual-level factors on Ex vivo mycobacterial growth inhibition: Associations of immune cell phenotype, cytomegalovirus-specific response and sex with immunity following BCG vaccination in humans",
    authors: ["Prabowo", "SA", "Smith", "SG", "Seifert", "K", "et al."],
    year: 2019,
    journal: "Tuberculosis",
    issn: "1472-9792",
  },
  {
    slug: "lee-2019-in-vitro-mycobacterial-growth-inhibition-in-south",
    title: "In vitro Mycobacterial Growth Inhibition in South Korean Adults With Latent TB Infection",
    authors: ["Lee", "H", "Kim", "J", "Kang", "YA", "et al."],
    year: 2019,
    journal: "Frontiers in immunology",
    issn: "1664-3224",
  },
  {
    slug: "rabeeah-2019-influenza-a-virus-interactions-with-complement-fac",
    title: "Influenza A Virus interactions with complement factor H",
    authors: ["Rabeeah", "I", "Kishore", "U", "Nal-Rogier", "B", "et al."],
    year: 2019,
    journal: "Access microbiology",
    volume: "1",
    issue: "1A",
    issn: "2516-8290",
  },
  {
    slug: "mangogna-2019-is-the-complement-protein-c1q-a-pro-or-anti-tum",
    title: "Is The Complement Protein C1q a Pro-  or Anti- tumorigenic Factor? Bioinformatics Analysis Involving Human Carcinomas",
    authors: ["Mangogna", "A", "Agostinis", "C", "Bonazza", "D", "et al."],
    year: 2019,
    journal: "Frontiers in immunology",
    volume: "10",
    issue: "MAY",
    issn: "1664-3224",
  },
  {
    slug: "ansari-2019-ischemia-reperfusion-injury-in-sickle-cell-disease",
    title: "Ischemia-Reperfusion Injury in Sickle Cell Disease: From Basics to Therapeutics",
    authors: ["Ansari", "J", "Gavins", "F"],
    year: 2019,
    journal: "The American journal of pathology",
    volume: "189",
    issue: "4",
    pages: "706 - 718",
    issn: "0002-9440",
  },
  {
    slug: "mccarthy-2019-maximum-overdrive-deegan-try-is-a-real-lyon-tamer",
    title: "Maximum overdrive: Deegan try is a real Lyon tamer [Eire Region]",
    authors: ["McCarthy R"],
    year: 2019,
    journal: "Sun (Plainfield, III",
    issn: "0307-2681",
  },
  {
    slug: "de-2019-multiancestry-genome-wide-association-study-of-lip",
    title: "Multiancestry Genome-Wide Association Study of Lipid Levels Incorporating Gene-Alcohol Interactions",
    authors: ["de Vries", "PS", "Brown", "MR", "Bentley", "AR", "et al."],
    year: 2019,
    journal: "American journal of epidemiology",
    volume: "188",
    issue: "6",
    pages: "1033 - 1054",
    issn: "0002-9262",
  },
  {
    slug: "evangelou-2019-new-alcohol-related-genes-suggest-shared-genetic-m",
    title: "New alcohol-related genes suggest shared genetic mechanisms with neuropsychiatric disorders",
    authors: ["Evangelou", "E", "Gao", "H", "Chu", "C", "et al."],
    year: 2019,
    journal: "Nature human behaviour",
    volume: "3",
    issue: "9",
    pages: "950-961",
    issn: "2397-3374",
  },
  {
    slug: "senchenkova-2019-novel-role-for-the-anxa1-fpr2-alx-signaling-axis-a",
    title: "Novel Role for the AnxA1-Fpr2/ALX Signaling Axis as a Key Regulator of Platelet Function to Promote Resolution of Inflammation",
    authors: ["Senchenkova", "EY", "Ansari", "J", "Becker F", "Vital", "et al."],
    year: 2019,
    journal: "Circulation",
    volume: "140",
    issue: "4",
    pages: "319 - 335",
    issn: "0009-7322",
  },
  {
    slug: "senchenkova-2019-novel-role-of-t-cells-and-il-6-interleukin-6-in",
    title: "Novel Role of T Cells and IL-6 (Interleukin-6) in Angiotensin II-Induced Microvascular Dysfunction. Hypertension",
    authors: ["Senchenkova", "EY", "Russell", "J", "Yildirim", "A", "et al."],
    year: 2019,
    journal: "Hypertension",
    volume: "73",
    issue: "4",
    pages: "829 - 838",
    issn: "0194-911X",
  },
  {
    slug: "tanner-2019-optimisation-harmonisation-and-standardisation-of",
    title: "Optimisation, harmonisation and standardisation of the direct mycobacterial growth inhibition assay using cryopreserved human peripheral blood mononuclear cells",
    authors: ["Tanner", "R", "Smith", "SG", "Van Meijgaarden", "KE", "et al."],
    year: 2019,
    journal: "Jornal of immunological methods",
    pages: "1 - 10",
    issn: "0022-1759",
  },
  {
    slug: "turner-2019-pathogenicity-factors-in-group-c-and-g-streptococc",
    title: "Pathogenicity Factors in Group C and G Streptococci",
    authors: ["Turner", "CE", "Bubba", "L", "Efstratiou", "A"],
    year: 2019,
    journal: "Microbiology spectrum",
    volume: "7",
    issue: "3",
    issn: "2165-0497",
  },
  {
    slug: "gunnarsson-2019-pharmacology-beyond-the-patient-the-environmenta",
    title: "Pharmacology beyond the patient - The environmental risks of human drugs",
    authors: ["Gunnarsson", "L", "Snape", "JR", "Verbruggen", "B", "et al."],
    year: 2019,
    journal: "Environment international",
    pages: "320- 332",
    issn: "0160-4120",
  },
  {
    slug: "preiss-2019-phenome-wide-association-analysis-of-ldl-cholester",
    title: "Phenome-wide association analysis of LDL-cholesterol lowering genetic variants in PCSK9",
    authors: ["Preiss", "D", "Swerdlow", "D", "Fatemifar", "G", "et al."],
    year: 2019,
    journal: "BMC cardiovascular disorders",
    volume: "19",
    issue: "1",
    issn: "1471-2261",
  },
  {
    slug: "barzegar-2019-potential-therapeutic-roles-of-stem-cells-in-ische",
    title: "Potential therapeutic roles of stem cells in ischemia-reperfusion injury",
    authors: ["Barzegar", "M", "Kaur", "G", "Gavins", "F", "et al."],
    year: 2019,
    journal: "International journal of molecular sciences",
    volume: "19",
    issue: "4",
    issn: "1661-6596",
  },
  {
    slug: "mangogna-2019-prognostic-implications-of-the-complement-protein",
    title: "Prognostic Implications of the Complement Protein C1q in Gliomas",
    authors: ["Mangogna", "A", "Belmonte", "B", "Agostinis", "C", "et al."],
    year: 2019,
    journal: "Frontiers in immunology",
    issn: "1664-3224",
  },
  {
    slug: "tanoue-2019-protecting-the-environment-from-psychoactive-drugs",
    title: "Protecting the environment from psychoactive drugs: Problems for regulators illustrated by the possible effects of tramadol on fish behaviour",
    authors: ["Tanoue", "R", "Margiotta-Casaluci", "L", "Huerta", "B", "et al."],
    year: 2019,
    journal: "The Science of the total environment",
    pages: "915 - 926",
    issn: "0048-9697",
  },
  {
    slug: "reen-2019-quorum-sensing-signaling-alters-virulence-potentia",
    title: "Quorum Sensing Signaling Alters Virulence Potential and Population Dynamics in Complex Microbiome-Host Interactomes",
    authors: ["Reen", "FJ", "Guitérrez-Barranquero", "JA", "McCarthy", "RR", "et al."],
    year: 2019,
    journal: "Frontiers in microbiology",
    issn: "1664-302X",
  },
  {
    slug: "decordova-2019-secretion-of-functionally-active-complement-factor",
    title: "Secretion of functionally active complement factor H related protein 5 (FHR5) by primary tumour cells derived from Glioblastoma Multiforme patients",
    authors: ["DeCordova", "S", "Abdelgany", "A", "Murugaiah", "V", "et al."],
    year: 2019,
    journal: "Immunobiology (1979)",
    volume: "224",
    issue: "5",
    pages: "625 - 631",
    issn: "0171-2985",
  },
  {
    slug: "kumar-2019-surfactant-protein-d-as-a-potential-biomarker-and",
    title: "Surfactant Protein D as a Potential Biomarker and Therapeutic Target in Ovarian Cancer",
    authors: ["Kumar", "J", "Murugaiah", "V", "Sotiriadis", "G", "et al."],
    year: 2019,
    journal: "Frontiers in oncology",
    issn: "2234-943X",
  },
  {
    slug: "pandit-2019-surfactant-protein-d-reverses-the-gene-signature-o",
    title: "Surfactant Protein D Reverses the Gene Signature of Transepithelial HIV-1 Passage and Restricts the Viral Transfer Across the Vaginal Barrier",
    authors: ["Pandit", "H", "Kale", "K", "Yamamoto", "H", "et al."],
    year: 2019,
    journal: "Frontiers in immunology",
    issn: "1664-3224",
  },
  {
    slug: "luykx-2019-t168-phenome-wide-and-genome-wide-analyses-of-qua",
    title: "T168. Phenome-Wide and Genome-Wide Analyses of Quality of  Life in Patients with Psychosis",
    authors: ["Luykx", "J", "Pazoki", "R", "Lin", "B", "et al."],
    year: 2019,
    journal: "Biological psychiatry (1969)",
    volume: "85",
    issue: "10",
    issn: "0006-3223",
  },
  {
    slug: "margiottacasaluci-2019-testing-the-translational-power-of-the-zebrafish",
    title: "Testing the Translational Power of the Zebrafish: An Interspecies Analysis of Responses to Cardiovascular Drugs",
    authors: ["Margiotta-Casaluci", "L", "Owen", "SF", "Rand-Weaver", "M", "et al."],
    year: 2019,
    journal: "Frontiers in pharmacology",
    issn: "1663-9812",
  },
  {
    slug: "mccarthy-2019-the-use-of-bacterial-polysaccharides-in-bioprintin",
    title: "The use of bacterial polysaccharides in bioprinting",
    authors: ["McCarthy", "RR", "Ullah", "MW", "Booth", "P", "et al."],
    year: 2019,
    journal: "Biotechnology advances",
    volume: "37",
    issue: "8",
    issn: "0734-9750",
  },
  {
    slug: "turner-2019-the-emergence-of-successful-streptococcus-pyogene",
    title: "The. Emergence of successful Streptococcus pyogenes lineages through convergent pathways of capsule loss and recombination directing high toxin expression",
    authors: ["Turner", "CE", "Holden", "MTG", "Blane", "B", "et al."],
    year: 2019,
    journal: "mBio",
    volume: "10",
    issue: "6",
    pages: "e02521-19",
    issn: "2161-2129",
  },
  {
    slug: "sharma-2019-toxic-shock-syndrome-toxin-1-evaluation-and-antibi",
    title: "Toxic Shock Syndrome Toxin 1 Evaluation and Antibiotic Impact in a Transgenic Model of Staphylococcal Soft Tissue Infection",
    authors: ["Sharma", "H", "Turner", "CE", "Siggins", "MK", "et al."],
    year: 2019,
    journal: "mSphere",
    volume: "4",
    issue: "5",
    pages: "e00665-19",
    issn: "2379-5042",
  },
  {
    slug: "agostinis-2019-transcriptomics-and-immunological-analyses-reveal",
    title: "Transcriptomics and Immunological Analyses Reveal a Pro-angiogenic and Anti-inflammatory Phenotype for Decidual Endothelial Cells",
    authors: ["Agostinis", "C", "Masat", "E", "Bossi", "F", "et al."],
    year: 2019,
    journal: "International Journal of molecular sciences",
    volume: "20",
    issue: "7",
    issn: "1661-6596",
  },
  {
    slug: "agostinis-2019-uterine-immunity-and-microbiota-a-shifting-paradi",
    title: "Uterine Immunity and microbiota: A shifting paradigm",
    authors: ["Agostinis", "C", "Mangogna", "A", "Bossi", "F", "et al."],
    year: 2019,
    journal: "Frontiers in immunology",
    issn: "1664-3224",
  },
];
