import type { PersonPublication } from "./publications-felicity-gavins";

export const anthonyTsolakiPublications: PersonPublication[] = [
  {
    slug: "d-souza-2025-ppe50-variants-as-novel-phylogeographic-signatures-of-host-p",
    type: "journal",
    typeLabel: "Journal article",
    title: "PPE50 variants as novel phylogeographic signatures of host-pathogen co-evolution in tuberculosis",
    authors: ["D'Souza, C", "Phelan, JE", "Gomez-Gonzalez, P-J", "Thorpe, J", "Clark, TG", "Tsolaki, AG"],
    year: 2025,
    journal: "Communications Biology",
    volume: "8",
    issue: "1",
    pages: "1 - 12",
    issn: "2399-3642",
    doi: "10.1038/s42003-025-08383-3",
    doiUrl: "http://dx.doi.org/10.1038/s42003-025-08383-3",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/30793",
  },
  {
    slug: "kishore-2025-differential-modulation-of-sars-cov-2-infection-by-complemen",
    type: "journal",
    typeLabel: "Journal article",
    title: "Differential Modulation of SARS-CoV-2 Infection by Complement Factor H and Properdin",
    authors: ["Kishore, U", "Varghese, PM", "Kumar, C", "Idicula-Thomas, S", "Mayora Neto, M", "Tsolaki, AG", "Ponanachan, P", "Masmoudi, K", "Al-Ramadi, B", "Vatish, M", "Madan, T", "Temperton, NJ", "Beirag, N"],
    year: 2025,
    journal: "Frontiers in Immunology",
    volume: "16",
    pages: "1 - 21",
    issn: "1664-3224",
    doi: "10.3389/fimmu.2025.1620229",
    doiUrl: "http://dx.doi.org/10.3389/fimmu.2025.1620229",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/30794",
  },
  {
    slug: "gomez-gonzalez-2023-functional-genetic-variation-in-pe-ppe-genes-contributes-to",
    type: "journal",
    typeLabel: "Journal article",
    title: "Functional genetic variation in pe/ppe genes contributes to diversity in Mycobacterium tuberculosis lineages and potential interactions with the human host",
    authors: ["Gómez-González, PJ", "Grabowska, AD", "Tientcheu, LD", "Tsolaki, AG", "Hibberd, ML", "Campino, S", "Phelan, JE", "Clark, TG"],
    year: 2023,
    journal: "Frontiers in Microbiology",
    volume: "14",
    pages: "1 - 12",
    issn: "1664-302X",
    doi: "10.3389/fmicb.2023.1244319",
    doiUrl: "http://dx.doi.org/10.3389/fmicb.2023.1244319",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/27341",
  },
  {
    slug: "d-souza-2022-the-pe-ppe-family-of-mycobacterium-tuberculosis-proteins-in",
    type: "journal",
    typeLabel: "Journal article",
    title: "The PE-PPE Family of Mycobacterium tuberculosis: Proteins in Disguise",
    authors: ["D'Souza, C", "Kishore, U", "Tsolaki, AG"],
    year: 2022,
    journal: "Immunobiology",
    volume: "228",
    issue: "2",
    pages: "1 - 18",
    issn: "0171-2985",
    doi: "10.1016/j.imbio.2022.152321",
    doiUrl: "http://dx.doi.org/10.1016/j.imbio.2022.152321",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/25969",
  },
  {
    slug: "jagatia-2021-the-role-of-complement-system-and-the-immune-response-to-tub",
    type: "journal",
    typeLabel: "Journal article",
    title: "The role of complement system and the immune response to tuberculosis infection",
    authors: ["Jagatia, H", "Tsolaki, AG"],
    year: 2021,
    journal: "Medicina (Lithuania)",
    volume: "57",
    issue: "2",
    pages: "1 - 18",
    issn: "1010-660X",
    doi: "10.3390/medicina57020084",
    doiUrl: "http://dx.doi.org/10.3390/medicina57020084",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/24042",
  },
  {
    slug: "decordova-2020-molecular-heterogeneity-and-immunosuppressive-microenvironme",
    type: "journal",
    typeLabel: "Journal article",
    title: "Molecular heterogeneity and immunosuppressive microenvironment in Glioblastoma",
    authors: ["DeCordova, S", "Shastri, A", "Tsolaki, AG", "Yasmin, H", "Klein, L", "Singh, SK", "Kishore, U"],
    year: 2020,
    journal: "Frontiers in Immunology",
    volume: "11",
    pages: "1 - 1",
    issn: "1664-3224",
    doi: "10.3389/fimmu.2020.01402",
    doiUrl: "http://dx.doi.org/10.3389/fimmu.2020.01402",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/20912",
  },
  {
    slug: "moses-2020-lepiniopsis-ternatensis-sap-stimulates-fibroblast-proliferat",
    type: "journal",
    typeLabel: "Journal article",
    title: "Lepiniopsis ternatensis sap stimulates fibroblast proliferation and down regulates macrophage TNF-α secretion",
    authors: ["Moses, RL", "Dally, J", "Lundy, FT", "Langat, M", "Kiapranis, R", "Tsolaki, AG", "Moseley, R", "Prescott, TAK"],
    year: 2020,
    journal: "Fitoterapia",
    volume: "141",
    issue: "March 2020",
    pages: "104478 - 104478",
    issn: "0367-326X",
    doi: "10.1016/j.fitote.2020.104478",
    doiUrl: "http://dx.doi.org/10.1016/j.fitote.2020.104478",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/20593",
  },
  {
    slug: "murugaiah-2020-complement-independent-modulation-of-influenza-a-virus-infec",
    type: "journal",
    typeLabel: "Journal article",
    title: "Complement-independent Modulation of Influenza A virus infection by Factor H",
    authors: ["Murugaiah, V", "Varghese, PM", "Saleh, SM", "Tsolaki, AG", "Alrokayan, SH", "Khan, HA", "Collison, KS", "Sim, RB", "Nal, B", "Al-Mohanna, FA", "Kishore, U"],
    year: 2020,
    journal: "Frontiers in Immunology",
    volume: "11",
    pages: "1 - 14",
    issn: "1664-3224",
    doi: "10.3389/fimmu.2020.00355",
    doiUrl: "http://dx.doi.org/10.3389/fimmu.2020.00355",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/20285",
  },
  {
    slug: "murugaiah-2020-collectins-innate-immune-pattern-recognition-molecules",
    type: "book-chapter",
    typeLabel: "Book chapter",
    title: "Collectins: Innate Immune Pattern Recognition Molecules",
    authors: ["Murugaiah, V", "Tsolaki, AG", "Kishore, U"],
    year: 2020,
    journal: "Advances in Experimental Medicine and Biology.",
    pages: "75 - 127",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/20592",
  },
  {
    slug: "varghese-2020-host-pathogen-interaction-in-covid-19-pathogenesis-potenti",
    type: "journal",
    typeLabel: "Journal article",
    title: "Host-pathogen interaction in COVID-19: Pathogenesis, potential therapeutics and vaccination strategies",
    authors: ["Varghese, PM", "Tsolaki, AG", "Yasmin, H", "Shastri, A", "Ferluga, J", "Vatish, M", "Madan, T", "Kishore, U"],
    year: 2020,
    journal: "Immunobiology",
    volume: "225",
    issue: "6",
    pages: "1 - 27",
    issn: "0171-2985",
    doi: "10.1016/j.imbio.2020.152008",
    doiUrl: "http://dx.doi.org/10.1016/j.imbio.2020.152008",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/21449",
  },
  {
    slug: "mehamood-2019-complement-dependent-and-independent-interaction-between-bov",
    type: "journal",
    typeLabel: "Journal article",
    title: "Complement dependent and independent interaction between bovine conglutinin and Mycobacterium bovis BCG: implications in bovine tuberculosis",
    authors: ["Mehamood, A", "Kouser, L", "Kaur, A", "Holmskov, U", "A-Ahdal, MN", "Sim, RB", "Kishore, U", "Tsolaki, AG"],
    year: 2019,
    journal: "Frontiers in Immunology",
    volume: "9",
    issue: "FEB",
    pages: "1 - 19",
    issn: "1664-3224",
    doi: "10.3389/fimmu.2018.03159",
    doiUrl: "http://dx.doi.org/10.3389/fimmu.2018.03159",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/17315",
  },
  {
    slug: "al-mozaini-2018-human-properdin-modulates-macrophage-mycobacterium-bovis-bc",
    type: "journal",
    typeLabel: "Journal article",
    title: "Human properdin modulates macrophage: Mycobacterium bovis BCG interaction via thrombospondin repeats (TSR) 4 and 5",
    authors: ["Al-Mozaini, M", "Tsolaki, AG", "Abdul-Aziz, M", "Abozaid, SM", "Al-Ahdal, MN", "Pathan, AA", "Murugaiah, V", "Makarov, EM", "Kaur, A", "Sim, RB", "Kishore, U", "Kouser, L"],
    year: 2018,
    journal: "Frontiers in Immunology",
    volume: "9",
    issue: "MAY",
    pages: "533",
    issn: "1664-3224",
    doi: "10.3389/fimmu.2018.00533",
    doiUrl: "http://dx.doi.org/10.3389/fimmu.2018.00533",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/15962",
  },
  {
    slug: "abdul-aziz-2016-complement-factor-h-interferes-with-mycobacterium-bovis-bcg",
    type: "journal",
    typeLabel: "Journal article",
    title: "Complement Factor H interferes with Mycobacterium bovis BCG entry into macrophages and modulates the pro-inflammatory cytokine response",
    authors: ["Abdul-Aziz, M", "Tsolaki, A", "Kouser, L", "Carroll, MV", "Al-Ahdal, MN", "Sim, RB", "Kishore, U"],
    year: 2016,
    journal: "Immunobiology",
    volume: "221",
    issue: "9",
    pages: "944 - 952",
    issn: "0722-6365",
    doi: "10.1016/j.imbio.2016.05.011",
    doiUrl: "http://dx.doi.org/10.1016/j.imbio.2016.05.011",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/12677",
  },
  {
    slug: "kouser-2016-a-recombinant-two-module-form-of-human-properdin-is-an-inhib",
    type: "journal",
    typeLabel: "Journal article",
    title: "A recombinant two-module form of human properdin is an inhibitor of the complement alternative pathway",
    authors: ["Kouser, L", "Abdul-Aziz, M", "Tsolaki, AG", "Singhal, D", "Schwaeble, WJ", "Urban, BC", "Khan, HA", "Sim, RD", "Kishore, U"],
    year: 2016,
    journal: "Molecular Immunology",
    volume: "73",
    pages: "76 - 87",
    issn: "0161-5890",
    doi: "10.1016/j.molimm.2016.03.005",
    doiUrl: "http://dx.doi.org/10.1016/j.molimm.2016.03.005",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/12361",
  },
  {
    slug: "pednekar-2016-analysis-of-the-interaction-between-globular-head-modules-of",
    type: "journal",
    typeLabel: "Journal article",
    title: "Analysis of the Interaction between Globular Head Modules of Human C1q and Its Candidate Receptor gC1qR",
    authors: ["Pednekar, L", "Pathan, AA", "Paudyal, B", "Tsolaki, AG", "Kaur, A", "Abozaid, SM", "Kouser, L", "Khan, HA", "Peerschke, EI", "Shamji, MH", "Stenbeck, G", "Ghebrehiwet, B", "Kishore, U"],
    year: 2016,
    journal: "Frontiers in Immunology",
    volume: "7",
    issue: "DEC",
    pages: "567",
    issn: "1664-3224",
    doi: "10.3389/fimmu.2016.00567",
    doiUrl: "http://dx.doi.org/10.3389/fimmu.2016.00567",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/13512",
  },
  {
    slug: "pondman-2016-pulmonary-surfactant-protein-sp-d-opsonises-carbon-nanotubes",
    type: "journal",
    typeLabel: "Journal article",
    title: "Pulmonary surfactant protein SP-D opsonises carbon nanotubes and augments their phagocytosis and subsequent pro-inflammatory immune response",
    authors: ["Pondman, KM", "Paudyal, B", "Sim, RB", "Kaur, A", "Kouser, L", "Tsolaki, AG", "Jones, LA", "Salvador-Morales, C", "Khan, HA", "ten Haken, B", "Stenbeck, G", "Kishore, U"],
    year: 2016,
    journal: "Nanoscale",
    volume: "9",
    issue: "3",
    pages: "1097 - 1109",
    issn: "2040-3364",
    doi: "10.1039/C6NR08807D",
    doiUrl: "http://dx.doi.org/10.1039/C6NR08807D",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/16965",
  },
  {
    slug: "pondman-2016-complement-deposition-on-nanoparticles-can-modulate-immune-r",
    type: "journal",
    typeLabel: "Journal article",
    title: "Complement Deposition on Nanoparticles Can Modulate Immune Responses by Macrophage, B and T Cells",
    authors: ["Pondman, KM", "Tsolaki, A", "Paudyal, B", "Shamji, M", "Switzer, A", "Pathan, A", "Abozaid, SM", "Haken, B", "Stenbeck, G", "Sim, RB", "Kishore, U"],
    year: 2016,
    journal: "Journal of Biomedical Nanotechnology",
    volume: "12",
    issue: "1",
    pages: "197 - 216",
    issn: "1550-7041",
    doi: "10.1166/jbn.2016.2124",
    doiUrl: "http://dx.doi.org/10.1166/jbn.2016.2124",
  },
  {
    slug: "deacon-2015-natural-ad-like-neuropathology-in-octodon-degus-impaired-bu",
    type: "journal",
    typeLabel: "Journal article",
    title: "Natural AD-like neuropathology in Octodon degus: Impaired burrowing and neuroinflammation",
    authors: ["Deacon, RMJ", "Altimiras, FJ", "Bazán-León, EA", "Pyarasani, RD", "Nachtigall, FM", "Santos, LS", "Tsolaki, AG", "Pednekar, L", "Kishore, U", "Biekofsky, RR", "Vásquez, RA", "Cogram, P"],
    year: 2015,
    journal: "Current Alzheimer Research",
    volume: "12",
    issue: "4",
    pages: "314 - 322",
    issn: "1567-2050",
    doi: "10.2174/1567205012666150324181652",
    doiUrl: "http://dx.doi.org/10.2174/1567205012666150324181652",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/11683",
  },
  {
    slug: "pondman-2015-innate-immune-humoral-factors-c1q-and-factor-h-with-differ",
    type: "journal",
    typeLabel: "Journal article",
    title: "Innate immune humoral factors, C1q and factor H, with differential pattern recognition properties, alter macrophage response to carbon nanotubes",
    authors: ["Pondman, KM", "Pednekar, L", "Paudyal, B", "Tsolaki, AG", "Kouser, L", "Khan, HA", "Shamji, MH", "ten Haken, B", "Stenbeck, G", "Sim, RB", "Kishore, U"],
    year: 2015,
    journal: "Nanomedicine: Nanotechnology, Biology, and Medicine",
    volume: "11",
    issue: "8",
    pages: "2109 - 2118",
    issn: "1549-9634",
    doi: "10.1016/j.nano.2015.06.009",
    doiUrl: "http://dx.doi.org/10.1016/j.nano.2015.06.009",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/12986",
  },
  {
    slug: "pondman-2014-complement-activation-by-carbon-nanotubes-and-its-influence",
    type: "journal",
    typeLabel: "Journal article",
    title: "Complement activation by carbon nanotubes and its influence on the phagocytosis and cytokine response by macrophages",
    authors: ["Pondman, KM", "Sobik, M", "Nayak, A", "Tsolaki, AG", "Jäkel, A", "Flahaut, E", "Hampel, S", "ten Haken, B", "Sim, RB", "Kishore, U"],
    year: 2014,
    journal: "Nanomedicine: Nanotechnology, Biology, and Medicine",
    volume: "10",
    issue: "6",
    pages: "1287 - 1299",
    issn: "1549-9634",
    doi: "10.1016/j.nano.2014.02.010",
    doiUrl: "http://dx.doi.org/10.1016/j.nano.2014.02.010",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/16664",
  },
  {
    slug: "tsolaki-2013-mycobacterium-tuberculosis-antigen-85b-and-esat-6-expressed",
    type: "journal",
    typeLabel: "Journal article",
    title: "Mycobacterium tuberculosis antigen 85B and ESAT-6 expressed as a recombinant fusion protein in Mycobacterium smegmatis elicits cell-mediated immune response in a murine vaccination model",
    authors: ["Tsolaki, AG", "Nagy, J", "Leiva, S", "Kishore, U", "Rosenkrands, I", "Robertson, BD"],
    year: 2013,
    journal: "Molecular Immunology",
    volume: "54",
    issue: "3-4",
    pages: "278 - 283",
    issn: "0161-5890",
    doi: "10.1016/j.molimm.2012.11.014",
    doiUrl: "http://dx.doi.org/10.1016/j.molimm.2012.11.014",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/8938",
  },
  {
    slug: "gupta-2012-mycobacterium-tuberculosis-immune-evasion-latency-and-reac",
    type: "journal",
    typeLabel: "Journal article",
    title: "Mycobacterium tuberculosis: Immune evasion, latency and reactivation",
    authors: ["Gupta, A", "Kaul, A", "Tsolaki, AG", "Kishore, U", "Bhakta, S"],
    year: 2012,
    journal: "Immunobiology",
    volume: "217",
    issue: "3",
    pages: "363 - 374",
    issn: "0171-2985",
    doi: "10.1016/j.imbio.2011.07.008",
    doiUrl: "http://dx.doi.org/10.1016/j.imbio.2011.07.008",
  },
  {
    slug: "nayak-2012-an-insight-into-the-diverse-roles-of-surfactant-proteins-sp",
    type: "journal",
    typeLabel: "Journal article",
    title: "An insight into the diverse roles of surfactant proteins, SP-A and SP-D in innate and adaptive immunity",
    authors: ["Nayak, A", "Dodagatta-Marri, E", "Tsolaki, AG", "Kishore, U"],
    year: 2012,
    journal: "Frontiers in Endocrinology",
    volume: "3",
    issue: "JUN",
    pages: "131",
    issn: "1664-3224",
    doi: "10.3389/fimmu.2012.00131",
    doiUrl: "http://dx.doi.org/10.3389/fimmu.2012.00131",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/7711",
  },
  {
    slug: "tsolaki-2009-innate-immune-recognition-in-tuberculosis-infection",
    type: "journal",
    typeLabel: "Journal article",
    title: "Innate immune recognition in tuberculosis infection",
    authors: ["Tsolaki, AG"],
    year: 2009,
    journal: "Advances in Experimental Medicine and Biology",
    volume: "653",
    pages: "185 - 197",
  },
  {
    slug: "tsolaki-2009-innate-immune-recognition-in-tuberculosis-infection-2",
    type: "book-chapter",
    typeLabel: "Book chapter",
    title: "Innate Immune Recognition in Tuberculosis Infection",
    authors: ["Tsolaki, AG"],
    year: 2009,
    journal: "Target pattern recognition in innate immunity.",
    pages: "185 - 197",
  },
  {
    slug: "chen-2007-deletion-targeted-multiplex-pcr-dtm-pcr-for-identification",
    type: "journal",
    typeLabel: "Journal article",
    title: "Deletion-targeted multiplex PCR (DTM-PCR) for identification of Beijing/W genotypes of Mycobacterium tuberculosis",
    authors: ["Chen, J", "Tsolaki, AG", "Shen, X", "Jiang, X", "Mei, J", "Gao, Q"],
    year: 2007,
    journal: "Tuberculosis",
    volume: "87",
    issue: "5",
    pages: "446 - 449",
    issn: "1472-9792",
    doi: "10.1016/j.tube.2007.05.014",
    doiUrl: "http://dx.doi.org/10.1016/j.tube.2007.05.014",
  },
  {
    slug: "tsolaki-2005-genomic-deletions-classify-the-beijing-w-strains-as-a-distin",
    type: "journal",
    typeLabel: "Journal article",
    title: "Genomic deletions classify the Beijing/W strains as a distinct genetic lineage of Mycobacterium tuberculosis",
    authors: ["Tsolaki, AG", "Gagneux, S", "Pym, AS", "Goguet de la Salmoniere, YO", "Kreiswirth, BN", "Soolingen, DV", "Small, PM"],
    year: 2005,
    journal: "Journal of Clinical Microbiology",
    volume: "43",
    issue: "7",
    pages: "3185 - 3191",
    issn: "0095-1137",
    doi: "10.1128/JCM.43.7.3185-3191.2005",
    doiUrl: "http://dx.doi.org/10.1128/JCM.43.7.3185-3191.2005",
  },
  {
    slug: "tsolaki-2004-functional-and-evolutionary-genomics-of-mycobacterium-tuberc",
    type: "journal",
    typeLabel: "Journal article",
    title: "Functional and evolutionary genomics of Mycobacterium tuberculosis: Insights from genomic deletions in 100 strains",
    authors: ["Tsolaki, A", "DeRiemer, K", "Enciso, JA", "Hirsh, AE"],
    year: 2004,
    journal: "Proceedings of the National Academy of Sciences",
    volume: "101",
    issue: "14",
    pages: "4865 - 4870",
    issn: "0027-8424",
    doi: "10.1073/pnas.0305634101",
    doiUrl: "http://dx.doi.org/10.1073/pnas.0305634101",
  },
  {
    slug: "tsolaki-2004-stable-association-between-strains-of-mycobacterium-tubercul",
    type: "journal",
    typeLabel: "Journal article",
    title: "Stable association between strains of Mycobacterium tuberculosis and their human host populations",
    authors: ["Tsolaki, A", "DeRiemer, K", "Feldman, MW", "Hirsh, AE"],
    year: 2004,
    journal: "Proceedings of the National Academy of Sciences",
    volume: "101",
    issue: "14",
    pages: "4871 - 4876",
    issn: "0027-8424",
    doi: "10.1073/pnas.0305627101",
    doiUrl: "http://dx.doi.org/10.1073/pnas.0305627101",
  },
  {
    slug: "mostowy-2003-the-in-vitro-evolution-of-bcg-vaccines",
    type: "journal",
    typeLabel: "Journal article",
    title: "The in vitro evolution of BCG vaccines",
    authors: ["MOSTOWY, S"],
    year: 2003,
    journal: "Vaccine",
    volume: "21",
    issue: "27-30",
    pages: "4270 - 4274",
    issn: "0264-410X",
    doi: "10.1016/s0264-410x(03)00484-5",
    doiUrl: "http://dx.doi.org/10.1016/s0264-410x(03)00484-5",
  },
  {
    slug: "rosenberg-2003-estimating-change-rates-of-genetic-markers-using-serial-samp",
    type: "journal",
    typeLabel: "Journal article",
    title: "Estimating change rates of genetic markers using serial samples: Applications to the transposon IS6110 in Mycobacterium tuberculosis",
    authors: ["Rosenberg, NA", "Tsolaki, A", "Tanaka, MM"],
    year: 2003,
    journal: "Theoretical Population Biology",
    volume: "63",
    issue: "4",
    pages: "347 - 363",
    issn: "0040-5809",
    doi: "10.1016/S0040-5809(03)00010-8",
    doiUrl: "http://dx.doi.org/10.1016/S0040-5809(03)00010-8",
  },
  {
    slug: "tsolaki-1999-oropharyngeal-samples-for-genotyping-and-monitoring-response",
    type: "journal",
    typeLabel: "Journal article",
    title: "Oropharyngeal samples for genotyping and monitoring response to treatment in AIDS patients with Pneumocystis carinii pneumonia",
    authors: ["Tsolaki, AG", "Miller, RF", "Wakefield, AE"],
    year: 1999,
    journal: "Journal of Medical Microbiology",
    volume: "48",
    issue: "10",
    pages: "897 - 905",
    issn: "0022-2615",
    doi: "10.1099/00222615-48-10-897",
    doiUrl: "http://dx.doi.org/10.1099/00222615-48-10-897",
  },
  {
    slug: "helweg-larsen-1998-clusters-of-pneumocystis-carinii-pneumonia-analysis-of-pers",
    type: "journal",
    typeLabel: "Journal article",
    title: "Clusters of Pneumocystis carinii pneumonia: analysis of person-to-person transmission by genotyping",
    authors: ["Helweg-Larsen, J", "Tsolaki, AG", "Miller, RF", "Lundgren, B", "Wakefield, AE"],
    year: 1998,
    journal: "QJM: an international journal of medicine",
    volume: "91",
    issue: "12",
    pages: "813 - 820",
    issn: "1460-2725",
    doi: "10.1093/qjmed/91.12.813",
    doiUrl: "http://dx.doi.org/10.1093/qjmed/91.12.813",
  },
  {
    slug: "tsolaki-1998-pre-aids-era-isolates-ofpneumocystis-cariniif-sp-hominis-h",
    type: "journal",
    typeLabel: "Journal article",
    title: "Pre-AIDS Era Isolates ofPneumocystis cariniif. sp.hominis: High Genotypic Similarity with Contemporary Isolates",
    authors: ["Tsolaki, AG", "Beckers, P", "Wakefield, AE"],
    year: 1998,
    journal: "Journal of Clinical Microbiology",
    volume: "36",
    issue: "1",
    pages: "90 - 93",
    issn: "0095-1137",
    doi: "10.1128/jcm.36.1.90-93.1998",
    doiUrl: "http://dx.doi.org/10.1128/jcm.36.1.90-93.1998",
  },
  {
    slug: "tsolaki-1996-genetic-diversity-at-the-internal-transcribed-spacer-regions",
    type: "journal",
    typeLabel: "Journal article",
    title: "Genetic Diversity at the Internal Transcribed Spacer Regions of the rRNA Operon among Isolates of Pneumocystis carinii from AIDS Patients with Recurrent Pneumonia",
    authors: ["Tsolaki, AG", "Miller, RF", "Underwood, AP", "Banerji, S", "Wakefield, AE"],
    year: 1996,
    journal: "Journal of Infectious Diseases",
    volume: "174",
    issue: "1",
    pages: "141 - 156",
    issn: "0022-1899",
    doi: "10.1093/infdis/174.1.141",
    doiUrl: "http://dx.doi.org/10.1093/infdis/174.1.141",
  },
];
