import type { PersonPublication } from "./publications-felicity-gavins";

export const suLingLiPublications: PersonPublication[] = [
  {
    slug: "li-2017-egr2-and-3-inhibit-t-bet-mediated-ifn-production-in-t-cell",
    type: "journal",
    typeLabel: "Journal article",
    title: "Egr2 and 3 Inhibit T-bet-Mediated IFN-γ Production in T Cells.",
    authors: ["Li, S"],
    year: 2017,
    journal: "Journal of Immunology",
    volume: "198",
    issue: "11",
    pages: "4394 - 4402",
    issn: "0022-1767",
    doi: "10.4049/jimmunol.1602010",
    doiUrl: "http://dx.doi.org/10.4049/jimmunol.1602010",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/14683",
  },
  {
    slug: "miao-2017-egr2-and-3-control-adaptive-immune-responses-by-temporally-u",
    type: "journal",
    typeLabel: "Journal article",
    title: "Egr2 and 3 control adaptive immune responses by temporally uncoupling expansion from T cell differentiation",
    authors: ["Miao, T", "Symonds, ALJ", "Singh, R", "Symonds, JD", "Ogbe, A", "Omodho, B", "Zhu, B", "Li, S", "Wang, P"],
    year: 2017,
    journal: "Journal of Experimental Medicine",
    volume: "214",
    issue: "6",
    pages: "1787 - 1787",
    issn: "0022-1007",
    doi: "10.1084/jem.20160553",
    doiUrl: "http://dx.doi.org/10.1084/jem.20160553",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/14505",
  },
  {
    slug: "liu-2012-il-2-engineered-nano-apc-effectively-activates-viral-antigen",
    type: "journal",
    typeLabel: "Journal article",
    title: "IL-2-engineered nano-APC effectively activates viral antigen-mediated T cell responses from chronic hepatitis B virus-infected patients",
    authors: ["Liu, M", "Miao, T", "Zhu, H", "Symonds, ALJ", "Li, L", "Schurich, A", "Maini, MK", "Zhang, J", "Kennedy, PTF", "Li, S", "Wang, P"],
    year: 2012,
    journal: "Journal of Immunology",
    volume: "188",
    issue: "3",
    pages: "1534 - 1543",
    issn: "0022-1767",
    doi: "10.4049/jimmunol.1102709",
    doiUrl: "http://dx.doi.org/10.4049/jimmunol.1102709",
  },
  {
    slug: "liu-2012-il-2engineered-nano-apc-effectively-activates-viral-antigen",
    type: "journal",
    typeLabel: "Journal article",
    title: "IL-2–engineered nano-APC effectively activates viral antigen-mediated T cell responses from chronic Hepatitis B virus-infected patients",
    authors: ["Liu, M", "Miao, T", "Zhu, H", "Symonds, ALJ", "Li, L", "Schurich, A", "Maini, MK", "Zhang, J", "Kennedy, PTF", "Li, S", "Wang, P"],
    year: 2012,
    journal: "Journal of Immunology",
    volume: "188",
    issue: "3",
    pages: "1534 - 1543",
    issn: "0022-1767",
    doi: "10.4049/​jimmunol.1102709",
    doiUrl: "http://dx.doi.org/10.4049/​jimmunol.1102709",
  },
  {
    slug: "li-2011-early-growth-response-gene-2-egr-2-regulates-the-developme",
    type: "journal",
    typeLabel: "Journal article",
    title: "Early growth response gene-2 (Egr-2) regulates the development of B and T cells",
    authors: ["Li, S", "Symonds, ALJ", "Zhu, B", "Liu, M", "Raymond, M", "Miao, T", "Wang, P"],
    year: 2011,
    journal: "PLoS ONE",
    volume: "6",
    issue: "4",
    pages: "e18498 - e18498",
    issn: "1932-6203",
    doi: "10.1371/journal.pone.0018498",
    doiUrl: "http://dx.doi.org/10.1371/journal.pone.0018498",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/5509",
  },
  {
    slug: "sofra-2009-antigenloaded-er-microsomes-from-apc-induce-potent-immune-r",
    type: "journal",
    typeLabel: "Journal article",
    title: "Antigen‐loaded ER microsomes from APC induce potent immune responses against viral infection",
    authors: ["Sofra, V", "Mansour, S", "Liu, M", "Gao, B", "Primpidou, E", "Wang, P", "Li, S"],
    year: 2009,
    journal: "European Journal of Immunology",
    volume: "39",
    issue: "1",
    pages: "85 - 95",
    issn: "0014-2980",
    doi: "10.1002/eji.200838443",
    doiUrl: "http://dx.doi.org/10.1002/eji.200838443",
  },
  {
    slug: "khalid-2008-maxlab-a-novel-application-for-the-cross-comparison-and-int",
    type: "journal",
    typeLabel: "Journal article",
    title: "MaXlab: A novel application for the cross comparison and integration of biological signatures from microarray studies",
    authors: ["Khalid, S", "Khan, M", "Gorle, CB", "Fraser, K", "Wang, P", "Liu, X", "Li, S"],
    year: 2008,
    journal: "In Silico Biology",
    volume: "8",
    issue: "3-4",
    pages: "363 - 376",
    issn: "1386-6338",
    doi: "10.3233/isb-00364",
    doiUrl: "http://dx.doi.org/10.3233/isb-00364",
  },
  {
    slug: "khalid-2008-designing-customised-gene-expression-arrays-based-on-specifi",
    type: "journal",
    typeLabel: "Journal article",
    title: "Designing customised gene expression arrays based on specific biological questions or functions",
    authors: ["Khalid, S", "Grazio, D", "Wang, P", "Liu, X", "Li, S"],
    year: 2008,
    journal: "Journal of Integrated Design & Process Science",
    volume: "11",
    issue: "3",
    pages: "67 - 81",
    issn: "1092-0617",
  },
  {
    slug: "zhu-2008-early-growth-response-gene-2-egr-2-controls-the-self-toler",
    type: "journal",
    typeLabel: "Journal article",
    title: "Early growth response gene 2 (Egr-2) controls the self-tolerance of T cells and prevents the development of lupuslike autoimmune disease",
    authors: ["Zhu, B", "Symonds, AL", "Martin, JE", "Kioussis, D", "Wraith, DC", "Li, S", "Wang, P"],
    year: 2008,
    journal: "J Exp Med",
    volume: "205",
    issue: "10",
    pages: "2295 - 2307",
    issn: "0022-1007",
    doi: "10.1084/jem.20080187",
    doiUrl: "http://dx.doi.org/10.1084/jem.20080187",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/8582",
  },
  {
    slug: "khalid-2007-cida-an-integrated-software-for-the-design-characterisatio",
    type: "journal",
    typeLabel: "Journal article",
    title: "CIDA: an integrated software for the design, characterisation and global comparison of microarrays",
    authors: ["Khalid, S", "Khan, M", "Symonds, A", "Fraser, K", "Wang, P", "Liu, X", "LI, S"],
    year: 2007,
    journal: "J. integrated Bioinformatics",
    volume: "4",
    issue: "3",
    pages: "78",
  },
  {
    slug: "wang-2007-genetic-models-a-powerful-technology-for-the-study-of-cance",
    type: "book-chapter",
    typeLabel: "Book chapter",
    title: "Genetic Models: A Powerful Technology for the Study of Cancer",
    authors: ["Wang, P", "Li, S"],
    year: 2007,
    journal: "The Cancer Handbook.",
  },
  {
    slug: "anderson-2006-persistent-antigenic-stimulation-alters-the-transcription-pr",
    type: "journal",
    typeLabel: "Journal article",
    title: "Persistent antigenic stimulation alters the transcription program in T cells, resulting in antigen-specific tolerance",
    authors: ["Anderson, PO", "Manzo, BA", "Sundstedt, A", "Minaee, S", "Symonds, A", "Khalid, S", "Rodriguez-Cabezas, ME", "Nicolson, K", "Li, S", "Wraith, DC", "Wang, P"],
    year: 2006,
    journal: "European Journal of Immunology",
    volume: "36",
    issue: "6",
    pages: "1374 - 1385",
    issn: "0014-2980",
    doi: "10.1002/eji.200635883",
    doiUrl: "http://dx.doi.org/10.1002/eji.200635883",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/5677",
  },
  {
    slug: "khalid-2006-analysing-microarray-data-using-the-multi-functional-immune",
    type: "journal",
    typeLabel: "Journal article",
    title: "Analysing Microarray Data using the Multi-functional Immune Ontounlogiser",
    authors: ["Khalid, S", "Fraser, K", "Khan, M", "Wang, P", "Liu, X", "LI, S"],
    year: 2006,
    journal: "J. integrated Bioinformatics",
    volume: "3",
    pages: "25",
  },
  {
    slug: "khalid-2006-application-of-bioinformatics-in-the-design-of-gene-expressi",
    type: "conference",
    typeLabel: "Conference paper",
    title: "Application of Bioinformatics in the Design of Gene Expression Microarrays",
    authors: ["Khalid, S", "Khan, M", "Wang, P", "Liu, X", "Li, S"],
    year: 2006,
  },
  {
    slug: "paulsson-2006-the-double-lysine-motif-of-tapasin-is-a-retrieval-signal-for",
    type: "journal",
    typeLabel: "Journal article",
    title: "The double lysine motif of tapasin is a retrieval signal for retention of unstable MHC class I molecules in the endoplasmic reticulum",
    authors: ["Paulsson, KM", "Jevon, M", "Anderson, P", "Li, S", "Wang, P"],
    year: 2006,
    journal: "The Journal of Immunology",
    volume: "176",
    issue: "12",
    pages: "7482 - 7488",
    issn: "0022-1767",
    doi: "10.4049/jimmunol.176.12.7482",
    doiUrl: "http://dx.doi.org/10.4049/jimmunol.176.12.7482",
  },
  {
    slug: "anderson-2005-il-2-overcomes-the-unresponsiveness-but-fails-to-reverse-the",
    type: "journal",
    typeLabel: "Journal article",
    title: "IL-2 Overcomes the Unresponsiveness but Fails to Reverse the Regulatory Function of Antigen-Induced T Regulatory Cells",
    authors: ["Anderson, PO", "Sundstedt, A", "Yazici, Z", "Minaee, S", "Woolf, R", "Nicolson, K", "Whitley, N", "Li, L", "Li, S", "Wraith, DC", "Wang, P"],
    year: 2005,
    journal: "The Journal of Immunology",
    volume: "174",
    issue: "1",
    pages: "310 - 319",
    issn: "0022-1767",
    doi: "10.4049/jimmunol.174.1.310",
    doiUrl: "http://dx.doi.org/10.4049/jimmunol.174.1.310",
  },
  {
    slug: "li-2004-insulin-induces-socs-6-expression-and-its-binding-to-the-p85",
    type: "journal",
    typeLabel: "Journal article",
    title: "Insulin Induces SOCS-6 Expression and Its Binding to the p85 Monomer of Phosphoinositide 3-Kinase, Resulting in Improvement in Glucose Metabolism",
    authors: ["Li, L", "Grønning, LM", "Anderson, PO", "Li, S", "Edvardsen, K", "Johnston, J", "Kioussis, D", "Shepherd, PR", "Wang, P"],
    year: 2004,
    journal: "Journal of Biological Chemistry",
    volume: "279",
    issue: "33",
    pages: "34107 - 34114",
    issn: "0021-9258",
    doi: "10.1074/jbc.m312672200",
    doiUrl: "http://dx.doi.org/10.1074/jbc.m312672200",
  },
  {
    slug: "anderson-2003-differential-activation-of-signal-transducer-and-activator-o",
    type: "journal",
    typeLabel: "Journal article",
    title: "Differential activation of signal transducer and activator of transcription (STAT)3 and STAT5 and induction of suppressors of cytokine signalling in Th1 and Th2 cells",
    authors: ["Anderson, P"],
    year: 2003,
    journal: "International Immunology",
    volume: "15",
    issue: "11",
    pages: "1309 - 1317",
    issn: "0953-8178",
    doi: "10.1093/intimm/dxg130",
    doiUrl: "http://dx.doi.org/10.1093/intimm/dxg130",
  },
  {
    slug: "anderson-2003-differential-activation-of-signal-transducers-and-activators",
    type: "journal",
    typeLabel: "Journal article",
    title: "Differential Activation of Signal Transducers and Activators of Transcription -3 and –5 (STAT)s and Induction of Suppressors Of Cytokine Signaling (SOCS) in T helper (Th) 1 and Th2 cells",
    authors: ["Anderson, P", "Sundstedt, A", "Massey, E", "LI, S", "Wraith, D", "Wang, P"],
    year: 2003,
    journal: "Int Immunol.",
    volume: "15",
    issue: "11",
    pages: "1309 - 1317",
  },
  {
    slug: "chen-2003-functional-association-of-cytokine-induced-sh2-protein-cis",
    type: "journal",
    typeLabel: "Journal article",
    title: "Functional association of cytokine-induced SH2 protein (CIS) and protein kinase C in activated T cells",
    authors: ["Chen, S", "Anderson, PO", "Li, L", "Sjögren, HO", "Wang, P", "Li, S"],
    year: 2003,
    journal: "International Immunology",
    volume: "15",
    issue: "3",
    pages: "403 - 409",
    issn: "1460-2377",
    doi: "10.1093/intimm/dxg039",
    doiUrl: "http://dx.doi.org/10.1093/intimm/dxg039",
  },
  {
    slug: "paulsson-2002-association-of-tapasin-and-copi-provides-a-mechanism-for-the",
    type: "journal",
    typeLabel: "Journal article",
    title: "Association of Tapasin and COPI Provides a Mechanism for the Retrograde Transport of Major Histocompatibility Complex (MHC) Class I Molecules from the Golgi Complex to the Endoplasmic Reticulum",
    authors: ["Paulsson, KM", "Kleijmeer, MJ", "Griffith, J", "Jevon, M", "Chen, S", "Anderson, PO", "Sjögren, H-O", "Li, S", "Wang, P"],
    year: 2002,
    journal: "Journal of Biological Chemistry",
    volume: "277",
    issue: "21",
    pages: "18266 - 18271",
    issn: "0021-9258",
    doi: "10.1074/jbc.m201388200",
    doiUrl: "http://dx.doi.org/10.1074/jbc.m201388200",
  },
  {
    slug: "turnquist-2002-calreticulin-binds-to-the-1-domain-of-mhc-class-i-independe",
    type: "journal",
    typeLabel: "Journal article",
    title: "Calreticulin binds to the α1 domain of MHC class I independently of tapasin",
    authors: ["Turnquist, HR", "Vargas, SE", "McIlhaney, MM", "Li, S", "Wang, P", "Solheim, JC"],
    year: 2002,
    journal: "Tissue Antigens",
    volume: "59",
    issue: "1",
    pages: "18 - 24",
    issn: "0001-2815",
    doi: "10.1034/j.1399-0039.2002.590104.x",
    doiUrl: "http://dx.doi.org/10.1034/j.1399-0039.2002.590104.x",
  },
  {
    slug: "paulsson-2001-distinct-differences-in-association-of-mhc-class-i-with-endo",
    type: "journal",
    typeLabel: "Journal article",
    title: "Distinct differences in association of MHC class I with endoplasmic reticulum proteins in wild-type, and β2-microglobulin- and TAP-deficient cell lines",
    authors: ["Paulsson, KM", "Wang, P", "Anderson, PO", "Chen, S", "Pettersson, RF", "Li, S"],
    year: 2001,
    journal: "International Immunology",
    volume: "13",
    issue: "8",
    pages: "101 - 111",
    issn: "1460-2377",
    doi: "10.1093/intimm/13.8.1063",
    doiUrl: "http://dx.doi.org/10.1093/intimm/13.8.1063",
  },
  {
    slug: "paulsson-2001-assembly-of-tapasin-associated-mhc-class-i-in-the-absence-of",
    type: "journal",
    typeLabel: "Journal article",
    title: "Assembly of tapasin-associated MHC class I in the absence of the transporter associated with antigen processing (TAP)",
    authors: ["Paulsson, KM", "Chen, S", "Sjögren, HO", "Wang, P", "Li, S"],
    year: 2001,
    journal: "International Immunology",
    volume: "13",
    issue: "1",
    pages: "23 - 37",
    issn: "1460-2377",
    doi: "10.1093/intimm/13.1.23",
    doiUrl: "http://dx.doi.org/10.1093/intimm/13.1.23",
  },
  {
    slug: "su-2001-the-tripeptide-glycyl-prolyl-glycine-amide-does-not-affect-t",
    type: "journal",
    typeLabel: "Journal article",
    title: "The tripeptide glycyl-prolyl-glycine amide does not affect the early steps of the human immunodeficiency virus type 1 replication",
    authors: ["Su, J", "Naghavi, MH", "Jejcic, A", "Horal, P", "Furuta, Y", "Wu, YP", "Li, SL", "Hall, WW", "Goobar-Larsson, L", "Svennerholm, B", "Vahlne, A"],
    year: 2001,
    journal: "Journal of Human Virology",
    volume: "4",
    issue: "1",
    pages: "8 - 15",
    issn: "1090-9508",
  },
  {
    slug: "turnquist-2001-a-region-of-tapasin-that-affects-ld-binding-and-assembly",
    type: "journal",
    typeLabel: "Journal article",
    title: "A Region of Tapasin That Affects Ld Binding and Assembly",
    authors: ["Turnquist, HR", "Vargas, SE", "Reber, AJ", "McIlhaney, MM", "Li, S", "Wang, P", "Sanderson, SD", "Gubler, B", "van Endert, P", "Solheim, JC"],
    year: 2001,
    journal: "The Journal of Immunology",
    volume: "167",
    issue: "8",
    pages: "4443 - 4449",
    issn: "0022-1767",
    doi: "10.4049/jimmunol.167.8.4443",
    doiUrl: "http://dx.doi.org/10.4049/jimmunol.167.8.4443",
  },
  {
    slug: "wang-2001-inhibition-of-the-transcription-factors-ap-1-and-nf-b-in-cd",
    type: "journal",
    typeLabel: "Journal article",
    title: "Inhibition of the transcription factors AP-1 and NF-κB in CD4 T cells by peroxisome proliferator-activated receptor γ ligands",
    authors: ["Wang, P", "Anderson, PO", "Chen, S", "Paulsson, KM", "Sjögren, H-O", "Li, S"],
    year: 2001,
    journal: "International Immunopharmacology",
    volume: "1",
    issue: "4",
    pages: "803 - 812",
    issn: "1567-5769",
    doi: "10.1016/s1567-5769(01)00015-7",
    doiUrl: "http://dx.doi.org/10.1016/s1567-5769(01)00015-7",
  },
  {
    slug: "li-2000-cytokine-induced-src-homology-2-protein-cis-promotes-t-cel",
    type: "journal",
    typeLabel: "Journal article",
    title: "Cytokine-induced Src homology 2 protein (CIS) promotes T cell receptor-mediated proliferation and prolongs survival of activated T cells",
    authors: ["Li, S", "Chen, S", "Xu, X", "Sundstedt, A", "Paulsson, KM", "Anderson, P", "Karlsson, S", "Sjögren, HO", "Wang, P"],
    year: 2000,
    journal: "Journal of Experimental Medicine",
    volume: "191",
    issue: "6",
    pages: "985 - 994",
    issn: "0022-1007",
    doi: "10.1084/jem.191.6.985",
    doiUrl: "http://dx.doi.org/10.1084/jem.191.6.985",
    openAccessUrl: "http://bura.brunel.ac.uk/handle/2438/8586",
  },
  {
    slug: "li-2000-tapasin-is-required-for-efficient-peptide-binding-to-transpo",
    type: "journal",
    typeLabel: "Journal article",
    title: "Tapasin Is Required for Efficient Peptide Binding to Transporter Associated with Antigen Processing",
    authors: ["Li, S", "Paulsson, KM", "Chen, S", "Sjögren, H-O", "Wang, P"],
    year: 2000,
    journal: "Journal of Biological Chemistry",
    volume: "275",
    issue: "3",
    pages: "1581 - 1586",
    issn: "0021-9258",
    doi: "10.1074/jbc.275.3.1581",
    doiUrl: "http://dx.doi.org/10.1074/jbc.275.3.1581",
  },
  {
    slug: "li-1999-peptide-bound-major-histocompatibility-complex-class-i-molec",
    type: "journal",
    typeLabel: "Journal article",
    title: "Peptide-bound Major Histocompatibility Complex Class I Molecules Associate with Tapasin before Dissociation from Transporter Associated with Antigen Processing",
    authors: ["Li, S", "Paulsson, KM", "Sjögren, H-O", "Wang, P"],
    year: 1999,
    journal: "Journal of Biological Chemistry",
    volume: "274",
    issue: "13",
    pages: "8649 - 8654",
    issn: "0021-9258",
    doi: "10.1074/jbc.274.13.8649",
    doiUrl: "http://dx.doi.org/10.1074/jbc.274.13.8649",
  },
  {
    slug: "li-1997-cloning-and-functional-characterization-of-a-subunit-of-the",
    type: "journal",
    typeLabel: "Journal article",
    title: "Cloning and functional characterization of a subunit of the transporter associated with antigen processing",
    authors: ["Li, S", "Sjögren, H-O", "Hellman, U", "Pettersson, RF", "Wang, P"],
    year: 1997,
    journal: "Proceedings of the National Academy of Sciences",
    volume: "94",
    issue: "16",
    pages: "8708 - 8713",
    issn: "0027-8424",
    doi: "10.1073/pnas.94.16.8708",
    doiUrl: "http://dx.doi.org/10.1073/pnas.94.16.8708",
  },
  {
    slug: "li-1995-thymic-immunopathology-and-progression-of-sivsm-infection-in",
    type: "journal",
    typeLabel: "Journal article",
    title: "Thymic Immunopathology and Progression of SIVsm Infection in Cynomolgus Monkeys",
    authors: ["Li, S-L", "Kaaya, EE", "Ord??nez, C", "Ekman, M", "Feichtinger, H", "Putkonen, P", "B??ttiger, D", "Biberfeld, G", "Biberfeld, P"],
    year: 1995,
    journal: "Journal of Acquired Immune Deficiency Syndromes & Human Retrovirology",
    volume: "9",
    issue: "1",
    issn: "1077-9450",
    doi: "10.1097/00042560-199505010-00001",
    doiUrl: "http://dx.doi.org/10.1097/00042560-199505010-00001",
  },
  {
    slug: "putkonen-1995-longterm-protection-against-sivinduced-disease-in-macaques",
    type: "journal",
    typeLabel: "Journal article",
    title: "Long–term protection against SIV–induced disease in macaques vaccinated with a live attenuated HIV–2 vaccine",
    authors: ["Putkonen, P", "Walther, L", "Zhang, Y-J", "Li, S-L", "Nilsson, C", "Albert, J", "Biberfeld, P", "Thorstensson, R", "Biberfeld, G"],
    year: 1995,
    journal: "Nature Medicine",
    volume: "1",
    issue: "9",
    pages: "914 - 918",
    issn: "1078-8956",
    doi: "10.1038/nm0995-914",
    doiUrl: "http://dx.doi.org/10.1038/nm0995-914",
  },
  {
    slug: "li-1994-dna-of-lymphomaassociated-herpesvirus-hvmf1-in-sivinfect",
    type: "journal",
    typeLabel: "Journal article",
    title: "DNA of lymphoma‐associated herpesvirus (HVMF1) in SIV‐infected monkeys (Macaca fascicularis) shows homologies to EBNA‐1, ‐2 and ‐5 genes",
    authors: ["Li, SL", "Biberfeld, P", "Ernberg, I"],
    year: 1994,
    journal: "International Journal of Cancer",
    volume: "59",
    issue: "2",
    pages: "287 - 295",
    issn: "0020-7136",
    doi: "10.1002/ijc.2910590223",
    doiUrl: "http://dx.doi.org/10.1002/ijc.2910590223",
  },
  {
    slug: "feichinger-1993-pathology-of-the-lymphoid-system-in-cynomolgus-monkeys-infec",
    type: "book-chapter",
    typeLabel: "Book chapter",
    title: "Pathology of the lymphoid system in cynomolgus monkeys infected with SIVsm",
    authors: ["Feichinger, H", "Kaaya, E", "LI, S", "Putkonen, P", "Ekman, M", "Mandache, E", "Grunewald, K", "Biberfeld, G", "Biberfeld, P"],
    year: 1993,
    journal: "Animal Models of HIV and Other Retroviral infection.",
    pages: "49 - 63",
  },
  {
    slug: "kaaya-1993-accessory-cells-and-macrophages-in-the-histopathology-of-siv",
    type: "journal",
    typeLabel: "Journal article",
    title: "Accessory cells and macrophages in the histopathology of SIVsm-infected cynomolgus monkeys",
    authors: ["Kaaya, E", "Li, S-L", "Feichtinger, H", "Stahmer, I", "Putkonen, P", "Mandache, E", "Mgaya, E", "Biberfeld, G", "Biberfeld, P"],
    year: 1993,
    journal: "Research in Virology",
    volume: "144",
    issue: "C",
    pages: "81 - 92",
    issn: "0923-2516",
    doi: "10.1016/s0923-2516(06)80016-6",
    doiUrl: "http://dx.doi.org/10.1016/s0923-2516(06)80016-6",
  },
  {
    slug: "li-1993-immunohistochemical-distribution-of-leucocyte-antigens-in-ly",
    type: "journal",
    typeLabel: "Journal article",
    title: "Immunohistochemical distribution of leucocyte antigens in lymphoid tissues of cynomolgus monkeys (Macaca fascicularis)",
    authors: ["Li, S", "Kaaya, E", "Feichtinger, H", "Biberfeld, G", "Biberfeld, P"],
    year: 1993,
    journal: "Journal of Medical Primatology",
    volume: "22",
    issue: "5",
    pages: "285 - 293",
    issn: "0047-2565",
    doi: "10.1111/j.1600-0684.1993.tb00673.x",
    doiUrl: "http://dx.doi.org/10.1111/j.1600-0684.1993.tb00673.x",
  },
  {
    slug: "li-1993-expression-of-epsteinbarrvirusrelated-nuclear-antigens-an",
    type: "journal",
    typeLabel: "Journal article",
    title: "Expression of epstein‐barr‐virus‐related nuclear antigens and B‐cell markers in lymphomas of SIV‐immunosuppressed monkeys",
    authors: ["Li, SL", "Feichtinger, H", "Kaaya, E", "Biberfeld, P", "Migliorini, P", "Putkonen, P", "Biberfeld, G", "Middeldorp, JM", "Ernberg, I"],
    year: 1993,
    journal: "International Journal of Cancer",
    volume: "55",
    issue: "4",
    pages: "609 - 615",
    issn: "0020-7136",
    doi: "10.1002/ijc.2910550416",
    doiUrl: "http://dx.doi.org/10.1002/ijc.2910550416",
  },
  {
    slug: "bottiger-1992-long-term-tolerance-and-efficacy-of-3-azidothymidine-and-3",
    type: "journal",
    typeLabel: "Journal article",
    title: "Long-term tolerance and efficacy of 3'-azidothymidine and 3'-fluorothymidine treatment of asymptomatic monkeys infected with simian immunodeficiency virus",
    authors: ["Böttiger, D", "Ståhle, L", "Li, SL", "Oberg, B"],
    year: 1992,
    journal: "Antimicrobial Agents and Chemotherapy",
    volume: "36",
    issue: "8",
    pages: "1770 - 1772",
    issn: "0066-4804",
    doi: "10.1128/aac.36.8.1770",
    doiUrl: "http://dx.doi.org/10.1128/aac.36.8.1770",
  },
  {
    slug: "feichtinger-1992-a-monkey-model-for-epstein-barr-virus-associated-lymphomagen",
    type: "journal",
    typeLabel: "Journal article",
    title: "A monkey model for Epstein Barr virus-associated lymphomagenesis in human acquired immunodeficiency syndrome.",
    authors: ["Feichtinger, H", "Li, SL", "Kaaya, E", "Putkonen, P", "Grünewald, K", "Weyrer, K", "Böttiger, D", "Ernberg, I", "Linde, A", "Biberfeld, G"],
    year: 1992,
    journal: "The Journal of experimental medicine",
    volume: "176",
    issue: "1",
    pages: "281 - 286",
    issn: "0022-1007",
    doi: "10.1084/jem.176.1.281",
    doiUrl: "http://dx.doi.org/10.1084/jem.176.1.281",
  },
  {
    slug: "feichtinger-1992-malignant-lymphoma-associated-with-human-aids-and-with-siv-i",
    type: "journal",
    typeLabel: "Journal article",
    title: "Malignant Lymphoma Associated with Human AIDS and with SIV-Induced Immunodeficiency in Macaques",
    authors: ["Feichtinger, H", "Kaaya, E", "Putkonen, P", "LI, S-L", "Ekman, M", "Gendelman, R", "Biberfeld, G", "Biberfeld, P"],
    year: 1992,
    journal: "AIDS Research and Human Retroviruses",
    volume: "8",
    issue: "3",
    pages: "339 - 348",
    issn: "0889-2229",
    doi: "10.1089/aid.1992.8.339",
    doiUrl: "http://dx.doi.org/10.1089/aid.1992.8.339",
  },
  {
    slug: "putkonen-1992-clinical-features-and-predictive-markers-of-disease-progress",
    type: "journal",
    typeLabel: "Journal article",
    title: "Clinical features and predictive markers of disease progression in cynomolgus monkeys experimentally infected with simian immunodeficiency virus",
    authors: ["Putkonen, P", "Kaaya, EE", "Böttiger, D", "Li, S-L", "Nilsson, C", "Biberfeld, P", "Biberfeld, G"],
    year: 1992,
    journal: "AIDS",
    volume: "6",
    issue: "3",
    pages: "257 - 264",
    issn: "0269-9370",
    doi: "10.1097/00002030-199203000-00002",
    doiUrl: "http://dx.doi.org/10.1097/00002030-199203000-00002",
  },
  {
    slug: "li-1991-monocyte-macrophage-giant-cell-disease-in-siv-infected-cynom",
    type: "journal",
    typeLabel: "Journal article",
    title: "Monocyte/macrophage giant cell disease in SIV-infected cynomolgus monkeys",
    authors: ["Li, SL", "Kaaya, EE", "Feichtinger, H", "Putkonen, P", "Parravicini, C", "Böttiger, D", "Biberfeld, G", "Biberfeld, P"],
    year: 1991,
    journal: "Research in Virology",
    volume: "142",
    issue: "2-3",
    pages: "173 - 182",
    issn: "0923-2516",
    doi: "10.1016/0923-2516(91)90054-7",
    doiUrl: "http://dx.doi.org/10.1016/0923-2516(91)90054-7",
  },
  {
    slug: "mellstedt-1991-patients-treated-with-a-monoclonal-antibody-ab1-to-the-col",
    type: "journal",
    typeLabel: "Journal article",
    title: "Patients treated with a monoclonal antibody (ab1) to the colorectal carcinoma antigen 17–1A develop a cellular response (DTH) to the “internal image of the antigen” (ab2)",
    authors: ["Mellstedt, H", "Frodin, J", "Biberfeld, P", "Fagerberg, J", "Gisombe, R", "Hernandez, A", "Masucci, G", "Li, S", "Steinitz, M"],
    year: 1991,
    journal: "International Journal of Cancer",
    volume: "48",
    issue: "3",
    pages: "344 - 349",
    issn: "0020-7136",
    doi: "10.1002/ijc.2910480306",
    doiUrl: "http://dx.doi.org/10.1002/ijc.2910480306",
  },
  {
    slug: "wang-1991-expression-of-mhc-class-i-antigens-in-human-carcinomas-and-s",
    type: "journal",
    typeLabel: "Journal article",
    title: "Expression of MHC-class-I antigens in human carcinomas and sarcomas analyzed by isoelectric focusing",
    authors: ["Wang, P", "Vánky, F", "Li, S-L", "Végh, Z", "Persson, U", "Klein, E"],
    year: 1991,
    journal: "International Journal of Cancer",
    volume: "47",
    issue: "S6",
    pages: "106 - 116",
    issn: "0020-7136",
    doi: "10.1002/ijc.2910470721",
    doiUrl: "http://dx.doi.org/10.1002/ijc.2910470721",
  },
  {
    slug: "feichtinger-1990-malignant-lymphomas-in-cynomolgus-monkeys-infected-with-simi",
    type: "journal",
    typeLabel: "Journal article",
    title: "Malignant lymphomas in cynomolgus monkeys infected with simian immunodeficiency virus",
    authors: ["Feichtinger, H", "Putkonen, P", "Parravicini, C", "Li, SL", "Kaaya, EE", "Böttiger, D", "Biberfeld, G", "Biberfeld, P"],
    year: 1990,
    journal: "American Journal of Pathology",
    volume: "137",
    issue: "6",
    pages: "1311 - 1315",
    issn: "0002-9440",
  },
  {
    slug: "wang-1990-functional-characteristics-of-the-intercellular-adhesion-mol",
    type: "journal",
    typeLabel: "Journal article",
    title: "Functional characteristics of the intercellular adhesion molecule-1 (CD54) expressed on cytotoxic human blood lymphocytes",
    authors: ["Wang, P", "Vánky, F", "Li, S-L", "Patarroyo, M", "Klein, E"],
    year: 1990,
    journal: "Cellular Immunology",
    volume: "131",
    issue: "2",
    pages: "366 - 380",
    issn: "0008-8749",
    doi: "10.1016/0008-8749(90)90261-o",
    doiUrl: "http://dx.doi.org/10.1016/0008-8749(90)90261-o",
  },
];
